### ISSUE TITLE
标签UI着色不均匀

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1003]
### 复现步骤 / Step to reproduce

随便打开一个画廊
随便长按一个标签

### 预期行为 / Expected behaviour

着色均匀

### 实际行为 / Actual Behaviour

![Screenshot_20240408_231427_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/5d071791-94ac-4d17-a7fa-b82d7de44b70)
![Screenshot_20240408_231253_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/c8b71b71-b72f-4fd8-bcab-c4dea60f0f93)

### 应用日志 / App logs

Nothing

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

8c7a371

### Android 系统版本 / Android version

HarmonyOS 4.0.0.132

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
浅色部分是不可点击的，不过上下应该一致

**Comment by tmby** [comment]
> 浅色部分是不可点击的，不过上下应该一致

b182c97 ，没有修好，不可点击的部分还是浅色

**Comment by FooIbar** [comment]
> > 浅色部分是不可点击的，不过上下应该一致
> 
> [b182c97](https://github.com/FooIbar/EhViewer/commit/b182c971859e3f7544b6361527435a3affe88d54) ，没有修好，不可点击的部分还是浅色

这是预期行为，不过我会再考虑下有没有必要用不同颜色区分可点击和不可点击部分
