### ISSUE TITLE
完全不知道什么原因，导致界面变成了粉色

### ISSUE THREAD

**Issue by yubanmeixiao** [FooIbar/EhViewer#1006]
### 复现步骤 / Step to reproduce

![2d3198aaef6e852ae4b62cb7708a2c2b](https://github.com/FooIbar/EhViewer/assets/59812878/f4caacba-b41f-471b-a7e4-6846e8a52d34)

### 预期行为 / Expected behaviour

突然变成了粉色

### 实际行为 / Actual Behaviour

应该是白色才对……

### 应用日志 / App logs

none

### 备注 / Addition details

none

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.13

### EhViewer CI 版本 / EhViewer CI Version

27224e8

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

vivo x fold3 pro

### SoC 型号 / Soc model

8gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by naloder** [comment]
这是Android的Monet取色特性

**Comment by yubanmeixiao** [comment]
> 这是Android的Monet取色特性

有、有办法变回去吗∑(ﾟДﾟ|||）

**Comment by FooIbar** [comment]
这是根据你壁纸来的，可以在“壁纸与个性化”里调

*即使在不支持动态配色的设备上也不会是白色，而是紫色
