### ISSUE TITLE
请求：给下载列表的画廊添加【下载完成】的功能或tag

### ISSUE THREAD

**Issue by moxue128** [FooIbar/EhViewer#1016]
### 复现步骤 / Step to reproduce

有时候全选已经下载完的的列表，手指头太大容易误触到下载，导致之前的画廊也跟着一起下载，希望能在这里添加一个定义这些画廊已经下载完成的功能，让后续下载不再识别之前因为误触全选到的画廊

### 预期行为 / Expected behaviour

*

### 实际行为 / Actual Behaviour

*

### 应用日志 / App logs

*

### 备注 / Addition details

*

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

107bb0b

### Android 系统版本 / Android version

Android 12

### 设备型号 / Device model

xiaomi 12

### SoC 型号 / Soc model

骁龙8 Gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by moxue128** [comment]
实在抱歉，我找不到除了bug以外的tag

**Comment by FooIbar** [comment]
误触到哪个按钮？能截图说明一下吗
