### ISSUE TITLE
想问下`下载列表手动排序`这么实用的功能为什么会砍掉？

### ISSUE THREAD

**Issue by devioa** [FooIbar/EhViewer#1017]
### 复现步骤 / Step to reproduce

这个真的太需要了，不知道为什么要砍掉呢？经常一个系列的画廊有时候点下载的时候没按系列的顺序添加到列表，就只能一个个删掉然后再按顺序添加到下载列表，非常麻烦

### 预期行为 / Expected behaviour

n/a

### 实际行为 / Actual Behaviour

n/a

### 应用日志 / App logs

n/a

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0-snapshot

### EhViewer CI 版本 / EhViewer CI Version

107bb0b

### Android 系统版本 / Android version

hyperos

### 设备型号 / Device model

redmi k70pro

### SoC 型号 / Soc model

8g3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
#890

**Comment by devioa** [comment]
> #890

这个issue我当时早就参与过讨论了，但还是没明白为什么要砍掉画廊的手动排序？下载标签可以手动排序ok，但通过标签分类后的画廊仍然有手动排序的需求

**Comment by z1137** [comment]
虽然我也想要类似功能，不过好像是因为数据库的问题？以前版本的数据库提供的功能比较少，而且有个bug：部分旧画廊移动只能一下一下移动：比如一个标签下有21本，把一个本子从头移动到尾部需要20*2次操作。
比起这个我现在更想要下载标签那个列表的标签搜索功能，2000多个本子100多标签一个个找作者挺折磨的

**Comment by FooIbar** [comment]
手动排序无法适应较大规模的下载列表

> 比起这个我现在更想要下载标签那个列表的标签搜索功能，2000多个本子100多标签一个个找作者挺折磨的

单独开 issue
