### ISSUE TITLE
一打开搜索界面 就开始卡顿

### ISSUE THREAD

**Issue by sakurrasama** [FooIbar/EhViewer#1023]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/50175396/925ee900-2b20-4958-9802-320f412961bb

### 预期行为 / Expected behaviour

只要打开搜索框就会开始掉帧 不打开就正常

### 实际行为 / Actual Behaviour

1

### 应用日志 / App logs

[log-2024-04-15-11-24-21-016.zip](https://github.com/FooIbar/EhViewer/files/14973642/log-2024-04-15-11-24-21-016.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

cf08bfd

### Android 系统版本 / Android version

oneui2.5 Android10

### 设备型号 / Device model

Samsung s20 

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/8683033713/artifacts/1412952874
试下这个版本，在 设置-高级 里关闭列表项动画

**Comment by sakurrasama** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/8683033713/artifacts/1412952874 试下这个版本，在 设置-高级 里关闭列表项动画

正常了 谢谢

**Comment by UjuiUjuMandan** [comment]
@Kgat9

**Comment by Kgat9** [comment]
@UjuiUjuMandan 很高兴您能答疑解惑，但结果最终不尽人意，

1. 作者FooIbar的软件不论是最新的还是上面分享的都无法看到内容（如图1），以及无法登录。
2. 而您的软件最新的我都试了一遍，发现就没有“列表项动画”这个选项（图2）
3. 顺便问问，之前自动更新的软件分享的地址是您的页面（图3），我还以为又换人了！UjuiUjuMandan和FooIbar是同一人吗？


下载旧版本的软件会无法使用，新版本的卡顿依然让人头疼我诚恳的须要帮助
![01 (1)](https://github.com/FooIbar/EhViewer/assets/149447502/9d56b9d4-9093-4ace-ba21-5dc234b16a6e)
![01 (2)](https://github.com/FooIbar/EhViewer/assets/149447502/de22ee00-5a54-41d5-ae97-417d6161dfcc)
![01 (3)](https://github.com/FooIbar/EhViewer/assets/149447502/87edfea0-b2b0-4b7e-97ce-7fbe4eca68a7)

**Comment by UjuiUjuMandan** [comment]
@Kgat9 
1. 因为它就不能直连。
2. 因为还没合并。
3. 不是。

这个版本应该可以关闭列表项动画了: https://github.com/UjuiUjuMandan/EhViewer/actions/runs/8685387084/artifacts/1413498163 。

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/8912383640/artifacts/1464430404
你能用这个版本打开列表项目动画试下还会卡顿吗？
如果会的话再传一下录屏和日志

**Comment by FooIbar** [comment]
已于最新 CI 版本修复，如果还有问题的话再单独开 issue
