### ISSUE TITLE
无法连接至exhentai服务器

### ISSUE THREAD

**Issue by Ptilopsis01** [FooIbar/EhViewer#1031]
### 复现步骤 / Step to reproduce

1. 安装应用
2. 登录账号，画廊获取正常
3. 切换至exhentai，无法获取内容，无法下载

### 预期行为 / Expected behaviour

正常获取exhentai内容及下载

### 实际行为 / Actual Behaviour

![MuMu12-20240417-214525](https://github.com/FooIbar/EhViewer/assets/93318731/2be97cc7-0871-4972-8768-df800c4e3d36)
无法连接至exhentai

### 应用日志 / App logs

[log-2024-04-17-21-46-17-539.zip](https://github.com/FooIbar/EhViewer/files/15011949/log-2024-04-17-21-46-17-539.zip)

### 备注 / Addition details

使用浏览器直接访问网页正常

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.3

### EhViewer CI 版本 / EhViewer CI Version

a3cb6d2

### Android 系统版本 / Android version

HyperOS, Android 14

### 设备型号 / Device model

Xiaomi 12S

### SoC 型号 / Soc model

骁龙8+g1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
https://nicebowl.fun/11

**Comment by Ptilopsis01** [comment]
> https://nicebowl.fun/11

不是，我浏览器可以正常访问的，只有ehviewer没法访问

**Comment by Ptilopsis01** [comment]
没事了我理解了（）
