### ISSUE TITLE
下载标签列表拖拽时的卡顿和闪烁

### ISSUE THREAD

**Issue by LX-676655103** [FooIbar/EhViewer#1041]
### 复现步骤 / Step to reproduce

1. 在下载标签页面创建若干标签
2. 拖动页面，发现会出现明显的卡顿和闪烁感
3. 快速拖动页面，在页面接近停止时，会出现卡顿

https://github.com/FooIbar/EhViewer/assets/85400846/82ae2027-76e8-4dc7-a8a8-8e092a22cac6

### 预期行为 / Expected behaviour

拖动下载标签列表时，应该是顺滑、无卡顿和闪烁的

### 实际行为 / Actual Behaviour

实际上会出现明显的卡顿情况

### 应用日志 / App logs

[log-2024-04-20-23-13-41-762.zip](https://github.com/FooIbar/EhViewer/files/15048725/log-2024-04-20-23-13-41-762.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.3

### EhViewer CI 版本 / EhViewer CI Version

a3cb6d2

### Android 系统版本 / Android version

MIUI 14.0.31

### 设备型号 / Device model

Xiaomi 13

### SoC 型号 / Soc model

骁龙 8 Gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by revonateB0T** [comment]
Probably duplicated of #994 ?

**Comment by LX-676655103** [comment]
> Probably duplicated of #994 ?

That seems to be the same reason. But I want to know is there any way to solve it? It is really uncomfortable to use.

**Comment by revonateB0T** [comment]
> > Probably duplicated of #994 ?
> 
> That seems to be the same reason. But I want to know is there any way to solve it? It is really uncomfortable to use.

@FooIbar may provide a workaround for it.
I will go play Battlefield 1 :P

**Comment by LX-676655103** [comment]
> @FooIbar may provide a workaround for it. I will go play Battlefield 1 :P

I see, XD, have fun
