### ISSUE TITLE
界面一种自动进入搜索页面

### ISSUE THREAD

**Issue by Restore000** [FooIbar/EhViewer#1060]
### 复现步骤 / Step to reproduce

我在vmware的安卓x86虚拟机中安装，只能用鼠标键盘操作，登录完成之后就一直自动打开搜索界面，尝试了游客模式，只要点击了搜索栏就一直自动进入搜索界面。

### 预期行为 / Expected behaviour

在用户点击搜索栏进入搜索界面，点击返回后关闭搜索界面，不会自动再次进入搜索界面。

### 实际行为 / Actual Behaviour

一直自动打开搜索界面，关闭搜索界面后又会自动打开搜索界面。

### 应用日志 / App logs

无法进行导出日志操作。

### 备注 / Addition details

推测是因为检测到物理键盘判断为键盘开启后自动打开搜索界面。

### 浏览站点 / Browsing site

主页

### EhViewer 版本号 / EhViewer version code

1.11.4

### EhViewer CI 版本 / EhViewer CI Version

71a4e84

### Android 系统版本 / Android version

Android x86_64 9.0 r2

### 设备型号 / Device model

VMware虚拟机

### SoC 型号 / Soc model

虚拟机CPU

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
为啥要在VMWare中跑EhViewer，宁愿开虚拟机也不用网页是吧。

**Comment by FooIbar** [comment]
建议用 WSA

**Comment by FooIbar** [comment]
可以在模拟器上复现
