### ISSUE TITLE
Unable to update normally

### ISSUE THREAD

**Issue by NeKoOuO** [FooIbar/EhViewer#1067]
### 复现步骤 / Step to reproduce

1. Check for updates
2. Click the download button
3. Waiting to install
4. Nothing happened

### 预期行为 / Expected behaviour

It should be update normally

### 实际行为 / Actual Behaviour

https://github.com/FooIbar/EhViewer/assets/111511925/56e431c6-2556-4876-b263-702fdfe8e4b7

### 应用日志 / App logs

[log-2024-04-26-23-49-57-512.zip](https://github.com/FooIbar/EhViewer/files/15132688/log-2024-04-26-23-49-57-512.zip)

### 浏览站点 / Browsing site

No

### EhViewer 版本号 / EhViewer version code

1.11.3

### EhViewer CI 版本 / EhViewer CI Version

a3cb6d2

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Mi 10 ultra 

### SoC 型号 / Soc model

Snap865

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
检查一下有没有安装未知应用的权限
![Screenshot_20240428-134739_Paranoid_Launcher](https://github.com/FooIbar/EhViewer/assets/118464521/8d2519f3-a767-4346-9869-989b03004017)

**Comment by NeKoOuO** [comment]
Yes

![Screenshot_2024-04-28-20-24-15-056_com.android.settings.jpg](https://github.com/FooIbar/EhViewer/assets/111511925/f0fd90d4-d085-4af5-9933-568e3b7228a4)

**Comment by FooIbar** [comment]
Try this https://github.com/FooIbar/EhViewer/actions/runs/8865686103/artifacts/1454239671.
Note this is a dev build, it's recommended to backup data before updating.

**Comment by NeKoOuO** [comment]
> Note this is a dev build, it's recommended to backup data before updating.

thx! ill try it
