### ISSUE TITLE
通过全部开始（倒序）进行下载，APP会崩溃

### ISSUE THREAD

**Issue by zhongjie10086** [FooIbar/EhViewer#109]
### 复现步骤 / Step to reproduce

全部开始（倒序）

### 预期行为 / Expected behaviour

倒序下载

### 实际行为 / Actual Behaviour

APP崩溃

### 应用日志 / App logs

[log-2023-10-27-09-41-24-272.zip](https://github.com/FooIbar/EhViewer/files/13189561/log-2023-10-27-09-41-24-272.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

10c7019

### Android 系统版本 / Android version

ONEUI 5.1

### 设备型号 / Device model

Samsung S23 ultra

### SoC 型号 / Soc model

Snapdragon 8 gen 2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你这日志怎么是 0 B 啊

**Comment by zhongjie10086** [comment]
> 你这日志怎么是 0 B 啊

[log-2023-10-27-09-41-24-272.zip](https://github.com/FooIbar/EhViewer/files/13189668/log-2023-10-27-09-41-24-272.zip)
看看这次行不行？

**Comment by FooIbar** [comment]
> > 你这日志怎么是 0 B 啊
> 
> [log-2023-10-27-09-41-24-272.zip](https://github.com/FooIbar/EhViewer/files/13189668/log-2023-10-27-09-41-24-272.zip) 看看这次行不行？

可以了
