### ISSUE TITLE
在软件内更新到12.0后闪退，重装了github上的11.4版本后依然闪退

### ISSUE THREAD

**Issue by vexling201515** [FooIbar/EhViewer#1090]
### 复现步骤 / Step to reproduce

0.在软件内更新到12.0
1.向下滑动时会闪退
2.下载了github上的EhViewer-1.11.4-default-arm64-v8a.apk后重新安装
3.点进去后直接闪退

https://github.com/FooIbar/EhViewer/assets/94334363/feccd224-40bc-4e83-a28a-d6e320e05191

### 预期行为 / Expected behaviour

向更新到12.0版本前那样正常使用

### 实际行为 / Actual Behaviour

一打开软件就闪退

### 应用日志 / App logs

闪退，无法导出日志

### 浏览站点 / Browsing site

E-Hentai 

### EhViewer 版本号 / EhViewer version code

手机12.0更新前的版本，闪退时为EhViewer-1.11.4-default-arm64-v8a

### EhViewer CI 版本 / EhViewer CI Version

闪退，无法确定

### Android 系统版本 / Android version

Android14

### 设备型号 / Device model

iQOO Neo8 Pro

### SoC 型号 / Soc model

3.35GHz 天玑 8200+ 八核

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
崩溃日志在 Android/data/moe.tarsin.ehviewer/files/crash 下，复制出来看看
如果访问不了 Android/data 可以用 https://github.com/zhanghai/MaterialFiles

**Comment by vexling201515** [comment]
[crash-2024-05-01-00-06-31-000.log](https://github.com/FooIbar/EhViewer/files/15168067/crash-2024-05-01-00-06-31-000.log)

**Comment by vexling201515** [comment]
> 崩溃日志在 Android/data/moe.tarsin.ehviewer/files/crash 下，复制出来看看 如果访问不了 Android/data 可以用 https://github.com/zhanghai/MaterialFiles

发了

**Comment by FooIbar** [comment]
只有这一个吗？
这是因为你从 CI 版本降级没有清数据，清了之后导入更新前备份的数据就行

**Comment by vexling201515** [comment]
> 只有这一个吗？ 这是因为你从 CI 版本降级没有清数据，清了之后导入更新前备份的数据就行

不好意思我以为给一个就行了，其实有11个log
[crash.zip](https://github.com/FooIbar/EhViewer/files/15168150/crash.zip)

**Comment by vexling201515** [comment]
> 只有这一个吗？ 这是因为你从 CI 版本降级没有清数据，清了之后导入更新前备份的数据就行

能不能教一下清数据和导入更新前备份数据的方法？

**Comment by vexling201515** [comment]
> 只有这一个吗？ 这是因为你从 CI 版本降级没有清数据，清了之后导入更新前备份的数据就行

更新前备份的数据在哪里找？

**Comment by FooIbar** [comment]
我看了一下日志，这个问题调查需要一定时间
你可以像我之前说的清除数据先用 1.11.4

**Comment by vexling201515** [comment]
> 我看了一下日志，这个问题调查需要一定时间 你可以像我之前说的清除数据先用 1.11.4

请问更新前备份的数据是这个吗？
[2024-04-30-23-16-18-600.zip](https://github.com/FooIbar/EhViewer/files/15168323/2024-04-30-23-16-18-600.zip)
清除数据会影响下载好的本子吗？

**Comment by FooIbar** [comment]
帮你编辑掉了备份数据的链接，你可能不想别人看到你的 XP
