### ISSUE TITLE
资金显示为空

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1094]
### 复现步骤 / Step to reproduce

1.点击设置
2.点击EH
3.点击图片配额

### 预期行为 / Expected behaviour

正常显示配额下方的credit和gp资金

### 实际行为 / Actual Behaviour

![Screenshot_20240501_122610_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/d0042a09-3e29-4bfd-963a-faaf3e3677b4)

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

9e13c1c

### Android 系统版本 / Android version

HarmonyOS 4.0.0.135

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
打算重新设计这个对话框
