### ISSUE TITLE
非原图下载时图片分辨率过低问题

### ISSUE THREAD

**Issue by 947zyz** [FooIbar/EhViewer#111]
### 复现步骤 / Step to reproduce

由1.8.8.3版本直接更新而来，关闭下载原图的情况下，发现该版本默认下载时图片分辨率过低，导致部分画廊中图片字体清晰度过低而模糊不清，希望能添加自定义图片分辨率的选项。

### 预期行为 / Expected behaviour

-

### 实际行为 / Actual Behaviour

-

### EhViewer 版本号 / EhViewer version code

1.8.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

10c7019

### Android 系统版本 / Android version

MIUI 14.0.19 (Android 13)

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

骁龙 7+Gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by RikkaBlue** [comment]
出现了类似问题，卸载重装了 deafult gms 的版本后问题消失。

**Comment by FooIbar** [comment]
> - When browsing on mobile, the system will now default to using 780x resamples instead of 1280x ones if the browsing resolution is set to "Auto".

https://forums.e-hentai.org/index.php?showtopic=244935

TL;DR: 在网站设置中更改

**Comment by phantomkings** [comment]
补充一下，https://forums.e-hentai.org/index.php?showtopic=244935
↑foolbar佬提供的地址里的确有my settings链接，但只包含表站。画廊的站点拥有e-h和exh。
若是不将表里站一同设置默认分辨率，没有设置的那个站画源会保留780x默认。
切换画廊站点到exh里站时发现浏览的分辨率变成了780x糊糊的用户，请将my settings链接里的域名e-h变成exh，再次设置一次里站的默认分辨率，便可下载对应的分辨率。

**Comment by InLem** [comment]
我的解決方法是把user agent改成跟pc一樣就解決了。
