### ISSUE TITLE
exh里站无法使用

### ISSUE THREAD

**Issue by 0xiaoshenap** [FooIbar/EhViewer#1117]
### 复现步骤 / Step to reproduce

在app改为exh里站模式，无法加载出首页，复制里站漫画链接，在app内也无法打开
下面是展示账号有里站权限

### 预期行为 / Expected behaviour

正常展示里站漫画/显示里站首页

### 实际行为 / Actual Behaviour

无法加载
![photo_2024-05-03_13-25-44 (2)](https://github.com/FooIbar/EhViewer/assets/60251029/237b26de-33bb-4557-97e3-42ec1d8e0290)

### 应用日志 / App logs

[log-2024-05-03-16-18-23-785.zip](https://github.com/FooIbar/EhViewer/files/15197605/log-2024-05-03-16-18-23-785.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.4

### EhViewer CI 版本 / EhViewer CI Version

71a4e84

### Android 系统版本 / Android version

HyperOS

### 设备型号 / Device model

Xiaomi k50u

### SoC 型号 / Soc model

Snapdragon 8+ Gen 1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
点账号检查 igneous 是不是 mystery，如果是选清除 igneous

**Comment by Mochimazii** [comment]
似乎是里站问题，我也这样，igneous有值但是sadpanda。上网页试了结果白嫖，看igneous也是有值的

**Comment by 0xiaoshenap** [comment]
@FooIbar 重置之后依然解决不了问题
@Mochimazii 里站是正常的，我在上面提供了访问里站的截图，同时表示我账号有里站权限

**Comment by 0xiaoshenap** [comment]
降级到1.10.3，使用cookie登录后正常，再升级回最新版本，目前看也是正常的，cookie过期机制我不清楚。

**Comment by FooIbar** [comment]
清除 igneous 之后重新获取的 igneous 是不是 mystery

**Comment by tmby** [comment]
> 清除 igneous 之后重新获取的 igneous 是不是 mystery

这个功能不是用账密登录才有用吗？（我一直是这么理解的）
> 降级到1.10.3，使用cookie登录后正常，再升级回最新版本，目前看也是正常的，cookie过期机制我不清楚。

但他不是cookies登录吗？

**Comment by 0xiaoshenap** [comment]
@FooIbar 是，清除了重新获取的还是mystery
@tmby 那句话我只是说找到了一个方案，我提交这个issues时是用的最新版本，没有cookie登录

**Comment by FooIbar** [comment]
> > 清除 igneous 之后重新获取的 igneous 是不是 mystery
> 
> 这个功能不是用账密登录才有用吗？

这个功能跟登录方式无关
账号登录的话 igneous 一个月后会自动过期，过期后的第一个请求是不带 igneous 的，此时服务器会设置新的 igneous
cookie 登录的话在 igneous 过期后还会使用已过期的 igneous 进行请求，此时服务器会将 igneous 设为 mystery
清除 igneous 后会从服务器重新获取

**Comment by tmby** [comment]
> @FooIbar 是，清除了重新获取的还是mystery
> @tmby 那句话我只是说找到了一个方案，我提交这个issues时是用的最新版本，没有cookie登录

我发现问题所在了
> 清除 igneous 之后重新获取的 igneous 是不是 mystery

测试过后发现igneous不会更新，照理说更新后和之前的igneous不是一个值，但是现在重新获取后依然是旧值

**Comment by FooIbar** [comment]
> 测试过后发现igneous不会更新，照理说更新后和之前的igneous不是一个值，但是现在重新获取后依然是旧值

清除 igneous 之后再点账号显示的 igneous 应该是 null

**Comment by tmby** [comment]
> > 测试过后发现igneous不会更新，照理说更新后和之前的igneous不是一个值，但是现在重新获取后依然是旧值
> 
> 清除 igneous 之后再点账号显示的 igneous 应该是 null

现在说一下时间线
看到这个issue之后我执行了一次清除igneous的过程，发现新获取的igneous和之前的igneous一样，就发表了上面的言论
然后我tg的群友告诉我`如果获取相隔一分钟内就是一样的`，我就想要排除这个误差
就又清除igneous
现在发现无论执行多少次搜索，igneous都不会更新，依旧为null

**Comment by FooIbar** [comment]
> > > 测试过后发现igneous不会更新，照理说更新后和之前的igneous不是一个值，但是现在重新获取后依然是旧值
> > 
> > 
> > 清除 igneous 之后再点账号显示的 igneous 应该是 null
> 
> 现在说一下时间线 看到这个issue之后我执行了一次清除igneous的过程，发现新获取的igneous和之前的igneous一样，就发表了上面的言论 然后我tg的群友告诉我`如果获取相隔一分钟内就是一样的`，我就想要排除这个误差 就又清除igneous 现在发现无论执行多少次搜索，igneous都不会更新，依旧为null

你在表站搜当然不会更新

**Comment by FooIbar** [comment]
浏览器里是刚登录的还是原先就已登录的
EHV 和浏览器登录时处在同一网络环境下吗

**Comment by 0xiaoshenap** [comment]
http://mtw.so/5yoqx5
这里用平板复现了一下完整过程，这里上传到我自己网盘上，为了网站安全，issues关闭后我会取消短链接。

**Comment by FooIbar** [comment]
> 这里用平板复现了一下完整过程，这里上传到我自己网盘上，为了网站安全，issues关闭后我会取消短链接。 @FooIbar

你 cookie 怎么不打码的呀
而且你这视频里只有 EHV，在同一个环境下浏览器能不能访问里站

**Comment by 0xiaoshenap** [comment]
@FooIbar 非常抱歉，我确实忽略了未登录里站取得igneous之前的第一次登录需要欧美ip，因为我的浏览器之前已经登录过exh，所以可以访问，抱歉占用了您的时间解决这个问题，再次给您道歉。

**Comment by FooIbar** [comment]
> @FooIbar 非常抱歉，我确实忽略了未登录里站取得igneous之前的第一次登录需要欧美ip，因为我的浏览器之前已经登录过exh，所以可以访问，抱歉占用了您的时间解决这个问题，再次给您道歉。

建议改下密码，你之前 cookie 没打码直接发谁都能看见
