### ISSUE TITLE
复制cookies闪退

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#112]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.cookies登录，进入Ehviewer
2.点击设置-EH-账户-复制cookies

### 预期行为 / Expected behaviour

正常复制

### 实际行为 / Actual Behaviour

复制成功并闪退

### 应用日志 / App logs

[log-2023-10-28-00-28-19-457.zip](https://github.com/FooIbar/EhViewer/files/13191241/log-2023-10-28-00-28-19-457.zip)

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

edbe650

### Android 系统版本 / Android version

HarmonyOS 4.0.0.116

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
这个可以确认
