### ISSUE TITLE
最新ci版本两侧侧边栏特别容易误触

### ISSUE THREAD

**Issue by lings03** [FooIbar/EhViewer#1146]
### 复现步骤 / Step to reproduce

正常上下滑

### 预期行为 / Expected behaviour

页面上下滑动

### 实际行为 / Actual Behaviour

误触发侧边栏

1.11.4版本测试
https://github.com/FooIbar/EhViewer/assets/90336521/c62fb4df-8177-47d7-a8ab-d29094498649

最近一天所有的ci版本测试
https://github.com/FooIbar/EhViewer/assets/90336521/a7a0bbe1-7d41-4b6e-8710-a788c2520155
https://github.com/FooIbar/EhViewer/assets/90336521/d859d96e-99dd-4c52-8e53-c332fee69dbe

### 应用日志 / App logs

[log-2024-05-07-23-12-19-037.zip](https://github.com/FooIbar/EhViewer/files/15237838/log-2024-05-07-23-12-19-037.zip)

### 浏览站点 / Browsing site

eh和ex

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

30e166b，测试了最近两天的ci都有同样问题

### Android 系统版本 / Android version

hyperos 1.02/安卓14

### 设备型号 / Device model

redmi note12t

### SoC 型号 / Soc model

7+gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
https://github.com/FooIbar/EhViewer/assets/88327304/b407f1e5-d7e8-4b88-800e-3beaeeaeba0c

同样的问题

**Comment by lings03** [comment]
这里还有一个清除数据测试后的log
[log-2024-05-07-23-32-35-331.zip](https://github.com/FooIbar/EhViewer/files/15237950/log-2024-05-07-23-32-35-331.zip)

**Comment by FooIbar** [comment]
我明天看一下，临时解决方案是回退到 https://github.com/FooIbar/EhViewer/actions/runs/8947696271
