### ISSUE TITLE
使用持续集成更新至1.8.11SNAPSHOT后阅读器无法使用

### ISSUE THREAD

**Issue by lvxinhang1996** [FooIbar/EhViewer#115]
### 复现步骤 / Step to reproduce

![Screenshot_2023-10-28-06-37-10-946_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/58155566/1c159d83-94a4-40d5-ad76-cbbf570c9608)
![Screenshot_2023-10-28-06-37-19-591_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/58155566/a931f2b5-63bc-45bd-9294-63db4fae72a9)

使用集成式更新至1.8.11-SNAPSHOT-gms（1021efb）后，无法正常进入阅读画面，表现为空屏。

### 预期行为 / Expected behaviour

进行正常图片浏览显示

### 实际行为 / Actual Behaviour

实际上显示为空屏
![Screenshot_2023-10-28-06-37-19-591_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/58155566/75efd660-4b83-4dee-b0a8-58cffa0f7422)

### 应用日志 / App logs

/--------- beginning of crash
10-21 04:57:47.109  4221  4221 E AndroidRuntime: FATAL EXCEPTION: main
10-21 04:57:47.109  4221  4221 E AndroidRuntime: Process: moe.tarsin.ehviewer, PID: 4221
10-21 04:57:47.109  4221  4221 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {moe.tarsin.ehviewer/eu.kanade.tachiyomi.ui.reader.ReaderActivity}: java.lang.NullPointerException
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5547)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5592)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8293)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: Caused by: java.lang.NullPointerException
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at Kx0.f(Unknown Source:29)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at oa0.e(Unknown Source:0)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at oa0.g(Unknown Source:97)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at hF.v(Unknown Source:3)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.onDestroy(Unknown Source:22)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:8547)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5534)
10-21 04:57:47.109  4221  4221 E AndroidRuntime: 	... 13 more
--------- beginning of system
10-23 06:16:41.075 12358 12762 W BpBinder: Slow Binder: BpBinder transact took 1464 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-23 06:17:19.698 12358 14674 W BpBinder: Slow Binder: BpBinder transact took 1456 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-23 06:20:08.920 12358 14667 W BpBinder: Slow Binder: BpBinder transact took 1474 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-23 06:22:39.286 12358 15288 W BpBinder: Slow Binder: BpBinder transact took 1524 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-23 06:24:01.872 16192 16192 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-23 06:24:01.956 16192 16192 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:38:50.804 22637 22637 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 04:38:50.879 22637 22637 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:39:38.813 23178 23178 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 04:39:38.870 23178 23178 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:39:39.267 23178 23178 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 118ms
10-26 04:41:30.979 25117 25117 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 04:41:31.031 25117 25117 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:41:31.300 25117 25117 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 82ms
10-26 04:44:30.845 25117 25145 W BpBinder: Slow Binder: BpBinder transact took 13599 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-26 04:46:38.621 26556 26556 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 04:46:38.661 26556 26556 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:46:38.933 26556 26556 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 80ms
10-26 04:50:24.912 27785 27785 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 04:50:24.954 27785 27785 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 04:50:25.206 27785 27785 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 79ms
10-26 23:36:06.253 15785 15785 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-26 23:36:06.341 15785 15785 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-26 23:36:06.669 15785 15785 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 62ms
10-26 23:36:55.987 15785 15825 W BpBinder: Slow Binder: BpBinder transact took 1461 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-26 23:37:22.543 15785 15821 W BpBinder: Slow Binder: BpBinder transact took 1485 ms, interface=android.content.IContentProvider, code=21 oneway=false
10-28 00:19:04.377 18788 18788 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-28 00:19:04.430 18788 18788 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-28 00:19:44.719 19217 19217 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-28 00:19:44.789 19217 19217 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-28 00:19:45.111 19217 19217 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 115ms
10-28 06:33:07.811 19239 19239 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-28 06:33:07.874 19239 19239 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-28 06:33:08.150 19239 19239 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 75ms
10-28 06:34:21.498 19684 19684 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-28 06:34:21.537 19684 19684 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-28 06:34:21.741 19684 19684 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 64ms
10-28 06:44:06.667 23831 23831 I ForceDarkHelperStubImpl: initialize for moe.tarsin.ehviewer , ForceDarkOrigin
10-28 06:44:06.743 23831 23831 D ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.015
10-28 06:44:07.036 23831 23831 W Activity: PerfMonitor: Slow Operation: Activity moe.tarsin.ehviewer/com.hippo.ehviewer.ui.MainActivity onPause took 86ms
--------- beginning of main
10-28 06:45:45.602 23831 23883 D AppScoutStateMachine: 23831-ScoutStateMachinecreated
10-28 06:45:45.728 23831 23831 D IS_CTS_MODE: false
10-28 06:45:45.728 23831 23831 D MULTI_WINDOW_SWITCH_ENABLED: false
10-28 06:45:45.729 23831 23879 D ViewContentFactory: initViewContentFetcherClass
10-28 06:45:45.729 23831 23879 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
10-28 06:45:45.729 23831 23831 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-28 06:45:45.729 23831 23879 D ViewContentFactory: createInterceptor took 0ms
10-28 06:45:45.746 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-28 06:45:45.801 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-28 06:45:45.836 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-28 06:45:47.408 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-28 06:45:54.646 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-28 06:45:55.234 23831 23866 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076c1c74e00 (j01) with handle 0xb4000076eb4500a0
10-28 06:45:56.517 23831 23938 D AppScoutStateMachine: 23831-ScoutStateMachinecreated
10-28 06:45:56.535 23831 23831 D IS_CTS_MODE: false
10-28 06:45:56.535 23831 23831 D MULTI_WINDOW_SWITCH_ENABLED: false
10-28 06:45:56.611 23831 23879 D ViewContentFactory: initViewContentFetcherClass
10-28 06:45:56.611 23831 23879 I ContentCatcher: ViewContentFetcher : ViewContentFetcher
10-28 06:45:56.611 23831 23879 D ViewContentFactory: createInterceptor took 0ms
10-28 06:45:56.612 23831 23831 D IS_CTS_MODE: false
10-28 06:45:56.612 23831 23831 D MULTI_WINDOW_SWITCH_ENABLED: false
10-28 06:45:56.613 23831 23831 D DecorView[]: getWindowModeFromSystem  windowmode is 1
10-28 06:45:56.680 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-28 06:45:56.686 23831 23831 D DecorView[]: onWindowFocusChanged hasWindowFocus false

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

1021efb

### Android 系统版本 / Android version

MIUI14.0.4

### 设备型号 / Device model

Redmi K30 Pro

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [x] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by lvxinhang1996** [comment]
抱歉，初次使用git，不知道如何上传文件，仅将压缩包中与导出时间一致的文档复制到这里

**Comment by FooIbar** [comment]
日志里没有什么有效信息
你能试下[这个版本](https://github.com/FooIbar/EhViewer/actions/runs/6677087005)再上传一次日志吗

**Comment by Pony-CW** [comment]
> 抱歉，初次使用git，不知道如何上传文件，仅将压缩包中与导出时间一致的文档复制到这里

上传文件用这个图标![Screenshot_2023-10-28-23-29-14-96_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/FooIbar/EhViewer/assets/44076275/4606eecd-d97a-4129-9afd-997d7df7be9a)

虽然是图片，但可以上传非图片文件，选择日志压缩包确定就行了

**Comment by lvxinhang1996** [comment]
[log-2023-10-28-06-44-25-017 (1).zip](https://github.com/FooIbar/EhViewer/files/13196237/log-2023-10-28-06-44-25-017.1.zip)
十分感谢告知，这里是我提出这个issue时的报告文件

**Comment by lvxinhang1996** [comment]
> 日志里没有什么有效信息 你能试下[这个版本](https://github.com/FooIbar/EhViewer/actions/runs/6677087005)再上传一次日志吗 上传文件通过输入框底部的 Attach files

十分抱歉。。我下载了里面最新的zip文件但是并不知道如何使用。。
这里是我刚刚通过软件内CI更新后生成的日志，问题依旧出现
[log-2023-10-29-00-11-04-872.zip](https://github.com/FooIbar/EhViewer/files/13196248/log-2023-10-29-00-11-04-872.zip)

**Comment by FooIbar** [comment]
> > 日志里没有什么有效信息 你能试下[这个版本](https://github.com/FooIbar/EhViewer/actions/runs/6677087005)再上传一次日志吗 上传文件通过输入框底部的 Attach files
> 
> 十分抱歉。。我下载了里面最新的zip文件但是并不知道如何使用。。 这里是我刚刚通过软件内CI更新后生成的日志，问题依旧出现 [log-2023-10-29-00-11-04-872.zip](https://github.com/FooIbar/EhViewer/files/13196248/log-2023-10-29-00-11-04-872.zip)

解压之后安装即可
很可惜，这份日志和之前一样不包含所需的调试信息

**Comment by asoulist** [comment]
> 日志里没有什么有效信息 你能试下[这个版本](https://github.com/FooIbar/EhViewer/actions/runs/6677087005)再上传一次日志吗 上传文件通过输入框底部的 Attach files

覆盖安装回1.8.10.2版本后也出现这个问题了
暂时可以用打开系统自由旋转开关在横屏模式下
点击开始阅读按钮(或已加载出来的缩略图)卡出正常阅读页面，(上个正常版本内设置为了竖屏/锁定竖屏)，在旋转回来时出现了加载图片的界面，试过很多次可以稳定复现。

**Comment by lvxinhang1996** [comment]
> > 日志里没有什么有效信息 你能试下[这个版本](https://github.com/FooIbar/EhViewer/actions/runs/6677087005)再上传一次日志吗 上传文件通过输入框底部的 Attach files
> 
> 覆盖安装回1.8.10.2版本后也出现这个问题了 暂时可以用打开系统自由旋转开关在横屏模式下 点击开始阅读按钮(或已加载出来的缩略图)卡出正常阅读页面，(上个正常版本内设置为了竖屏/锁定竖屏)，在旋转回来时出现了加载图片的界面，试过很多次可以稳定复现。

十分感谢！取消系统旋转锁定后，横屏状态进入阅读器，能够成功进入竖版阅读器了！个人认为可能是某些设置导致正常调用阅读器时出现了问题，因此也不会产生故障报告，期待作者更新！

**Comment by zycilcy** [comment]
我也遇到了这个bug，通过屏幕开启自由旋转可以暂时解决。

**Comment by FooIbar** [comment]
我大概知道是什么问题了，将于下个版本修复

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/releases/tag/1.8.10.3
