### ISSUE TITLE
在下载界面内，点开图片后退出，将短暂无法显示标题(包括画廊本身和右滑的标签)

### ISSUE THREAD

**Issue by Abraxas730** [FooIbar/EhViewer#1153]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/134248780/7b690d53-4f83-44cc-8d21-dc7298016054

在下载界面打开已下载的文件，退出后标题无法显示，包括画廊本身和下载标签的标题。可以看出必须来回上下刷页面才会恢复正常。
此外，切换成别的应用再切回来也会出现相同bug。

### 预期行为 / Expected behaviour

退出后可以直接显示标题

### 实际行为 / Actual Behaviour

黑屏，但可以拖动来恢复显示。

### 应用日志 / App logs

[log-2024-05-08-23-28-21-001.zip](https://github.com/FooIbar/EhViewer/files/15255737/log-2024-05-08-23-28-21-001.zip)

### 备注 / Addition details

我使用的版本是ujuiuju mandan的版本分支，这个分支仅维护代理相关事宜。

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.11.4.1

### EhViewer CI 版本 / EhViewer CI Version

df472b9

### Android 系统版本 / Android version

安卓14 oneui 6.1

### 设备型号 / Device model

三星s23u

### SoC 型号 / Soc model

8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [ ] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
其他版本与本仓库无关
