### ISSUE TITLE
下载内容会被文件资源管理器扫描到

### ISSUE THREAD

**Issue by BurgerL0ver** [FooIbar/EhViewer#1161]
### 复现步骤 / Step to reproduce

0.打开应用
1.下载内容
2.打开文件管理器
3.在最近文件列表中显示下载的内容

### 预期行为 / Expected behaviour

正常情况下下载的内容不会在文件资源管理器的最近文件列表中显示。

### 实际行为 / Actual Behaviour

但现在会被扫描出来

### 应用日志 / App logs

[log-2024-05-10-00-55-34-508.zip](https://github.com/FooIbar/EhViewer/files/15265114/log-2024-05-10-00-55-34-508.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.4

### EhViewer CI 版本 / EhViewer CI Version

71a4e84

### Android 系统版本 / Android version

android14 ONE UI 4.0

### 设备型号 / Device model

Samsung S22ultra

### SoC 型号 / Soc model

Snapdragon 8 Gen 1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你文件管理器的问题
如果你已经在设置里关闭了媒体扫描那没什么我们能做的
最多在下载设置里打开保存为压缩包
