### ISSUE TITLE
看图似乎跟的是下载设置

### ISSUE THREAD

**Issue by railgun100** [FooIbar/EhViewer#1170]
### 复现步骤 / Step to reproduce

下载设置并发1，延迟0，预载5，此时看图加载很慢
当把并发调成3，延迟和预载数不变，看图也流畅起来

### 预期行为 / Expected behaviour

如上

### 实际行为 / Actual Behaviour

如上

### 应用日志 / App logs

[log-2024-05-10-22-34-01-944.zip](https://github.com/FooIbar/EhViewer/files/15276281/log-2024-05-10-22-34-01-944.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0-snapshot

### EhViewer CI 版本 / EhViewer CI Version

02c1e63

### Android 系统版本 / Android version

ColorOS14

### 设备型号 / Device model

oneplus 12

### SoC 型号 / Soc model

骁龙8+gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
预期行为
