### ISSUE TITLE
开启“流量计费网络警告”选项时打开即崩溃

### ISSUE THREAD

**Issue by Pony-CW** [FooIbar/EhViewer#118]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.在正常时开启“流量计费网络警告”选项
2.正常退出
3.使用流量打开即立刻崩溃

### 预期行为 / Expected behaviour

正常运行

### 实际行为 / Actual Behaviour

立刻崩溃

### 应用日志 / App logs

[log-2023-10-28-12-34-11-334.zip](https://github.com/FooIbar/EhViewer/files/13194451/log-2023-10-28-12-34-11-334.zip)

### 备注 / Addition details

WiFi 正常
#113 也是这个原因，#117 可能也是
> 感觉也不好在相似 issue 下说这个，重新开更好

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT Default OSS

### EhViewer CI 版本 / EhViewer CI Version

e6a44ee

### Android 系统版本 / Android version

ColorOS 13.1 PGZ110_13.1.0.182(CN01) / Android 13

### 设备型号 / Device model

一加 Ace 竞速版 / OnePlus Ace Racing Edition / PGZ110

### SoC 型号 / Soc model

天玑 8100-MAX / Dimensity 8100-MAX

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Pony-CW** [comment]
嘶……#113 和这个没关系，因为我关了选项仍然崩溃，反正我是不懂了🫠

**Comment by FooIbar** [comment]
#141
