### ISSUE TITLE
IP没有被ban的情况下提示被ban

### ISSUE THREAD

**Issue by 8620hachiroku** [FooIbar/EhViewer#1182]
### 复现步骤 / Step to reproduce

![Screenshot_20240512_015113](https://github.com/FooIbar/EhViewer/assets/135826748/d303bfad-e627-46da-843a-d94cda48faf1)
![Screenshot_20240512_015059_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/135826748/2dead8ae-e4ca-402f-95f3-5ecf4368304c)
![Screenshot_20240512_015055_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/135826748/95f5f35b-eb6a-4621-b63f-4c386f75829b)

### 预期行为 / Expected behaviour

正常加载页面

### 实际行为 / Actual Behaviour

没有加载

### 应用日志 / App logs

[log-2024-05-12-01-53-30-962.zip](https://github.com/FooIbar/EhViewer/files/15283767/log-2024-05-12-01-53-30-962.zip)

### 备注 / Addition details

浏览器测试网站正常访问，没有被ban

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

3b83d87

### Android 系统版本 / Android version

EMUI 11

### 设备型号 / Device model

MRX-W09

### SoC 型号 / Soc model

Kirin 990

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 8620hachiroku** [comment]
更改默认的UA为 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 就恢复正常，不清楚原因，希望作者修改默认UA

**Comment by FooIbar** [comment]
如果是同一个 UA + IP 用的人多了导致的话，我们改成什么都是一样的
建议自己选择不同的 UA
