### ISSUE TITLE
收藏页面向下滑动时闪退

### ISSUE THREAD

**Issue by nopp7456** [FooIbar/EhViewer#1190]
### 复现步骤 / Step to reproduce

0. 重新安装
1. 打开eh
2. 登陆
3. 打开任意收藏列表
4. 滑动
5. 闪退

https://github.com/FooIbar/EhViewer/assets/48388256/4e08512b-ff0a-47be-aa70-f6730707aea7

### 预期行为 / Expected behaviour

正常滑动

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2024-05-12-04-29-26-113.zip](https://github.com/FooIbar/EhViewer/files/15286165/log-2024-05-12-04-29-26-113.zip)

### 备注 / Addition details

快速滑动必定触发，慢速则更稳定一些。印象里存在了很久，具体版本号记不清了

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

7276c37

### Android 系统版本 / Android version

One UI 6.1, Android 14

### 设备型号 / Device model

Samsung Galaxy Z Fold 5

### SoC 型号 / Soc model

Snapdragon 8 Gen 2 for Galaxy

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
从日志来看似乎是同一个画廊出现在了不同的两页里
用这个版本复现后再上传一下日志，添加了一些日志以便于进一步诊断
https://github.com/FooIbar/EhViewer/actions/runs/9058428307/artifacts/1496051335

**Comment by FooIbar** [comment]
> [log-2024-05-13-05-53-03-473.zip](https://github.com/FooIbar/EhViewer/files/15294755/log-2024-05-13-05-53-03-473.zip) 辛苦了

谢谢，日志很好，我已经知道出现这个问题的原因了
这其实是E站返回的数据的问题，出现重复项目的条件是：

1. 使用按收藏时间排序
2. 列表最后两项的收藏时间在同一秒

这也解释了为什么之前测试的时候没有发现
我之后会处理一下，过滤到重复的数据

**Comment by FooIbar** [comment]
已于 9e1f7ca 修复，更新至最新 CI 版本即可
