### ISSUE TITLE
是直接把访问网站的辅助功能给直接砍掉了吗？

### ISSUE THREAD

**Issue by X012C** [FooIbar/EhViewer#12]
### 复现步骤 / Step to reproduce

如题。

### 预期行为 / Expected behaviour

如题。

### 实际行为 / Actual Behaviour

如题。

### EhViewer 版本号 / EhViewer version code

如题。

### EhViewer CI 版本 / EhViewer CI Version

如题。

### Android 系统版本 / Android version

如题。

### 设备型号 / Device model

如题。

### SoC 型号 / Soc model

如题。

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
见更新日志https://github.com/FooIbar/EhViewer/releases/tag/1.8.9.0

**Comment by X012C** [comment]
> 见更新日志https://github.com/FooIbar/EhViewer/releases/tag/1.8.9.0

好的，刚从前面分支过来，没意识到这边已经更了几个版本的了。

**Comment by UjuiUjuMandan** [comment]
即使是 QUIC 直连也不想要吗，我觉得内置一个 cronet 增大了体积多数人也不在乎罢？

我是不是该维护一个加回内置 cronet 的分支？

**Comment by UjuiUjuMandan** [comment]
> 当前版本只会在下载图片时使用 cronet
那直连不是需要主站用 cronet + QUIC 嘛？图片的 .hath.network 没被封锁倒是用上了。

**Comment by UjuiUjuMandan** [comment]
> 所以不支持直连

可是可是，我想要直连啊。满足我的愿望吧。

**Comment by FooIbar** [comment]
> > 所以不支持直连
> 
> 可是可是，我想要直连啊。满足我的愿望吧。

你可以在 GMS 版的基础上把 b3a8547 revert 了，应该不用改太多

**Comment by UjuiUjuMandan** [comment]
行了，差不多能用了。

https://github.com/UjuiUjuMandan/EhViewer 。

**Comment by FooIbar** [comment]
> 行了，差不多能用了。
> 
> https://github.com/UjuiUjuMandan/EhViewer 。

GMS 版不需要内置 cronet，如果你要内置的话应该把 GMS 组件删了并修改`isCronetSupported`的条件

**Comment by UjuiUjuMandan** [comment]
> GMS 版不需要内置 cronet，如果你要内置的话应该把 GMS 组件删了并修改`isCronetSupported`的条件

GMS 有提供 ExperimentalCronetEngine 嘛？如果没有就需要内置吧。

**Comment by FooIbar** [comment]
> > GMS 版不需要内置 cronet，如果你要内置的话应该把 GMS 组件删了并修改`isCronetSupported`的条件
> 
> GMS 有提供 ExperimentalCronetEngine 嘛？如果没有就需要内置吧。

你现在其实用的就是 GMS 提供的 cronet，因为它的默认顺位最高

**Comment by UjuiUjuMandan** [comment]
> 你现在其实用的就是 GMS 提供的 cronet，因为它的默认顺位最高

那么，[删除这些行](https://github.com/UjuiUjuMandan/EhViewer/commit/56b30d3901f5a6594842c6887d3fa20a2ec1d68d)之后呢？

**Comment by FooIbar** [comment]
> > 你现在其实用的就是 GMS 提供的 cronet，因为它的默认顺位最高
> 
> 那么，[删除这些行](https://github.com/UjuiUjuMandan/EhViewer/commit/56b30d3901f5a6594842c6887d3fa20a2ec1d68d)之后呢？

这样可以
用 GMS 还是内置的取舍就是 文件更小 VS 支持更广

**Comment by Pony-CW** [comment]
> 行了，差不多能用了。
> 
> https://github.com/UjuiUjuMandan/EhViewer 。

牛皮，当初飞鸟澪去掉 SNI 等直连方式时，我也想 revert 回来
但一 revert 编译都过不了，看不懂编译日志和代码改都没法改🫠🫠🫠

**Comment by PennyFranklin** [comment]
> > 即使是 QUIC 直连也不想要吗，我觉得内置一个 cronet 增大了体积多数人也不在乎罢？
> > 
> > 我是不是该维护一个加回内置 cronet 的分支？
> 
> 有 GMS 版
> 而且我之前已经说过当前版本只会在下载图片时使用 cronet https://github.com/FooIbar/EhViewer/commit/37a3edd44bc21fb010f97d0db54c4270ea77d095#commitcomment-126890574

那也就是说每个大版本或者每过几个大版本就有一个支持直连的gms版本吗
