### ISSUE TITLE
严重卡顿，无法使用

### ISSUE THREAD

**Issue by Kgat9** [FooIbar/EhViewer#1210]
### 复现步骤 / Step to reproduce

视频1-验证是最新版

https://github.com/FooIbar/EhViewer/assets/149447502/c1888512-fdfa-48cc-bdaa-c3c1f2922ff9

视频2-开始不到半分钟便或点击返回键开始卡顿

https://github.com/FooIbar/EhViewer/assets/149447502/efbf3b3c-f86c-4796-b0f6-a8dfbce17610

视频3-重新打开点击标签必然卡顿

https://github.com/FooIbar/EhViewer/assets/149447502/0381ca5d-cacd-415b-a91b-496b8af8c074

### 预期行为 / Expected behaviour

它应该正常使用

### 实际行为 / Actual Behaviour

实际上卡顿崩溃的无法使用

### 应用日志 / App logs

[log-2024-05-16-10-57-17-795.zip](https://github.com/FooIbar/EhViewer/files/15329242/log-2024-05-16-10-57-17-795.zip)

### 备注 / Addition details

彩E一直是最好用的E站软件，但自从3月份更新后。便一直是无法使用的困难。有在UjuiUjuMandan发布地址那里反映却一直没解决。

近两月我不得不转用绿E或JHT。在收到邮件后我以为这次更新会回归。但结果任然是期望老版本的回归吧（哭哭）

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.3.4-cc

### EhViewer CI 版本 / EhViewer CI Version

d724014

### Android 系统版本 / Android version

Android10

### 设备型号 / Device model

OPPO R17

### SoC 型号 / Soc model

PBEM00

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
设置-高级里关闭列表项目动画试试

**Comment by FooIbar** [comment]
本仓库不处理其他版本的问题，自己去找对应维护者
