### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Kgat9** [FooIbar/EhViewer#1211]
### 复现步骤 / Step to reproduce

无法使用，打开没有反应。视频末尾点击返回键也会卡顿

https://github.com/FooIbar/EhViewer/assets/149447502/017a8507-b58b-4ea1-b97e-d597ce5db275

### 预期行为 / Expected behaviour

应该正常运行

### 实际行为 / Actual Behaviour

无法使用

### 应用日志 / App logs

[log-2024-05-16-12-15-20-652.zip](https://github.com/FooIbar/EhViewer/files/15330790/log-2024-05-16-12-15-20-652.zip)

### 备注 / Addition details

是这个账号彩E的最新版本，点击更新还会更新别人的版本？你们到底是什么关系。反馈问题被撤销，说是版本不同。那问题是此版本的软件无法使用。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.4

### EhViewer CI 版本 / EhViewer CI Version

71a4e84

### Android 系统版本 / Android version

Android10

### 设备型号 / Device model

OPPO R17

### SoC 型号 / Soc model

PBEM00

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
打开使用持续集成构建频道更新至最新 CI 版本
另：#12

**Comment by Kgat9** [comment]
> 打开使用持续集成构建频道更新至最新 CI 版本

去年5月份的1.8.8.3版本？古早版本，无法打开
![Screenshot_2024-05-16-16-22-05-66](https://github.com/FooIbar/EhViewer/assets/149447502/8eff715f-8d9a-4d5b-b53c-501716448093)

**Comment by Kgat9** [comment]
> 打开使用持续集成构建频道更新至最新 CI 版本 另：#12

你看看有哪不对
![F版无用1](https://github.com/FooIbar/EhViewer/assets/149447502/3c7150f9-23d3-4247-a79d-22d050d35187)
![F版无用2](https://github.com/FooIbar/EhViewer/assets/149447502/307a710c-ab19-4fc8-b550-fa01f492085a)

**Comment by FooIbar** [comment]
检查更新

**Comment by Kgat9** [comment]
> 检查更新

新版同样
![Screenshot_2024-05-17-08-57-19-14](https://github.com/FooIbar/EhViewer/assets/149447502/fa8d6b04-7f18-412d-bad4-e7dd5c1efbd3)
![Screenshot_2024-05-17-08-57-24-60](https://github.com/FooIbar/EhViewer/assets/149447502/a35c0ed9-0028-46a3-a838-1895b8c64089)
![Screenshot_2024-05-17-08-58-23-96](https://github.com/FooIbar/EhViewer/assets/149447502/fdd53bec-83b3-4130-9e49-90f957884144)

**Comment by tmby** [comment]
> > 检查更新
> 
> 新版同样
> ![Screenshot_2024-05-17-08-57-19-14](https://github.com/FooIbar/EhViewer/assets/149447502/fa8d6b04-7f18-412d-bad4-e7dd5c1efbd3)
> ![Screenshot_2024-05-17-08-57-24-60](https://github.com/FooIbar/EhViewer/assets/149447502/a35c0ed9-0028-46a3-a838-1895b8c64089)
> ![Screenshot_2024-05-17-08-58-23-96](https://github.com/FooIbar/EhViewer/assets/149447502/fdd53bec-83b3-4130-9e49-90f957884144)
> 

该版本无法直连，请自行代理

**Comment by BlackC0** [comment]
@FooIbar CI版本有在线apk下载吗 我不小心点了更新 升级到1.11.4 现在打不开了

**Comment by FooIbar** [comment]
> @FooIbar CI版本有在线apk下载吗 我不小心点了更新 升级到1.11.4 现在打不开了

https://github.com/FooIbar/EhViewer/actions

**Comment by FooIbar** [comment]
Duplicate of #1023
