### ISSUE TITLE
请求添加一个小功能

### ISSUE THREAD

**Issue by shirokurakana** [FooIbar/EhViewer#122]
### 复现步骤 / Step to reproduce

感谢作者的辛勤付出！
我注意到本项目使用的是Tachiyomi的阅读器实现，它有个著名的分支版本 [TachiyomiJ2K](https://github.com/Jays2Kings/tachiyomiJ2K)，此分支版本的阅读器中提供了一项我认为十分有用的功能：自定义滤镜中的【悬浮窗】选项。
长期以来，总是有一些整体颜色偏淡的本子，观感较差。开启这个选项后，就可以通过调节A滑块来调节画面上色条浓度（对比度？），极大提升了黑白本子的观感。以下为开启前后对比图：
![123123.jpg](https://s2.loli.net/2023/10/28/AdNQUR79GyzwXtB.jpg)

### 预期行为 / Expected behaviour

如果作者方便的话，希望能够添加上述功能。赞美作者！

### 实际行为 / Actual Behaviour

无

### EhViewer 版本号 / EhViewer version code

无

### EhViewer CI 版本 / EhViewer CI Version

无

### Android 系统版本 / Android version

无

### 设备型号 / Device model

无

### SoC 型号 / Soc model

无

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by nullArrayList** [comment]
草 确实

**Comment by FooIbar** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/669

**Comment by nullArrayList** [comment]
这个和那个不一样 是系统已经实现好的功能 https://github.com/FooIbar/EhViewer/blob/60f031e7e3330644c3d3b182d7dbbfc56d271903/app/src/main/res/layout/reader_color_filter_settings.xml#L239
给这个把string资源加上去就行
@shirokurakana 甚至你自己都可以来试试（

**Comment by nullArrayList** [comment]
https://github.com/FooIbar/EhViewer/blob/60f031e7e3330644c3d3b182d7dbbfc56d271903/app/src/main/kotlin/eu/kanade/tachiyomi/ui/reader/ReaderColorFilterView.kt#L23
这里已经handle过了

**Comment by ZerOri** [comment]
这个滤镜原版tachiyomi就有，叫“覆盖”，“悬浮窗”怎么看都是错误翻译
