### ISSUE TITLE
下载特定画廊的时候下载配额狂飙，但是进度条不变

### ISSUE THREAD

**Issue by RxinnotRstar** [FooIbar/EhViewer#1236]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/56676566/ede52727-e165-4d9c-ae02-976dc443cdfb

### 预期行为 / Expected behaviour

-

### 实际行为 / Actual Behaviour

下载配额以不正常的速度增长

下载进度始终为0

软件里的下载速度和状态栏的下载速度匹配不上

### 应用日志 / App logs

[log-2024-05-22-06-47-03-399.zip](https://github.com/UjuiUjuMandan/EhViewer/files/15396453/log-2024-05-22-06-47-03-399.zip)

### 备注 / Addition details

我勾选了原图下载。

因为我不能确定是程序代码本身的问题还是直连模块的问题，所以我会同时在原分支和直连分支（https://github.com/UjuiUjuMandan/EhViewer ）提同样的issue。

特定的画廊：https://exhentai.org/g/2857166/47fa65cc23

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.5-cc

### EhViewer CI 版本 / EhViewer CI Version

6d6e2f2

### Android 系统版本 / Android version

MIUI 14｜Android 13

### 设备型号 / Device model

redmi note 12 turbo

### SoC 型号 / Soc model

高通骁龙 7+ Gen 2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
本仓库不接受其他版本的问题

**Comment by RxinnotRstar** [comment]
> 本仓库不接受其他版本的问题



https://github.com/UjuiUjuMandan/EhViewer/issues/62

该问题已解决，是由于未知原因文件创建失败导致的异常。

希望此分支可以增加相关检测机制，避免再次出现该问题。
