### ISSUE TITLE
存储访问被拒绝时仍然继续请求API导致配额消耗

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1237]
### 复现步骤 / Step to reproduce

1. 设置好下载目录，给予应用对特定目录的访问权限。
2. 取消该权限，可以到系统设置中找到EhViewer，在存储设置中取消授权。（在 #1236 中这个权限被取消的原因未知）
3. 下载任意画廊。

### 预期行为 / Expected behaviour

应当告知用户本应用对相关目录没有访问权限。

### 实际行为 / Actual Behaviour

一直重试API并消耗配额。

参见 #1236 的录屏：

https://github.com/UjuiUjuMandan/EhViewer/assets/56676566/50880be2-712c-41b2-9da9-290b106bb7e1

### 应用日志 / App logs

[log-2024-05-22-14-22-16-199.zip](https://github.com/FooIbar/EhViewer/files/15400301/log-2024-05-22-14-22-16-199.zip)

### 备注 / Addition details

参见 #1236 。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

c87059e

### Android 系统版本 / Android version

Android 14 / CalyxOS 5.7.0

### 设备型号 / Device model

Google Pixel 5

### SoC 型号 / Soc model

Snapdragon 765G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
取消权限后再打开 app 时会提示无效的

**Comment by UjuiUjuMandan** [comment]
取消权限后直接打开不会提示，清掉后台应用再打开才会提示。

**Comment by FooIbar** [comment]
> 取消权限后直接打开不会提示，清掉后台应用再打开才会提示。

预期行为，正常情况下权限也不会在重启应用前被撤销

**Comment by UjuiUjuMandan** [comment]
> 权限也不会在重启应用前被撤销

可是在重启前确实撤销了。

**Comment by FooIbar** [comment]
> 可是在重启前确实撤销了。

故意撤销权限显然不是“正常情况”，我指的是由于系统更新/长时间未使用等原因导致的权限消失，这些都不应该在使用中发生
#1236 只在特定画廊出现，明显是别的问题导致的，只不过重新设置下载路径刚好解决了而已
