### ISSUE TITLE
搜索栏出现换行报错

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1258]
### 复现步骤 / Step to reproduce

执行示例搜索
```
1
1
```

### 预期行为 / Expected behaviour

![Screenshot_20240531_184408_org.mozilla.firefox.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/93c2b96b-f990-4233-92d9-ff816ef4ad71)

### 实际行为 / Actual Behaviour

对于表站
![Screenshot_20240531_183158_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/11ab4adf-c718-417f-ad27-6939c52057ca)
对于里站
![Screenshot_20240531_183206_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/9b5be3da-0c83-4e16-a810-30801a7d4bb9)

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

db1f0bc

### Android 系统版本 / Android version

HarmonyOS 4.0.0.137

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
我想知道什么情况下搜索文本里有换行符会是有效的用例
搜索栏回车会直接执行搜索，所以换行符只能是粘贴来的

**Comment by tmby** [comment]
> 我想知道什么情况下搜索文本里有换行符会是有效的用例
> 搜索栏回车会直接执行搜索，所以换行符只能是粘贴来的

今天我在识屏复制画廊标题，执行搜索以后发现了这个bug，经过测试以后才发现是换行符的问题
