### ISSUE TITLE
阅读为条漫或从上到下(连续)时，自由放大缩小后再次拖拽屏幕，会进入点按画面后的界面

### ISSUE THREAD

**Issue by Marsblast** [FooIbar/EhViewer#127]
### 复现步骤 / Step to reproduce

1. 将阅读模式设置为“条漫”或“从上到下（连续）”
2. 双击后拖动屏幕自由放大缩小画面（有时需要多次自由放大缩小后才会出现该情况）
3. 再次拖拽屏幕，会进入点按画面后的界面，并且每拖拽一次就会出现一次
4. 退出画廊重进可以恢复正常

我不知道能否在github插入gif，所以这里是复现演示的图床地址：https://freeimage.host/i/JffwLba

PS:如果只是双击放大缩小，而不是双击后拖拽画面自由选择放大缩小的尺度的话，则不会出现该情况

### 预期行为 / Expected behaviour

自由放大缩小画面后再拖拽画面，应当不会触发点按画面后的界面，而是正常拖拽画面

### 实际行为 / Actual Behaviour

自由放大缩小画面后，拖拽画面并松开手指后，会触发点按画面后的界面

### 备注 / Addition details

GIF是在电脑使用安卓12模拟器录制的，与手机端（Android13）出现的情况完全一致

### EhViewer 版本号 / EhViewer version code

1.8.10.2

### EhViewer CI 版本 / EhViewer CI Version

10c7019

### Android 系统版本 / Android version

Android13

### 设备型号 / Device model

oppo findx3pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Marsblast** [comment]
另外，希望可以恢复左右滑动呼出侧边栏的功能

**Comment by FooIbar** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/535
