### ISSUE TITLE
根据语言的搜索或附带翻译语言的tag搜索时，会不显示部分画廊

### ISSUE THREAD

**Issue by hood-cat** [FooIbar/EhViewer#1275]
### 复现步骤 / Step to reproduce

下方

### 预期行为 / Expected behaviour

例如直接点击作者"urakaryuu"tag时，会出现所有与作者相关的画廊
![S40604-11185385_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/90712651/45a8490d-1d9f-47bb-ab5b-f5a7e0c0ef0c)

### 实际行为 / Actual Behaviour

但是搜索框内输入该tag再搜索时会缺少部分画廊（语言为不限）
![S40604-11191471_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/90712651/4e54d438-c58a-4dcc-8fb7-54e10ee1ba1e)
带上"chinese"tag（或者语言为汉语）搜索时，直接不显示了…
![S40604-11193030_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/90712651/d7ab8c43-e862-4d96-b1a9-245ef5d1999b)

### 应用日志 / App logs

[log-2024-06-04-11-24-05-577.zip](https://github.com/user-attachments/files/15542125/log-2024-06-04-11-24-05-577.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6

### EhViewer CI 版本 / EhViewer CI Version

2ed17da

### Android 系统版本 / Android version

flyme 10.3

### 设备型号 / Device model

meizu 20

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [ ] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [ ] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
搜索类别选的什么？是不是把 DOUJINSHI 过滤了
