### ISSUE TITLE
非bug，也可能算bug，有点功能上的疑问

### ISSUE THREAD

**Issue by guest-zero** [FooIbar/EhViewer#1278]
### 复现步骤 / Step to reproduce

点击左上工具栏，依次点击设置→下载→恢复下载项或清理下载冗余

### 预期行为 / Expected behaviour

恢复未删除的下载项或清理仍存在的下载项

### 实际行为 / Actual Behaviour

优先清理下载冗余后，显示未发现冗余，但再点击恢复下载项后，仍会恢复下载项，但下载页面没出现多的下载项

### 应用日志 / App logs

无

### 备注 / Addition details

不清楚这个功能是否会清理仍在下载页面，但已经被版权的作品。
且有点题外话，为什么部分在较早期已下载的作品，在不勾选删除图片文件时，再次点击下载会进行重新下载？
具体情况如下
![Screenshot_2024-06-05-01-54-00-044_moe tarsin ehv](https://github.com/FooIbar/EhViewer/assets/133760269/6be8600a-4326-451f-ba0c-d63be82189cd)
![Screenshot_2024-06-05-01-54-15-215_moe tarsin ehv](https://github.com/FooIbar/EhViewer/assets/133760269/1035771c-dd2f-47c5-8068-a9a0f048d9ac)
![Screenshot_2024-06-05-01-54-20-106_moe tarsin ehv](https://github.com/FooIbar/EhViewer/assets/133760269/c375216c-2cd9-41e3-84fb-7d0e3b104cc2)
![Screenshot_2024-06-05-01-54-24-214_moe tarsin ehv](https://github.com/FooIbar/EhViewer/assets/133760269/26e1d7de-f6d5-45f8-ae5d-bd5f931ebb2b)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

 1.11.6-RC1

### EhViewer CI 版本 / EhViewer CI Version

最新版本

### Android 系统版本 / Android version

miui 14.0.8

### 设备型号 / Device model

红米note10pro

### SoC 型号 / Soc model

不确定

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你是不是移动过下载的文件？
这是因为数据库中的下载目录和实际的下载目录不一致，也是导致重新下载的原因
124 是更新了的数据库记录数

**Comment by guest-zero** [comment]
从旧版本移动过一次，然后就有了别的问题，就这个功能是否会清理仍在下载页面，但已经被版权的作品？之前有一次，没先阅读作品，而是先点击作品详情，然后页面显示作品已被删除，再阅读作品时已无法再阅读作品

**Comment by FooIbar** [comment]
不会
被版权的画廊无法阅读可能是移动时 .ehviewer 文件丢失了
