### ISSUE TITLE
无法获取已被封禁账号的用户名

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1285]
### 复现步骤 / Step to reproduce

1. 普通登录，或者网页登录。
2. 输入用户名 suspendthisaccount ，密码 password 。
3. 登录后进入EH设置。

### 预期行为 / Expected behaviour

显示用户名。

### 实际行为 / Actual Behaviour

显示游客模式。

### 应用日志 / App logs

[log-2024-06-07-13-46-44-466.zip](https://github.com/user-attachments/files/15710741/log-2024-06-07-13-46-44-466.zip)

### 备注 / Addition details

该错误是由于应用尝试从用户资料页获取信息，而被封禁的账号资料页不存在，无法获取到用户名和头像信息。

头像无关紧要，但是用户名可以直接就在封禁通知页面获取，在页面的左上位置。

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

4604a25

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

Google Pixel 5

### SoC 型号 / Soc model

N/A

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #134
