### ISSUE TITLE
屏蔽列表无法生效

### ISSUE THREAD

**Issue by Tsukihuyu** [FooIbar/EhViewer#129]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.添加任意屏蔽
2.刷新后屏蔽无法生效

### 预期行为 / Expected behaviour

屏蔽应该整成生效

### 实际行为 / Actual Behaviour

屏蔽无法生效

### EhViewer 版本号 / EhViewer version code

1.8.10.3

### EhViewer CI 版本 / EhViewer CI Version

8cde607

### Android 系统版本 / Android version

MIUI14

### 设备型号 / Device model

xiaomi13

### SoC 型号 / Soc model

8+gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现
