### ISSUE TITLE
从上到下（连续）翻页方式导致崩溃

### ISSUE THREAD

**Issue by naivecat** [FooIbar/EhViewer#1290]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/35908382/e7098f2d-8fa4-4c79-b32a-730049b6b7b4

### 预期行为 / Expected behaviour

0

### 实际行为 / Actual Behaviour

默认使用 从上到下&条漫 翻页方式会在浏览4页画面后崩溃，稳定复现，更改其他翻页方式可正常浏览

### 应用日志 / App logs

[log-2024-06-07-16-59-43-097.zip](https://github.com/user-attachments/files/15727459/log-2024-06-07-16-59-43-097.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-rc2

### EhViewer CI 版本 / EhViewer CI Version

70f4644

### Android 系统版本 / Android version

MIUI13.0.15

### 设备型号 / Device model

Xiaomi 12X

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你能试下这个版本吗 https://github.com/FooIbar/EhViewer/actions/runs/9293228045

**Comment by Melt69** [comment]
试了一下，从上到下、条漫这两种翻页方式似乎也会导致崩溃，从左到右和从右到左不会

**Comment by FooIbar** [comment]
> 试了一下，从上到下、条漫这两种翻页方式似乎也会导致崩溃，从左到右和从右到左不会

日志也传一下

**Comment by tmby** [comment]
> > 试了一下，从上到下、条漫这两种翻页方式似乎也会导致崩溃，从左到右和从右到左不会
> 
> 日志也传一下

![log-2024-06-08-13-15-35-021.zip](https://github.com/user-attachments/files/15746549/log-2024-06-08-13-15-35-021.zip)

**Comment by FooIbar** [comment]
> > 你能试下这个版本吗 https://github.com/FooIbar/EhViewer/actions/runs/9293228045
> 
> 该版本条漫阅读无闪退

RC1 有没有问题

**Comment by tmby** [comment]
> > > 你能试下这个版本吗 https://github.com/FooIbar/EhViewer/actions/runs/9293228045
> > 
> > 该版本条漫阅读无闪退
> 
> RC1 有没有问题

RC1 从上到下，条漫阅读无问题

**Comment by FooIbar** [comment]
> RC1 从上到下，条漫阅读无问题

https://github.com/FooIbar/EhViewer/actions/runs/9437053719
https://github.com/FooIbar/EhViewer/actions/runs/9437104661
这两个版本呢

**Comment by FooIbar** [comment]
> > https://github.com/FooIbar/EhViewer/actions/runs/9437053719
> 
> ![03e4e16.zip](https://github.com/user-attachments/files/15752900/03e4e16.zip)
> 
> > https://github.com/FooIbar/EhViewer/actions/runs/9437104661
> 
> 该版本无闪退 补充：似乎 #1284 也解决了，到目前为止没有发现bug复现。

https://github.com/FooIbar/EhViewer/actions/runs/9437273620
这个呢

**Comment by tmby** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/9437273620
> 这个呢

![log-2024-06-09-22-45-53-057.zip](https://github.com/user-attachments/files/15752989/log-2024-06-09-22-45-53-057.zip)

**Comment by FooIbar** [comment]
最新 CI 版本应该修复了这个问题
