### ISSUE TITLE
请问可以把域名前置添加回来吗？

### ISSUE THREAD

**Issue by iiikunn** [FooIbar/EhViewer#13]
### 复现步骤 / Step to reproduce

如题

### 预期行为 / Expected behaviour

能够在中国大陆直连ehviewer

### 实际行为 / Actual Behaviour

已经无法直连ehviewer

### 备注 / Addition details

彩E似乎是无可替代的好用，可惜目前没有直连功能。恳请作者将直连功能添加回来。

### EhViewer 版本号 / EhViewer version code

1.8.9.5

### EhViewer CI 版本 / EhViewer CI Version

如上

### Android 系统版本 / Android version

MIUI 14

### 设备型号 / Device model

REDMI12 turbo

### SoC 型号 / Soc model

骁龙7gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
Duplicate of #12

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer

**Comment by UjuiUjuMandan** [comment]
还有不是直连ehviewer，是直连e站。还有ehviewer不是e站。

**Comment by iiikunn** [comment]
> 还有不是直连ehviewer，是直连e站。还有ehviewer不是e站。

感谢感谢
