### ISSUE TITLE
在阅读时切换回桌面，短暂间隔后 再重新切回app内时会回退到对应的画廊页，并丢失阅读进度

### ISSUE THREAD

**Issue by BEIVSIQIN** [FooIbar/EhViewer#1302]
### 复现步骤 / Step to reproduce

在阅读时切换回桌面，短暂间隔后 再重新切回app内时会回退到对应的画廊页，并丢失阅读进度

### 预期行为 / Expected behaviour

之前的版本切回app内并不会回退到画廊页

### 实际行为 / Actual Behaviour

之前的版本切回app内并不会回退到画廊页

### 应用日志 / App logs

> 
[log-2024-06-13-01-51-13-404.zip](https://github.com/user-attachments/files/15809029/log-2024-06-13-01-51-13-404.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

*

### Android 系统版本 / Android version

originos 4

### 设备型号 / Device model

iqoo 11pro

### SoC 型号 / Soc model

8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by BEIVSIQIN** [comment]
演示情况如下
Uploading MXClip_Screenrecording_20240613_020706_2024_06_13_02_13_05.mp4…

**Comment by FooIbar** [comment]
你有试过最新 CI 版本吗
