### ISSUE TITLE
[不影响使用]切换网络导致搜索停滞

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1306]
### 复现步骤 / Step to reproduce

因为部分画廊只能在部分地区搜索到，因此切换了网络，但紧接着发生了搜索无法进行的问题： 1.搜索结果永远转圈; 2.转圈大约1-2分钟可以加载出来; 3.上述问题可以通过重开app避免并且瞬间加载

### 预期行为 / Expected behaviour

正常加载

### 实际行为 / Actual Behaviour

加载停滞

### 应用日志 / App logs

[log-2024-06-13-07-41-10-285.zip](https://github.com/user-attachments/files/15812036/log-2024-06-13-07-41-10-285.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

70f4644

### Android 系统版本 / Android version

Magic OS 8.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现，感觉是网络问题

**Comment by z1137** [comment]
此现象可能仅发生在切换到香港ip时，并且主要是出现退出应用后原先搜索卡顿结果瞬间打开这个现象，而如果在情况2加载后再次刷新则是正常加载了搜索但是依然比其他ip慢，不知为何。可能是香港ip会搜到更多画廊，那说不定exhentai的问题

**Comment by FooIbar** [comment]
不是 E 站的问题，是你梯子的问题

**Comment by z1137** [comment]
此问题以前未出现过，梯子也没有换过，更新至RC2后出现

**Comment by z1137** [comment]
看了下
`06-16 03:31:01.737 29983 29983 W HiTouch_PressGestureDetector: action:Up,touchSlop:24,interrupted:false
06-16 03:31:01.775 29983 30030 I OpenGLRenderer: graphicsLayer getImageFilter
06-16 03:31:01.786 29983 30030 E FrameEvents: updateAcquireFence: Did not find frame.`
这段刷了大概80多回
查了下隔壁视频软件的库也有这个错误，状态不明
目前唯一疑惑的是关闭app后可以瞬间加载，开着的情况下却不行

**Comment by FooIbar** [comment]
> 此问题以前未出现过，梯子也没有换过，更新至RC2后出现

没换过梯子不代表梯子的节点不会变，除非你是自建
可以降级到 RC1 试试


> `06-16 03:31:01.737 29983 29983 W HiTouch_PressGestureDetector: action:Up,touchSlop:24,interrupted:false 06-16 03:31:01.775 29983 30030 I OpenGLRenderer: graphicsLayer getImageFilter 06-16 03:31:01.786 29983 30030 E FrameEvents: updateAcquireFence: Did not find frame.`

跟这个无关

**Comment by z1137** [comment]
好像真是，降级后无论哪个ip都是应用内换ip搜索卡顿，但是重启应用瞬间成功搜索，但有的时候则是情况完全相反
