### ISSUE TITLE
使用TUN模式时无法联网

### ISSUE THREAD

**Issue by Ptilopsis01** [FooIbar/EhViewer#1317]
### 复现步骤 / Step to reproduce

1. clash启用TUN模式
![image](https://github.com/FooIbar/EhViewer/assets/93318731/2cc724b8-97db-4d82-b330-1770afde0ad2)

2. 打开Ehviewer
3. 无法正常连接
![image](https://github.com/FooIbar/EhViewer/assets/93318731/197e7e71-7f19-4de8-a21f-f3cecd72d93b)

### 预期行为 / Expected behaviour

在tun模式下正常联网

### 实际行为 / Actual Behaviour

如上所述

### 应用日志 / App logs

[log-2024-06-16-20-20-03-598.zip](https://github.com/user-attachments/files/15857933/log-2024-06-16-20-20-03-598.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.5

### EhViewer CI 版本 / EhViewer CI Version

ada8f3a

### Android 系统版本 / Android version

HyperOS A14

### 设备型号 / Device model

Xiaomi12S

### SoC 型号 / Soc model

sd8+g1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
不是我们的问题，向相关软件报告
