### ISSUE TITLE
老设备看不了条漫

### ISSUE THREAD

**Issue by sana9626** [FooIbar/EhViewer#1321]
### 复现步骤 / Step to reproduce

查看条漫

### 预期行为 / Expected behaviour

显示图片

### 实际行为 / Actual Behaviour

黑屏，没有图片

### 应用日志 / App logs

[log-2024-06-17-14-27-17-746.zip](https://github.com/user-attachments/files/15862961/log-2024-06-17-14-27-17-746.zip)

### 备注 / Addition details

试过之前的版本，1.10.2之前还可以的，1.10.3后就不行了，而且不是所以不显示，过长了的才不显示

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

无

### Android 系统版本 / Android version

Android 9

### 设备型号 / Device model

BKL-AL00

### SoC 型号 / Soc model

kirin970

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
打开裁剪边缘（屏幕方向右边的按钮）试下

**Comment by sana9626** [comment]
> 打开裁剪边缘（屏幕方向右边的按钮）试下

还是看不到

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/9562995122/artifacts/1612227392
试下这个版本

**Comment by sana9626** [comment]
依旧是有的看不到

**Comment by sana9626** [comment]
更新了Android System WEbView后重启下，就看得到了。劳烦你了

**Comment by FooIbar** [comment]
最新 CI 版本遇到长图加载问题可在 设置-高级 中调节硬件位图阈值
