### ISSUE TITLE
拖動產生黑屏

### ISSUE THREAD

**Issue by NeKoOuO** [FooIbar/EhViewer#1329]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/111511925/4d6189c6-24c4-40ea-bdea-bef623ccfdc4

### 预期行为 / Expected behaviour

不應該黑屏

### 实际行为 / Actual Behaviour

拖動產生黑屏

### 应用日志 / App logs

[log-2024-06-18-23-38-54-159.zip](https://github.com/user-attachments/files/15889089/log-2024-06-18-23-38-54-159.zip)

### 备注 / Addition details

推測是 upstream 問題因為有在別的應用發現同樣問題

### 浏览站点 / Browsing site

ExHentai 

### EhViewer 版本号 / EhViewer version code

1.11.6

### EhViewer CI 版本 / EhViewer CI Version

6d1d737

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Mi 10 ultra 

### SoC 型号 / Soc model

Snap865

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by revonateB0T** [comment]
这是历史界面还是别的界面？
历史界面是这样正常因为没有加载出来的条目没有placeholder

**Comment by NeKoOuO** [comment]
歷史介面和收藏

**Comment by FooIbar** [comment]
> 这是历史界面还是别的界面？ 历史界面是这样正常因为没有加载出来的条目没有placeholder

不是，是那个滚动条的实现有问题
