### ISSUE TITLE
部分公共账号无法获取 Profile，导致 Cookies 登录失败

### ISSUE THREAD

**Issue by Zhousiru** [FooIbar/EhViewer#134]
### 复现步骤 / Step to reproduce

0. 重新安装 App
1. 选择 Cookie 登录
2. 输入无法访问 Profile（但仍具有里站权限）的公共账号 Cookies
3. 登录，出现登录失败

### 预期行为 / Expected behaviour

希望无法访问 Profile 时可以添加一个对话框，询问用户是否继续储存 Cookies

### 实际行为 / Actual Behaviour

登录失败

### EhViewer 版本号 / EhViewer version code

1.8.10.3

### EhViewer CI 版本 / EhViewer CI Version

8cde607

### Android 系统版本 / Android version

MIUI 13.0.8, Android 12

### 设备型号 / Device model

Xiaomi 10

### SoC 型号 / Soc model

骁龙 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Zhousiru** [comment]
应该是这里校验的问题，这个评论也有反馈，但是 Issue 被 Close 了：https://github.com/Ehviewer-Overhauled/Ehviewer/issues/845#issuecomment-1464309397

https://github.com/FooIbar/EhViewer/blob/e2f024ae2917c11198172bb58e63782b82e3dfd2/app/src/main/kotlin/com/hippo/ehviewer/ui/login/CookieSignInScreen.kt#L125

**Comment by FooIbar** [comment]
封号了建议换个号

**Comment by Zhousiru** [comment]
虽然是这样，但还是希望未来可以考虑添加一个对话框，询问用户是否继续储存 Cookies
感谢接手 (≧∇≦)ﾉ

**Comment by FooIbar** [comment]
不考虑添加
