### ISSUE TITLE
下载版权本时会出现读取失败

### ISSUE THREAD

**Issue by zdfy5** [FooIbar/EhViewer#1348]
### 复现步骤 / Step to reproduce

附件录屏https://pan.baidu.com/s/1lWX9Iek2Hvd9nMz-GZEsWg?pwd=c545 
提取码:c545
一不小心脑抽把版权本删了想通过恢复下载项来恢复，但发现在读取未下载过且已被版权炮的本会出现读取失败的提示，读取已下载过且已被版权炮的本会出现自动返回且无法读取的现象。

### 预期行为 / Expected behaviour

之前安卓9时未出现过这种情况，如果是未被版权下架的本子是可以正常下载观看的。

### 实际行为 / Actual Behaviour

现在被版权下架的本子无法通过恢复下载项的方式来复原。

### 应用日志 / App logs

[log-2024-06-26-13-17-22-097.zip](https://github.com/user-attachments/files/15982786/log-2024-06-26-13-17-22-097.zip)

### 备注 / Addition details

已经下载的版权本不删除就不会出现问题，但删除了就无法恢复

### 浏览站点 / Browsing site

ExHentai和-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.6-rc2

### EhViewer CI 版本 / EhViewer CI Version

70f4644

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

pixel 7 pro

### SoC 型号 / Soc model

Google Tensor

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
下载目录里有没有 .ehviewer

**Comment by zdfy5** [comment]
> 下载內里有沒.ehviewer

没

**Comment by FooIbar** [comment]
如果没有开启保存为 CBZ 压缩包的话，恢复下载是需要 .ehviewer 文件的
在已下载但是 .ehviewer 文件丢失的情况下，可以将图片打包为以 GID 命名的 zip 文件，见https://github.com/FooIbar/EhViewer/releases/tag/1.11.6-RC1

**Comment by zdfy5** [comment]
> 如果没有开启保存为 CBZ 压缩包的话，恢复下载是需要 .ehviewer 的文件 在已下载但是 .ehviewer 文件丢失的话，可以将图片打包为以 GID 命名的 zip 文件，见https://github.com/FooIbar/EhViewer/releases/tag/1.11.6-RC1

通过一些手段恢复了.eh文件和.xml文件但还是出现闪退的问题。
如https://pan.baidu.com/s/1Bxlqcskigkh3qQpNIrbEBw?pwd=c545 
提取码:c545

翻了几页就闪退

**Comment by FooIbar** [comment]
闪退是不同的问题，已于最新 CI 版本修复

**Comment by zdfy5** [comment]
> > 如果没有开启保存为 CBZ 压缩包的话，恢复下载是需要 .ehviewer 的文件在已下载但是 .ehviewer 文件丢失的话，可以将图片打包为以 GID 命名的 zip 文件，见https://github.com/FooIbar/EhViewer/releases/tag/1.11.6-RC1
> 
> 通过一些手段恢复了.eh文件和.xml文件但仍然出现闪退的问题。 如[https://pan.baidu.com/s/1Bxlqcskigkh3qQpNIrbEBw?pwd=c545 ](https://pan.baidu.com/s/1Bxlqcskigkh3qQpNIrbEBw?pwd=c545%C2%A0) 提取代码:c545
> 
> 翻了页就闪退

曲线救国了，翻页从上到下改为左到右就好了😂

**Comment by FooIbar** [comment]
#1290
