### ISSUE TITLE
使用 CIFS documents provider 挂载的文件夹无法读取图片

### ISSUE THREAD

**Issue by Mapaler** [FooIbar/EhViewer#1356]
## 背景

在 *Ehviewer-Overhauled* 开发时我曾提出希望按照普通的文件夹进行管理，这样有利于进行增量更新。 https://github.com/Ehviewer-Overhauled/Ehviewer/issues/493

1. 我以前是插TF卡的，自从手机不能插TF卡后，我就只能用OTG功能外挂固态硬盘来使用额外储存。我希望这些数据是便携的。  
    ![Strip 1](https://github.com/FooIbar/EhViewer/assets/6565860/ab611b44-26ee-48c5-8d9c-5597db3faea9)
2. 晚上一般手机都没电了，再外挂很容易电量不足，我目前的解决方案是用Swtich便携充电底座来实现OTG+充电功能。缺点是受充电头限制，仍然得连接一条线，同时3.0全功能线又粗又短。  
    ![IMG_20240629_044324](https://github.com/FooIbar/EhViewer/assets/6565860/aab95f4c-f081-4b8d-999b-263ab98089b2)
3. 之前在 #52 了解到 [CIFS Documents Provider](https://github.com/wa2c/cifs-documents-provider) 这个软件，如果能够使用的话，可以很大程度解决问题。

## 复现步骤 / Step to reproduce

1. 移动硬盘插电脑上，打开共享。将用来登陆的账号的共享权限设为完全控制，以确保能写入。
![dllhost_aak5cFN07u](https://github.com/FooIbar/EhViewer/assets/6565860/af884dfa-b3b3-4246-a063-10f404b3e1d2)
（设置SMB共享还有一些细节此处略过）
2. *CIFS Documents Provider* 挂载局域网文件夹
![HD-Player_hsEdinT1il](https://github.com/FooIbar/EhViewer/assets/6565860/d265aee8-f24e-412e-b53c-167db1c48b0f)![HD-Player_tPjPvHlkn3](https://github.com/FooIbar/EhViewer/assets/6565860/7ba63f80-9805-4cc0-9563-5c8efff122f9)
3. *EhViewer* 内选择下载文件夹到 *CIFS Documents Provider* 内设定好的文件夹。
![HD-Player_R8H1vIrH9h](https://github.com/FooIbar/EhViewer/assets/6565860/5047a81c-49f7-4c51-8881-9135a774a6ca)
![HD-Player_J1YWjSECue](https://github.com/FooIbar/EhViewer/assets/6565860/10c28f05-ca9b-4dce-a8de-d6938d7721ec)
4. 不爬梯（即保证不是E站远端图片），打开下载列表。（为了方便我用模拟器演示，已导入手机数据，问题和手机上一样）
5. 读取下载列表时可以正常读取到缓存的图片封面，移动硬盘也显示有读取。  
![TotalCMD64_AgRoQy6KLd](https://github.com/FooIbar/EhViewer/assets/6565860/232fef56-dfd7-453c-bd36-438a55236199)
6. 打开画廊查看已完成的图片时发生错误。

### 预期行为 / Expected behaviour

和使用 OTG 时一样，可以正常读取图片。

### 实际行为 / Actual Behaviour

实际上没有读取文件夹内已下载图片，只从远端下载。

## 视频片段

1. 可以正常读取到缓存的图片封面，移动硬盘也显示有读取，但是无法读取已下载的画廊图片。

    https://github.com/FooIbar/EhViewer/assets/6565860/f2767968-93bf-4595-a41e-c8f52525fc5b

2. 爬梯后也可以正常写入新的下载，在本地缓存内时也能查看图片。但是一旦下载完成后，就无法读取下载目录的图片。

    https://github.com/FooIbar/EhViewer/assets/6565860/660ff3ab-327c-4afb-b0b9-234647b17985
   
### 应用日志 / App logs

[log-2024-06-29-04-29-44-269.zip](https://github.com/user-attachments/files/16036545/log-2024-06-29-04-29-44-269.zip)

### 备注 / Addition details
SMB 共享时容易失败的细节

由于 Win10 的安全性要求，SMB 共享需要通过有密码的账户来访问。

如果使用微软账户登录的账号，可能需要关闭**要求 Microsoft 账户使用 Windows Helllo 登录**。

![ApplicationFrameHost_Fmr4X4k9Pw](https://github.com/FooIbar/EhViewer/assets/6565860/1c9923c6-5b10-4685-9f59-b43e87dde28b)

之后锁定账户，使用微软账号密码登陆一次，这样才能将密码添加到账户里，密码就是微软账户密码。

在手机上添加SMB服务器时，可以使用这个账户在 计算机管理-本地用户和组-用户 内看到的名称，也可以用 微软账号的邮箱登录。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC1

### EhViewer CI 版本 / EhViewer CI Version

6d1d737

### Android 系统版本 / Android version

MIUI 14.0.9, BlueStacks 5-安卓9

### 设备型号 / Device model

Redmi K40s, BlueStacks 5-安卓9

### SoC 型号 / Soc model

晓龙870, Xeon E5-2696 v2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by revonateB0T** [comment]
你打开了 下载-保存为cbz 开关?
为了实现高性能读取 此功能需要文件系统下的文件可被内存映射(https://man7.org/linux/man-pages/man2/mmap.2.html)

**Comment by Mapaler** [comment]
![Screenshot_2024-06-29-07-28-34-078_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/6565860/a80c54f9-0570-4ae0-adce-a1a2f8088575)

当然没有，我平时都是保存为独立图片。

**Comment by FooIbar** [comment]
CIFS Documents Provider 的实现有问题
![image](https://github.com/FooIbar/EhViewer/assets/118464521/654b0e0b-5fe9-4d94-9125-51270af453e7)
![image](https://github.com/FooIbar/EhViewer/assets/118464521/a60e86c4-2b0a-4f40-9f18-58de1c24a9ac)

**Comment by FooIbar** [comment]
你可以试下 https://github.com/FooIbar/EhViewer/actions/runs/9723289585
不过这玩意就算能用也速度感人

**Comment by Mapaler** [comment]
> 其实不是，是我们在[这里](https://github.com/FooIbar/EhViewer/blob/7e7be8d40a34c64f31c8cf8a4d15bbe5dc34199b/app/src/main/kotlin/com/hippo/unifile/DocumentsContractApi21.kt#L36-L38)依赖实现细节了

不是很明白“依赖实现细节”是什么意思。

> 你可以试下 https://github.com/FooIbar/EhViewer/actions/runs/9723289585 不过这玩意就算能用也速度感人

目前确实是可以用了，这样使用网络共享的话，还可以实现多个设备共用一个下载目录。

我可以同时用 模拟器(本机网络连接) 和 真实手机(通过WiFi访问) 读取电脑硬盘里这个共享目录。

https://github.com/FooIbar/EhViewer/assets/6565860/49b94c9f-52ed-4b22-a327-0842f6197788

**Comment by Mapaler** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/493

另外想问一下这里说的增量更新功能是否有可能内置实现呢？

以前我可以用明文的 .ehviewer 内编号和hash来对应图片，现在改成了二进制文件，就不知道怎么手动操作了。

**Comment by FooIbar** [comment]
> [Ehviewer-Overhauled/Ehviewer#493](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/493)
> 
> 另外想问一下这里说的增量更新功能是否有可能内置实现呢？

不在短期计划内

> 以前我可以用明文的 .ehviewer 内编号和hash来对应图片，现在改成了二进制文件，就不知道怎么手动操作了。

现在的 .ehviewer 是 CBOR 格式的，可以随便找个在线解码器或者写个脚本解码

**Comment by Mapaler** [comment]
> > 以前我可以用明文的 .ehviewer 内编号和hash来对应图片，现在改成了二进制文件，就不知道怎么手动操作了。
> 
> 现在的 .ehviewer 是 CBOR 格式的，可以随便找个在线解码器或者写个脚本解码

我观察了一下二进制，发现下载新的画廊时，不会先获取所有页面的hash值，`.ehviewer`文件是按需求动态更新的。这样我就无法去对应图片的编号，也无法手动更新。

**Comment by FooIbar** [comment]
> > > 以前我可以用明文的 .ehviewer 内编号和hash来对应图片，现在改成了二进制文件，就不知道怎么手动操作了。
> > 
> > 
> > 现在的 .ehviewer 是 CBOR 格式的，可以随便找个在线解码器或者写个脚本解码
> 
> 我观察了一下二进制，发现下载新的画廊时，不会先获取所有页面的hash值，`.ehviewer`文件是按需求动态更新的。这样我就无法去对应图片的编号，也无法手动更新。

以前也是动态更新的
