### ISSUE TITLE
搜尋autocomplete沒有顯示所有的結果

### ISSUE THREAD

**Issue by newbiegituserj** [FooIbar/EhViewer#1361]
### 复现步骤 / Step to reproduce

1. Click on homepage
2. Go to the top search bar
3. Type in yagen
4. Don't hit enter. Just let autocomplete results show up.
5. See results from autocomplete

### 预期行为 / Expected behaviour

The autocomplete result "g:yagen nankotsu" should show up

### 实际行为 / Actual Behaviour

Did not see the expected result:
"g:yagen nankotsu" 

Only see: 
a:hakuyagen
a:kitamiya genbu
a:tsurimiya gen
c:yagen toushirou

### 应用日志 / App logs

None

### 备注 / Addition details

常常有看到此類問題，autocomplete無法顯現所有的結果
像查“fujii"，autocomplete不會秀"a:fujii akiko"
查”yuriko," autocomplete不會秀“g:yuriko club"

謝謝
### 浏览站点 / Browsing site

都有

### EhViewer 版本号 / EhViewer version code

1.11.6-RC1

### EhViewer CI 版本 / EhViewer CI Version

6d1d737

### Android 系统版本 / Android version

android 14

### 设备型号 / Device model

pixel 3

### SoC 型号 / Soc model

none

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
自动补全使用的数据库是社区维护的，有缺自己加 https://github.com/EhTagTranslation/Database
