### ISSUE TITLE
网站设置好的图片分辨率在ehviewer中会变动

### ISSUE THREAD

**Issue by Celticwind** [FooIbar/EhViewer#137]
### 复现步骤 / Step to reproduce

正常使用

### 预期行为 / Expected behaviour

加载在网站的设置中设定的分辨率

### 实际行为 / Actual Behaviour

我设定的是2400x，刚开始浏览是正常的，但是过了一会图片的分辨率就变成auto，降到780x

### 备注 / Addition details

使用PC在网站设置好2400x的分辨率后，网页浏览的图片大小符合分辨率设定的。
但是在ehviewer中使用，图片变得很糊，去网站后发现分辨率变成了auto，按照10.27的改动，加载的是780x的分辨率。
我只有一个default profile，所以app使用的就是网站设定好的分辨率，但是为何会从2400x变成auto？
另外，在app设置中进入网页修改会遇到设定2400x点击apply后变成了1280x的情况，此时使用PC登录网站发现也变成了1280x。
在e站论坛我也发帖询问了，目前还不能确定是哪一边出现的问题。所以我在这里也提交一个issue。

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

e2f024a

### Android 系统版本 / Android version

Harmony OS 3.0

### 设备型号 / Device model

HUAWEI MATE 20

### SoC 型号 / Soc model

麒麟980

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你使用的画廊站点是？
是否开启了强制使用 e-hentai 缩略图/API服务器？

**Comment by Celticwind** [comment]
这个选项我是关闭的

**Comment by FooIbar** [comment]
能否提供以下操作的录屏：

1. 在 app 中进入网站设置
2. 修改设置并确定
3. 再次进入网站设置

**Comment by Celticwind** [comment]
好的，我录一下

**Comment by FooIbar** [comment]
你的 UID 是否小于 3,000,000
还是通过hath perk/捐赠获得的2400x选项？

**Comment by Celticwind** [comment]
我是使用hath perk获得的

**Comment by fenfenyangyangmate** [comment]
这似乎并不是bug，我在论坛上看到tenboro在forums里回复到∶
I primarily browse e-hentai on mobile, and although the rest of the update is pretty good, I severely dislike this change to make resamples smaller by default on mobile. It makes the image samples needlessly small and blurry. By any chance, would you please consider reverting it back to 1280x by default instead of 780x by default?

The change was made due to UI scaling, and I'm not planning on reverting it. People can choose 1280x manually if they want it.

**Comment by fenfenyangyangmate** [comment]
> 你的UID是否小于3,000,000 还是通过hath perk/转让获得的2400x选项？

这似乎并不是bug，我在论坛上看到tenboro在forums里回复到∶
I primarily browse e-hentai on mobile, and although the rest of the update is pretty good, I severely dislike this change to make resamples smaller by default on mobile. It makes the image samples needlessly small and blurry. By any chance, would you please consider reverting it back to 1280x by default instead of 780x by default?

The change was made due to UI scaling, and I'm not planning on reverting it. People can choose 1280x manually if they want it.

**Comment by FooIbar** [comment]
> > 你的UID是否小于3,000,000 还是通过hath perk/转让获得的2400x选项？
> 
> 这似乎并不是bug，我在论坛上看到tenboro在forums里回复到∶ I primarily browse e-hentai on mobile, and although the rest of the update is pretty good, I severely dislike this change to make resamples smaller by default on mobile. It makes the image samples needlessly small and blurry. By any chance, would you please consider reverting it back to 1280x by default instead of 780x by default?
> 
> The change was made due to UI scaling, and I'm not planning on reverting it. People can choose 1280x manually if they want it.

你没看懂他说的是啥，和这个issue完全是两个问题

**Comment by fenfenyangyangmate** [comment]
> > > 你的UID是否小于3,000,000 还是通过hath perk/转让获得的2400x选项？
> > 
> > 
> > 这似乎并不是bug，我在论坛上看到tenboro在forums里回复到∶ I primarily browse e-hentai on mobile, and although the rest of the update is pretty good, I severely dislike this change to make resamples smaller by default on mobile. It makes the image samples needlessly small and blurry. By any chance, would you please consider reverting it back to 1280x by default instead of 780x by default?
> > 该更改是由于 UI 缩放而进行的，我不打算恢复它。人们可以根据需要手动选择 1280x。
> 
> 你没看懂他说的是啥，和这个issue完全是两个问题

看来是的，我本以为是自动 UI 缩放所导致的

**Comment by OkazakiUshio0** [comment]
UA改成
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36 JiSu/100.0.0.14
试试

**Comment by tmby** [comment]
你是拿cookies直接登的吗？要不要试试重新获取cookies登录？

**Comment by Celticwind** [comment]
> UA改成 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36 JiSu/100.0.0.14 试试

没有在ehviewer中看见修改UA的选项。

**Comment by tmby** [comment]
> > UA改成 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36 JiSu/100.0.0.14 试试
> 
> 没有在ehviewer中看见修改UA的选项。

ci版本的高级选项里

**Comment by Celticwind** [comment]
目前结果是不使用cookie登录，而是退出然后使用账号密码登录解决了这个问题。跟UA应该无关，默认就是Chrome的UA。

**Comment by Celticwind** [comment]
使用账号密码登录又会变回去，所以我重新打开了这个issue。而且我发现即使是在平板（三星Tab S6）上用Firefox浏览器登录，也遇到了修改2400x保存然后还是1280x的情况。但很诡异的是在电脑上就可以修改成功，这是什么情况？🍍直接检测设备名称？发现是移动设备所以不能修改嘛？疑点很多，而且平板上修改浏览器的UA也没有效果。

**Comment by Celticwind** [comment]
使用账号密码登录又会变回去，所以我重新打开了这个issue。而且我发现即使是在平板（三星Tab S6）上用Firefox浏览器登录，也遇到了修改2400x保存然后还是1280x的情况。但很诡异的是在电脑上就可以修改成功，这是什么情况？🍍直接检测设备名称？发现是移动设备所以不能修改嘛？疑点很多，而且平板上修改浏览器的UA也没有效果。

**Comment by FooIbar** [comment]
如果连浏览器也有问题应该直接向菠萝报告，这不是我们能控制的

**Comment by Celticwind** [comment]
嗯，我同时也去论坛发帖了。

**Comment by FooIbar** [comment]
我好像没在论坛看到你的帖子，怕不是被删了
你可以再发一个不要提第三方app，或者直接私信菠萝

**Comment by Celticwind** [comment]
好的，我私信菠萝吧

**Comment by Celticwind** [comment]
问题似乎解决了（？，可能🍍调整了反爬虫的措施，群里也有人遇到了同样的问题。按照群友说的把下载延时调高（我调到5000）和并发下载数调成1，浏览了很久分辨率都不会发生变动。缺点就是载图有时候慢了点，还能接受吧。

**Comment by XiaoMiao458331** [comment]
现在的情况是，不管是您的APP最新版还是隔壁新彩eh，我登录之后想改动移动端为1600x，均无法成功，刷新就回到1280x或者auto

**Comment by mirh** [comment]
\>1280x可为高级会员保留. 也许尝试[这些建议](https://github.com/FooIbar/EhViewer/issues/111#issuecomment-1792052843). 

Anyway, my suggestion would be for db57e2dde6033d50361d8111f0480f8eb2019e00 to be reverted or at least partially adjusted. 
It seems clear that the big unexpected hurdle is triggering the mobile filter downgrade.

**Comment by FooIbar** [comment]
> >1280x可为高级会员保留. 也许尝试[这些建议](https://github.com/FooIbar/EhViewer/issues/111#issuecomment-1792052843).
> 
> Anyway, my suggestion would be for [db57e2d](https://github.com/FooIbar/EhViewer/commit/db57e2dde6033d50361d8111f0480f8eb2019e00) to be reverted or at least partially adjusted. It seems clear that the big unexpected hurdle is triggering the mobile downgrade filter.

Nah, the mobile filter has nothing to do with this.
Someone faced this even with PC https://github.com/ccloli/E-Hentai-Downloader/issues/274.
