### ISSUE TITLE
无法下载或观看部分漫画。

### ISSUE THREAD

**Issue by 8008208820DHC** [FooIbar/EhViewer#1375]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/174375457/01903b33-2bc9-4599-9e72-c449b8979243

### 预期行为 / Expected behaviour

应该正常下载或观看。

### 实际行为 / Actual Behaviour

事实上它一直显示余额不足或者一直加载。

### 应用日志 / App logs

[log-2024-07-02-12-30-25-343.zip](https://github.com/user-attachments/files/16061714/log-2024-07-02-12-30-25-343.zip)

### 备注 / Addition details

比如下载这个漫画。https://exhentai.org/g/1593641/a8105523eb
有图片配额的情况下，不管什么时间，用哪里的节点，都一直无法下载，也无法观看。大部分时间显示余额不足，另一部分时间就一直加载不出来。目前这种情况已经碰到了十一个漫画。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.6-RC2

### EhViewer CI 版本 / EhViewer CI Version

70f4644

### Android 系统版本 / Android version

1.0.8.0.UNXCNXM/Android14

### 设备型号 / Device model

小米pad 6s Pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 8008208820DHC** [comment]
以上问题使用手机也无法下载或观看。

**Comment by 8008208820DHC** [comment]
以上问题使用手机也无法下载或观看。

**Comment by 8008208820DHC** [comment]
以上问题使用手机下载或观看也是一样的。

**Comment by FooIbar** [comment]
没 GP 别开原图 https://ehwiki.org/wiki/Downloading
