### ISSUE TITLE
更新后无法下载图库，也无法查看已下载图库

### ISSUE THREAD

**Issue by vexling201515** [FooIbar/EhViewer#1379]
### 复现步骤 / Step to reproduce

更新到最新版，无法阅读已下载图库，无法下载新图库

### 预期行为 / Expected behaviour

应该正常观看已下载图库，正常下载新图库

### 实际行为 / Actual Behaviour

更新到最新版后下载列表的图库缩略图无法加载，点击阅读已下载图库中图片无法显示，下载新图库会失败闪退
此外生成的应用日志过大

### 应用日志 / App logs

[log-2024-07-04-00-25-03-947.zip](https://github.com/user-attachments/files/16087987/log-2024-07-04-00-25-03-947.zip)

### 备注 / Addition details

无法下载新图库，即使有新版本可能也无法在app内更新，希望提供能稳定使用的旧版本

### 浏览站点 / Browsing site

E-hentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

c805ca8

### Android 系统版本 / Android version

Android14

### 设备型号 / Device model

iQOO Neo8 Pro

### SoC 型号 / Soc model

3.35GHz 天玑 8200+ 八核

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by vexling201515** [comment]
降级到：https://github.com/FooIbar/EhViewer/actions/runs/9755678942
这个版本后能正常使用了

**Comment by FooIbar** [comment]
日志是旧版的，缺少最新版本闪退的日志

**Comment by FooIbar** [comment]
可以备份数据之后全新安装

**Comment by FooIbar** [comment]
是

**Comment by vexling201515** [comment]
> 是

安装刚发布的版本吗？：https://github.com/FooIbar/EhViewer/actions/runs/9794272023

**Comment by FooIbar** [comment]
是，清除数据然后直接更新也行

**Comment by vexling201515** [comment]
导出来了：[log-2024-07-04-20-47-10-256.zip](https://github.com/user-attachments/files/16099123/log-2024-07-04-20-47-10-256.zip)
