### ISSUE TITLE
GMS 版本会被提示更新至 Latest Release 版本

### ISSUE THREAD

**Issue by cherinyy** [FooIbar/EhViewer#14]
### 复现步骤 / Step to reproduce

0. 安装 GMS 版本应用
1. 检查更新

### 预期行为 / Expected behaviour

它应该获取 GMS 版本更新信息

### 实际行为 / Actual Behaviour

实际上它获取了所有 Release 版本的更新信息

![Screenshot_2023-09-15-02-27-39-57_f2f1746601bf3b868d00d5efaf12e601](https://github.com/FooIbar/EhViewer/assets/9050713/53483c87-3dcf-4e1d-b635-92c28ed2dfd9)

### EhViewer 版本号 / EhViewer version code

 1.8.9.5-gms

### EhViewer CI 版本 / EhViewer CI Version

 e94424a

### Android 系统版本 / Android version

Android 12

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
Fixed by https://github.com/FooIbar/EhViewer/commit/01742ac6b913f42b3a65fbe72bee7d26c790b70a
不过 GMS 版基本上不会有 CI 版本
