### ISSUE TITLE
滚动条大小不固定

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1400]
### 复现步骤 / Step to reproduce

搜索`group:rockinchair$`

### 预期行为 / Expected behaviour

正常大小
![Screenshot_20240710_085744_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/339773fa-ecbb-4629-b9e5-29281048b933)

### 实际行为 / Actual Behaviour

超级大
![Screenshot_20240710_085507_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/2dad0417-b78d-456c-8691-441d70454f25)

### 应用日志 / App logs

无

### 备注 / Addition details

搜索画廊很少的tag就会出现这种情况。

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

8164847

### Android 系统版本 / Android version

HarmonyOS 4.2.0.125

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
预期行为
