### ISSUE TITLE
搜索画廊时显示什么都没有找到

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1418]
### 复现步骤 / Step to reproduce

搜索`uploader:chenjingjun`

### 预期行为 / Expected behaviour

不显示什么都没有找到

### 实际行为 / Actual Behaviour

![Screenshot_20240713_170300_moe tarsin ehviewer](https://github.com/user-attachments/assets/f666d311-d022-4669-9b7b-8c001fc94ae9)
显示什么都没有找到

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

c09173d

### Android 系统版本 / Android version

HarmonyOS 4.2.0.125

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
这似乎是 E 站的一个错误，搜索该上传者有两页，但第二页其实是空的

**Comment by tmby** [comment]
> 这似乎是 E 站的一个错误，搜索该上传者有两页，但第二页其实是空的

在订阅中，我搜索`m:"males only$"`和`m:yaoi$`
出现了`解析失败`和`什么都没有找到`
操作视频如下：
https://github.com/user-attachments/assets/28f153c6-82f6-43c3-ba8f-a3aea2da3733

日志：![log-2024-08-17-16-39-32-359.zip](https://github.com/user-attachments/files/16644148/log-2024-08-17-16-39-32-359.zip)
