### ISSUE TITLE
闲置一段时间之后再启动会闪退一次

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#142]
### 复现步骤 / Step to reproduce

1. 打开 EhViewer 再回到桌面。
2. 等一段时间，是多少我不确定，测过 10 分钟是不够的。
3. 再次打开 EhViewer。

### 预期行为 / Expected behaviour

回到上次位置。

### 实际行为 / Actual Behaviour

出现 splashscreen 之后立即闪退。

### 应用日志 / App logs

https://fars.ee/lEaa.txt

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.10.3

### EhViewer CI 版本 / EhViewer CI Version

e2f024a

### Android 系统版本 / Android version

GrapheneOS: Android 14

### 设备型号 / Device model

N/A

### SoC 型号 / Soc model

N/A

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
版本号和 CI 版本不匹配

**Comment by UjuiUjuMandan** [comment]
> 版本号和 CI 版本不匹配

因为我在 UUM fork ，就找了个同步到了的 commit 填了。

**Comment by UjuiUjuMandan** [comment]
等我换到你的版本用几天再看看。

**Comment by FooIbar** [comment]
Release 版的日志是混淆了的，版本不对还原不了堆栈

**Comment by UjuiUjuMandan** [comment]
似乎是 bypassVpn 的问题，其在 installSplashScreen 之前会执行一次。

但是我也懒得排查 bypassVpn 有什么问题了，直接删除好了。
