### ISSUE TITLE
退出阅读器后，在画廊详情页立即触发返回手势但不返回，会导致app卡顿或者白屏

### ISSUE THREAD

**Issue by lings03** [FooIbar/EhViewer#1423]
### 复现步骤 / Step to reproduce

随便点击一本画廊，进入阅读器后退出，在画廊详情界面长按触发返回手势动画但不返回

### 预期行为 / Expected behaviour

正常显示画廊详情界面

### 实际行为 / Actual Behaviour

实际出现卡顿或者白屏

退出阅读器后尝试
https://github.com/user-attachments/assets/40f69343-94d1-4746-abfc-fcd7fccb6e2a
https://github.com/user-attachments/assets/0d874d6c-7378-45e2-9fc4-44541a84fa15

不进入阅读器直接触发的正常情况
https://github.com/user-attachments/assets/2cbdedc5-e408-4cd6-bb9e-ca0c7947cba5

### 应用日志 / App logs

[log-2024-07-16-00-06-50-274.zip](https://github.com/user-attachments/files/16237272/log-2024-07-16-00-06-50-274.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

5d92fc6 最近的ci版均有此问题

### Android 系统版本 / Android version

hyperos1.03 安卓14

### 设备型号 / Device model

note12turbo

### SoC 型号 / Soc model

骁龙7+gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
最近我们重构了阅读器，最新 CI 版本是否还有这个问题？

**Comment by lings03** [comment]
用最新ci版测试了一下，的确没问题了
