### ISSUE TITLE
阅读器页面过渡动画无法被关闭

### ISSUE THREAD

**Issue by devioa** [FooIbar/EhViewer#1467]
### 复现步骤 / Step to reproduce

更新最新 CI 版本后，阅读器页面过渡动画默认启用，即使已经在阅读器设置-通用中关闭了`页面过渡动画`
尝试过开关页面过渡动画并大小退重启应用，问题依旧
![Screenshot_2024-07-29-13-16-26-042_moe tarsin ehv](https://github.com/user-attachments/assets/5d5b0ead-2f0d-4943-bc84-739e0bed8fac)

### 预期行为 / Expected behaviour

阅读器设置-通用中关闭了页面过渡动画，应不再使用翻页过渡动画

### 实际行为 / Actual Behaviour

阅读器设置-通用中关闭了页面过渡动画，翻页过渡动画仍然启用

### 应用日志 / App logs

[log-2024-07-29-13-21-32-051.zip](https://github.com/user-attachments/files/16407770/log-2024-07-29-13-21-32-051.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-snapshot

### EhViewer CI 版本 / EhViewer CI Version

2531fa2

### Android 系统版本 / Android version

HyperOS 1.0.18.0

### 设备型号 / Device model

Redmi K70Pro

### SoC 型号 / Soc model

骁龙 8g3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
已确认使用音量键翻页时会有这个问题

**Comment by Kuma15781** [comment]
> 已确认使用音量键翻页时会有这个问题

版本1.11.7   画廊1000页  页面过渡动画关闭状态
一页一页点正常  不会出现过度动画
点下面进度条 跳页 （例 从1跳到100）  会出现三张左右的过度动画

我不确定这个是不是BUG

**Comment by FooIbar** [comment]
> > 已确认使用音量键翻页时会有这个问题
> 
> 版本1.11.7 安卓9 画廊1000页 页面过渡动画关闭状态 一页一页点正常 不会出现过度动画 点下面进度条 跳页 （例 从1跳到100） 会出现三张左右的过度动画
> 
> 我不确定这个是不是BUG

进度条本来就是有动画的，那个选项只影响翻页动画
