### ISSUE TITLE
无法处理已下载的版权本

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1505]
### 复现步骤 / Step to reproduce

由于无法直接找版权本来下载和复现，我只能尝试模拟下载了版权本的情况。

比如某版权本链接为 https://e-hentai.org/g/1978672/7ae091bd0c/  。

1. 设定好下载目录，下载某画廊，比如 https://e-hentai.org/g/2214883/6bb715bc88/ 。
2. 导出数据，重命名文件为 eh.db 。
3. 使用以下脚本将导出的数据库中的已下载画廊链接替换为版权本：

```python
# ehrep.py

import sqlite3
import sys

def replace_string_in_database(db_path, old_string, new_string, column_type):
    # 连接到 SQLite 数据库
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # 获取数据库中所有表的名称
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()

    # 对每个表进行替换操作
    for table in tables:
        table_name = table[0]
        
        # 获取表中的所有指定类型的列
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = cursor.fetchall()
        target_columns = [col[1] for col in columns if col[2].upper() == column_type.upper()]
        
        for column in target_columns:
            # 生成更新语句
            update_query = f"""
            UPDATE {table_name}
            SET {column} = REPLACE({column}, ?, ?)
            WHERE {column} LIKE ?;
            """
            
            # 执行替换操作
            cursor.execute(update_query, (old_string, new_string, f"%{old_string}%"))
            print(f"Updated table {table_name}, column {column} of type {column_type}")

    # 提交更改并关闭连接
    conn.commit()
    conn.close()

if __name__ == "__main__":
    # 检查参数数量
    if len(sys.argv) != 5:
        print("Usage: python script_name.py <database_path> <old_string> <new_string> <column_type>")
        sys.exit(1)

    # 从命令行获取参数
    db_path = sys.argv[1]
    old_string = sys.argv[2]
    new_string = sys.argv[3]
    column_type = sys.argv[4]

    # 执行替换操作
    replace_string_in_database(db_path, old_string, new_string, column_type)

```

需要替换的值有两个，GID 和 TOKEN 。

对于 GID ：`python ehrep.py eh.db 2214883 1978672 INTEGER`
对于 TOKEN：`python ehrep.py eh.db 6bb715bc88 7ae091bd0c TEXT`

4. 清空应用数据。
5. 设定下载目录到原目录。
6. 导入处理后的数据库。
7. 进入下载页，根据封面找到目标画廊，进入阅读。
8. 点击目标画廊上的下载“开始”按键。

### 预期行为 / Expected behaviour

1. 已经下载的画廊应当能够独立阅读，在线获取到的数据为空时不影响阅读。
2. 点击下载时，不应当改动已下载的图片。

### 实际行为 / Actual Behaviour

1. 读取失败。
2. 该画廊下载目录内的图片、ComicInfo.xml 和 .ehviewer 被删除。封面没有被删除。

### 应用日志 / App logs

N/A

### 备注 / Addition details

参见：

- UjuiUjuMandan#30

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

ffe47b2

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

N/A

### SoC 型号 / Soc model

N/A

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
1. 读取失败是因为你只改了数据库没改 .ehviewer
2. 无法复现

**Comment by UjuiUjuMandan** [comment]
确实，2 是我看错了，因为此时应用会生成新的以版权本GID开头的文件夹，里面只有 thumb.jpg 。

.ehviewer 是什么格式？如何读取和修改？

**Comment by FooIbar** [comment]
CBOR, 随便找个在线工具都能修改
