### ISSUE TITLE
[已解決]無法檢查更新

### ISSUE THREAD

**Issue by InLem** [FooIbar/EhViewer#1512]
### 复现步骤 / Step to reproduce

已重新安裝APP

### 预期行为 / Expected behaviour

點[關於]->[檢查更新]應該要檢查app是否有更新。

### 实际行为 / Actual Behaviour

點[檢查更新]會出現錯誤訊息。有沒有開啟CI更新頻道會出現不同的錯誤。
![Screenshot_2024-08-12-17-39-12-177_moe tarsin ehviewer](https://github.com/user-attachments/assets/bfeb4012-e1ab-492b-b75d-dfff106534cf)
![Screenshot_2024-08-12-17-39-18-023_moe tarsin ehviewer](https://github.com/user-attachments/assets/c8483c2d-8246-4fcd-99fe-0e5ed26b626f)

### 应用日志 / App logs

[log-2024-08-12-17-39-41-039.zip](https://github.com/user-attachments/files/16579966/log-2024-08-12-17-39-41-039.zip)

### 备注 / Addition details

問題大約是在7/30開始發生。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

7e1b3ab

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

POCO F6

### SoC 型号 / Soc model

Snapdragon 8s Gen 3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [x] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
已于 fded0fd08d3d4999f9d60dd06f456a58feb530cb 修复

**Comment by InLem** [comment]
> 已於 [fded0fd](https://github.com/FooIbar/EhViewer/commit/fded0fd08d3d4999f9d60dd06f456a58feb530cb) 修復
剛才在試了更新一次，但沒用。
所以跟之前的問題不一樣。

**Comment by Hayakee** [comment]
![Screenshot_20240812_211458_EhViewer](https://github.com/user-attachments/assets/0a22e104-e0f6-4676-ad17-16c18f423a65)
![Screenshot_20240812_211508_EhViewer](https://github.com/user-attachments/assets/9c5a5b36-3503-45e9-8922-4da54b9ef0de)
我从 https://github.com/FooIbar/EhViewer/actions/runs/10282765745 也就是 fded0fd 版本点击更新能弹出更新的，你可能没勾选使用CI更新。

**Comment by InLem** [comment]
> 你用的這個版本沒有修復，所以你需要更新到 https://github.com/FooIbar/EhViewer/actions/runs/10282765745 建構的版本。

謝謝，問題解決了。
原來修正版載點在其他地方。

![Screenshot_2024-08-12-21-33-39-644_moe tarsin ehviewer](https://github.com/user-attachments/assets/1bb9dab3-4abc-4785-a1c9-0c7355d9b5b3)

**Comment by AstonMar** [comment]
我想问下如何获得这个fded0fd版本的更新？要pull下来自己build吗？我现在也是卡在了最新的release版本，勾选了ci也更新不了

**Comment by InLem** [comment]
> 我想问下如何获得这个fded0fd版本的更新？要pull下来自己build吗？我现在也是卡在了最新的release版本，勾选了ci也更新不了

點上面人給的連結，往下拉找到“Artifacts”。
他下面就有載點，依你的系統版本下載後解壓&安裝就好。

**Comment by AstonMar** [comment]
> > 我想问下如何获得这个fded0fd版本的更新？要pull下来自己build吗？我现在也是卡在了最新的release版本，勾选了ci也更新不了
> 
> 點上面人給的連結，往下拉找到“Artifacts”。 他下面就有載點，依你的系統版本下載後解壓&安裝就好。

更新好啦，十分感谢！
