### ISSUE TITLE
搜索标签 403 Forbidden

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1521]
### 复现步骤 / Step to reproduce

1.打开带有`female:"mind control$" `的画廊
如：[https://e-hentai.org/g/3022471/c100375036](https://e-hentai.org/g/3022471/c100375036)
2.点击标签，执行搜索

### 预期行为 / Expected behaviour

![Screenshot_20240814_220938_moe tarsin ehviewer](https://github.com/user-attachments/assets/8b7dbca8-e6a3-4a26-8eea-498555f551e1)

### 实际行为 / Actual Behaviour

![Screenshot_20240814_220524_moe tarsin ehviewer](https://github.com/user-attachments/assets/86dc181d-fcb0-4f66-b935-1ed63d27aaa8)

### 应用日志 / App logs

无

### 备注 / Addition details

讨论见[https://t.me/ehviewer/2539712](https://t.me/ehviewer/2539712)
操作视频见[https://t.me/ehviewer/2539806](https://t.me/ehviewer/2539806)
由[@Aris_Otto](https://t.me/Aris_Otto)发现的复现方式见[https://t.me/ehviewer/2539807](https://t.me/ehviewer/2539807)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

03ab435

### Android 系统版本 / Android version

HarmonyOS 4.2.0.125

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
日志

**Comment by tmby** [comment]
> 日志

已无法复现
等待此问题可稳定浮现后在开启该issue
