### ISSUE TITLE
Can not see the thumbnail in the apps(1.11.7的APP中使用Ex节点无法查看缩略图)

### ISSUE THREAD

**Issue by Bryan-zt** [FooIbar/EhViewer#1529]
### 复现步骤 / Step to reproduce

0. install the lastest version which is default arm64
1. reopen the app to check again
2. recheck fail
3. log out the account
4. log in again
5. recheck fail
6. check the same type question on Github
7. not found

### 预期行为 / Expected behaviour

重新登录后理应可以通过Ex（里站节点）查看缩略图

### 实际行为 / Actual Behaviour

it should be used in Exhetai point, but when i re- log in and update the newest version. still not working. 重复登陆和更新之后无法解决用里站观看缩略图的问题，表站节点可行。

### 应用日志 / App logs

[log-2024-08-16-20-22-08-394.zip](https://github.com/user-attachments/files/16636991/log-2024-08-16-20-22-08-394.zip)
[log-2024-08-16-20-22-08-394.zip](https://github.com/user-attachments/files/16636993/log-2024-08-16-20-22-08-394.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.7

### EhViewer CI 版本 / EhViewer CI Version

(7e1b3ab)

### Android 系统版本 / Android version

MIUI 14 14.0.23.0.TMRCNXM

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

第二代骁龙 7+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
已于 CI 版本中修复，可在 设置-关于 中更新
我会在发布 Release 版本前置顶这个 issue

**Comment by EDMI88** [comment]
> 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue

是什么原因导致的ex站点的这个问题呀

**Comment by FooIbar** [comment]
> > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> 
> 是什么原因导致的ex站点的这个问题呀

E 站更改了缩略图服务器

**Comment by EDMI88** [comment]
> > > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> > 
> > 
> > 是什么原因导致的ex站点的这个问题呀
> 
> E 站更改了缩略图服务器

请问现在更新之后华为手机还能打字吗？现在可以靠点击历史记录再删除然后打字，怕更新之后又打不了字了

**Comment by FooIbar** [comment]
> > > > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> > > 
> > > 
> > > 是什么原因导致的ex站点的这个问题呀
> > 
> > 
> > E 站更改了缩略图服务器
> 
> 请问现在更新之后华为手机还能打字吗？现在可以靠点击历史记录再删除然后打字，怕更新之后又打不了字了

我没有华为设备所以没有测试

**Comment by EDMI88** [comment]
> > > > > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> > > > 
> > > > 
> > > > 是什么原因导致的ex站点的这个问题呀
> > > 
> > > 
> > > E 站更改了缩略图服务器
> > 
> > 
> > 请问现在更新之后华为手机还能打字吗？现在可以靠点击历史记录再删除然后打字，怕更新之后又打不了字了
> 
> 我没有华为设备所以没有测试

好的，链接https://github.com/FooIbar/EhViewer/actions/runs/10423401444 中的安装包看起来比以前的小，会有问题吗请问

**Comment by FooIbar** [comment]
> > > > > > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> > > > > 
> > > > > 
> > > > > 是什么原因导致的ex站点的这个问题呀
> > > > 
> > > > 
> > > > E 站更改了缩略图服务器
> > > 
> > > 
> > > 请问现在更新之后华为手机还能打字吗？现在可以靠点击历史记录再删除然后打字，怕更新之后又打不了字了
> > 
> > 
> > 我没有华为设备所以没有测试
> 
> 好的，链接https://github.com/FooIbar/EhViewer/actions/runs/10423401444 中的安装包看起来比以前的小，会有问题吗请问

小是因为是压缩包，需要先解压再安装

关于某些华为设备无法输入的问题，我估计是仍然存在的
由于我没有相关设备也无从下手修复，因此建议使用 https://github.com/EhViewer-NekoInverter/EhViewer ，预计也会在近期修复缩略图问题

**Comment by EDMI88** [comment]
> > > > > > > 已于 CI 版本中修复，可在 设置-关于 中更新 我会在发布 Release 版本前置顶这个 issue
> > > > > > 
> > > > > > 
> > > > > > 是什么原因导致的ex站点的这个问题呀
> > > > > 
> > > > > 
> > > > > E 站更改了缩略图服务器
> > > > 
> > > > 
> > > > 请问现在更新之后华为手机还能打字吗？现在可以靠点击历史记录再删除然后打字，怕更新之后又打不了字了
> > > 
> > > 
> > > 我没有华为设备所以没有测试
> > 
> > 
> > 好的，链接https://github.com/FooIbar/EhViewer/actions/runs/10423401444 中的安装包看起来比以前的小，会有问题吗请问
> 
> 小是因为是压缩包，需要先解压再安装
> 
> 关于某些华为设备无法输入的问题，我估计是仍然存在的 由于我没有相关设备也无从下手修复，因此建议使用 https://github.com/EhViewer-NekoInverter/EhViewer ，预计也会在近期修复缩略图问题

谢谢您的帮助，不过没有关系。我使用了你的新版本，虽然无法打字，但是搜索栏依然可以靠使用历史记录激活，这对我来说就够了。再次感谢您的帮助。
