### ISSUE TITLE
无法更新or无法看到画廊的缩略图

### ISSUE THREAD

**Issue by nickhe800** [FooIbar/EhViewer#1535]
### 复现步骤 / Step to reproduce

1点击更新不显示相关更新内容
2点开画廊看不到缩略图
![Screenshot_2024-08-19-08-25-00-808_moe tarsin ehviewer](https://github.com/user-attachments/assets/ced38a9f-eb1f-4561-b4fd-fc0fac39cc5c)
![Screenshot_2024-08-19-08-25-47-444_moe tarsin ehviewer](https://github.com/user-attachments/assets/c0cc4002-cca4-46b4-8fa6-77c87742ebd5)

### 预期行为 / Expected behaviour

1应该看到更新相关信息
2应该看到缩略图

### 实际行为 / Actual Behaviour

1无法获得更新有关信息
2无法看到缩略图

### 应用日志 / App logs

[log-2024-08-19-08-26-03-446.zip](https://github.com/user-attachments/files/16653745/log-2024-08-19-08-26-03-446.zip)

### 备注 / Addition details

无

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.12.0-SNOPSHOT

### EhViewer CI 版本 / EhViewer CI Version

b9994ea

### Android 系统版本 / Android version

MIUI14.0.4

### 设备型号 / Device model

xiaomi12

### SoC 型号 / Soc model

骁龙8+Gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by nickhe800** [comment]
抱歉，版本号应为1.12.0-SNAPSHOT（b9994ea）

**Comment by tmby** [comment]
#1512 #1529
都是已经解决的问题

**Comment by nickhe800** [comment]
谢谢，已解决
