### ISSUE TITLE
手机qq在后台，ehviewer就无法预览缩略图

### ISSUE THREAD

**Issue by xyzdomice** [FooIbar/EhViewer#1539]
### 复现步骤 / Step to reproduce

1 打开手机qq（8.8.20）
2打开ehviewer
3无法显示缩略图

https://github.com/user-attachments/assets/361b0302-0ebb-49ca-bd16-f8f415de7699

### 预期行为 / Expected behaviour

1可以预览缩略图

### 实际行为 / Actual Behaviour

1无法预览缩略图，直到关闭手机qq以后

### 应用日志 / App logs

[
[log-2024-08-20-02-04-02-581.zip](https://github.com/user-attachments/files/16663752/log-2024-08-20-02-04-02-581.zip)
](url)

### 备注 / Addition details

很奇秒的bug？我之前一直是以为更新也没有作用，但是手机重启后却能加载，最后逐步摸索出来的

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13.0-snapshot(40c1b7e)

### EhViewer CI 版本 / EhViewer CI Version

1.13.0-snapshot(40c1b7e)

### Android 系统版本 / Android version

Hydrogen OS 10

### 设备型号 / Device model

OnePlus 7 pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by xyzdomice** [comment]
视频可能需要下载才能预览？

**Comment by yinzhefuyun** [comment]
> 视频可能需要下载才能预览？

居然还有H.263的编码格式，我以为都是H.264天下了，是需要下载才能播放，我刚刚看了一下视频格式，估计Chrome删除H.263的视频支持了

**Comment by FooIbar** [comment]
有点神奇
日志中显示的错误是连接被重置，恐怕没有什么我们能做的
