### ISSUE TITLE
请求添加旧版本阅读器的选项（例如1.11.2版本中“高级”选项里的“New Compose Reader”不启用时候的版本）（新版本阅读器在打开已下载图片时的延迟问题）

### ISSUE THREAD

**Issue by 1670081661** [FooIbar/EhViewer#1543]
### 复现步骤 / Step to reproduce

下载1.11.2版本的ehv软件，打开“高级”选项，取消选项“New Compose Reader”

### 预期行为 / Expected behaviour

若启用新版本阅读器，则已下载图片的加载效率大大降低：
旧版本阅读器打开已下载图片的时间为0到0.05秒
新版本阅读器启用后打开已下载图片的时间增至0.1到0.2秒
严重影响阅读感受

### 实际行为 / Actual Behaviour

在最新版本里，“高级”选项卡里的“New Compose Reader”选项已经消失，但是打开已下载图片的速度仍然为0.1-0.2秒，严重影响观感
但是我找不到任何启用旧版本图片阅读器的方法
所以请求加入一个启用旧版本阅读器的选项
（准确来说，新版本阅读器打开一个本子后，每张图片第一次加载都需要花费比旧版阅读器多0.1到0.2秒的时间，这对于阅读体验来说影响巨大，原本能几乎0加载时间变得每次翻页得看一下黑屏零点几秒才能看到图片，因此才要求加回旧版本阅读器）

### 应用日志 / App logs

[logcat-2024-08-20-21-56-41-847.txt](https://github.com/user-attachments/files/16676840/logcat-2024-08-20-21-56-41-847.txt)

### 备注 / Addition details

我原本一直不升级，用着1.11.2版本倒是还可以接受，但是最近Exhentai他更换了预览图服务器后旧版本全部都无法查看预览图了，但是新版又强制使用新版本的阅读器，而我确定目前所有比1.11.2版本高级的版本在强制使用新版本阅读器后加载时间都被延长，导致我这个机型在阅读已下载本子的时候极度难受。故在此请求加回旧版本阅读器。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

6a64ff5

### Android 系统版本 / Android version

Magic UI 4.2 ; Android 11

### 设备型号 / Device model

Honor 50

### SoC 型号 / Soc model

骁龙778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 1670081661** [comment]
我注意到在1.11.3版本的时候有个改进：
优化预加载逻辑和图片加载顺序
我怀疑是这个导致的我图片加载时间增加的问题

**Comment by FooIbar** [comment]
最新版本录屏

**Comment by 1670081661** [comment]
怪，直到1.11.7版本的时候上述问题仍然存在，但是在1.12.0版本后问题已经消失了，我暂时关闭这个问题吧，直到我发现某个新版本又出现这种问题后我再重新录屏并开启issue
抱歉打扰您了

**Comment by FooIbar** [comment]
Duplicate of #1510
