### ISSUE TITLE
评论区刷新闪退

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#1548]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/2979d8dd-9c61-42e0-adfd-b4e7459ad45f

画廊链接：[https://e-hentai.org/g/3029689/021a8d0970](https://e-hentai.org/g/3029689/021a8d0970)

### 预期行为 / Expected behaviour

不闪退

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[log-2024-08-21-11-57-32-722.zip](https://github.com/user-attachments/files/16685804/log-2024-08-21-11-57-32-722.zip)

### 备注 / Addition details

评论分数阈值：`6`
评论屏蔽列表：`([彩白绿][Ee]|[Ff][Ee]|[Jj][Hh]|[Ee][Hh]|解析|加载|用不了|转圈|509|软件|[aA][pP]{2}|配额|白屏|熊猫|网络|直连|梯子|代理|兼容|导入|导出|[Gg][Ii][Tt][Hh][Uu][Bb])`

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT 

### EhViewer CI 版本 / EhViewer CI Version

876bb68

### Android 系统版本 / Android version

HarmonyOS 4.2.0.125

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
画廊删了

**Comment by tmby** [comment]
> 画廊删了

我找找有没有可以复现的其它画廊链接😭

**Comment by FooIbar** [comment]
@1670081661 @z1137
我无法复现，最新 CI 版本可能解决了这个问题

**Comment by 1670081661** [comment]
> @1670081661 @z1137 我无法复现，最新 CI 版本可能解决了这个问题

用的就是1.12.0来着，目前没看到更新的版本了。顺带就是这个闪退也很奇特，有时候你单纯的在下载页面上下快速滑动都有可能造成闪退

**Comment by tmby** [comment]
> > @1670081661 @z1137 我无法复现，最新 CI 版本可能解决了这个问题
> 
> 用的就是1.12.0来着，目前没看到更新的版本了。顺带就是这个闪退也很奇特，有时候你单纯的在下载页面上下快速滑动都有可能造成闪退

你需要打开`设置-关于-使用持续集成（CI）构建频道更新`，然后检查更新，安装最新的CI版本
