### ISSUE TITLE
下载时发生闪退，闪退后打开下载页面时候选择的下载标签强制变回“全部”

### ISSUE THREAD

**Issue by 1670081661** [FooIbar/EhViewer#1555]
### 复现步骤 / Step to reproduce

1、下载多个本子
2、快速滑动页面（非必须，但我连续2次闪退都是因为这个）
3、崩溃

### 预期行为 / Expected behaviour

他不应该在我有十几个等待下载的本子时候崩溃掉，而且崩溃后会强制吧我目前选择的下载标签改为“全部”（我通常使用“默认”）

### 实际行为 / Actual Behaviour

实际上会在下载时因未知原因崩溃，应用日志里会有崩溃记录

### 应用日志 / App logs

[log-2024-08-22-15-31-15-882.zip](https://github.com/user-attachments/files/16707102/log-2024-08-22-15-31-15-882.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

Magic UI 4.2 ; Android 11

### 设备型号 / Device model

Honor 50

### SoC 型号 / Soc model

骁龙778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 1670081661** [comment]
还有一个问题就是，我发现现在只要你关闭软件重进，那么下载标签一定会变回“全部”，我还得手动改回“默认”

**Comment by UjuiUjuMandan** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/85

**Comment by FooIbar** [comment]
Duplicate of #1548
