### ISSUE TITLE
【预载图片】几乎不工作，阅览体验很差

### ISSUE THREAD

**Issue by Silver7758** [FooIbar/EhViewer#1560]
### 问题描述
1.0.几版本的漫画预加载原本是十分流畅的，往后快速翻页也大多是已加载图片。

但是最近更新到[1.12.0](https://github.com/FooIbar/EhViewer/releases/tag/1.12.0)版本后，**翻页时经常出现0%加载圈**。

### 推测
根据实际表现推测，预载图片的数值应该是卡在了1。使用某动图图库测试，待在本页，过一段时间后再翻页，下一页已加载，但是下下页就是0%加载圈了。

### 复现步骤
0. 重装[1.12.0](https://github.com/FooIbar/EhViewer/releases/tag/1.12.0)
1. 登录/不登录账号皆可
2. 将预载图片设置为17
3. 打开并阅读漫画

### EhViewer信息
版本：1.12.0 (6191ad7)
浏览站点：E-Hentai / ExHentai

### 设备信息
系统版本：HyperOS 1.0.045.0.UNBCNXM
设备型号：Xiaomi 14 Pro
SoC：骁龙 8 Gen 3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by yinzhefuyun** [comment]
我也发现了现在最多加载1张感觉和mpv体验差不多

**Comment by YuuzhanLiu** [comment]
同样有这个问题，预载图片功能时好时坏

**Comment by FooIbar** [comment]
无法复现
https://github.com/FooIbar/EhViewer/actions/runs/10777035901
可以用这个版本复现之后把日志传上来
另外说一下阅读模式（从左到右/从上到下/条漫等）

**Comment by YuuzhanLiu** [comment]
> 无法复现 https://github.com/FooIbar/EhViewer/actions/runs/10777035901 可以用这个版本复现之后把日志传上来 另外说一下阅读模式（从左到右/从上到下/条漫等）

从左到右，无翻页动画
我怀疑和网络环境有关系，能给个标准的使用方法吗？就是开不开代理，设置开关什么的

**Comment by Silver7758** [comment]
> 无法复现 https://github.com/FooIbar/EhViewer/actions/runs/10777035901 可以用这个版本复现之后把日志传上来 另外说一下阅读模式（从左到右/从上到下/条漫等）

根据我的初步测试，预加载问题貌似有些许改善，但是我仍然有遇到。我会继续关注并提供复现日志。

**Comment by Silver7758** [comment]
@FooIbar 这是bug发生时的日志与录屏
![log-2024-09-15-09-58-55-266.zip](https://github.com/user-attachments/files/17004177/log-2024-09-15-09-58-55-266.zip)
