### ISSUE TITLE
[BUG]向上滑动后不明原因的闪退

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1568]
### 复现步骤 / Step to reproduce

目前有两种能成功复现：1.在app界面滑动至最上，在撞击的动画效果出现后闪退；2.从桌面转回至app后向上滑后闪退

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[crash-2024-08-28-02-12-06-085.log](https://github.com/user-attachments/files/16767240/crash-2024-08-28-02-12-06-085.log)
[crash-2024-08-28-02-14-22-512.log](https://github.com/user-attachments/files/16767252/crash-2024-08-28-02-14-22-512.log)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

Magic OS 8.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by z1137** [comment]
新增种类：1.阅读后退出阅读节目上下滑动；2.拖动下载列表右侧滑条
[crash-2024-08-30.zip](https://github.com/user-attachments/files/16819070/crash-2024-08-30.zip)

**Comment by FooIbar** [comment]
Duplicate of #1548
