### ISSUE TITLE
[BUG]打开“设置-EH”后闪退

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1569]
### 复现步骤 / Step to reproduce

反复复现，打开后大约1秒左右就会闪退，但是目录下无crash，导出日志后也只有机器本身的检测报告

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

无

### 备注 / Addition details

可能和新版本更新配额那边有关？打开“EH”这个选项卡的闪退所需时间要比“EH-更新配额”闪退所需时间长，也可能单纯操作问题

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

Magic OS 8.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by z1137** [comment]
抱歉突然想起来看过那个iss都忘了，重复问题关闭

**Comment by FooIbar** [comment]
Duplicate of #1563
