### ISSUE TITLE
ex里站疑似访问错误

### ISSUE THREAD

**Issue by xiaoweiXX** [FooIbar/EhViewer#1573]
### 复现步骤 / Step to reproduce

0.重新安装旧版应用
1.使用cookie登录有ex里站权限的账号
2.升级成最新ci版应用
3.进入设置把画廊站点改成exhentai
4.退出应用
5.进入应用

### 预期行为 / Expected behaviour

正常显示里站内容

### 实际行为 / Actual Behaviour

显示sad panda

### 应用日志 / App logs

[log-2024-08-29-03-32-49-341.zip](https://github.com/user-attachments/files/16788117/log-2024-08-29-03-32-49-341.zip)

### 备注 / Addition details

使用相同的cookie，用浏览器直接登录ex里站，可以正常浏览内容，搜索里站专属tag也有结果。
并非别的issue中所说只是不解析缩略图，而是首页就没有任何结果，显示sad panda，尝试搜索也是这样。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

cb69a16

### Android 系统版本 / Android version

Hyper OS/安卓14

### 设备型号 / Device model

小米14Pro

### SoC 型号 / Soc model

骁龙 8 Gen 3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by xiaoweiXX** [comment]
今天一开始进入应用的时候显示sad panda，我还以为账号不行了，但是用浏览器登录又能正常看到里站的内容，折腾了半天应用（包括尝试旧版，更新最新ci，卸载重装等等）还是无法访问，看了issue之后，遂怀疑是不是里站解析规则之类的又有变化而应用未跟进

**Comment by FooIbar** [comment]
Cookie 登录不受支持

**Comment by xiaoweiXX** [comment]
> Cookie 登录不受支持

跟登录没关系，实际上已经成功登录，并且表站内容能够刷新访问，但是里站内容刷新不出来。同样的账号，使用浏览器能访问里站浏览内容，所以能够排除是账号的问题。

**Comment by FooIbar** [comment]
Sad panda 就是 igneous cookie 有问题，在账号设置里清除 igneous 然后在主页刷新，不行就换节点，直到 igneous 不是 mystery 或 null

**Comment by xiaoweiXX** [comment]
> Sad panda 就是 igneous cookie 有问题，在账号设置里清除 igneous 然后在主页刷新，不行就换节点，直到 igneous 不是 mystery 或 null

好，我试试
