### ISSUE TITLE
进不去exhentai

### ISSUE THREAD

**Issue by 8008208820DHC** [FooIbar/EhViewer#1576]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/e6cfee46-d418-4877-bf2f-3ff5b2ecd8b6

### 预期行为 / Expected behaviour

应该直接进入加载图片。

### 实际行为 / Actual Behaviour

![Screenshot_2024-08-31-19-02-48-386_moe tarsin ehviewer](https://github.com/user-attachments/assets/4869f713-3ab6-4150-89e9-ec85d25893a6)

### 应用日志 / App logs

[log-2024-08-31-19-04-09-961.zip](https://github.com/user-attachments/files/16824476/log-2024-08-31-19-04-09-961.zip)

### 备注 / Addition details

同一个账号，手机一直可以进里站，pad的前段时间突然进不去了，之前两个设备都可以进里站。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

SNAPSHOT(9436655)

### Android 系统版本 / Android version

1.0.8.0.UNXCNXM/Android14

### 设备型号 / Device model

小米pad 6s Pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
见[1.11.0](https://github.com/FooIbar/EhViewer/releases/tag/1.11.0)更新日志
在`设置-EH-账户`处`清除 igneous`，于表站执行搜索后可获取到有效的igneous值，即可进入EX。

**Comment by Nia1098718** [comment]
可以换到米国节点

**Comment by 8008208820DHC** [comment]
> 见[1.11.0](https://github.com/FooIbar/EhViewer/releases/tag/1.11.0)更新日志 在`设置-EH-账户`处`清除 igneous`，于表站执行搜索后可获取到有效的火成值，即可进入EX。

已尝试，但是没有效果。

**Comment by 8008208820DHC** [comment]
> 可以搬到米國月亮

试了，还是进不去。

**Comment by FooIbar** [comment]
https://nicebowl.fun/11

**Comment by 8008208820DHC** [comment]
> https://nicebowl.fun/11

解决了，非常感谢！
