### ISSUE TITLE
里站无法显示收藏夹

### ISSUE THREAD

**Issue by ODtian** [FooIbar/EhViewer#1577]
### 复现步骤 / Step to reproduce

1.重新安装应用
2.登录里站
3.打开收藏夹

### 预期行为 / Expected behaviour

显示收藏

### 实际行为 / Actual Behaviour

显示ERR_CERT_COMMON_NAME_INVALID ErrorCode=11 InternalErrorCode=-200

### 应用日志 / App logs

无

### 备注 / Addition details

用浏览器可以打开里站的收藏夹，但用app就错误

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13

### EhViewer CI 版本 / EhViewer CI Version

541f9e8

### Android 系统版本 / Android version

安卓14

### 设备型号 / Device model

小米11

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
与 app 无关
