### ISSUE TITLE
里站无法显示封面

### ISSUE THREAD

**Issue by ODtian** [FooIbar/EhViewer#1578]
### 复现步骤 / Step to reproduce

1.安装最新版
2.打开首页

### 预期行为 / Expected behaviour

加载本子的封面

### 实际行为 / Actual Behaviour

无法加载封面

### 应用日志 / App logs

无

### 备注 / Addition details

里站封面域名是s.exhentai.org，但是不知道为什么这个域名没法加载，梯子和DNS都检查过，重定向到ehgt.org就可以加载了

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13

### EhViewer CI 版本 / EhViewer CI Version

541f9e8

### Android 系统版本 / Android version

安卓14

### 设备型号 / Device model

小米11

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
同 https://github.com/FooIbar/EhViewer/issues/1577#issuecomment-2323285853
