### ISSUE TITLE
下载标签依据作者分类大部分无法识别

### ISSUE THREAD

**Issue by laowanglr** [FooIbar/EhViewer#1585]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/a6c821e5-9840-4e55-b0b5-92bf8cc296e5

将下载分类依据改为作者后，大部分无法识别

### 预期行为 / Expected behaviour

应该如说明一般正确按照作者分类

### 实际行为 / Actual Behaviour

实际上大部分显示不全
![Screenshot_2024-09-03-22-23-12-826_moe tarsin ehviewer-edit](https://github.com/user-attachments/assets/793be910-40e8-419a-8a12-59c06a64f1d0)

### 应用日志 / App logs

[log-2024-09-03-22-23-48-997.zip](https://github.com/user-attachments/files/16850294/log-2024-09-03-22-23-48-997.zip)

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

be83105

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

小米14

### SoC 型号 / Soc model

骁龙8gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
这是因为缺少 ComicInfo.xml
可以在下载设置中重新加载元数据，3000+ 本预计会花费一定时间

**Comment by laowanglr** [comment]
重新加载后仍有两百余本无法识别，不过整体上可以使用，感谢

**Comment by FooIbar** [comment]
该功能依据的是 E 站上的 artist 标签（对于 cosplay 画廊则是 cosplayer），所以如果没有标签的话就无法识别
