### ISSUE TITLE
因为想解决进EH闪退问题，点进了一个问题底下的CI版链接，安装了以后发现软件不能再直连了，并且高级中没有两个节点的选择了

### ISSUE THREAD

**Issue by aosan1** [FooIbar/EhViewer#1599]
### 复现步骤 / Step to reproduce

>

https://github.com/user-attachments/assets/1b14afb0-8817-475c-937a-af5cb922f97d

### 预期行为 / Expected behaviour

原本应该可以直连，不需要使用VPN

### 实际行为 / Actual Behaviour

因为胡乱安装以后发现不能使用国内网络，并且高级中少了很多设置，类似于节点的选择

### 应用日志 / App logs

[log-2024-09-06-01-46-32-411.zip](https://github.com/user-attachments/files/16898378/log-2024-09-06-01-46-32-411.zip)

### 备注 / Addition details

可以还原成能使用直连的状态吗

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

HarmonyOS4.0

### 设备型号 / Device model

华为p50p

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Kuma15781** [comment]
https://github.com/FooIbar/EhViewer/issues/12

**Comment by aosan1** [comment]
版本太低安装不了，是不是只能删了重装呀，主要是里面有一堆下载的本子，舍不得删😢

**Comment by aosan1** [comment]
> #12

版本太低安装不了，是不是只能删了重装呀，主要是里面有一堆下载的本子，舍不得删😢

**Comment by Kuma15781** [comment]
> > #12
> 
> 版本太低安装不了，不是只能删了重装呀，主要是里面有大量下载的本子，舍不得删😢

https://github.com/UjuiUjuMandan/EhViewer/releases

**Comment by aosan1** [comment]
> > > #12
> > 
> > 
> > 版本太低安装不了，不是只能删了重装呀，主要是里面有大量下载的本子，舍不得删😢
> 
> https://github.com/UjuiUjuMandan/EhViewer/releases

已解决🙏🏻感谢
