### ISSUE TITLE
收藏夹设置了名字之后，收藏UI样式会出现文字重叠

### ISSUE THREAD

**Issue by X012C** [FooIbar/EhViewer#16]
### 复现步骤 / Step to reproduce

文件夹设置了名字之后，会以比较密集的样式呈现，出现文字重叠，当屏幕比较大的时候，这块UI会臃肿地挤在中央；
![1694773986279](https://github.com/FooIbar/EhViewer/assets/99554281/4bb6d608-fece-428d-baa7-79d99b69cf44)

### 预期行为 / Expected behaviour

如题

### 实际行为 / Actual Behaviour

如题

### EhViewer 版本号 / EhViewer version code

1.8.10.0

### EhViewer CI 版本 / EhViewer CI Version

6adc7f7

### Android 系统版本 / Android version

无

### 设备型号 / Device model

无

### SoC 型号 / Soc model

无

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
Fixed by 21b3913
