### ISSUE TITLE
[bug]因闪退造成的无法挽回的下载失败

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1602]
### 复现步骤 / Step to reproduce

下载途中闪退致使画廊下载出错，但是似乎是判定为下载成功了，但是打开发现无法解析。
![Screenshot_20240906_124711_moe_tarsin_ehviewer_MainActivity](https://github.com/user-attachments/assets/0278a8f2-22be-4166-bc85-0d5dbc401fb3)
![Screenshot_20240906_124020_moe_tarsin_ehviewer_MainActivity](https://github.com/user-attachments/assets/f8f6a32b-646e-44e0-9055-effb780d1f4e)

### 预期行为 / Expected behaviour

下载正常

### 实际行为 / Actual Behaviour

下载出错且显示下载成功，图片无法解析，且无法通过刷新/刷新(原图)/下载列表选定后开始来拯救，只能删除重新下

### 应用日志 / App logs

[log-2024-09-06-12-40-56-646.zip](https://github.com/user-attachments/files/16902945/log-2024-09-06-12-40-56-646.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

ada8f3a

### Android 系统版本 / Android version

Magic OS 8.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Kuma15781** [comment]
你可以进入下载目录按时间排序
找到并删除错误的那几张图片后再点击开始下载

**Comment by z1137** [comment]
我采用的归档的cbz 图片的话蛮久没用了

> 你可以进入下载目录按时间排序 找到并删除错误的那几张图片后再点击下载按钮

用的cbz，图片的话蛮久没用过了。cbz里面可能没法通过app改，自己加图也麻烦。主要是这个应该算是可能可以避免的bug？应该算是之前的完整性检查的内容，但是很明显在这个案例没生效。

**Comment by z1137** [comment]
主要cbz这个传统归档还挺好转移数据的，如果图片的话需要至少300x3000个文件，而cbz只需要3x3000
