### ISSUE TITLE
无法正常上下滑动界面

### ISSUE THREAD

**Issue by acuma7** [FooIbar/EhViewer#161]
### 复现步骤 / Step to reproduce

打开应用，滑到底部或滑至顶部刷新

### 预期行为 / Expected behaviour

加载过程中仍可以用手势上下浏览

### 实际行为 / Actual Behaviour

上下滑动被锁死，只能左右滑动出菜单界面

### 应用日志 / App logs

太多了不知道放哪段

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

bf6aa3e

### Android 系统版本 / Android version

miui12

### 设备型号 / Device model

redminote9 pro

### SoC 型号 / Soc model

骁龙750

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by knwcat** [comment]
另注意到加载画廊新页面的过程变得异常缓慢，并时常出现超时现象

**Comment by FooIbar** [comment]
https://issuetracker.google.com/issues/267096397

> 另注意到加载画廊新页面的过程变得异常缓慢，并时常出现超时现象

超时是网络问题

**Comment by acuma7** [comment]
> https://issuetracker.google.com/issues/267096397
> 
> > 另注意到加载画廊新页面的过程变得异常缓慢，并时常出现超时现象
> 
> 超时是网络问题

切换回上个版本几乎感觉不到加载时间，而最新版本下加载时间很长，很长，应该不是网络问题

**Comment by Pony-CW** [comment]
这个右滑抽屉太敏感了，你认为抽屉已经回完了结果还在，这时快速上下滑系统仍然判你在抽屉左右划

**Comment by junkoshinichiro** [comment]
更新后不能裸连了，得挂梯子

**Comment by junkoshinichiro** [comment]
为什么会显示网络错误

**Comment by zznsz** [comment]
同希望优化上下滑动判定，左面板的判定过于灵敏导致上下滑动很困难

**Comment by FooIbar** [comment]
> 同希望优化上下滑动判定，左面板的判定过于灵敏导致上下滑动很困难

CI 版本已修复
