### ISSUE TITLE
最新版本下，新下载的文件会产生多个重复命名文件夹。

### ISSUE THREAD

**Issue by ferutospencer** [FooIbar/EhViewer#1619]
### 复现步骤 / Step to reproduce

![QQ截图20240912234452](https://github.com/user-attachments/assets/75ac0c29-0a69-4bbd-bdfa-49c9326d098c)

下载一个页数较多的新的画廊，打开下载路径查看，发现存在多个重复命名文件夹

### 预期行为 / Expected behaviour

期望1：不产生重复命名的文件夹

### 实际行为 / Actual Behaviour

实际行为:产生多个重复命名文件夹

### 应用日志 / App logs

[log-2024-09-12-23-22-43-020.zip](https://github.com/user-attachments/files/16981926/log-2024-09-12-23-22-43-020.zip)

### 备注 / Addition details

顺带问一个问题：目前APP上能否查看上传的私人画廊？

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

MIUI12.5  12.5.5.0，Android 11

### 设备型号 / Device model

Redmi K30 ultra

### SoC 型号 / Soc model

天玑1000+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
重复文件夹的完整路径是什么

**Comment by ferutospencer** [comment]
> 重复文件夹的完整路径是什么

此电脑\Redmi K30 Ultra\内部存储设备\EhViewer\download\3032622-[Danimaru] Kouhai Kanjo Tsujinaka-Chan + Koi ni Naru made + Mou Ichido, Shite Mitai + Amayakashi Onee-san ni Ochinchin o Torottoro ni Sarete Nukedasenai +How to Advance Your Love . [Chinese]
此电脑\Redmi K30 Ultra\内部存储设备\EhViewer\download\3032622-[Danimaru] Kouhai Kanjo Tsujinaka-Chan + Koi ni Naru made + Mou Ichido, Shite Mitai + Amayakashi Onee-san ni Ochinchin o Torottoro ni Sarete Nukedasenai +How to Advance Your Love . [Chinese] (2)
此电脑\Redmi K30 Ultra\内部存储设备\EhViewer\download\3032622-[Danimaru] Kouhai Kanjo Tsujinaka-Chan + Koi ni Naru made + Mou Ichido, Shite Mitai + Amayakashi Onee-san ni Ochinchin o Torottoro ni Sarete Nukedasenai +How to Advance Your Love . [Chinese] (1)


其中(1)与(2)均为空文件夹，该漫画一共有206页。

另一个有505页的漫画重复生成了含有(1)(2)(3)共四个文件夹，同样只有不带序号标的文件夹存在文件。

**Comment by naivecat** [comment]
MIUI13.0.15 版本号1.13.0-SNAPSHOT（9436655）也有发生，由相关空文件夹创建日期推断，似乎在1.12.0之前的版本就有此问题

**Comment by Kuma15781** [comment]
https://github.com/UjuiUjuMandan/EhViewer/issues/62#issuecomment-2183856703

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/10979809205/artifacts/1962913162
删除重复文件夹，把原文件夹改个名字，然后用这个版本重新下载
如果还会产生重复文件夹再导出日志

**Comment by ferutospencer** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/10979809205/artifacts/1962913162 删除重复文件夹，把原文件夹改个名字，然后用这个版本重新下载 如果还会产生重复文件夹再导出日志

[log-2024-09-22-18-22-40-090.zip](https://github.com/user-attachments/files/17089213/log-2024-09-22-18-22-40-090.zip)
![QQ截图20240922182227](https://github.com/user-attachments/assets/8a2b45fb-dc77-4eb0-b4c1-9c0eae35cc32)
使用该版本下载依然存在重复文件夹问题

**Comment by FooIbar** [comment]
> > https://github.com/FooIbar/EhViewer/actions/runs/10979809205/artifacts/1962913162 删除重复文件夹，把原文件夹改个名字，然后用这个版本重新下载 如果还会产生重复文件夹再导出日志
> 
> [log-2024-09-22-18-22-40-090.zip](https://github.com/user-attachments/files/17089213/log-2024-09-22-18-22-40-090.zip)

日志中没有我们的日志，检查一下系统设置是不是哪里关了
其他重复文件夹的名字是什么？

**Comment by ferutospencer** [comment]
> > > https://github.com/FooIbar/EhViewer/actions/runs/10979809205/artifacts/1962913162 删除重复文件夹，把原文件夹改个名字，然后用这个版本重新下载 如果还会产生重复文件夹再导出日志
> > 
> > 
> > [log-2024-09-22-18-22-40-090.zip](https://github.com/user-attachments/files/17089213/log-2024-09-22-18-22-40-090.zip)
> 
> 日志中没有我们的日志，检查一下系统设置是不是哪里关了 其他重复文件夹的名字是什么？

![1727006380858](https://github.com/user-attachments/assets/51676f81-8472-45ef-b3a1-b328315118fb)
高级设置界面的选项截图都是默认的，没去关闭过什么日志相关选项。
其他重复文件夹名字也差不多，都是作品名全称+(1)(2)(3)类似的，只要页数超过一定数量就会出现重复命名的文件夹。
可以用你们那边的设备看看下载一个150页的作品是否会出现该情况？

**Comment by FooIbar** [comment]
我说的是手机系统的设置不是 app 的设置
这个问题跟页数是没有关系的，只跟文件夹名有关，所以我才问

**Comment by ferutospencer** [comment]
> 我说的是手机系统的设置不是 app 的设置 这个问题跟页数是没有关系的，只跟文件夹名有关，所以我才问

系统设置里面关于app所需要使用的权限设置没有更改，开发者选项里面有若干个与日志相关的选项均为默认状态未更改过。

**Comment by Kuma15781** [comment]
> > 我说的是手机系统的设置不是app的设置这个问题跟页数是没有关系的，只跟文件夹名有关，所以我才问
> 
> 系统设置里面关于app所需要使用的权限设置没有更改，开发者选项里面有几个与日志相关的选项默认状态未更改过。


备份数据后重新安装后试下

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/10982735077/artifacts/1963467770
用这个版本生成重复文件夹后上传日志

**Comment by ferutospencer** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/10982735077/artifacts/1963467770 用这个版本生成重复文件夹后上传日志

[log-2024-09-23-23-57-10-367.zip](https://github.com/user-attachments/files/17100510/log-2024-09-23-23-57-10-367.zip)

已上传，且该测试版还存在一个问题：进入作品页面，会直接显示全部页数的预览图，而不是和之前一样只显示40页。

**Comment by FooIbar** [comment]
已于 CI 版本修复，重复文件夹可通过下载设置中的“清理下载冗余”清理
显示全部预览图是预定更改
