### ISSUE TITLE
更新APP版本时会重新修改过往文件夹日期

### ISSUE THREAD

**Issue by ferutospencer** [FooIbar/EhViewer#1620]
### 复现步骤 / Step to reproduce

更新APP，过往下载项日期均被修改

### 预期行为 / Expected behaviour

不修改过往文件夹日期（以往若干次更新APP并未发现该行为）

### 实际行为 / Actual Behaviour

过往下载项日期均被修改
![QQ截图20240912232009](https://github.com/user-attachments/assets/5e3ee419-7ad5-4a50-8c98-7aaa5ddb4a33)

### 应用日志 / App logs

[log-2024-09-12-23-22-43-020.zip](https://github.com/user-attachments/files/16982000/log-2024-09-12-23-22-43-020.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

MIUI12.5  12.5.5.0，Android 11

### 设备型号 / Device model

Redmi K30 ultra

### SoC 型号 / Soc model

天玑1000+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
8月24也不是现在啊
文件夹里被修改了的是哪个文件

**Comment by ferutospencer** [comment]
> 8月24也不是现在啊 文件夹里被修改了的是哪个文件

日期是8月24日的原因可能为：在8月24日我发现预览图无法加载，所以下载了8月24日的1.12.0版本更新包并更新了APP

经抽样核实，文件夹修改日期为8月24日的文件夹内，均为预览图文件".thumb"被修改，日期均为对应时间点。
初步推断原因为：更新APP后，打开下载列表发现下载列表缩略图均为灰色确实状态，下载列表内缩略图均需要重新加载（通过下拉列表方式加载缩略图，证据修改日期为8月24日的文件夹中，存在13:51到13:54时间段的修改时间，且排序方式为从新到旧，对应下拉列表从上到下），导致了该现象的发生。
另发现：少部分该日期之前的文件夹未被重新加载缩略图，文件夹修改日期未被修改。

**Comment by Kuma15781** [comment]
> > 8月24也不是现在啊文件夹里被修改了是哪个文件
> 
> 日期是8月24日的原因可能是：在8月24日我发现预览图无法加载，所以下载了8月24日的1.12.0版本更新包并更新了APP
> 
> 经最终修改，文件夹日期为8月24日的文件夹内，结果预览图文件“.thumb”被修改，日期结果修改对应时间点。 初步推断原因为：更新APP后，打开下载列表发现下载列表今晚需要重新加载，下载列表内都需要重新加载，导致了该现象的发生。最近 需要通过下拉列表方式加载，证明修改日期为8月24日的文件夹中，存在13:51到13:54时间段的修改时间，且排序方式大致为从新到旧（下载列表顺序，因加载速度不同，可能一个区间内的顺序有颠倒，但趋势总体是按照列表顺序），对应下拉列表从上到下
> 
> 另发现：少部分该日期之前的文件夹需要重新安装一次，文件夹修改日期需要修改。

几个月前有个版本更新了数据库
会把.thumb修改成thumb.jpg
你把本地下载的缩略图全部重新加载完以后就不会再出现了
