### ISSUE TITLE
Marshmallow 变种无必要保留

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#1633]
### 复现步骤 / Step to reproduce

0. 找台 Android 7 设备安装 EhViewer
1. 浏览任意画廊大图

### 预期行为 / Expected behaviour

看到图。

### 实际行为 / Actual Behaviour

看不到图，系统不信任 hath.network 用的 Let's Encrypt 证书。

### 应用日志 / App logs

N/A

### 备注 / Addition details

- https://github.com/UjuiUjuMandan/EhViewer/issues/90#issuecomment-2352183519

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

N/A

### EhViewer CI 版本 / EhViewer CI Version

N/A

### Android 系统版本 / Android version

Android 7

### 设备型号 / Device model

N/A

### SoC 型号 / Soc model

N/A

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
对于运行 Android 6 的设备，需要手动安装 [ISRG Root X1 证书](https://letsencrypt.org/certs/isrgrootx1.pem)
