### ISSUE TITLE
[bug]本地收藏无法导入

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#1634]
### 复现步骤 / Step to reproduce

迁移数据到新手机无法导入本地收藏，其他成功
![IMG_20240916_155902](https://github.com/user-attachments/assets/733dd43c-34e3-4e64-ac9e-15519f60cdc6)
![Screenshot_2024-09-16-16-17-57-35_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/e784e73f-0a30-4a5a-a692-ad96dcc2c06c)

### 预期行为 / Expected behaviour

正常导入

### 实际行为 / Actual Behaviour

无法导入

### 应用日志 / App logs

[log-2024-09-16-16-21-05-734.zip](https://github.com/user-attachments/files/17010158/log-2024-09-16-16-21-05-734.zip)

### 浏览站点 / Browsing site

ehentai

### EhViewer 版本号 / EhViewer version code

1.20

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

coloros14

### 设备型号 / Device model

oneplus ace3

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
日志中缺少相关信息，可以尝试重新导入数据再导出日志，或者提供数据库文件

> 不止此处，本来是日文名字的画廊不少变成了英文，看的很费力

设置里开了显示日文标题吗

**Comment by z1137** [comment]
这个就是重新导入过数据之后再导出换手机导入之后的日志，设置里面开了日文标题，e-和ex都检查并且切换重置了
[2024-09-16-15-52-42-569.zip](https://github.com/user-attachments/files/17084180/2024-09-16-15-52-42-569.zip)
这个压缩包里面大的是完整的，小的是导入错误之后再导出的

**Comment by FooIbar** [comment]
我说的是 app 设置里的日文标题，图中的两个画廊我导入后是可以正确显示的

**Comment by z1137** [comment]
> 我说的是 app 设置里的日文标题，图中的两个画廊我导入后是可以正确显示的

正常了，之前因为配额那个bug一进就闪退，还以为下面没有相关选项
