### ISSUE TITLE
里站突然sadpanda

### ISSUE THREAD

**Issue by TY12354** [FooIbar/EhViewer#1637]
### 复现步骤 / Step to reproduce

用的好好的突然就sadpanda换了无数ip都不行，表站没问题

### 预期行为 / Expected behaviour

出现列表

### 实际行为 / Actual Behaviour

sadpanda

### 应用日志 / App logs

[](url)
[log-2024-09-17-20-55-47-642.zip](https://github.com/user-attachments/files/17028509/log-2024-09-17-20-55-47-642.zip)

### 浏览站点 / Browsing site

eh

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

miui13.0.10

### 设备型号 / Device model

红米k50

### SoC 型号 / Soc model

 8+1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by RxinnotRstar** [comment]
设置-eh-账户

看一下igneous是不是改了

**Comment by TY12354** [comment]
> 设置-eh-账户
> 
> 看一下igneous是不是改了
变了，但是改不了，最多1秒就闪退

**Comment by TY12354** [comment]
> 设置-eh-账户
> 
> 看一下igneous是不是改了

清除了好几次最后还是my什么东西

**Comment by RxinnotRstar** [comment]
> 清除了好几次最后还是my什么东西

mystery是吗？
说明你的ex权限没了
重新登录一下吧

**Comment by FooIbar** [comment]
https://nicebowl.fun/11

闪退问题见 #1563
