### ISSUE TITLE
本地已下载漫画批量打包cbz功能

### ISSUE THREAD

**Issue by LinXu-LinXu** [FooIbar/EhViewer#1658]
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

无

### 实际行为 / Actual Behaviour

无

### 应用日志 / App logs

无

### 备注 / Addition details

https://github.com/FooIbar/EhViewer/issues/967
在出现“保存为cbz压缩包”开关前下载的漫画，都是jpg图片格式的，并且没有comicinfo.xml文件，不能被komga识别
希望能够添加将本地已下载漫画批量打包成cbz的功能

### 浏览站点 / Browsing site

E-Hentai / ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

6191ad7

### Android 系统版本 / Android version

MIUI 14.0.4 / Andriod 12

### 设备型号 / Device model

Redmi K30 Pro

### SoC 型号 / Soc model

骁龙 865

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #968
