### ISSUE TITLE
图片配额无法读取

### ISSUE THREAD

**Issue by TNTGans665** [FooIbar/EhViewer#1659]
### 复现步骤 / Step to reproduce

更新到最新版本后无法正常下载图集，翻了一下发现账户的图片配额无法显示，感觉是不能下载的原因所在
![Screenshot_1726856351](https://github.com/user-attachments/assets/c4341773-4332-44c5-ab5e-deb9121cf7de)

### 预期行为 / Expected behaviour

正常下载图集，正常显示和操作图片配额

### 实际行为 / Actual Behaviour

无法下载图集，不能显示和操作图片配额

### 应用日志 / App logs

[log-2024-09-21-02-25-49-664.zip](https://github.com/user-attachments/files/17079228/log-2024-09-21-02-25-49-664.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

b9da0ed

### Android 系统版本 / Android version

14

### 设备型号 / Device model

sdk_gphone64_arm64

### SoC 型号 / Soc model

在M1Mac上隐运行的模拟器

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by LinXu-LinXu** [comment]
https://github.com/FooIbar/EhViewer/issues/1563

**Comment by FooIbar** [comment]
根据所提供的日志，不能下载 https://e-hentai.org/g/3064373/694d8b2a67 是因为有正太 tag，无法从表站访问
