### ISSUE TITLE
返回手势导致应用闪退以及返回显示异常

### ISSUE THREAD

**Issue by teralomaniac** [FooIbar/EhViewer#1662]
### 复现步骤 / Step to reproduce

1. 
https://github.com/user-attachments/assets/c386f82c-a8ed-4648-b4ff-fb10c37f1cc6

2. 
https://github.com/user-attachments/assets/5d4980a6-8a97-4d55-8dd9-e52739561e91

### 预期行为 / Expected behaviour

1. 应当正常返回上一个页面
2. 应当在返回手势未完成前到取消手势后都不改变显示内容

### 实际行为 / Actual Behaviour

1. 应用闪退
2. 返回手势未完成前就跳转上一个页面，在取消手势后又回到原页面

### 应用日志 / App logs

[log-2024-09-21-19-33-36-576.zip](https://github.com/user-attachments/files/17083883/log-2024-09-21-19-33-36-576.zip)

### 浏览站点 / Browsing site

E-Hentai / ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

b9da0ed

### Android 系统版本 / Android version

OriginOS 4, Android 14

### 设备型号 / Device model

vivo X Fold 3

### SoC 型号 / Soc model

骁龙8Gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
2是预期行为 https://developer.android.com/design/ui/mobile/guides/patterns/predictive-back?hl=zh-cn

**Comment by FooIbar** [comment]
```
java.lang.IllegalArgumentException: Expecting fraction between 0 and 1. Got NaN
        at androidx.compose.animation.core.PreconditionsKt.throwIllegalArgumentException(Preconditions.kt:26)
        at androidx.compose.animation.core.SeekableTransitionState.seekTo(Transition.kt:2142)
        at androidx.navigation.compose.NavHostKt$NavHost$28$1.invokeSuspend(NavHost.kt:612)
```
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:navigation/navigation-compose/src/main/java/androidx/navigation/compose/NavHost.kt;l=612;drc=ea936f8359250bc9cb4c6c92bed301146c5dc57e

**Comment by FooIbar** [comment]
1是系统问题，建议向厂商反馈，可以附上我上面贴的堆栈跟踪
