### ISSUE TITLE
建议增加下载文件夹隐藏功能

### ISSUE THREAD

**Issue by vicentory** [FooIbar/EhViewer#1665]
### 复现步骤 / Step to reproduce

下载漫画的图片会被相册扫描到，相册里隐藏后在系统文件夹最近文件里还是会有展示。
建议增加隐藏功能，比如在默认下载文件夹里加个.nomedia文件，拒绝图库和文件系统扫描。

### Android 系统版本 / Android version

安卓14

### 设备型号 / Device model

小米14PRO

### SoC 型号 / Soc model

骁龙8gen3处理器

**Comment by FooIbar** [comment]
默认就会创建 .nomedia 文件，除非在下载设置里开启了允许媒体扫描
