### ISSUE TITLE
搜索时联想栏出现的前缀“a：作者名“无法搜索到作品。或者用前缀”a“搜索时作品缺失，而点击作者名字却能正常搜索到作品。

### ISSUE THREAD

**Issue by Gorilla-png** [FooIbar/EhViewer#1668]
### 复现步骤 / Step to reproduce

从1.12.0更新到1.13.0  ci版后问题依旧没有解决。

### 预期行为 / Expected behaviour

![Screenshot_2024-09-23-23-40-11-142_com xjs ehview](https://github.com/user-attachments/assets/d06456aa-8d76-484c-b0a6-a5ec21d7d46e)

### 实际行为 / Actual Behaviour

![Screenshot_2024-09-23-23-38-22-720_moe tarsin ehv](https://github.com/user-attachments/assets/4f946f70-7dbf-4714-b6e5-c29ea5c72207)

### 应用日志 / App logs

[log-2024-09-23-23-49-55-646.zip](https://github.com/user-attachments/files/17100434/log-2024-09-23-23-49-55-646.zip)

### 备注 / Addition details

第二个问题试验用的作者是”朝凪“。第一个问题实验用是作者”狛形“（很多其他作者也搜索不到），因为表里站区别的问题吗？直接搜索作品名字也搜索不到，只能从绿e拿一张图做对比。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

00ea9e9

### Android 系统版本 / Android version

android 12

### 设备型号 / Device model

redmi k30 pro

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你是不是选了 image set

**Comment by Gorilla-png** [comment]
谢谢，应该是不小心点到了

**Comment by Gorilla-png** [comment]
> 你是不是选了 image set

谢谢，应该是不小心点到了
