### ISSUE TITLE
评论选项框样式异常

### ISSUE THREAD

**Issue by LzNOHentai** [FooIbar/EhViewer#1677]
### 复现步骤 / Step to reproduce

如题
![Screenshot_2024-09-25-08-03-46-674_moe tarsin ehviewer-edit](https://github.com/user-attachments/assets/9bb2150c-632c-4a80-affa-a0def333eeb6)

### 预期行为 / Expected behaviour

应为正常大小

### 实际行为 / Actual Behaviour

大小异常

### 应用日志 / App logs

暂无

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

601713d

### Android 系统版本 / Android version

HyperOS

### 设备型号 / Device model

Xiaomi 14 Pro

### SoC 型号 / Soc model

骁龙 8Gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by revonateB0T** [comment]
@LzNOHentai Steps to reproduce?

**Comment by revonateB0T** [comment]
@revonateB0T Edit: Got it, install latest CI then I can reproduce it.
