### ISSUE TITLE
Can we have a new feature to filter the downloaded galaries which have been removed, show the galaries ID is enough? 可以添加一个筛选哪些已下载画廊已被删除的功能吗，有画廊id就好

### ISSUE THREAD

**Issue by zbt000** [FooIbar/EhViewer#1688]
### 复现步骤 / Step to reproduce

as description
如题

### 预期行为 / Expected behaviour

as description
如题

### 实际行为 / Actual Behaviour

as description
如题

### 应用日志 / App logs

as description
如题

### 备注 / Addition details

I want to buy a new phone but realized it is too hard to transfer files from old phone to new phone. (about 300GB download galaries) Try to save them in my computer but also find it is really slow to copy from phone to computer. (too many small files and speed is only about 30~40 m/s) So if it can have a new feature to filter removed galaries‘ id, then I can just copy the removed galaries to my computer then transfer them to my new phone. I think others may also have this need, since when change to new phone, if just import the data and redownload, removed galaries are not able to be downloaded.

我想换手机，但发现从旧手机到新手机传输文件太麻烦了。(大约300GB的已下载)我试着把它们先存在我的电脑里，但发现从手机复制到电脑太慢了。(小文件太多，速度只有30~40m/s)所以如果它能过滤出删除的图库的id，那么我可以手动把删除的图库复制到我的电脑上，然后挪到我的新手机上。其他人应该也能用上，因为如果光转移数据然后恢复下载，已删除画廊是没法下回来的

### 浏览站点 / Browsing site

E-Hentai / ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

24d2072

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

Samsung Fold 4

### SoC 型号 / Soc model

骁龙8+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
都是小文件的问题，可以在下载设置里开启保存为压缩包，然后在下载里全选-开始下载，会将已下载的画廊打包
