### ISSUE TITLE
怎么自定义筛选分数（如≥4.5分）

### ISSUE THREAD

**Issue by FloweretMing** [FooIbar/EhViewer#1690]
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

无

### 实际行为 / Actual Behaviour

无

### 应用日志 / App logs

无

### 备注 / Addition details

请问怎么自定义筛选分数？如筛选评分≥4.5的漫画。如果不能进行这种筛选的话，希望可以增加该功能。谢谢！

### 浏览站点 / Browsing site

中文

### EhViewer 版本号 / EhViewer version code

最新版本

### EhViewer CI 版本 / EhViewer CI Version

最新版本

### Android 系统版本 / Android version

小米澎湃系统

### 设备型号 / Device model

小米14

### SoC 型号 / Soc model

骁龙8gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
筛选不支持小数分数
