### ISSUE TITLE
作品标题太长，画廊页面无法完整展示

### ISSUE THREAD

**Issue by hxdhttk** [FooIbar/EhViewer#1707]
### 复现步骤 / Step to reproduce

进入一个作品标题很长的画廊

### 预期行为 / Expected behaviour

有符合直觉的办法展示作品完整标题

### 实际行为 / Actual Behaviour

标题被截断，无法找到完整展示的办法
![1000029997](https://github.com/user-attachments/assets/b1e649cb-aff6-4a31-872b-02e801cb0537)

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1012.1

### EhViewer CI 版本 / EhViewer CI Version

 cfe2cff

### Android 系统版本 / Android version

HyperOS 1.0.13.0，Android 14

### 设备型号 / Device model

Xiaomi 13

### SoC 型号 / Soc model

骁龙 8 Gen 2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by kagg886** [comment]
复制一下这个作品的链接，谢谢喵

**Comment by FooIbar** [comment]
点击封面右侧的信息栏可以查看完整标题
