### ISSUE TITLE
返回手势不会返回上一级页面，错误的退出了软件

### ISSUE THREAD

**Issue by xymb-world** [FooIbar/EhViewer#1714]
### 复现步骤 / Step to reproduce

0.全新安装应用
1.登录账号
2.打开任意漫画
3.使用全局返回手势，返回上一级

### 预期行为 / Expected behaviour

它应该是返回上一级的漫画预览页面

### 实际行为 / Actual Behaviour

实际上直接退出了软件，回到了桌面

### 应用日志 / App logs

[log-2024-10-09-23-08-27-609.zip](https://github.com/user-attachments/files/17310551/log-2024-10-09-23-08-27-609.zip)

### 备注 / Addition details
图例：
![Screenshot_2024-10-09-23-10-09-451_moe tarsin ehviewer-edit](https://github.com/user-attachments/assets/82aec3bd-8f1f-4616-b72e-c353b6be55d6)
![Screenshot_2024-10-09-23-11-53-480_moe tarsin ehviewer-edit](https://github.com/user-attachments/assets/898db757-759b-47c4-bfe7-fc78f9afbe77)

临时解决办法：使用经典导航键，点击返回，可正常返回上一级

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

aef02d3

### Android 系统版本 / Android version

Hyper OS , Android 14

### 设备型号 / Device model

Xiaomi 13 Pro

### SoC 型号 / Soc model

骁龙 8 Gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by lings03** [comment]
装了beta内测版桌面吧，系统问题

**Comment by xymb-world** [comment]
> 装了beta内测版桌面吧，系统问题

感谢，我卸载桌面试试。

**Comment by xymb-world** [comment]
系统：Hyper OS Beta增强版
软件：系统桌面
版本：RELEASE-5.39.30.9413-09111514
问题：全局返回手势重构，EhVierwer会出现返回手势失效问题。

**Comment by yinzhefuyun** [comment]
> 系统：Hyper OS Beta增强版 软件：系统桌面 版本：RELEASE-5.39.30.9413-09111514 问题：全局返回手势重构，EhVierwer会出现返回手势失效问题。

实际上是，调用了新的预览返回，然后这个预览返回报错了，闪退了，不是ehv的问题，大概率的安卓14安装安卓15内存桌面导致的组件不兼容或者缺少
