### ISSUE TITLE
打开下载原图时, 不下载原图, 且第二张之后显示解析失败

### ISSUE THREAD

**Issue by chikinrais** [FooIbar/EhViewer#172]
### 复现步骤 / Step to reproduce

登录后, 打开下载原图的状态下
进入任何一个画集, 都不显示原图, 而是明显压缩过的版本
1.8.8.3之前的版本, 只会加载第一张图, 其后所有图变为“解析失败”

### 预期行为 / Expected behaviour

本来应该下载原图, 选择“保存为”时显示的文件后缀名为.png或.jpg

### 实际行为 / Actual Behaviour

加载出来的图片明显分辨率低, 且“保存为”保存的文件也是压缩过的jpeg

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.8.3, 1.8.11.0, 1.7.31.0-alpha04

### EhViewer CI 版本 / EhViewer CI Version

未知

### Android 系统版本 / Android version

ColorOS 11

### 设备型号 / Device model

Oneplus 9R

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #170

**Comment by chikinrais** [comment]
啊？所以这个问题是等待修复中吗, 不太熟悉github, 希望说一下

**Comment by FooIbar** [comment]
CI 版已经修了

**Comment by chikinrais** [comment]
那么下一个能下载的版本会整合这个修复吗

**Comment by FooIbar** [comment]
CI 版本可以下载，上面的自查步骤里就有链接，你打勾前都不看的吗？

**Comment by chikinrais** [comment]
抱歉, 我以为自查步骤指的是releases的最新版本, 我试试cl版

**Comment by FooIbar** [comment]
稳定版1.8.11.1已经包含这个修复了

**Comment by D2Joy** [comment]
问题还是存在呀, 只能加载一张图

**Comment by FooIbar** [comment]
> 问题还是存在呀, 只能加载一张图

有问题单独开issue
