### ISSUE TITLE
移动网络无法直连

### ISSUE THREAD

**Issue by a845542683** [FooIbar/EhViewer#177]
### 复现步骤 / Step to reproduce

一周之前解析失败那个版本更新之前，一直可以使用流量或者wifi直连，更新之后这几个版本都不可以了，一直提示超时，网络错误，使用VPN就直接锁ip

### 预期行为 / Expected behaviour

无法直连

### 实际行为 / Actual Behaviour

![Screenshot_20231102_070629_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/22552660/1929d5b5-cee8-460a-bae7-66080b8e3e49)

### 应用日志 / App logs

/

### 备注 / Addition details

。。。

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1

### EhViewer CI 版本 / EhViewer CI Version

7e90555

### Android 系统版本 / Android version

安卓10

### 设备型号 / Device model

华为

### SoC 型号 / Soc model

不知道

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by acuma7** [comment]
这个版本把域名前置功能删了
那个功能个人理解是无限接近黑色的灰色

**Comment by a845542683** [comment]
那么有什么解决办法吗？或者能恢复一下吗？因为无法直连，而VPN因为用的人太多，又会打开app就直接ip几小时到几天不等，现在根本用不了eh

**Comment by acuma7** [comment]
你可以试试其他版本，比如https://github.com/xiaojieonly/Ehviewer_CN_SXJ，或者换个梯子
我也不是开发者，就一吃瓜群众

**Comment by FooIbar** [comment]
Duplicate of #12
