### ISSUE TITLE
Limit thumb request concurrency

### ISSUE THREAD

**Issue by revonateB0T** [FooIbar/EhViewer#1776]
Seems thumb server will not respond if there is too many parallel requests until you change IP.

**Comment by yinzhefuyun** [comment]
那如果这个IP只有我自己在用我能拉爆这个并行请求数吗？毕竟我电脑看的时候同时加载数是远大于手机端的

**Comment by FooIbar** [comment]
> 那如果这个IP只有我自己在用我能拉爆这个并行请求数吗？毕竟我电脑看的时候同时加载数是远大于手机端的

开启使用表站缩略图服务器的话不受限制

**Comment by yinzhefuyun** [comment]
> > 那如果这个IP只有我自己在用我能拉爆这个并行请求数吗？毕竟我电脑看的时候同时加载数是远大于手机端的
> 
> 开启使用表站缩略图服务器的话不受限制

有一个问题我想问一下啊，现在详情页和缩略图合并了，这样体验上会好很多，就是假如我要看一个韩漫，有1800多页，然后我直接滚动条拉到尾巴，要多久能加载到第1800张，然后如果我这个时候放弃了，然后返回了，然后搜索列表剩下的缩略图的加载逻辑是什么，是不是要等韩漫那1800张加载完成才加载返回后看到的搜索结果缩略图

**Comment by FooIbar** [comment]
> > > 那如果这个IP只有我自己在用我能拉爆这个并行请求数吗？毕竟我电脑看的时候同时加载数是远大于手机端的
> > 
> > 
> > 开启使用表站缩略图服务器的话不受限制
> 
> 有一个问题我想问一下啊，现在详情页和缩略图合并了，这样体验上会好很多，就是假如我要看一个韩漫，有1800多页，然后我直接滚动条拉到尾巴，要多久能加载到第1800张，然后如果我这个时候放弃了，然后返回了，然后搜索列表剩下的缩略图的加载逻辑是什么，是不是要等韩漫那1800张加载完成才加载返回后看到的搜索结果缩略图

直接拉到底只会加载最后一页的缩略图，中间的会被跳过，具体数量取决于网站里的缩略图行数设置
返回的话没加载完的请求会被取消

**Comment by yinzhefuyun** [comment]
> > > > 那如果这个IP只有我自己在用我能拉爆这个并行请求数吗？毕竟我电脑看的时候同时加载数是远大于手机端的
> > > 
> > > 
> > > 开启使用表站缩略图服务器的话不受限制
> > 
> > 
> > 有一个问题我想问一下啊，现在详情页和缩略图合并了，这样体验上会好很多，就是假如我要看一个韩漫，有1800多页，然后我直接滚动条拉到尾巴，要多久能加载到第1800张，然后如果我这个时候放弃了，然后返回了，然后搜索列表剩下的缩略图的加载逻辑是什么，是不是要等韩漫那1800张加载完成才加载返回后看到的搜索结果缩略图
> 
> 直接拉到底只会加载最后一页的缩略图，中间的会被跳过，具体数量取决于网站里的缩略图行数设置 返回的话没加载完的请求会被取消

如果是用手划到1800张（比加载速度快）这样加载逻辑是什么？还有我想问一个问题，是不是手机端APP都做不到和电脑的谷歌浏览器一样加载图片，即便图片没有加载完成也能把先下载完成的部分显示加载出来，然后一块一块显示完全，这种图片加载方式好像除非是浏览器我都没在app里面见过

**Comment by yinzhefuyun** [comment]
> 如果开了激进预载的话，所有缩略图都会被下载，但超出屏幕范围一定距离的不会被解码（因为它们反正不会被显示，需要的时候再解码也很快） 第二个问题，做当然是能做到的，问题是是否值得

如果我开了激进预载，然后滑倒了1800张，然后返回，理论上剩下的只要不是已经开始下载的省略图应该会被清空下载任务吧。

第二个问题还是能提升阅读体验的，甚至可以加快阅读速度，毕竟我可以和下载同步阅读图片，被运营商限制pcdn和Tenboro站长的奇葩调度限制，导致现在H@H客户端更容易分配给普通家用节点，而不是大的H@H站点，这导致现在图片的加载速度普遍比起大虚拟机做H@H普遍慢了很多，所以如果能一边下载一边阅读应该能弥补等待的时间

**Comment by yinzhefuyun** [comment]
> 已经开始下载的也会被取消
> 
> Android 官方 API 不支持，带来的好处和额外的复杂性和维护成本相比不值得

官方API不支持确实可惜，主要是维护成本会变高，以前国区能达到全球一半的流量，然后下降到和亚洲和大洋洲流量相当，现在差点和美洲区差不多流量了，现在获取的H@H节点都很邪门基本不是国内，导致平均加载时间变长
下面附一张图https://e-hentai.org/hentaiathome.php
![image](https://github.com/user-attachments/assets/0224ff5e-8b40-470d-a9b6-c33d79e487d8)
