### ISSUE TITLE
[Enhancement]画廊信息这里能不能长按复制或者任意方法复制每一行的信息

### ISSUE THREAD

**Issue by yinzhefuyun** [FooIbar/EhViewer#1791]
### 复现步骤 / Step to reproduce

建议能复制画廊信息中所有的数据
![Screenshot_2024-10-25-09-21-45-137_moe tarsin ehv](https://github.com/user-attachments/assets/c66c882a-168b-4392-a747-8eba57084cf1)

### 预期行为 / Expected behaviour

点击或者长按文字能够复制文字

### 实际行为 / Actual Behaviour

什么都没有

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

62927cb

### Android 系统版本 / Android version

澎湃OS1

### 设备型号 / Device model

红米K50U/三星note3

### SoC 型号 / Soc model

8+1/800

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by revonateB0T** [comment]
@yinzhefuyun 本来就能 只是你的系统在复制成功后不会按预期的在左下角显示剪切板

**Comment by revonateB0T** [comment]
@yinzhefuyun 建议向你的系统供应商汇报此问题

**Comment by yinzhefuyun** [comment]
> @yinzhefuyun 本来就能 只是你的系统在复制成功后不会按预期的在左下角显示剪切板

还真的能复制，确实是没有toast提醒，垃圾小米
