### ISSUE TITLE
画廊无法加载，显示check failed

### ISSUE THREAD

**Issue by Noctulus** [FooIbar/EhViewer#1792]
### 复现步骤 / Step to reproduce

1. 主页及搜索页面可以正常加载，点击任意画廊

### 预期行为 / Expected behaviour

它应该可以正常加载画廊

### 实际行为 / Actual Behaviour

实际上它加载失败，显示Check failed.
![Screenshot_2024-10-25-15-32-01-46_f2f1746601bf3b868d00d5efaf12e601](https://github.com/user-attachments/assets/13323429-e8a3-4747-8abb-28ed5595529f)

### 应用日志 / App logs

[log-2024-10-25-15-29-47-769.zip](https://github.com/user-attachments/files/17517865/log-2024-10-25-15-29-47-769.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

8612027

### Android 系统版本 / Android version

Realme UI 6.0

### 设备型号 / Device model

Realme GT5 Pro

### SoC 型号 / Soc model

骁龙 8 Gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
> 2024-10-25
> - The previously announced backend and DOM changes are now live for a section of the site, let me know if you encounter any issues with this NOT related to outdated scripts.

https://forums.e-hentai.org/index.php?showtopic=244935

**Comment by FooIbar** [comment]
在修复之前可以先用表站

**Comment by InLem** [comment]
> ~在修复之前可以先用表站~ 已于最新 CI 版本修复

你好，我更新CI還是一樣的問題。

**Comment by FooIbar** [comment]
> > ~在修复之前可以先用表站~ 已于最新 CI 版本修复
> 
> 你好，我更新CI還是一樣的問題。

首先，检查更新确保版本号里的提交时间在 2024-10-25 14:00 之后
如果仍存在问题上传日志

**Comment by escape0707** [comment]
App检查更新一般是只看release版本。CI版本才是每次提交都会编译一次的版本，相当于nightly。

~~（我非想评论一下的原因其实是我今天打开app然后发现这个错误的时候看到是同一个画廊我会说吗~~

**Comment by FooIbar** [comment]
> App检查更新一般是只看release版本。CI版本才是每次提交都会编译一次的版本，相当于nightly。
> 
> ~（我非想评论一下的原因其实是我今天打开app然后发现这个错误的时候看到是同一个画廊我会说吗~

你要开启使用 CI 频道更新
