### ISSUE TITLE
里站无法正常显示画廊

### ISSUE THREAD

**Issue by Ferraridino001** [FooIbar/EhViewer#1799]
### 复现步骤 / Step to reproduce

0重新安装应用
1在网页端重置cookie，拥有里站权限
2使用网页登录，进入里站，发现无法打开画廊

### 预期行为 / Expected behaviour

正常打开画廊

### 实际行为 / Actual Behaviour

无法正常打开，显示如下
![Screenshot_20241025_212852](https://github.com/user-attachments/assets/ff641b5c-5b7f-4acd-8045-ad726287e487)

### 应用日志 / App logs

[log-2024-10-25-16-34-04-572.zip](https://github.com/user-attachments/files/17524106/log-2024-10-25-16-34-04-572.zip)

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.12.1.3

### EhViewer CI 版本 / EhViewer CI Version

9fbe308

### Android 系统版本 / Android version

Origin os3

### 设备型号 / Device model

Iqoo neo8

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
我们版本号只有三位
本仓库不处理其他版本的问题
