### ISSUE TITLE
请求加入键盘快捷键支持

### ISSUE THREAD

**Issue by 627992512** [FooIbar/EhViewer#1801]
### 复现步骤 / Step to reproduce

请求加入键盘快捷键支持

### 预期行为 / Expected behaviour

目前正在使用手柄映射键盘的方式作为翻页器，但目前ehviewer并没有对键盘快捷键的支持，目前发现可以音量键翻页，但很多手柄没办法映射手机的音量键。

### 实际行为 / Actual Behaviour

-

### 应用日志 / App logs

-

### 备注 / Addition details

-

### 浏览站点 / Browsing site

-

### EhViewer 版本号 / EhViewer version code

-

### EhViewer CI 版本 / EhViewer CI Version

-

### Android 系统版本 / Android version

-

### 设备型号 / Device model

-

### SoC 型号 / Soc model

-

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
添加了对 PageUp/PageDown 和方向键上/下翻页的支持
