### ISSUE TITLE
1.13.0版本出现的错误报告 错误代码如图

### ISSUE THREAD

**Issue by sakana456** [FooIbar/EhViewer#1802]
### 复现步骤 / Step to reproduce

安装EhViewer-1.12.1-default-arm64-v8a.apk并启动

### 预期行为 / Expected behaviour

应该正常加载画廊

### 实际行为 / Actual Behaviour

实际却出现了如下代码
![Screenshot_2024-10-26-02-36-05-126_moe tarsin ehviewer](https://github.com/user-attachments/assets/f7fd6e24-12d1-4408-aa6a-f56944bb120b)

### 应用日志 / App logs

[log-2024-10-26-03-08-40-144.zip](https://github.com/user-attachments/files/17526584/log-2024-10-26-03-08-40-144.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

e843a54

### Android 系统版本 / Android version

xiaomi hyperos 1.0.7.0

### 设备型号 / Device model

redmi note 12 turbo

### SoC 型号 / Soc model

骁龙7＋

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by sakana456** [comment]
图片上传错了，这张是升级到新版的错误代码

**Comment by sakana456** [comment]
![Uploading Screenshot_2024-10-26-03-05-59-707_moe.tarsin.ehviewer.jpg…]()

**Comment by FooIbar** [comment]
Duplicate of #12
