### ISSUE TITLE
1.13.0打开应用不能加载画廊

### ISSUE THREAD

**Issue by sakana456** [FooIbar/EhViewer#1805]
### 复现步骤 / Step to reproduce

安装EhViewer-1.12.1-default-arm64-v8a.apk
发现首页报错
检查并更新
回到主页依旧报错

### 预期行为 / Expected behaviour

本应正常加载画廊

### 实际行为 / Actual Behaviour

实际出现了错误代码，p1为1.12.1版本的报错，p2为升级到1.13.0版本的错误代码
![Uploading Screenshot_2024-10-26-03-05-59-707_moe.tarsin.ehviewer.jpg…]()

### 应用日志 / App logs

[log-2024-10-26-03-08-40-144.zip](https://github.com/user-attachments/files/17526647/log-2024-10-26-03-08-40-144.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

e843a54

### Android 系统版本 / Android version

xiaomi hyperos 1.0.7.0

### 设备型号 / Device model

redmi note 12 turbo

### SoC 型号 / Soc model

骁龙7＋

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by J4ckTh3R1pper** [comment]
去用最新CI版本，可以加载

**Comment by escape0707** [comment]
Duplicate of #1792?

**Comment by sakana456** [comment]
已更新至最新ci版本，当前版本1.13.1abccf71
但问题并未解决
![Uploading Screenshot_2024-10-26-10-49-46-846_moe.tarsin.ehviewer.jpg…]()

**Comment by FooIbar** [comment]
Duplicate of #12

**Comment by escape0707** [comment]
只有我看不到sakana发的截图嘛。。

嘛要是看日志也能定位这次的问题就当我没说好了。。

**Comment by sakana456** [comment]
原来大家都看不到，我自己也看不到🤔，可能是浏览器的问题，等下在电脑上传

**Comment by escape0707** [comment]
我怀疑你是在截图还没上传完的时候就发出来了，就变成这样了。

**Comment by sakana456** [comment]
![Screenshot_2024-10-26-10-49-46-846_moe tarsin ehviewer](https://github.com/user-attachments/assets/078a0543-1739-4124-b82c-882fb5bad0e6)
还真是

**Comment by sakana456** [comment]
对不起🙏via

**Comment by escape0707** [comment]
超时的问题你确定不是自己的网络环境的原因？我反正是没问题了

**Comment by sakana456** [comment]
我也不清楚，用cookie也登录不上，暂时先用绿e吧，正犯愁怎么把本地收藏转过去😱
