### ISSUE TITLE
网站设置中自定义分辨率失效

### ISSUE THREAD

**Issue by 947zyz** [FooIbar/EhViewer#182]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/149185072/d0cbbcd7-aedc-41bb-9fa5-1d700f01e858

如视频所示 在网站设置中更改分辨率为1280x后，主页中选择画廊，图片加载后分辨率仍为低分辨率，退出后重新回到网站设置发现分辨率选项又变为自动选项。

### 预期行为 / Expected behaviour

网站设置中选用1280x分辨率后，所加载的画廊图片分辨率都应为1280x

### 实际行为 / Actual Behaviour

网站中的分辨率设置失效，画廊中的图片仍为默认低分辨率

### 应用日志 / App logs

[log-2023-11-02-14-10-13-337.zip](https://github.com/FooIbar/EhViewer/files/13235007/log-2023-11-02-14-10-13-337.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1-gms

### EhViewer CI 版本 / EhViewer CI Version

7e90555

### Android 系统版本 / Android version

MIUI 14.0.19 (Android 13)

### 设备型号 / Device model

Redmi Note 12 Turbo

### SoC 型号 / Soc model

骁龙 7+ Gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #137
