### ISSUE TITLE
某些小米系统上应用闪退

### ISSUE THREAD

**Issue by feelqgit** [FooIbar/EhViewer#1826]
### 复现步骤 / Step to reproduce

1. 选择任意画廊
2. 阅读

### 预期行为 / Expected behaviour

它应该正常维持页面可供阅读

### 实际行为 / Actual Behaviour

实际上无论图片是否加载出来，时间或长或短，最长不到2秒，随即闪退

### 应用日志 / App logs

[log-2024-10-28-23-46-15-311.zip](https://github.com/user-attachments/files/17545454/log-2024-10-28-23-46-15-311.zip)

[log-2024-10-28-23-52-14-041.zip](https://github.com/user-attachments/files/17545457/log-2024-10-28-23-52-14-041.zip)

### 备注 / Addition details

闪退时没有提示，信息最多的一次是瞥见有error code=10或者11，该信息不太可靠。另外，进排行会立即闪退，进收藏会报错，点击报错信息之后会闪退，或者直接闪退，如图。
![Screenshot_2024-10-28-23-50-50-891_moe tarsin ehviewer](https://github.com/user-attachments/assets/ffd3fe5a-e531-48ef-bae0-101d4b0991ba)
不清楚以上是否全部都是一个原因。因此有两份日志，一份是画廊闪退的，一份是收藏报错的。以上错误仅在本次反馈的设备上出现，在平板上没有出现。

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13.0-snapshot

### EhViewer CI 版本 / EhViewer CI Version

4d2b7b3

### Android 系统版本 / Android version

小米澎湃OS 1.0.6.0UKACNXM

### 设备型号 / Device model

小米11ultra

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你手机系统里的某个组件有问题，我看看我们有没有补救办法

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/11558997256/artifacts/2113544904
试下这个版本，在高级设置里关闭 Cronet 后重启

**Comment by feelqgit** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/11558997256/artifacts/2113544904 试下这个版本，在高级设置里关闭 Cronet 后重启

该版本关闭cronet重启应用后问题已解决，感谢🙏🏻

**Comment by FooIbar** [comment]
> 米板6s pro，安卓15测试版有同样的问题。禁用cronet后不再闪退

也传一下日志

**Comment by RnJ4** [comment]
> > 米板6s pro，安卓15测试版有同样的问题。禁用cronet后不再闪退
> 
> 也传一下日志

[log-2024-10-29-04-24-48-958.zip](https://github.com/user-attachments/files/17553371/log-2024-10-29-04-24-48-958.zip)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/11662639052
这个版本之后检测到该错误会自动禁用 Cronet 并重启

**Comment by RnJ4** [comment]
手机升级到hyperos2之后也出现cronet闪退了，我推测所有小米Android15都会有这个问题。

**Comment by FooIbar** [comment]
> 手机升级到hyperos2之后也出现cronet闪退了，我推测所有小米Android15都会有这个问题。

我们能做的就这些，建议使用相关日志向小米报告
