### ISSUE TITLE
安卓8.0没有预览图

### ISSUE THREAD

**Issue by ssmisim** [FooIbar/EhViewer#1829]
### 复现步骤 / Step to reproduce

1、重新安装CI版本
2、打开彩e

### 预期行为 / Expected behaviour

所有封面/画廊预览图都应该能看见

### 实际行为 / Actual Behaviour

![1](https://github.com/user-attachments/assets/fb613280-62d2-4168-b2d1-637e816a4b13)
![2](https://github.com/user-attachments/assets/47728b71-6aa5-4a33-9ddc-ee517d2bad84)

### 应用日志 / App logs

[log-2024-10-29-12-10-02-310.zip](https://github.com/user-attachments/files/17551661/log-2024-10-29-12-10-02-310.zip)

### 备注 / Addition details

可以正常观看和下载

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT-M

### EhViewer CI 版本 / EhViewer CI Version

e76777b

### Android 系统版本 / Android version

Android 8.0

### 设备型号 / Device model

G8441

### SoC 型号 / Soc model

骁龙835

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你 8.0 为什么用的是 Marshmallow 版（6.0-7.1）
从日志来看是网络错误

**Comment by ssmisim** [comment]
> 你8.0为什么用的是Marshmallow版本（6.0-7.1） 从日志来看是网络错误

我安装了两个版本，Marshmallow的用得比较流畅就一直用这个了，其实两个版本都不能看预览图，可以正常看和下载，隔壁绿E有预览图

**Comment by ssmisim** [comment]
> @ssmisim请问绿叶是直连吗？
> 
> 直连和VPN分别在浏览器能否打开https://ehgt.org/83/d2/83d28a61ac57f5f77c7fb0b66f4a4846b6940af3-1151359-1057-1500-jpg_250.jpg？

绿E和彩E都是挂全局代理的，直连和VPN都能在浏览器打开那张飞燕老师的图片

**Comment by PlexPt** [comment]
eh更新了

**Comment by PlexPt** [comment]
https://forums.e-hentai.org/index.php?showtopic=244935
