### ISSUE TITLE
无法正确加载画廊

### ISSUE THREAD

**Issue by laowanglr** [FooIbar/EhViewer#1833]
### 复现步骤 / Step to reproduce

在软件中下载画廊，出现该提示，并下载失败
![Screenshot_2024-10-29-21-27-39-038_moe tarsin ehviewer-edit](https://github.com/user-attachments/assets/0753b0b8-804a-4341-a225-4f4c2f5ee086)

### 预期行为 / Expected behaviour

预期能够正常下载

### 实际行为 / Actual Behaviour

实际上无法正确下载

### 应用日志 / App logs

[log-2024-10-29-21-29-35-530.zip](https://github.com/user-attachments/files/17557491/log-2024-10-29-21-29-35-530.zip)

### 备注 / Addition details

最新版本

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.2-cc

### EhViewer CI 版本 / EhViewer CI Version

006d5af

### Android 系统版本 / Android version

hyper os

### 设备型号 / Device model

xiaomi14

### SoC 型号 / Soc model

8gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by xb2016** [comment]
@laowanglr 《您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决》

**Comment by FooIbar** [comment]
非本仓库版本
