### ISSUE TITLE
更新后bt种子下载出现的一些问题

### ISSUE THREAD

**Issue by nickhe800** [FooIbar/EhViewer#1838]
### 复现步骤 / Step to reproduce

1.选择画廊点击下载bt种子
2.画廊bt种子新增了链接对话框
3.下载种子连接困难，成功下载后名称与对应画廊名称不符（图2为更新前和更新后的下载记录，显示名称不同）
![Uploading IMG_20241030_134251.jpg…]()
![Screenshot_2024-10-29-23-06-37-173_com android providers downloads ui](https://github.com/user-attachments/assets/3066a9c9-748d-49a0-aaec-fa504024a481)

### 预期行为 / Expected behaviour

应该流畅下载，下载种子的名称应与画廊内的种子名称相符

### 实际行为 / Actual Behaviour

实际上下载卡顿，且下载种子名称不符

### 应用日志 / App logs

[log-2024-10-30-13-34-24-447.zip](https://github.com/user-attachments/files/17566881/log-2024-10-30-13-34-24-447.zip)

### 备注 / Addition details

很抱歉帖子发在bug这边，因为这可能不算bug，只是一个优化建议，麻烦开发者大大了！
之前下载bt种子很方便，直接点击下载并且很流畅，保存文件名也是画廊种子的名称，不知道从哪个小版本开始就变了。
看其他帖子发现有老哥说了下网页端种子下载的优化问题，是否是某些改动导致客户端这边的下载产生了某种变化？

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.13.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

53dc622

### Android 系统版本 / Android version

MIUI13

### 设备型号 / Device model

xiaomi12

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
请使用合适的软件下载磁力链接
