### ISSUE TITLE
鸿蒙系统无法通过CI频道更新

### ISSUE THREAD

**Issue by KiraBoXin** [FooIbar/EhViewer#1840]
### 复现步骤 / Step to reproduce

CI频道更新会在应用内下载并安装新版，导致鸿蒙认为病毒软件想安装apk从而阻止软件安装，希望提供新的release版或者更新过的旧版本。

### 预期行为 / Expected behaviour

在浏览器上下载的release版本可以通过勾选“我已了解风险”来继续安装。

### 实际行为 / Actual Behaviour

![Screenshot_20241030_145749_com huawei appmarket](https://github.com/user-attachments/assets/f6b963e6-59dc-4374-b3f3-78436bfb77bb)

### 应用日志 / App logs

无

### 备注 / Addition details

想更新的原因是check failed无法进入画廊。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.1

### EhViewer CI 版本 / EhViewer CI Version

dd29496

### Android 系统版本 / Android version

Harmony OS 4.0.0.130

### 设备型号 / Device model

Mate 40 pro

### SoC 型号 / Soc model

麒麟9000

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
可自行于 https://github.com/FooIbar/EhViewer/actions 下载 CI 版本
