### ISSUE TITLE
开始下载或者更新的时候的时候应用会消失

### ISSUE THREAD

**Issue by Momotk** [FooIbar/EhViewer#1876]
### 复现步骤 / Step to reproduce

在应用内开始下载或者更新

### 预期行为 / Expected behaviour

应该下载或者更新

### 实际行为 / Actual Behaviour

实际上应用要么报个错误提示，要么整个应用界面消失。

### 应用日志 / App logs

![Screenshot_2024-11-04-11-17-38-089_moe tarsin ehv](https://github.com/user-attachments/assets/3ee96e12-e2f6-4866-918a-fccd0e98b32a)
[log-2024-11-04-11-15-18-489(1).zip](https://github.com/user-attachments/files/17613453/log-2024-11-04-11-15-18-489.1.zip)

### 备注 / Addition details

系统已经打开应用崩溃提醒，未收到应用崩溃提示。

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.14.0

### EhViewer CI 版本 / EhViewer CI Version

94da911

### Android 系统版本 / Android version

Xiaomi HyperOS 1.0.13.0.UNVCNXM

### 设备型号 / Device model

小米fold4

### SoC 型号 / Soc model

骁龙8Gen3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #1826
