### ISSUE TITLE
进不去里站，没有igoenus

### ISSUE THREAD

**Issue by 1572139021** [FooIbar/EhViewer#1891]
### 复现步骤 / Step to reproduce

重新登录账户，cookie显示igneous:null
站点选择exhentai显示超时

### 预期行为 / Expected behaviour

它应该正常显示画廊

### 实际行为 / Actual Behaviour

实际显示超时

### 应用日志 / App logs

[log-2024-11-05-11-06-03-020.zip](https://github.com/user-attachments/files/17626417/log-2024-11-05-11-06-03-020.zip)

### 备注 / Addition details

浏览器可以正常进去exhentai，但是速度明显变慢，ehentai好像更新了，但是我不知道和这个有什么关联

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.14.0

### EhViewer CI 版本 / EhViewer CI Version

5f2f3f9

### Android 系统版本 / Android version

originos4

### 设备型号 / Device model

iqoo11pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
网络问题
