### ISSUE TITLE
更新1.13.0之后，调整音量键翻页速度的功能消失

### ISSUE THREAD

**Issue by LX-676655103** [FooIbar/EhViewer#1892]
### 复现步骤 / Step to reproduce

在更新1.13.0版本之后，调整音量键翻页速度的功能消失

### 预期行为 / Expected behaviour

原先存在可以调整音量键翻页速度的速度条

### 实际行为 / Actual Behaviour

当前调整音量键翻页速度的功能消失，导致当前翻页速度过快

### 应用日志 / App logs

[log-2024-11-05-13-23-12-154.zip](https://github.com/user-attachments/files/17627344/log-2024-11-05-13-23-12-154.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

fe4ab6f

### Android 系统版本 / Android version

MIUI 14.0.31

### 设备型号 / Device model

Xiaomi 13

### SoC 型号 / Soc model

骁龙 8 Gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
预期行为
