### ISSUE TITLE
下载画廊后图片没有保存cbz至下载路径里也没comiclnfo.xml,但图片存在用户数据缓存里

### ISSUE THREAD

**Issue by keart-of-fade** [FooIbar/EhViewer#1895]
### 复现步骤 / Step to reproduce

下载画廊后下载路径里大概率没有cbz和comiclnfo.xml,只生成文件夹和略缩图和.ehviewer文件
![屏幕截图 2024-11-05 224721](https://github.com/user-attachments/assets/59c166e2-6db1-48ce-a0d2-125d91fd9670)

但应用用户数据里有很大数据 下载界面里可以直接阅读
![Screenshot_2024-11-05-22-37-10-1657174199](https://github.com/user-attachments/assets/3d7ad0fc-f147-4a4e-8dab-fbe5152ccd48)

### 预期行为 / Expected behaviour

应该存在cbz压缩包并且存在comiclnfo.xml

### 实际行为 / Actual Behaviour

以前版本只有小概率发生,即使发生了在下载界面重新点击下载也会保存到下载路径
现在漫画下载完成后下载路径里大部分只有.ehviewer文件和略缩图,图片都存到了用户数据里,
即使在下载界面多次重新点击也大概率没法重新保存,
只有在画廊详情页里导出档案直到到成功会保存
或直接点击漫画阅读有概率保存

### 应用日志 / App logs

[log-2024-11-05-22-36-40-581.zip](https://github.com/user-attachments/files/17634238/log-2024-11-05-22-36-40-581.zip)

### 浏览站点 / Browsing site

 ExHentai

### EhViewer 版本号 / EhViewer version code

1.14.0

### EhViewer CI 版本 / EhViewer CI Version

3432a15

### Android 系统版本 / Android version

11

### 设备型号 / Device model

小新 pad pro 12.6

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
从日志来看是请求 https://s.exhentai.org/api.php 超时导致无法获取 ComicInfo.xml 所需的元数据，进而导致 CBZ 打包失败
之后会改进以下错误信息

**Comment by keart-of-fade** [comment]
我更新我的v2rayNG到最新版后已解决
感谢回复!
