### ISSUE TITLE
下载时下载进度条没有同步下载进度,一直显示为零

### ISSUE THREAD

**Issue by foamsea** [FooIbar/EhViewer#1914]
### 复现步骤 / Step to reproduce

0.使用的是雷电模拟器,两周前并无此问题,这个问题发生在两周前app打开显示Check failed后所有修正Check failed错误的版本
1. 点击下载后,进入下载页面,可以看到一直显示0/26
![Snipaste_2024-11-10_18-37-25](https://github.com/user-attachments/assets/8a7b2778-0f77-4436-9b15-d4f4568aaad6)
其实进入共享文件夹查看下载是正常的
![Snipaste_2024-11-10_18-37-03](https://github.com/user-attachments/assets/65a75931-f243-495c-bbc5-28755b8d8748)
2. 下载完成后下载页面会显示未完成
![Snipaste_2024-11-10_18-44-50](https://github.com/user-attachments/assets/17abc0e2-6659-4a38-941f-511f37112bfd)
进入下载文件夹查看下载其实是已经完成的
![Snipaste_2024-11-10_18-50-22](https://github.com/user-attachments/assets/242dc99b-14d5-42a1-8d91-162d77e57e7d)

![Snipaste_2024-11-10_18-46-21](https://github.com/user-attachments/assets/103123ad-2a55-4685-ac88-f5f17d696da0)

3. 这时候再次点击未完成,会快速读条并显示已完成

https://github.com/user-attachments/assets/01d50b67-1565-42fc-8b38-5d2fbb22f333

### 预期行为 / Expected behaviour

希望下载进度条可以正常显示下载进度,画册下载完成时显示已完成

### 实际行为 / Actual Behaviour

下载进度条在下载时一直显示进度为零,即使实际上下载已经成功
画册下载彻底完成时它会显示未完成

### 应用日志 / App logs

[log-2024-11-10-18-57-25-870.zip](https://github.com/user-attachments/files/17691134/log-2024-11-10-18-57-25-870.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.0

### EhViewer CI 版本 / EhViewer CI Version

fe4ab6f

### Android 系统版本 / Android version

安卓9

### 设备型号 / Device model

雷电模拟器 sm-n9760

### SoC 型号 / Soc model

雷电模拟器 7800x3d

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
不要把下载路径设成 Download/Pictures 等系统文件夹

**Comment by foamsea** [comment]
我新建了一个下载路径  storage/emulated/0/ehvpic

不过它依然没有办法正常的显示下载进度

https://github.com/user-attachments/assets/73537c68-82fe-4e68-a164-6502d9b147c4

[log-2024-11-10-21-50-24-941.zip](https://github.com/user-attachments/files/17691648/log-2024-11-10-21-50-24-941.zip)

**Comment by FooIbar** [comment]
https://android-review.googlesource.com/c/platform/frameworks/base/+/767532
我大概知道是什么原因了

**Comment by foamsea** [comment]
我需要做什么别的操作吗,还是我等待新的 ci 更新就可以了

**Comment by foamsea** [comment]
我需要做什么别的操作吗,还是等待新的 ci 更新就可以了

**Comment by foamsea** [comment]
实测已修复,感谢
