### ISSUE TITLE
Cannot back to original position in favorite list

### ISSUE THREAD

**Issue by joejoe2** [FooIbar/EhViewer#192]
### 复现步骤 / Step to reproduce

1. go to favorite list
2. scroll down the list (as many as you can, maybe 100+ items)
3. click an item
4. click "go back" button return to favorite list

### 预期行为 / Expected behaviour

It should be fixed in the original position before clicking an item in favorite list.

### 实际行为 / Actual Behaviour

It jumps to the start of the favorite list (or random position much earlier than the original).

### 应用日志 / App logs

 no

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.8.11

### EhViewer CI 版本 / EhViewer CI Version

7e90555

### Android 系统版本 / Android version

Android 11

### 设备型号 / Device model

Samsung s20

### SoC 型号 / Soc model

s865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Are you using cloud favorites or local favorites?

**Comment by joejoe2** [comment]
Local.

**Comment by FooIbar** [comment]
Got it, this will be fixed in next release.

**Comment by joejoe2** [comment]
@FooIbar The problem still exists after I upgraded to 1.9.0/latest ci ver. Here is the demo:

https://github.com/FooIbar/EhViewer/assets/39475537/b38ec7f9-efb7-48b2-a5b0-b87786d41731

**Comment by FooIbar** [comment]
Apparently it was broken again by fec2c39, should be fixed in 70f9522.
