### ISSUE TITLE
【功能请求】被版权删除的画廊获取可查看内容

### ISSUE THREAD

**Issue by Sayaori** [FooIbar/EhViewer#1952]
### 复现步骤 / Step to reproduce

发现一个脚本，可以查看被版权删除的画廊的一些信息，如标题、作者、标签、磁力链接（种子）等。有了这些信息我们可以做一些补救措施
https://sleazyfork.org/zh-CN/scripts/411277-exresurrect
![image](https://github.com/user-attachments/assets/79f9ad3b-2f08-401b-a202-9d079bd77bd5)

### 预期行为 / Expected behaviour

以上

### 实际行为 / Actual Behaviour

以上

### 应用日志 / App logs

以上

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.13.1-cc

### EhViewer CI 版本 / EhViewer CI Version

2f14296

### Android 系统版本 / Android version

安卓13/ColorOS13

### 设备型号 / Device model

一加9pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by n-ine** [comment]
干脆再集成个Lib得了，给你下下来

**Comment by FooIbar** [comment]
有画廊链接（可从分享菜单获取）就够了
