### ISSUE TITLE
No more inverted/flipped volume keys

### ISSUE THREAD

**Issue by Bastekol** [FooIbar/EhViewer#1962]
### 复现步骤 / Step to reproduce

Flipped volume keys option not in general settings

### 预期行为 / Expected behaviour

Flipped volume keys option should be there

### 实际行为 / Actual Behaviour

Flipped volume keys options is gone
![Screenshot_2024-11-22-01-42-52-708_moe tarsin ehviewer](https://github.com/user-attachments/assets/346d844d-fa7c-4e5e-beb3-1860fbc928e2)

### 应用日志 / App logs

[log-2024-11-22-01-43-36-578.zip](https://github.com/user-attachments/files/17849988/log-2024-11-22-01-43-36-578.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.13.1

### EhViewer CI 版本 / EhViewer CI Version

571969f

### Android 系统版本 / Android version

MUI 12.5.2

### 设备型号 / Device model

Xiami mi 9t Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
It was removed intentionally to match other physical keys (arrow keys, PgUp/PgDn).

**Comment by Bastekol** [comment]
> It was removed intentionally to match other physical keys (arrow keys, PgUp/PgDn), but we can reconsider adding it back if there's a convincing reason.

My volume down volume key is broken, so I just flip it.
