### ISSUE TITLE
能否重新加回cookie登录

### ISSUE THREAD

**Issue by Huan-Ye** [FooIbar/EhViewer#1964]
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

由于过去使用老版本的彩e和白e都是使用cookie登录，换成新版版后最近因为cookie的igneous：mystery导致里站无法登录。退出后再进入无法通过cookie登录

### 实际行为 / Actual Behaviour

无

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

Ex_hentai

### EhViewer 版本号 / EhViewer version code

1.14.0

### EhViewer CI 版本 / EhViewer CI Version

046350c

### Android 系统版本 / Android version

android

### 设备型号 / Device model

vivo

### SoC 型号 / Soc model

晓龙

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #692
