### ISSUE TITLE
使用VPN代理时网络错误，使用http代理正常

### ISSUE THREAD

**Issue by w4fd** [FooIbar/EhViewer#201]
### 复现步骤 / Step to reproduce

0. 打开代理软件(NekoBox, V2rayNg)，选择代理服器后开启VPN连接，可以正常访问浏览器网页版exhentai。
1. 打开EhViewer，代理软件和服务器只显示EhViewer发起IP连接，无exhentai域名的DNS查询记录，随后连接失败，显示网络错误。
2. 打开代理软件添加http代理至VPN功能或Wifi设置http代理。
3. 重新打开EhViewer，网络连接成功，主页画廊正常显示，代理软件内可见exhentai域名查询记录。

### 预期行为 / Expected behaviour

使用VPN而不设置http代理时可以正常连接网络

### 实际行为 / Actual Behaviour

只有http代理能正常连接网络

### 应用日志 / App logs

[log-2023-11-06-22-41-12-491.zip](https://github.com/FooIbar/EhViewer/files/13268028/log-2023-11-06-22-41-12-491.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0

### EhViewer CI 版本 / EhViewer CI Version

26906f6

### Android 系统版本 / Android version

Zephyrus 14.0

### 设备型号 / Device model

Redmi K40

### SoC 型号 / Soc model

骁龙 870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [x] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by w4fd** [comment]
btw，翻了一下issue，因为要去除直连功能，好像软件内设置Proxy的功能也被移除了，但Proxy应该不算用在直连的功能吧🥲

**Comment by FooIbar** [comment]
应用内的代理设置是当初清理设置项的时候因为没什么人用删掉的，倒是跟直连无关

至于这个问题，无法复现
VPN对应用来说应该是透明的，所以大概不是我们的问题
可能相关的issue：https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/349

**Comment by w4fd** [comment]
> 应用内的代理设置是当初清理设置项的时候因为没什么人用删掉的，倒是跟直连无关
> 
> 至于这个问题，无法复现 VPN对应用来说应该是透明的，所以大概不是我们的问题

因为其他软件能正常使用代理VPN，遂尝试了原仓库最后一个版本1.8.8.3，以及EhViewer-NekoInverter仓库最新版本，均可以在软件内设置direct、不设置域名前置和host情况下，使用同一代理VPN正常访问eh网络，而本仓库第一个版本1.8.9.0及之后版本均无法通过同一代理VPN访问eh（表现为直接显示网络错误而不是连不上过一会提示超时），这是否能说明确实是本仓库这边的代码更改导致的问题？

**Comment by FooIbar** [comment]
> > 应用内的代理设置是当初清理设置项的时候因为没什么人用删掉的，倒是跟直连无关
> > 至于这个问题，无法复现 VPN对应用来说应该是透明的，所以大概不是我们的问题
> 
> 因为其他软件能正常使用代理VPN，遂尝试了原仓库最后一个版本1.8.8.3，以及EhViewer-NekoInverter仓库最新版本，均可以在软件内设置direct、不设置域名前置和host情况下，使用同一代理VPN正常访问eh网络，而本仓库第一个版本1.8.9.0及之后版本均无法通过同一代理VPN访问eh（重试时直接显示网络错误而不是连不上过一会提示超时），这是否能说明确实是本仓库这边的代码更改导致的问题？

你要试也应该拿system而不是direct试，因为那才是默认行为
看起来是某些应用错误地设置了系统代理，设成direct只是忽略了而已

**Comment by w4fd** [comment]
> 你要试也应该拿system而不是direct试，因为那才是默认行为 

尝试使用了system，还是一样的结果，1.8.8.3连接正常，之后版本网络错误，这是否😢

**Comment by FooIbar** [comment]
就像我之前说的，VPN对应用来说应该是透明的，建议排查代理软件的问题

**Comment by w4fd** [comment]
> 就像我之前说的，VPN对应用来说应该是透明的，建议排查代理软件的问题

我排查出原因了，不是代理软件问题，就是ehv的问题，只设置VPN而不设置http代理时，其他软件正常走VPN的DNS，而ehv始终去访问本地DNS而得到被污染的IP！连接记录仅为：Ehviewer Request URL: https://exhentai.org, Destination address:80.87.199.46:443

同时，不开VPN时，termux的dig exhentai结果为：
~ $ dig exhentai.org

; <<>> DiG 9.16.41 <<>> exhentai.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14410
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;exhentai.org.                  IN      A

;; ANSWER SECTION:
exhentai.org.           220     IN      A       67.228.102.32

;; Query time: 44 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 09 03:00:02 CST 2023
;; MSG SIZE  rcvd: 46

~ $ dig exhentai.org

; <<>> DiG 9.16.41 <<>> exhentai.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19026
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;exhentai.org.                  IN      A

;; ANSWER SECTION:
exhentai.org.           110     IN      A       162.125.18.129

;; Query time: 76 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 09 03:00:04 CST 2023
;; MSG SIZE  rcvd: 46

开VPN时，termux的dig exhentai结果为：
~ $ dig exhentai.org

; <<>> DiG 9.16.41 <<>> exhentai.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63505
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0060, udp: 512
;; QUESTION SECTION:
;exhentai.org.                  IN      A

;; ANSWER SECTION:
exhentai.org.           96      IN      A       172.64.106.3
exhentai.org.           96      IN      A       172.64.107.3

;; Query time: 112 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 09 03:01:51 CST 2023
;; MSG SIZE  rcvd: 97

下面这个才是通过VPN的DNS返回的正确结果，而ehv在设置了VPN情况下依然访问本地DNS，这是否确实是因为代码更改导致的问题？

**Comment by FooIbar** [comment]
> 下面这个才是通过VPN的DNS返回的正确结果，而ehv在设置了VPN情况下依然访问本地DNS，这是否确实是因为代码更改导致的问题？

所有流量都会经过TUN设备，包括DNS
你应该问你的代理软件为什么没处理好DNS请求
