### ISSUE TITLE
新版本 不联网的情况下无法观看已下载本子！在下载后加一个东西，导致一旦你的ip被ban，或者本子被下架，你就无法阅览你下载过的本子

### ISSUE THREAD

**Issue by 1670081661** [FooIbar/EhViewer#2031]
### 复现步骤 / Step to reproduce

0.下载最新cc版本
1.登录有里站权限的本子，随便下一个loli本
2.取消登录，再以游客状态登录，并点击已下载好的本子
3.点进去后提示画廊已经被移出，哪怕你已经存在手机里了也无法观看了
4.最离谱的来了。只要手机断网，你将不可能通过EHV阅览任何已下载的本子。

### 预期行为 / Expected behaviour

他应该就和老版本一样，直接下载直接就能看。我用老版本下载的本子全部没这种问题，点进去直接就能看。新版本读取已下载本子的方式不知道为啥更改了，进已下载本子之前还得读取信息，就很离谱。
最离谱的是，已下载本子在断网后完全无法进行观看，会显示connect lost。

### 实际行为 / Actual Behaviour

实际上就应该和老版本一样，直接下载直接就能看。不然现在你就算在本子被关小黑屋之前下载，你也不可能阅读的了了。请务必改回旧版本的下载方式。和读取下载内容的方式。我怀疑是读取下载的方式多了个步骤导致的。

### 应用日志 / App logs

在下面的文件

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.31.1

### EhViewer CI 版本 / EhViewer CI Version

最新版本

### Android 系统版本 / Android version

Magic UI 4.2 ; Android 11

### 设备型号 / Device model

HONOR 50

### SoC 型号 / Soc model

骁龙778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by 1670081661** [comment]
![Screenshot_20241219_140013](https://github.com/user-attachments/assets/38896b57-2203-450e-877e-1f8eeeae8a7d)
这个图片里就是，我明明已经完全下载完毕了，但就是不给观看。旧版本不可能出现这种情况。

**Comment by 1670081661** [comment]
[log-2024-12-19-13-56-23-688.zip](https://github.com/user-attachments/files/18193295/log-2024-12-19-13-56-23-688.zip)

**Comment by 1670081661** [comment]
以上bug出现在uj大佬的改版（即为可以不用梯子都能观看的改版）本体并无出现。

**Comment by MC57348** [comment]
老哥没懂什么意思，但是我也出现这问题了

**Comment by MC57348** [comment]
我发现发生如上情况的下载的版权本是日本节点下载的，现在换个港区节点下载再试一下

**Comment by MC57348** [comment]
好像就是前几个版本没有下载那个ehfile导致每一次都要重新加载

**Comment by MC57348** [comment]
老哥我明白了，前一个版本下载的时候没有下载那个eh的file导致读取失败

**Comment by 1670081661** [comment]
> 老哥我明白了，前一个版本下载的时候没有下载那个eh的file导致读取失败

问题是旧版本好像就没有这个file来着，怪的。不知道这个file的意义

**Comment by MC57348** [comment]
不，这文件一直是有的，只不过是隐藏的

**Comment by 1670081661** [comment]
> 不，这文件一直是有的，只不过是隐藏的

我经常用mixplayer去删下载的本子，我很确定，旧版本只存在2个文件，一个ehv一个i开头的。
新版本多了一个comic的文件

**Comment by 1670081661** [comment]
> 不，这文件一直是有的，只不过是隐藏的

准确来说新版本和旧版本相比多了一个comicinfo.xml

**Comment by MC57348** [comment]
哦那个文件是压缩包元数据，可以在下载里面关掉，主要诱导这个问题发生的文件是那个.ehviewer

**Comment by MC57348** [comment]
里面加密了ip和token以及预览图数据，前一个版本下载不到必须进本子重新加载一次，现在好像是好了

**Comment by MC57348** [comment]
我那会发现的原因是我发现问题之后更新了版本依旧出现重加载问题，然后我发现我挂的日本节点，换了个节点那个。eh文件就能正常加载

**Comment by 1670081661** [comment]
> 我那会发现的原因是我发现问题之后更新了版本依旧出现重加载问题，然后我发现我挂的日本节点，换了个节点那个。eh文件就能正常加载

原来如此，反正现在这个版本下载的就没问题，我不知道必须删除重下才能解决，还是咋才能解决

**Comment by MC57348** [comment]
> > 我那会发现的原因是我发现问题之后更新了版本依旧出现重加载问题，然后我发现我挂的日本节点，换了个节点那个。eh文件就能正常加载
> 
> 原来如此，反正现在这个版本下载的就没问题，我不知道必须删除重下才能解决，还是咋才能解决

在下载好但是出问题的本子里面重新打开一遍或者重新下载一边吧

**Comment by MC57348** [comment]
有几个版权本我已经放弃了，.eh文件不知道怎么补救，直接去jm找了

**Comment by 1670081661** [comment]
> 有几个版权本我已经放弃了，.eh文件不知道怎么补救，直接去jm找了

版权本，不嫌烦的话去wnacg里看看有没有的下载。里面大概率会有留档。

**Comment by MC57348** [comment]
等过段时间随机刷新吧hhh，总之就是避开日本以及可能的韩国节点，这俩可能都有问题

**Comment by MC57348** [comment]
huh？

**Comment by MC57348** [comment]
> 所以你跑这里报告干啥？
> 
> * [本地存在元数据时仍请求网站 UjuiUjuMandan/EhViewer#113](https://github.com/UjuiUjuMandan/EhViewer/issues/113)

看了一下你的那个issue，和我情况不一样，我的.eh文件是0kb

**Comment by 1670081661** [comment]
> 所以你跑这里报告干啥？
> 
> * [本地存在元数据时仍请求网站 UjuiUjuMandan/EhViewer#113](https://github.com/UjuiUjuMandan/EhViewer/issues/113)

因为我不确定是本体的问题还是你那里的问题啊？一开始报告的时候。你的github不是写着说有issue找本体，你只负责上国内免翻墙吗？

**Comment by 1670081661** [comment]
> 嗯，好吧。现在确定了。不是我的问题。
> 
> [862143d](https://github.com/FooIbar/EhViewer/commit/862143d7a4b8ef27f61fb21580071a26676f5ba1) 这个版本可以复现。
> 
> [325e756](https://github.com/FooIbar/EhViewer/commit/325e756e4caa7d85ec2fd612cb86885d23ef5078) 及其之后不可以。
> 
> 这两次原始提交隔了3天，我同步也隔了3天。在这期间下载版权本的不好意思了。

原来如此，难怪了。顺带，不知道为啥现在只剩下okhttp了？另一个cornet还是啥的一直点了也没反应。

**Comment by FooIbar** [comment]
Duplicate of #2027

**Comment by FooIbar** [comment]
a075a7c 起已下载的画廊不需要 .ehviewer 文件
