### ISSUE TITLE
无网络时启动app会立即闪退

### ISSUE THREAD

**Issue by Steve-337** [FooIbar/EhViewer#2041]
### 复现步骤 / Step to reproduce

断开设备网络后重启app

### 预期行为 / Expected behaviour

正常打开下载页

### 实际行为 / Actual Behaviour

立即闪退

### 应用日志 / App logs

[crash-2024-12-25-12-21-10-141.log](https://github.com/user-attachments/files/18243269/crash-2024-12-25-12-21-10-141.log)

### 备注 / Addition details

全新安装无此问题，导入之前的数据后首次启动无问题，第二次启动即出现此问题

### 浏览站点 / Browsing site

ex

### EhViewer 版本号 / EhViewer version code

1.14.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

782dafc

### Android 系统版本 / Android version

14

### 设备型号 / Device model

redmi note 12 turbo

### SoC 型号 / Soc model

骁龙7g2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
https://issuetracker.google.com/382564799

https://github.com/FooIbar/EhViewer/actions/runs/12489949211
试下这个，如果仍然崩溃上传新的日志

**Comment by Steve-337** [comment]
还是闪退，日志看上去好像一样 [crash-2024-12-25-18-41-16-161.log](https://github.com/user-attachments/files/18245510/crash-2024-12-25-18-41-16-161.log)
