### ISSUE TITLE
进入ex显示read error

### ISSUE THREAD

**Issue by fiveboxcloud** [FooIbar/EhViewer#2043]
### 复现步骤 / Step to reproduce

打开软件直接显示read error

### 预期行为 / Expected behaviour

能够正常加载页面

### 实际行为 / Actual Behaviour

![Screenshot_20241225_150405](https://github.com/user-attachments/assets/8ca59c32-5a39-44fc-855a-e4b70b8bfdde)

### 应用日志 / App logs

[log-2024-12-25-15-04-21-091.zip](https://github.com/user-attachments/files/18244079/log-2024-12-25-15-04-21-091.zip)

### 备注 / Addition details

pc上能正常进入里站，app表站浏览没有问题

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.13.1-cc

### EhViewer CI 版本 / EhViewer CI Version

4111805

### Android 系统版本 / Android version

magicos 7.0

### 设备型号 / Device model

honor v40

### SoC 型号 / Soc model

天玑1000+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
与本仓库无关
