### ISSUE TITLE
本子下载中时在主页打开关闭加载画廊大概率会卡顿至闪退

### ISSUE THREAD

**Issue by liuxuming3303** [FooIbar/EhViewer#207]
### 复现步骤 / Step to reproduce

当有本子下载中时在主页不断关闭加载画廊，概率应用会逐渐变卡，一个操作等待十几秒响应直至闪退。由于触发不稳定且要大量浏览画廊，一日不一定能触发一次，所以直接看日志。原Overhauled v1.8.8.3不存在该问题。

### 预期行为 / Expected behaviour

不卡

### 实际行为 / Actual Behaviour

不断打开画廊过程中逐渐变卡最后闪退，这过程需要几分钟

### 应用日志 / App logs

[log-2023-11-05-22-23-19-927.zip](https://github.com/FooIbar/EhViewer/files/13283796/log-2023-11-05-22-23-19-927.zip)

### 备注 / Addition details

通过该日志，其他群友提出可能是 https://github.com/FooIbar/EhViewer/pull/195 有关的·问题，并给出了修改版 https://github.com/UjuiUjuMandan/EhViewer/actions/runs/6762445362 。

经过在红米note7pro\crdorid\android12\有magisk\TF卡带中文路径 & 红米note9pro\miui14\android12\未root\默认路径 三晚的大量刷画廊后，未再在下载时出现闪退，大概是已解决。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1、1.8.11.1-cc

### EhViewer CI 版本 / EhViewer CI Version

7e90555、42297a3

### Android 系统版本 / Android version

crDroidOS 8.10 Android 12

### 设备型号 / Device model

Redmi Note 7 Pro

### SoC 型号 / Soc model

Snapdragon 675

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
已解决为啥要发新 issue ...?

**Comment by FooIbar** [comment]
之后再遇到了再开
