### ISSUE TITLE
网页登录和应用直接登录bug

### ISSUE THREAD

**Issue by RX93CN** [FooIbar/EhViewer#215]
### 复现步骤 / Step to reproduce

1.退出账号
2.再次登录，选择直接登录或网页登录

### 预期行为 / Expected behaviour

正常登录进去

### 实际行为 / Actual Behaviour

![IMG_20231108_183856](https://github.com/FooIbar/EhViewer/assets/110704357/00cafa7b-ce44-4087-a5ab-7b0e4e659386)
![Screenshot_2023-11-08-18-31-18-788_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/110704357/47aa146d-ff1d-4f8d-98e3-943d732f9850)
网页登录会在点击log me in后跳回网页登录页面

### 应用日志 / App logs

无

### 备注 / Addition details

怎么上传日志?附件的操作与以前不同

### 浏览站点 / Browsing site

E-hentai

### EhViewer 版本号 / EhViewer version code

18.11.1-gms

### EhViewer CI 版本 / EhViewer CI Version

7e90555

### Android 系统版本 / Android version

MIUI13.0.10

### 设备型号 / Device model

xiaomi 12 pro

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by skymkmk** [comment]
![IMG_20231108_192216](https://github.com/FooIbar/EhViewer/assets/62805286/7ee68384-643f-4766-81ea-010537eecf04)

**Comment by RX93CN** [comment]
> ![IMG_20231108_192216](https://user-images.githubusercontent.com/62805286/281381581-7ee68384-643f-4766-81ea-010537eecf04.jpg)

这个是之前的截图，密码输入正确会卡顿一下返回网页登录

**Comment by RX93CN** [comment]
问题原因找到:clash for Android的代理有问题，使用时部分网站和应用无法正常打开，换用surbroad和clash metaz在同一节点下能正常登录
