### ISSUE TITLE
搜索功能似乎不太对劲

### ISSUE THREAD

**Issue by SnowArk** [FooIbar/EhViewer#22]
从上游更新到这里之后使用发现了一点问题:

1.直接在搜索结果列表下拉刷新，列表有时候会自动跳转到后面，而不是最新的部分。

2.使用高级选项搜索限制评分最低为5星依旧能搜到4星和4星半的结果。不知道是不是刻意为之的？

3.使用高级搜索得到结果后（例如搜索l:chinese，高级选项设置最低五星），点击任意画廊返回后会导致高级搜索的调教被重置，具体表现启用高级选项这个复选框被取消。

**Comment by FooIbar** [comment]
1. 新的结果会被添加到上方
2. Fixed by 2b8bfab
3. Fixed by 6a65b61

**Comment by SnowArk** [comment]
> 1. 新的结果会被添加到上方
> 2. Fixed by 2b8bfab
> 3. Fixed by 6a65b61

有关1，我测试下来似乎并不是直接将新的结果添加到上方，个人感觉这处理的逻辑有点怪。直接刷新就算没有新的结果也会跳转到后面，并且有时候不会跳转到后面。https://github.com/FooIbar/EhViewer/assets/44255555/7c55a206-ae19-4df0-94fb-43f60af74056

**Comment by FooIbar** [comment]
> 有关1，我测试下来似乎并不是直接将新的结果添加到上方，个人感觉这处理的逻辑有点怪。直接刷新就算没有新的结果也会跳转到后面，并且有时候不会跳转到后面。

Fixed by d13b09a
