### ISSUE TITLE
是否有默认收藏夹功能

### ISSUE THREAD

**Issue by ODtian** [FooIbar/EhViewer#222]
### 复现步骤 / Step to reproduce

点击收藏按钮

### 预期行为 / Expected behaviour

未设置默认收藏夹时有个设置为默认收藏夹的选项

### 实际行为 / Actual Behaviour

没有选项

### 应用日志 / App logs

无

### 备注 / Addition details

原项目应该是有的，现在选择收藏夹的弹窗有点大，也不是很方便定位

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11

### EhViewer CI 版本 / EhViewer CI Version

ed91a65

### Android 系统版本 / Android version

evolution x, a13

### 设备型号 / Device model

小米11

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
设置 - EH
