### ISSUE TITLE
文件夹内没有.ehviewer文件导致无法离线查看

### ISSUE THREAD

**Issue by Trenza1ore** [FooIbar/EhViewer#227]
### 复现步骤 / Step to reproduce

0. 将旧设备中的存储文件夹（包含绿E和旧版彩E时下载的内容）备份并在彩E选择导出数据
1. 将备份的存储文件夹adb push到新设备，安装最新版本彩E并设置存储路径、导入数据
2. 本子都会显示已下载且点击▶️按钮也是瞬间就再次显示已下载
3. 文件夹内没有.ehviewer的本子，离线点开就黑屏，未卡死可退出
5. 通过全选所有本子后点击▶️按钮可强制全部本子走一边流程创建.ehviewer文件

### 预期行为 / Expected behaviour

应当有一个可以一次性处理所有没有.ehviewer文件的旧本子的独立功能（最好下架但图片还在的也可以复原？），或者restore download item可以顺便处理这些本子而不是直接跳过

### 实际行为 / Actual Behaviour

假如删除所有本子（不删除存储文件）再执行restore download items，仅有含有.ehviewer文件的本子会被复原，其他本子还得靠导入数据后点击▶️按钮走一次快速的下载流程（已下架的本子还会卡下载）

### 应用日志 / App logs

前面很多行都是一样的，放了会超字数
11-09 12:36:54.700  5665  5665 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
11-09 12:36:54.933  5665 15124 W System.err: zp0: Parse pages error
11-09 12:36:54.933  5665 15124 W System.err: 	at DM0.n(Unknown Source:230)
11-09 12:36:54.933  5665 15124 W System.err: 	at AM0.s(Unknown Source:11)
11-09 12:36:54.933  5665 15124 W System.err: 	at hd.r(Unknown Source:8)
11-09 12:36:54.933  5665 15124 W System.err: 	at Uy.run(Unknown Source:112)
11-09 12:36:54.933  5665 15124 W System.err: 	at y1.run(Unknown Source:28)
11-09 12:36:54.933  5665 15124 W System.err: 	at ZR0.run(Unknown Source:2)
11-09 12:36:54.933  5665 15124 W System.err: 	at wt.run(Unknown Source:91)
11-09 12:36:55.726  5665  5665 W BpBinder: Large outgoing transaction of 332352 bytes, interface descriptor <uncached descriptor>, code 7
11-09 12:37:32.631  5665  5665 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
11-09 12:37:32.631  5665  5665 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
11-09 12:37:37.137  5665  5699 D OpenGLRenderer: endAllActiveAnimators on 0xb400006f29d2fcc0 (QZ0) with handle 0xb400006e398521d0
11-09 12:37:41.162  5665  5665 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
11-09 12:37:41.162  5665  5665 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
11-09 12:37:41.178  5665  5665 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
11-09 12:37:41.178  5665  5665 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1

### EhViewer CI 版本 / EhViewer CI Version

7e90555

### Android 系统版本 / Android version

Android 13.0

### 设备型号 / Device model

Google Pixel 6 Pro

### SoC 型号 / Soc model

Google Tensor

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [x] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
> 啊，虽然刚刚才看到还未测试，但是是否已经在这个commit修复了： [04a7656](https://github.com/FooIbar/EhViewer/commit/04a7656afaa7fdd7bcfaeb025c68b31002a7562b)

跟这个无关

所以你没备份.ehviewer？
没有的话恢复不了

**Comment by Trenza1ore** [comment]
这样啊，那请问加入一个这样的功能是否可行：
扫描下载路径并将缺失.ehviewer且并未下架的本子全部走一遍下载流程创建.ehviewer
（不过这样好像下载任务多了还是会被ban IP）

**Comment by FooIbar** [comment]
我不是很明白你的需求，直接用下载中的全部开始不可以吗？

**Comment by Trenza1ore** [comment]
也是，只是感觉有些用户没意识到是.ehviewer文件的问题的话可能会想不到重新下载一遍，不过好像如果是这种用户应该也不会去设置里面找解决方法。

**Comment by FooIbar** [comment]
一般来说，不会出现缺少.ehviewer文件的情况
备份的时候应该一起备份
