### ISSUE TITLE
导入数据功能失效

### ISSUE THREAD

**Issue by a180wyh** [FooIbar/EhViewer#244]
### 复现步骤 / Step to reproduce

导入数据

### 预期行为 / Expected behaviour

导入成功

### 实际行为 / Actual Behaviour

显示导入成功通知但导入没有成功

### 应用日志 / App logs

none

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1

### EhViewer CI 版本 / EhViewer CI Version

42297a3

### Android 系统版本 / Android version

android 12

### 设备型号 / Device model

Huawei p4)

### SoC 型号 / Soc model

None

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by a180wyh** [comment]
试过将导出数据得到的db导进navicat里，然后用insert语句向彩e的表增加数据，还是不能导入数据

**Comment by FooIbar** [comment]
不是这个仓库的版本
