### ISSUE TITLE
Unable to build the project locally

### ISSUE THREAD

**Issue by bossanovaorca** [FooIbar/EhViewer#25]
hello, the main repo was archived and discussions were not enabled on this fork so I apologize for creating this as a bug report

This is a continuation of https://github.com/Ehviewer-Overhauled/Ehviewer/discussions/1375 where I installed the matching NDK version and then ran into issues with nettle:

<img width="461" alt="image" src="https://github.com/FooIbar/EhViewer/assets/13033321/87467af7-e66e-4e38-b770-03d780348099">

I am also facing this issue on a fresh install of this fork, which automatically installs NDK from what I can tell

I'm sorry for asking these questions related to local builds, but I am trying to poke around in Android Studio so I can learn about everything interactively. I would appreciate any help 🙏

**Comment by UjuiUjuMandan** [comment]
Run `git submodule update --init --recursive` in repo root.

**Comment by bossanovaorca** [comment]
thank you! after doing that I can proceed further along with the build process and I then run into a brand new error, but I will troubleshoot that separately
