### ISSUE TITLE
Can't find local favorites to delete them

### ISSUE THREAD

**Issue by Besharia** [FooIbar/EhViewer#252]
### 复现步骤 / Step to reproduce

I accidentally pressed the button to download favorites to local device and I can't find them to free up space. I don't know where to post this because I can't find a place to ask a question. Where does EhViewer store local favorites I have a fire tablet running FireOS 7.3.2.7 and EhViewer 1.8.10.2. I don't know where it placed local favorites because it never prompted me to pick a location and i searched everywhere for them.

### 预期行为 / Expected behaviour

Should have prompted me to choose download directory.

### 实际行为 / Actual Behaviour

Just downloaded the favorites and gave no indication where they are.

### 应用日志 / App logs

[log-2023-11-12-16-51-25-458.zip](https://github.com/FooIbar/EhViewer/files/13329263/log-2023-11-12-16-51-25-458.zip)

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.10.2

### EhViewer CI 版本 / EhViewer CI Version

10c7019

### Android 系统版本 / Android version

FireOS 7.3.2.7

### 设备型号 / Device model

Fire HD 10 9th generation

### SoC 型号 / Soc model

armeabi-v7a

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
![Screenshot_20231113_110504](https://github.com/FooIbar/EhViewer/assets/118464521/84db4ea1-5166-4862-aff2-44b2a60d9d28)

And it doesn't "download" anything, just fetches the data and stores in the database, so won't take up much space.
