### ISSUE TITLE
不知道为什么加载不出来了

### ISSUE THREAD

**Issue by yys764** [FooIbar/EhViewer#264]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/150843322/e64869d7-5246-4a8a-9d7c-8a1b37fcdb87

### 预期行为 / Expected behaviour

没有可预览的项目

### 实际行为 / Actual Behaviour

没有可预览的项目

### 应用日志 / App logs

[日志1.zip](https://github.com/FooIbar/EhViewer/files/13353969/1.zip)

### 备注 / Addition details

没有可预览的项目

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1

### EhViewer CI 版本 / EhViewer CI Version

1.8.11.1-gms（7e90555）于2023/11/01 15:34 构建

### Android 系统版本 / Android version

MOLY.NR15.R3.TC19.PR4.SP.V1.P10 2

### 设备型号 / Device model

V2166A

### SoC 型号 / Soc model

2.2GHz 天玑 700八核

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by yys764** [comment]
不知道为什么突然加载不出来了，更新了也没用。

**Comment by yys764** [comment]
> 不知道为什么突然加载不出来了，更新了也没用。

起初我以为是网的问题后来发现不是，然后我想到可能是手机的问题就换了手机发现也不是，反正所有我想到的问题都试过了，一直也没用解决

**Comment by tmby** [comment]
本项目没有直连功能，使用请自行代理。

**Comment by yys764** [comment]
> 本项目没有直连功能，使用请自行代理。

怎么弄？

**Comment by tmby** [comment]
> > 本项目没有直连功能，使用请自行代理。
> 
> 怎么弄？

谷歌
或者左转能直连的项目

**Comment by yys764** [comment]
> > > 本项目没有直连功能，使用请自行代理。
> > 
> > 
> > 怎么弄？
> 
> 谷歌 或者左转能直连的项目

请问具体的怎么操作
