### ISSUE TITLE
搜索栏未正确适应宽度

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#265]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.游客登录，进入Ehviewer

### 预期行为 / Expected behaviour

适应宽度

### 实际行为 / Actual Behaviour

![Screenshot_20231115_131618_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/d3e1b62f-86e0-4a26-84d5-a884858381bb)
![Screenshot_20231115_131624_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/577d4bc1-d354-4f02-9ac4-ac1676d67629)

### 应用日志 / App logs

[log-2023-11-15-13-23-51-275.zip](https://github.com/FooIbar/EhViewer/files/13360422/log-2023-11-15-13-23-51-275.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

2094fd4

### Android 系统版本 / Android version

HarmonyOS 4.0.0.126

### 设备型号 / Device model

HUAWEI MatePad 11

### SoC 型号 / Soc model

Qualcomm Snapdragon 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
![Screenshot_20231115_172900_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/40a8256d-3ec8-4edb-854b-6e98382db160)
之前是这样的
![Screenshot_20231115_173223_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/885a0ade-212c-4e7f-a0a2-5cceda5d3ee3)

**Comment by FooIbar** [comment]
> 之前是这样的

之前的实际上不符合 M3 规范（最宽 720 dp）

**Comment by tmby** [comment]
> > 之前是这样的
> 
> 之前的实际上不符合 M3 规范（最宽 720 dp）

明白了，等我习惯习惯
