### ISSUE TITLE
关于快速搜索抽屉的相关问题

### ISSUE THREAD

**Issue by Orligei** [FooIbar/EhViewer#28]
### 复现步骤 / Step to reproduce

1.展开快速搜索抽屉，且快速搜索列表高度超过一屏可以进行滚动。
2.滚动快速搜索列表，点击任意标签进行快速搜索。
3.进入搜索结果页再次唤出快速搜索抽屉。
4.快速搜索抽屉的列表滚动进度被重置，列表重新回到最顶端。

### 预期行为 / Expected behaviour

“复现步骤”的第4步时，列表的滚动进度应该保留。
还有请问能否恢复左滑唤出快速搜索抽屉的操作。
该问题出现于飞鸟澪的较新版本，并且您的项目也继承了此问题。

### 实际行为 / Actual Behaviour

“复现步骤”的第4步。

### EhViewer 版本号 / EhViewer version code

1.8.10.0

### EhViewer CI 版本 / EhViewer CI Version

96b9223

### Android 系统版本 / Android version

MIUI 14.0.10,Android 13

### 设备型号 / Device model

Redmi K50 Ultra

### SoC 型号 / Soc model

骁龙 8+ Gen 1, Snapdragon 8+ Gen 1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by FooIbar** [comment]
确实，收藏和下载页面的抽屉没这个问题
