### ISSUE TITLE
本地搜索关键词bug

### ISSUE THREAD

**Issue by Sayaori** [FooIbar/EhViewer#283]
### 复现步骤 / Step to reproduce

![Screenshot_2023-11-16-14-14-47-51_f2f1746601bf3b8](https://github.com/FooIbar/EhViewer/assets/73752368/de113951-c17e-4ccd-8791-d6a4ab2e0305)
搜索日文关键词只出现3个
![Screenshot_2023-11-16-14-14-32-23_f2f1746601bf3b8](https://github.com/FooIbar/EhViewer/assets/73752368/1784434a-d851-4de3-8e8c-58f6a45a0ef0)
而搜索其假名罗马音能搜出更多
![Screenshot_2023-11-16-14-15-04-25_f2f1746601bf3b8](https://github.com/FooIbar/EhViewer/assets/73752368/11320849-df99-4e70-a2c4-2e1a75e4b500)
我测试了下在线搜索，使用日文是能够搜得到的

### 预期行为 / Expected behaviour

本地搜索使用日文或者罗马音都可以搜索得到

### 实际行为 / Actual Behaviour

本地搜索使用日文搜索到的内容少于罗马音搜索到的内容

### 应用日志 / App logs

[log-2023-11-16-14-25-05-838.zip](https://github.com/FooIbar/EhViewer/files/13373079/log-2023-11-16-14-25-05-838.zip)

### 备注 / Addition details

使用的是可直连分支，根据描述只添加了直连功能，所以向您提交issue

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.11.1

### EhViewer CI 版本 / EhViewer CI Version

42297a3

### Android 系统版本 / Android version

安卓13/ColorOS13

### 设备型号 / Device model

一加9pro

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
这是因为本地数据库里的这些画廊没有日文标题
取决于设置，在搜索时我们只能拿到英文或日文标题其中之一
在详情页才能两者都拿到，同时更新本地数据库
