### ISSUE TITLE
[建议] 使用优化/动画

### ISSUE THREAD

**Issue by RecursionInt** [FooIbar/EhViewer#291]
### 复现步骤 / Step to reproduce

-

### 预期行为 / Expected behaviour

如题。
现在的动画太过快速和刺眼。

建议优化点击控件时的动画，例如在「设置」中点击「Eh」选项时使用 从右向左 的动画而不是 从下至上。

### 实际行为 / Actual Behaviour

-

### 应用日志 / App logs

-

### 备注 / Addition details

.

### 浏览站点 / Browsing site

.

### EhViewer 版本号 / EhViewer version code

.

### EhViewer CI 版本 / EhViewer CI Version

.

### Android 系统版本 / Android version

.

### 设备型号 / Device model

.

### SoC 型号 / Soc model

.

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
@VDostoyevskiy Any thoughts?
Maybe we just use `RootNavGraphDefaultAnimations.ACCOMPANIST_FADING`.
