### ISSUE TITLE
设置-高级里面移除了之前有的域名前置、内置hosts.txt等一些功能导致现在不用VPN看不了漫画

### ISSUE THREAD

**Issue by PennyFranklin** [FooIbar/EhViewer#296]
### 复现步骤 / Step to reproduce

打开应用

### 预期行为 / Expected behaviour

应该是直接裸连加载出来图片

### 实际行为 / Actual Behaviour

![Screenshot_2023-11-19-21-53-17-028_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/104998459/2a9135cd-e8b2-417a-b79e-27aa14af65be)

### 应用日志 / App logs

log-2023-11-19-22-01-23-768

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.12.0

### EhViewer CI 版本 / EhViewer CI Version

e69eba6

### Android 系统版本 / Android version

HyperOS Android14

### 设备型号 / Device model

Xiaomi 14

### SoC 型号 / Soc model

骁龙8GEN3

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Duplicate of #12
