### ISSUE TITLE
搜索框被状态栏遮挡

### ISSUE THREAD

**Issue by RxinnotRstar** [FooIbar/EhViewer#32]
### 复现步骤 / Step to reproduce

启动软件，发现搜索框异常
![Screenshot_2023-09-28-06-34-04-346_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/56676566/52c49312-2734-45c4-8fa3-2fd1fe6c9e39)

### 预期行为 / Expected behaviour

-

### 实际行为 / Actual Behaviour

-

### EhViewer 版本号 / EhViewer version code

1.8.9.6

### EhViewer CI 版本 / EhViewer CI Version

d58e08e

### Android 系统版本 / Android version

MIUI 12.0，Android 10

### 设备型号 / Device model

redmi note9 4G

### SoC 型号 / Soc model

高通骁龙662

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现，这个问题是从哪个版本开始有的？

**Comment by FooIbar** [comment]
https://issuetracker.google.com/issues/236862874
