### ISSUE TITLE
下载界面的按钮渲染

### ISSUE THREAD

**Issue by IZUMI-Zu** [FooIbar/EhViewer#320]
### 复现步骤 / Step to reproduce

下载界面的右下角存在按键 但未渲染

https://github.com/FooIbar/EhViewer/assets/23271676/6c847371-6472-4e3f-996f-838c19c55780

### 预期行为 / Expected behaviour

按键正常渲染

### 实际行为 / Actual Behaviour

![Screenshot_2023-11-24-15-25-27-75_f2f1746601bf3b868d00d5efaf12e601](https://github.com/FooIbar/EhViewer/assets/23271676/2586709d-5123-4fc8-80fd-c517c45c0b12)

### 应用日志 / App logs

[log-2023-11-24-15-33-55-830.zip](https://github.com/FooIbar/EhViewer/files/13456282/log-2023-11-24-15-33-55-830.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.18.12

### EhViewer CI 版本 / EhViewer CI Version

17a9c02

### Android 系统版本 / Android version

ColorOS 12.1

### 设备型号 / Device model

OnePlus 7 pro

### SoC 型号 / Soc model

骁龙 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
那个按钮是不应该存在的
