### ISSUE TITLE
屏幕方向为横屏状态下打开压缩包Ehviewer奔溃

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#34]
### 复现步骤 / Step to reproduce

0.重新安装应用
1.游客登录，进入Ehviewer
2.默认状态下打开压缩包，正常进入
3.切换横屏后打开压缩包，Ehviewer奔溃（横屏+条漫&从上到下连续）

### 预期行为 / Expected behaviour

正常预览

### 实际行为 / Actual Behaviour

Ehviewer奔溃

### 应用日志 / App logs

[log-2023-09-30-01-30-44-420.zip](https://github.com/FooIbar/EhViewer/files/12769751/log-2023-09-30-01-30-44-420.zip)

### EhViewer 版本号 / EhViewer version code

1.8.10.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

098068f

### Android 系统版本 / Android version

HarmonyOS 4.0.0.115

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
有的系统64位的 libjpeg 的实现可能有点问题，你有没有试过32位的版本

**Comment by FooIbar** [comment]
```
********** Crash dump: **********
Build fingerprint: 'HUAWEI/RNA-AL00/HWRTE:12/HUAWEIRNA-AL00/104.0.0.115C00:user/release-keys'
#00 0x000000000003ac50 /system/lib64/libjpeg.so (decode_mcu+2984) (BuildId: 7b1b4a374cae87c0a76fe9aa0cbf08f5)
#01 0x0000000000033500 /system/lib64/libjpeg.so (decompress_onepass+180) (BuildId: 7b1b4a374cae87c0a76fe9aa0cbf08f5)
#02 0x000000000003c5a0 /system/lib64/libjpeg.so (process_data_simple_main+64) (BuildId: 7b1b4a374cae87c0a76fe9aa0cbf08f5)
#03 0x0000000000030588 /system/lib64/libjpeg.so (jpeg_read_scanlines+164) (BuildId: 7b1b4a374cae87c0a76fe9aa0cbf08f5)
#04 0x00000000007c5610 /system/lib64/libhwui.so (SkJpegCodec::readRows(SkImageInfo const&, void*, unsigned long, int, SkCodec::Options const&)+272) (BuildId: bd1f0753bf2f489027c450a5698db604)
#05 0x00000000007c524c /system/lib64/libhwui.so (SkJpegCodec::onGetPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const&, int*)+248) (BuildId: bd1f0753bf2f489027c450a5698db604)
#06 0x00000000007b2880 /system/lib64/libhwui.so (SkCodec::getPixels(SkImageInfo const&, void*, unsigned long, SkCodec::Options const*)+580) (BuildId: bd1f0753bf2f489027c450a5698db604)
#07 0x000000000045220c /system/lib64/libhwui.so (SkSampledCodec::onGetAndroidPixels(SkImageInfo const&, void*, unsigned long, SkAndroidCodec::AndroidOptions const&)+604) (BuildId: bd1f0753bf2f489027c450a5698db604)
#08 0x0000000000821048 /system/lib64/libhwui.so (SkAndroidCodec::getAndroidPixels(SkImageInfo const&, void*, unsigned long, SkAndroidCodec::AndroidOptions const*)+404) (BuildId: bd1f0753bf2f489027c450a5698db604)
#09 0x00000000008027cc /system/lib64/libhwui.so (android::ImageDecoder::decode(void*, unsigned long)+1100) (BuildId: bd1f0753bf2f489027c450a5698db604)
#10 0x0000000000801864 /system/lib64/libhwui.so (ImageDecoder_nDecodeBitmap(_JNIEnv*, _jobject*, long, _jobject*, unsigned char, int, int, _jobject*, unsigned char, int, unsigned char, unsigned char, unsigned char, long, unsigned char)+1048) (BuildId: bd1f0753bf2f489027c450a5698db604)
#11 0x00000000001d3cf0 /system/framework/arm64/boot-framework.oat (art_jni_trampoline+224) (BuildId: 5e6786e1a38514c6081980b931680304aa5c274f)
#12 0x00000000002f7fa8 /system/framework/arm64/boot-framework.oat (android.graphics.ImageDecoder.decodeBitmapInternal+440) (BuildId: 5e6786e1a38514c6081980b931680304aa5c274f)
#13 0x00000000002f8178 /system/framework/arm64/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawableImpl+200) (BuildId: 5e6786e1a38514c6081980b931680304aa5c274f)
#14 0x00000000002f8038 /system/framework/arm64/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawable+56) (BuildId: 5e6786e1a38514c6081980b931680304aa5c274f)
```

**Comment by tmby** [comment]
> 有的系统64位的 libjpeg 的实现可能有点问题，你有没有试过32位的版本

试过了，部分压缩包依旧奔溃
![log-2023-10-01-15-03-34-865.zip](https://github.com/FooIbar/EhViewer/files/12776578/log-2023-10-01-15-03-34-865.zip)

**Comment by FooIbar** [comment]
```
********** Crash dump: **********
Build fingerprint: 'HUAWEI/RNA-AL00/HWRTE:12/HUAWEIRNA-AL00/104.0.0.115C00:user/release-keys'
#00 0x000308dc /system/lib/libjpeg.so (jpeg_fill_bit_buffer+148) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
#01 0x0003110c /system/lib/libjpeg.so (decode_mcu+1004) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
#02 0x0002a39c /system/lib/libjpeg.so (decompress_onepass+164) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
#03 0x00032ef8 /system/lib/libjpeg.so (process_data_simple_main+56) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
#04 0x00027248 /system/lib/libjpeg.so (jpeg_read_scanlines+184) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
#05 0x00348bc1 /system/lib/libhwui.so (SkJpegCodec::readRows(SkImageInfo const&, void*, unsigned int, int, SkCodec::Options const&)+176) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#06 0x003489a1 /system/lib/libhwui.so (SkJpegCodec::onGetPixels(SkImageInfo const&, void*, unsigned int, SkCodec::Options const&, int*)+156) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#07 0x0033e041 /system/lib/libhwui.so (SkCodec::getPixels(SkImageInfo const&, void*, unsigned int, SkCodec::Options const*)+404) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#08 0x001380d5 /system/lib/libhwui.so (SkSampledCodec::onGetAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const&)+204) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#09 0x00394bb5 /system/lib/libhwui.so (SkAndroidCodec::getAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const*)+316) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#10 0x0037c5cf /system/lib/libhwui.so (android::ImageDecoder::decode(void*, unsigned int)+1038) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#11 0x0037b9b5 /system/lib/libhwui.so (ImageDecoder_nDecodeBitmap(_JNIEnv*, _jobject*, long long, _jobject*, unsigned char, int, int, _jobject*, unsigned char, int, unsigned char, unsigned char, unsigned char, long long, unsigned char)+832) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
#12 0x001c7bf3 /system/framework/arm/boot-framework.oat (art_jni_trampoline+178) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
#13 0x002ab6d7 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeBitmapInternal+462) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
#14 0x002ab835 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawableImpl+164) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
#15 0x002ab737 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawable+46) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
```
看起来都是解码的时候出了问题，白e也是用的ImageDecoder，是否也有这个问题？

**Comment by tmby** [comment]
> ```
> ********** Crash dump: **********
> Build fingerprint: 'HUAWEI/RNA-AL00/HWRTE:12/HUAWEIRNA-AL00/104.0.0.115C00:user/release-keys'
> #00 0x000308dc /system/lib/libjpeg.so (jpeg_fill_bit_buffer+148) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
> #01 0x0003110c /system/lib/libjpeg.so (decode_mcu+1004) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
> #02 0x0002a39c /system/lib/libjpeg.so (decompress_onepass+164) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
> #03 0x00032ef8 /system/lib/libjpeg.so (process_data_simple_main+56) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
> #04 0x00027248 /system/lib/libjpeg.so (jpeg_read_scanlines+184) (BuildId: 25ca23ca5ad2b38561bd2ee6db10b728)
> #05 0x00348bc1 /system/lib/libhwui.so (SkJpegCodec::readRows(SkImageInfo const&, void*, unsigned int, int, SkCodec::Options const&)+176) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #06 0x003489a1 /system/lib/libhwui.so (SkJpegCodec::onGetPixels(SkImageInfo const&, void*, unsigned int, SkCodec::Options const&, int*)+156) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #07 0x0033e041 /system/lib/libhwui.so (SkCodec::getPixels(SkImageInfo const&, void*, unsigned int, SkCodec::Options const*)+404) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #08 0x001380d5 /system/lib/libhwui.so (SkSampledCodec::onGetAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const&)+204) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #09 0x00394bb5 /system/lib/libhwui.so (SkAndroidCodec::getAndroidPixels(SkImageInfo const&, void*, unsigned int, SkAndroidCodec::AndroidOptions const*)+316) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #10 0x0037c5cf /system/lib/libhwui.so (android::ImageDecoder::decode(void*, unsigned int)+1038) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #11 0x0037b9b5 /system/lib/libhwui.so (ImageDecoder_nDecodeBitmap(_JNIEnv*, _jobject*, long long, _jobject*, unsigned char, int, int, _jobject*, unsigned char, int, unsigned char, unsigned char, unsigned char, long long, unsigned char)+832) (BuildId: 1741c8c73b2151a7c7f70db23c7693e2)
> #12 0x001c7bf3 /system/framework/arm/boot-framework.oat (art_jni_trampoline+178) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
> #13 0x002ab6d7 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeBitmapInternal+462) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
> #14 0x002ab835 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawableImpl+164) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
> #15 0x002ab737 /system/framework/arm/boot-framework.oat (android.graphics.ImageDecoder.decodeDrawable+46) (BuildId: 4cbdf75af95f059f3ab1e3038d03e7cc60b8f1dc)
> ```
> 看起来都是解码的时候出了问题，白e也是用的ImageDecoder，是否也有这个问题？

白e也崩溃
![log-2023-10-01-19-58-36-724.zip](https://github.com/FooIbar/EhViewer/files/12777083/log-2023-10-01-19-58-36-724.zip)

**Comment by FooIbar** [comment]
根据之前的日志来看，崩溃是在这里发生的
https://github.com/FooIbar/EhViewer/blob/a21ba04e95bf976332cca8c69e2e80bf46c16fa9/app/src/main/java/com/hippo/ehviewer/gallery/ArchivePageLoader.kt#L121
我怀疑是这里解压的时候破坏了这一块的内存，导致后面解码的时候出现了非法内存访问
https://github.com/FooIbar/EhViewer/blob/a21ba04e95bf976332cca8c69e2e80bf46c16fa9/app/src/main/java/com/hippo/ehviewer/gallery/ArchivePageLoader.kt#L102

**Comment by FooIbar** [comment]
卧槽，我发现能复现哦
我之前一直以为你是在屏幕横屏的状态下打开，下了https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1122 的录屏才发现是在屏幕竖屏但阅读器设置为横屏的情况下打开
如果一开始不是横屏的话会导致 Activity 重新创建，就像 @asuka-mio 说的那样

**Comment by asuka-mio** [comment]
> 卧槽，我发现能复现哦 我之前一直以为你是在屏幕横屏的状态下打开，下了[Ehviewer-Overhauled/Ehviewer#1122](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1122) 的录屏才发现是在屏幕竖屏但阅读器设置为横屏的情况下打开 如果一开始不是横屏的话会导致 Activity 重新创建，就像 @asuka-mio 说的那样

整个deferred close吧

**Comment by FooIbar** [comment]
直接跳过得了，开开关关完全是没必要的开销
