### ISSUE TITLE
Blocker is not working/設置的屏蔽項（Tag）沒有效果

### ISSUE THREAD

**Issue by mika-savijarvi** [FooIbar/EhViewer#35]
### 复现步骤 / Step to reproduce

0. 重新安裝應用/Reinstall.
1. 登錄帳號/Log in
2. 選擇站點（ex）/Choose exhentai
3. 進入訂閲列表/Enter Subscription
4. 進入任一畫廊，將其語言標籤添加屏蔽（例：Language:korean）/Enter a Gallery, long-push the language tag, and choose  "Add blocker"(e.g. language:korean)。
5. 刷新訂閲、回到主頁或進行任意搜索，會發現屏蔽項沒有生效/Refresh subscription, or back to homepage or search with any word. The blocker is not working.

### 预期行为 / Expected behaviour

刷新或載入新的畫廊時應當會自動移除帶有被屏蔽的標籤的畫廊。
Galleries with blocked tags should be removed.

### 实际行为 / Actual Behaviour

實際依舊出現在列表中。
It still appeared on the list.

### 应用日志 / App logs

[log-2023-09-30-17-53-17-111.zip](https://github.com/FooIbar/EhViewer/files/12774300/log-2023-09-30-17-53-17-111.zip)

### 备注 / Addition details

這個問題在多部設備上復現，包括 Pixel 6 Pro, Xiaomi 13 Pro 及下方表格中填寫的 Xperia 1 V。

### EhViewer 版本号 / EhViewer version code

1.8.9.6-gms

### EhViewer CI 版本 / EhViewer CI Version

13f2555

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Xperia 1 V

### SoC 型号 / Soc model

Snapdragon 8 Gen 2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
一般来说，建议使用官方的屏蔽功能对[语言](https://e-hentai.org/uconfig.php#languages)或[标签](https://e-hentai.org/mytags)进行屏蔽
因为官方的是在返回结果前过滤，而应用是在拿到网站的结果后进行过滤

无法复现，请提供搜索条件、屏蔽项以及未被屏蔽的画廊链接，或录屏
