### ISSUE TITLE
阅读界面下方页码文字错位

### ISSUE THREAD

**Issue by rurires** [FooIbar/EhViewer#37]
### 复现步骤 / Step to reproduce

1.阅读任意画廊；
2.切换阅读背景为白色会更明显。

### 预期行为 / Expected behaviour

页码应显示为白字+黑色(深灰色)描边。

### 实际行为 / Actual Behaviour

似乎是作为描边的“阴影”显示在正确位置，而白色的文字显示错位。
![ehvPageNum_2023-10-01](https://github.com/FooIbar/EhViewer/assets/33484515/16ddb1d3-493f-49fa-bd02-4bf8899f93dd)

### EhViewer 版本号 / EhViewer version code

1.8.10.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

cac65d9

### Android 系统版本 / Android version

MIUI 12.5 (Android 10)

### 设备型号 / Device model

Xiaomi Mix 2S

### SoC 型号 / Soc model

骁龙 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法在真机（Android 11）和模拟器（Android 10/14）上复现
这似乎是一个特定系统的问题

**Comment by FooIbar** [comment]
你用的tachiyomi是什么版本的？
我们现在的实现应该是一样的

**Comment by rurires** [comment]
> 你用的tachiyomi是什么版本的？ 我们现在的实现应该是一样的

最新的Releases版，不过也是好几个月没更新的版本了。
[Tachiyomi v0.14.6_arm64-v8a](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.6)

**Comment by FooIbar** [comment]
> > 你用的tachiyomi是什么版本的？ 我们现在的实现应该是一样的
> 
> 最新的Releases版，不过也是好几个月没更新的版本了。 [Tachiyomi v0.14.6_arm64-v8a](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.14.6)
> 
> 我试了下安装最新的Weekly Preview版，发现出现了一样的情况，看来是上游就有的问题。 [Tachiyomi Preview r6071](https://github.com/tachiyomiorg/tachiyomi-preview/releases/tag/r6071)
> 
> 那我应该去Tachiyomi那边报bug了

Tachiyomi 在 https://github.com/tachiyomiorg/tachiyomi/commit/3c79777e66d701958c2a20dfb5ccbdfef6e5c294 把页码迁移到了 compose 实现
确实去那边报比较好，我没有 MIUI 设备复现不了不好修，那边可能人手多一些

**Comment by rurires** [comment]
[Page Indicator Text Dislocation (Preview r6071)](https://github.com/tachiyomiorg/tachiyomi/issues/9976)
在Tachiyomi提issues了

**Comment by FooIbar** [comment]
我先回退到旧的实现吧

**Comment by FooIbar** [comment]
在 ab37399 之后这个问题有再次出现吗？
