### ISSUE TITLE
此分支是否不支持直连功能？

### ISSUE THREAD

**Issue by RxinnotRstar** [FooIbar/EhViewer#39]
### 复现步骤 / Step to reproduce

关闭VPN，安装[ 飛鳥澪版ehviewer](https://github.com/Ehviewer-Overhauled/Ehviewer/releases) ；

尝试直连下载图片，正常；

尝试检测剩余下载量，正常；

安装foolbar版ehviewer；

打开之后，无法加载首页内容，也无法下载未完成的部分；

尝试检测剩余下载量，提示“timeout”；

开启VPN，上述测试恢复正常。

### 预期行为 / Expected behaviour

ehviewer的一大特色就是可以免VPN直连eh

### 实际行为 / Actual Behaviour

然而目前似乎并没有用

### 备注 / Addition details

三大运营商用 飛鳥澪ehv 直连的情况：
中国联通：畅连
中国电信：低速
中国移动：基本不可能

我的网络是中国联通

### EhViewer 版本号 / EhViewer version code

当前分支版本：1.8.9.7； 飛鳥澪分支版本：1.8.8.3

### EhViewer CI 版本 / EhViewer CI Version

97f9889

### Android 系统版本 / Android version

Android 10 / MIUI 12

### 设备型号 / Device model

redmi note 9 4G

### SoC 型号 / Soc model

高通骁龙 662

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
请看[1.8.9.0](https://github.com/FooIbar/EhViewer/releases/tag/1.8.9.0)的更新日志，已移除域名前置

**Comment by FooIbar** [comment]
Duplicate of #12
