### ISSUE TITLE
快速搜索面板弹出导致程序无响应

### ISSUE THREAD

**Issue by Krosec** [FooIbar/EhViewer#42]
### 复现步骤 / Step to reproduce

打开快速搜索面板后返回
打开视频录制

### 预期行为 / Expected behaviour

快速搜索面板不弹出

### 实际行为 / Actual Behaviour

![Screenshot_2023-10-04-16-15-35-43_f2f1746601bf3b868d00d5efaf12e601](https://github.com/FooIbar/EhViewer/assets/107551827/bcf78916-7297-453f-9afc-d97c4113421c)

### 备注 / Addition details

返回桌面后重新打开程序则恢复正常

### EhViewer 版本号 / EhViewer version code

1.8.10.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

7f541e2

### Android 系统版本 / Android version

OxygenOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7t

### SoC 型号 / Soc model

Snapdragon 855+

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现
你这快速搜索怎么不全的，高度也不对

**Comment by Krosec** [comment]
> 无法复现 你这快速搜索怎么不全的，高度也不对

这个bug目前看来，只在oppo系的手机出现，快速搜索显示不全就是这个bug的体现，已经收回去的快速搜索，在点击录制视频的时候弹出
[log-2023-10-05-13-24-54-646.zip](https://github.com/FooIbar/EhViewer/files/12812637/log-2023-10-05-13-24-54-646.zip)

**Comment by FooIbar** [comment]
> > 无法复现 你这快速搜索怎么不全的，高度也不对
> 
> 这个bug目前看来，只在oppo系的手机出现，快速搜索显示不全就是这个bug的体现。已经收回去的快速搜索，在点击录制视频的时候弹出，弹出的快速搜索界面就是截图所示 [log-2023-10-05-13-24-54-646.zip](https://github.com/FooIbar/EhViewer/files/12812637/log-2023-10-05-13-24-54-646.zip)

只有录制的时候会弹出？

**Comment by Krosec** [comment]
> > > 无法复现 你这快速搜索怎么不全的，高度也不对
> > 
> > 
> > 这个bug目前看来，只在oppo系的手机出现，快速搜索显示不全就是这个bug的体现。已经收回去的快速搜索，在点击录制视频的时候弹出，弹出的快速搜索界面就是截图所示 [log-2023-10-05-13-24-54-646.zip](https://github.com/FooIbar/EhViewer/files/12812637/log-2023-10-05-13-24-54-646.zip)
> 
> 只有录制的时候会弹出？

还没开始录制，oppo系的手机点击视频录制后，会弹出一个开关，来控制视频录制的开始和结束，截图的情况就是弹出这个开关的同时出现的，系统自带的截图没有把这个开关截取下来

**Comment by FooIbar** [comment]
如果只有录屏的时候有问题的话不会修，这是上游的问题
