### ISSUE TITLE
下载速度只有十几K

### ISSUE THREAD

**Issue by Weijuxian** [FooIbar/EhViewer#420]
### 复现步骤 / Step to reproduce

进入应用之后，下载选中，只有十几K的速度，而且很快就停下来了

https://github.com/FooIbar/EhViewer/assets/106127371/644e47b8-33aa-4d41-8a48-d9a31ec0a136

### 预期行为 / Expected behaviour

他应该拥有一个正常的下载速度。

### 实际行为 / Actual Behaviour

![Screenshot_2023-12-02-11-21-43-388_com miui mediaviewer](https://github.com/FooIbar/EhViewer/assets/106127371/13155c35-b142-45cb-8841-1f2a4e688a92)

### 应用日志 / App logs

[log-2023-12-02-11-22-02-663.zip](https://github.com/FooIbar/EhViewer/files/13533234/log-2023-12-02-11-22-02-663.zip)

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.8.9.6

### EhViewer CI 版本 / EhViewer CI Version

d58e08e

### Android 系统版本 / Android version

MIUI14,Android13

### 设备型号 / Device model

Xiaomi 10 Ultra

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
更新
