### ISSUE TITLE
被版權的畫廊不會移到歷史頁面的最上層

### ISSUE THREAD

**Issue by InLem** [FooIbar/EhViewer#424]
### 复现步骤 / Step to reproduce

在歷史頁面或在收藏點畫廊。

### 预期行为 / Expected behaviour

只要點畫廊，這畫廊就會顯示在歷史頁面的最上層。

### 实际行为 / Actual Behaviour

升級到1.9.0版後點 被版權 的畫廊不會移到最上層，但其他尚未被版權的是正常的。

### 应用日志 / App logs

[log-2023-12-02-16-20-40-909.zip](https://github.com/FooIbar/EhViewer/files/13533824/log-2023-12-02-16-20-40-909.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.9.0

### EhViewer CI 版本 / EhViewer CI Version

0538326

### Android 系统版本 / Android version

Android 11

### 设备型号 / Device model

Realme6

### SoC 型号 / Soc model

MTK Helio G90T

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
预期行为，历史中只会记录能访问的画廊

**Comment by InLem** [comment]
> 预期行为，历史中只会记录能访问的画廊

但之前的版本沒有這問題。
我點已被版權(已下載，所以還能觀看)的畫廊是會移到最上層。

**Comment by FooIbar** [comment]
这是 1.9.0 起的预期行为，变更日志里忘了提了

**Comment by InLem** [comment]
> 这是 1.9.0 起的预期行为，变更日志里忘了提了

好，我明白了。

**Comment by FooIbar** [comment]
我想了一下，直接下载中进行阅读时在历史中记录是合理的
之后会改一下

**Comment by InLem** [comment]
> 自 [75e3e78](https://github.com/FooIbar/EhViewer/commit/75e3e78ecb97e41cd538e6e90b49909d747b9cae) 起在下載中閱讀會寫入歷史記錄

但我安裝75e3e78還是一樣的問題。
是指之後的版本會解決這問題嗎?

**Comment by FooIbar** [comment]
被版权的画廊在下载中直接阅读才会写入历史，访问详情页不会

InLem ***@***.***> 于 2023年12月2日周六 17:55写道：

**Comment by InLem** [comment]
知道了。

我順便問一下。
EhViewer是不是不會從本地已下載的檔案中讀取資料? 需要從伺服器上重新載入。
我發現重裝EhViewer後原先 已下載 的版權本變得不能閱讀了(畫面全黑)，但看檔案還在而且正常。
其他 未被版權但已下載 的畫廊雖然還是能觀看，但發現有吃流量，且如果把網路全關就變得無法觀看。

**Comment by FooIbar** [comment]
如果下载文件夹里的 .ehviewer 文件还在的话不需要联网
没了的话要从网络加载画廊元数据

**Comment by InLem** [comment]
這我有檢查過，但 .ehviewer檔 還在。
我也有想過可能是更新後.ehviewer檔被更改(或破壞)。我將檔案全部從雲端還原(不管有沒有被更改過)，結果也是一樣。

> 如果下載資料夾裡的 .ehviewer 檔案還在的話不需要聯網 沒了的話要從網路載入畫廊中繼資料

**Comment by InLem** [comment]
> 那之前应该是由于下载路径不一致导致重新下载

但我原先就是用預設的路徑。

對了，另外說一下。
之前有人回報說[非原图下载时图片分辨率过低问题 #111]，我發現更新後問題還是有。
這個問題我是將user agent改成跟PC的一樣就解決了。

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by FooIbar** [comment]
> 對了，另外說一下。 之前有人回報說[非原图下载时图片分辨率过低问题 #111]，我發現更新後問題還是有。 這個問題我是將user agent改成跟PC的一樣就解決了。
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

这个问题跟网站设置有关，改设置或者改UA都可以

**Comment by InLem** [comment]
> 这个问题跟网站设置有关，改设置或者改UA都可以

我剛才再試著修改(表/裡)網站設定成1280x，但設定完還是會有模糊的問題。
不管是直接在網站或是在ehviewer上設定都一樣。

**Comment by FooIbar** [comment]
如果是之前看过的画廊会从缓存里读取

**Comment by FooIbar** [comment]
可以

**Comment by InLem** [comment]
> 可以

啊，如果是這樣的話我剛才已經試過很多次了。
結果不行。

**Comment by FooIbar** [comment]
你可以另开一个issue，执行以下操作：

1. 在设置里改成 1280
2. 随便选个画廊，清除缓存并下载，下一张就可以暂停
3. 回到设置里看分辨率是不是 1280

然后把日志传上来

**Comment by InLem** [comment]
> 你可以另开一个issue，执行以下操作：
> 
> 1. 在设置里改成 1280
> 2. 随便选个画廊，清除缓存并下载，下一张就可以暂停

有需要更到最新版來測試嗎？
因為我退回舊版了，想說穩穩用就好。
昨天下午折騰的有點累。

> 3. 回到设置里看分辨率是不是 1280
> 
> 然后把日志传上来

這個我昨天在測試時有發現他設定會一直跳回auto，不管是在網頁上，還是在app上設定都一樣。

**Comment by FooIbar** [comment]
> 這個我昨天在測試時有發現他設定會一直跳回auto，不管是在網頁上，還是在app上設定都一樣。

那就是 #137 了，不用测了

**Comment by InLem** [comment]
> 被版權的畫廊在下載中直接閱讀才會寫入歷史，訪問詳情頁不會

呃...不好意思。
原本是想發功能建議，但找不到地方發，所以就發在這裡。

請問能讓點詳情頁也能寫入歷史嗎? 因為我常從歷史頁面看常看的漫畫。
因為只要越常看，這漫畫就會在歷史頁面的上層。
反之只要不常看，這漫畫就會慢慢移到最下層，最終自動消失。
我覺得歷史頁面有這好處。

當然，因為你之前有說這是新版的規定，所以應該是有某些考量。
所以不用免強。
