### ISSUE TITLE
操作过程中出现闪屏

### ISSUE THREAD

**Issue by wordly123** [FooIbar/EhViewer#431]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/21117763/e8d61b9f-5d12-4aa7-b34b-82696eff502a

https://github.com/FooIbar/EhViewer/assets/21117763/19f30383-e454-4e2c-b1f0-878a5a34ea62

### 预期行为 / Expected behaviour

不会发生闪屏

### 实际行为 / Actual Behaviour

闪屏

### 应用日志 / App logs

没有日志

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.9.0

### EhViewer CI 版本 / EhViewer CI Version

19d14e1

### Android 系统版本 / Android version

MagicOS 7.1  Android 13

### 设备型号 / Device model

Magic5pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
尝试在 设置-高级 中关闭预见式返回动画

**Comment by FooIbar** [comment]
> > 尝试在 设置-高级 中关闭预见式返回动画
> 
> 我试了下关闭后就没有问题了，不过预见式返回动画开启后闪屏是正常行为吗？

在某些魔改系统（比如华为）上会有问题

**Comment by VDostoyevskiy** [comment]
@wordly123 你能在 https://github.com/FooIbar/EhViewer/actions/runs/7339314202
中开启预见式返回动画并复现这个问题吗

**Comment by VDostoyevskiy** [comment]
@wordly123 如果不能的话我们将考虑移除这个选项

**Comment by wordly123** [comment]
> @wordly123 如果不能的话我们将考虑移除这个选项

看起来好像没有闪屏的问题了，但是这个开和不开好像没什么两样了。 https://github.com/FooIbar/EhViewer/assets/21117763/bf7a19a8-3679-45bf-935f-b001936b9ab4

https://github.com/FooIbar/EhViewer/assets/21117763/f41cec63-d2b7-4b54-8122-4a9c5432ce1e

**Comment by VDostoyevskiy** [comment]
了解
