### ISSUE TITLE
无法由外部应用进入画廊页面

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#436]
### 复现步骤 / Step to reproduce

0. 验证外部链接打开方式。
1. 进入应用，此时应该在首页画廊列表页面。
2. 在任意外部应用（比如Telegram）打开 E-Hentai 链接，比如 https://e-hentai.org/g/2285550/6947688057/ 。

### 预期行为 / Expected behaviour

进入该画廊。

### 实际行为 / Actual Behaviour

仍然在列表页面。

### 应用日志 / App logs

[logcat-2023-12-03-15-47-54-596.txt](https://github.com/FooIbar/EhViewer/files/13538336/logcat-2023-12-03-15-47-54-596.txt)

### 备注 / Addition details

~~如果提前在应用内进入任意一个画廊，此时再去外部应用打开链接就可以进入相应画廊。~~

之前的表述有误，应该是：

1. 退出应用
2. 打开外部链接进入应用，此时会进入列表页面
3. 在列表页面进入任意画廊
4. 回到外部应用，再次打开链接

只有这样，才能进入相应画廊。如果一开始不是从外部链接打开应用，而是在，比如启动器启动应用，则无论如何都无法进入相应画廊。

打开评论区的画廊链接没有该问题。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

fc3b9d7

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

Google Pixel 5

### SoC 型号 / Soc model

Snapdragon 765G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by VDostoyevskiy** [comment]
@FooIbar https://github.com/FooIbar/EhViewer/blob/fc3b9d73ec613424044740b1178729494cb02492/app/src/main/kotlin/com/hippo/ehviewer/ui/MainActivity.kt#L215 这是不是应该await一帧
