### ISSUE TITLE
浏览较多画廊之后应用崩溃

### ISSUE THREAD

**Issue by Cathgao** [FooIbar/EhViewer#437]
### 复现步骤 / Step to reproduce

0.正常使用，浏览较多作品
2.突然变得非常卡，每个动作耗时花费半秒左右，包括滑动
3.应用崩溃回到桌面

### 预期行为 / Expected behaviour

应用不会变卡和崩溃

### 实际行为 / Actual Behaviour

长时间使用后崩溃回到桌面

### 应用日志 / App logs

[log-2023-12-03-18-37-53-256.zip](https://github.com/FooIbar/EhViewer/files/13538638/log-2023-12-03-18-37-53-256.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.9.0-gms

### EhViewer CI 版本 / EhViewer CI Version

19d14e1

### Android 系统版本 / Android version

MIUI14.0.7 Android13

### 设备型号 / Device model

Redmi k40s

### SoC 型号 / Soc model

snapdragon870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Cathgao** [comment]
这个是被MIUI捕获的log，像是炸堆栈了。系统后台当时还有4GB左右空余RAM
[1.txt](https://github.com/FooIbar/EhViewer/files/13538711/1.txt)

**Comment by FooIbar** [comment]
在有限的信息下很难定位是什么原因
需要更详细的崩溃前的活动记录

**Comment by Cathgao** [comment]
> 在有限的信息下很难定位是什么原因
> 需要更详细的崩溃前的活动记录

需要怎么获取？目前log只有这些。操作的话就是随意逛了半个多小时，点点tag点点画师

**Comment by FooIbar** [comment]
> > 在有限的信息下很难定位是什么原因
> > 需要更详细的崩溃前的活动记录
> 
> 需要怎么获取？目前log只有这些。操作的话就是随意逛了半个多小时，点点tag点点画师

只是浏览，没有进行阅读吗？

**Comment by FooIbar** [comment]
> > > > 在有限的信息下很难定位是什么原因
> > > > 需要更详细的崩溃前的活动记录
> > > 
> > > 
> > > 需要怎么获取？目前log只有这些。操作的话就是随意逛了半个多小时，点点tag点点画师
> > 
> > 
> > 只是浏览，没有进行阅读吗？
> > 是稳定出现还是偶尔出现？
> 
> 浏览就是点进去画廊里面，也包括阅读 稳定不算稳定，因为我也很少长时间浏览和阅读这么多画廊，但如日志里的压缩包所见，崩溃也不止一次

日志中由于内存不足导致的崩溃其实只有一次，其他的已由 e0cad86 修复

**Comment by UjuiUjuMandan** [comment]
我也发一下日志吧，变更追到的是这边的 b2368b312f8f4465b9493ad4bd9e6d78d2dfc2ee 。

[crash-2023-12-06-01-40-08-733.decoded.log](https://github.com/FooIbar/EhViewer/files/13577102/crash-2023-12-06-01-40-08-733.decoded.log)
[logcat-2023-12-06-14-02-24-142.decoded.txt](https://github.com/FooIbar/EhViewer/files/13577106/logcat-2023-12-06-14-02-24-142.decoded.txt)

因为看起来太像了，我推测是同一个问题。当时我正在主页搜索某艺术家的画廊，结果很多，正在往下翻，然后突然变得很卡，再翻一会应用就退出了，整个过程没有进入阅读器页面。

**Comment by XiaoMiao458331** [comment]
请问大家有没有遇到过打开“下载”后应用无法跳转下载页面软件无反应的情况？软件等待很长时间都无反应，最后被系统杀掉，错误日志无登记。

**Comment by XiaoMiao458331** [comment]
感觉画廊的卡顿闪退和下载列表的复现都差不多，当出现列表缩略图无法加载的时候，闪退或者应用无反应就准备出现了。这种情况下如果选择无详细信息的马赛克显示模式立马闪退。
但是我还是不能理解为什么不看到缩略图，就不会因为缩略图没有加载卡顿，难道列表没有下拉到抓取的部分就不会加载吗？或者开软件不会加载下载列表？

**Comment by UjuiUjuMandan** [comment]
@XiaoMiao458331 
> 这种情况下如果选择无详细信息的马赛克显示模式立马闪退。

无响应被系统杀了没有日志，闪退了就发一下日志啊。

> 难道列表没有下拉到抓取的部分就不会加载吗？或者开软件不会加载下载列表？

是这样的。

**Comment by FooIbar** [comment]
> 我也发一下日志吧，变更追到的是这边的 [b2368b3](https://github.com/FooIbar/EhViewer/commit/b2368b312f8f4465b9493ad4bd9e6d78d2dfc2ee) 。
> 
> [crash-2023-12-06-01-40-08-733.decoded.log](https://github.com/FooIbar/EhViewer/files/13577102/crash-2023-12-06-01-40-08-733.decoded.log) [logcat-2023-12-06-14-02-24-142.decoded.txt](https://github.com/FooIbar/EhViewer/files/13577106/logcat-2023-12-06-14-02-24-142.decoded.txt)
> 
> 因为看起来太像了，我推测是同一个问题。当时我正在主页搜索某艺术家的画廊，结果很多，正在往下翻，然后突然变得很卡，再翻一会应用就退出了，整个过程没有进入阅读器页面。

你这日志里是在收藏页面闪退的啊

**Comment by UjuiUjuMandan** [comment]
> 你这日志里是在收藏页面闪退的啊

我记错了是吧。那应该是在收藏里搜索艺术家。

**Comment by XiaoMiao458331** [comment]
> @XiaoMiao458331 
> > 这种情况下如果选择无详细信息的马赛克显示模式立马闪退。
> 
> 无响应被系统杀了没有日志，闪退了就发一下日志啊。
> 
> > 难道列表没有下拉到抓取的部分就不会加载吗？或者开软件不会加载下载列表？
> 
> 是这样的。

我试了下现在没法还原闪退，请问卡顿甚至无响应的视频记录是否能帮助你们呢？

**Comment by FooIbar** [comment]
> 
> 我试了下现在没法还原闪退，请问卡顿甚至无响应的视频记录是否能帮助你们呢？

不相关的问题单独开issue

**Comment by Cathgao** [comment]
> > 我也发一下日志吧，变更追到的是这边的 [b2368b3](https://github.com/FooIbar/EhViewer/commit/b2368b312f8f4465b9493ad4bd9e6d78d2dfc2ee) 。
> > 
> > [crash-2023-12-06-01-40-08-733.decoded.log](https://github.com/FooIbar/EhViewer/files/13577102/crash-2023-12-06-01-40-08-733.decoded.log) [logcat-2023-12-06-14-02-24-142.decoded.txt](https://github.com/FooIbar/EhViewer/files/13577106/logcat-2023-12-06-14-02-24-142.decoded.txt)
> > 
> > 因为看起来太像了，我推测是同一个问题。当时我正在主页搜索某艺术家的画廊，结果很多，正在往下翻，然后突然变得很卡，再翻一会应用就退出了，整个过程没有进入阅读器页面。
> 
> 你这日志里是在收藏页面闪退的啊

我也补充一下，我这次崩溃也是在收藏里面翻看旧本，然后点tag（包括画师）来随便逛

**Comment by liuxuming3303** [comment]
手机：红米note7pro，已刷第三方rec twrp以刷第三方ROM crDroid 9.8 Android 13，曾手动装谷歌套装但闪退无法使用又卸载并在twrp挂载system分区清除残留，app版本为UjuiUjuMandan的1.9.0-cc(62f966c)。
[log-2023-12-17-23-10-52-699.zip](https://github.com/FooIbar/EhViewer/files/13696616/log-2023-12-17-23-10-52-699.zip)
[mysyslog231217.txt](https://github.com/FooIbar/EhViewer/files/13696617/mysyslog231217.txt)
爆炸过程视频大于10MB，用telegram链接代替吧，https://t.me/ehviewer/2436198

**Comment by FooIbar** [comment]
> 手机：红米note7pro，已刷第三方rec twrp以刷第三方ROM crDroid 9.8 Android 13，曾手动装谷歌套装但闪退无法使用又卸载并在twrp挂载system分区清除残留，app版本为UjuiUjuMandan的1.9.0-cc([62f966c](https://github.com/FooIbar/EhViewer/commit/62f966cda9b1a5e31af96f38af3c4baff2b64e88))。 [log-2023-12-17-23-10-52-699.zip](https://github.com/FooIbar/EhViewer/files/13696616/log-2023-12-17-23-10-52-699.zip) [mysyslog231217.txt](https://github.com/FooIbar/EhViewer/files/13696617/mysyslog231217.txt) 爆炸过程视频https://files.catbox.moe/8fecg3.mp4

日志里只有崩溃后的日志，没有崩溃前的日志，并没有什么有效信息

无论如何，自 5c36577 起 OOM 时会创建堆转储，这应该有助于排查原因

**Comment by liuxuming3303** [comment]
又一次，UjuiUjuMandan的1.10.1-cc(762a7ca)
https://files.catbox.moe/a31fs3.mp4
[log-2023-12-24-22-47-05-649.zip](https://github.com/FooIbar/EhViewer/files/13762379/log-2023-12-24-22-47-05-649.zip)
[mysyslog231224.txt](https://github.com/FooIbar/EhViewer/files/13762380/mysyslog231224.txt)

**Comment by FooIbar** [comment]
> 又一次，UjuiUjuMandan的1.10.1-cc([762a7ca](https://github.com/FooIbar/EhViewer/commit/762a7cab7c1cfb2d8187658c45d48cb34f164b5e)) https://files.catbox.moe/a31fs3.mp4 [log-2023-12-24-22-47-05-649.zip](https://github.com/FooIbar/EhViewer/files/13762379/log-2023-12-24-22-47-05-649.zip) [mysyslog231224.txt](https://github.com/FooIbar/EhViewer/files/13762380/mysyslog231224.txt)

不同的问题
以及，别的版本的别来这里发

**Comment by VDostoyevskiy** [comment]
Does this issue still need to be opened? I have never triggered that until now.

**Comment by Cathgao** [comment]
最新版逛了一个多小时都没崩，可以关了
