### ISSUE TITLE
#44 之后，连续搜索不显示结果

### ISSUE THREAD

**Issue by rurires** [FooIbar/EhViewer#45]
### 复现步骤 / Step to reproduce

1.打开软件，点击任意非中文画廊(即不含l:Chinese标签)；
2.点击作者标签，进行搜索；
3.点击搜索栏，添加l:Chinese标签进行第二次搜索(存在此作者的中文画廊的情况下)。

### 预期行为 / Expected behaviour

显示搜索结果。

### 实际行为 / Actual Behaviour

搜索结果列表空白。
此时从右划抽屉进入下载界面(即显示其它画廊列表)再返回的话，会恢复显示搜索结果。直接刷新也会恢复。

### 备注 / Addition details

[b0896ea](https://github.com/FooIbar/EhViewer/commit/b0896ea46582838d88a2f0b67ae0f3a3cc56c0ff) 后出现。
推测更具体的情况是：第二次搜索结果导致第一次搜索结果的前几个画廊被隐去时，会连带整个列表一起隐去。
切换界面重新读取搜索结果进行列表绘制时就会恢复显示。
在收藏界面中从云端收藏切换到细分收藏夹时也可能出现一样的情况。

### EhViewer 版本号 / EhViewer version code

1.8.10.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

8fb5153

### Android 系统版本 / Android version

MIUI 12.5 (Android 10)

### 设备型号 / Device model

Xiaomi Mix 2S

### SoC 型号 / Soc model

骁龙 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by rurires** [comment]
> 短时间内修不了，因为我手机摔坏了

心疼兄弟😨
那慢慢来，先用着[654e9a7](https://github.com/FooIbar/EhViewer/actions/runs/6406411743)前的版本完全没问题。

**Comment by FooIbar** [comment]
这个我不能稳定复现，你试下#61 还有没有问题

**Comment by rurires** [comment]
> 这个我不能稳定复现，你试下#61 还有没有问题

[CI #553](https://github.com/FooIbar/EhViewer/actions/runs/6535520842) 还是会不显示，但有一点区别：
之前是先看到靠前的、被排除的搜索结果划走消失的动态效果，然后才会整个列表渐隐；
现在是没有划走的动态效果，而直接出现排除完毕后的列表，然后整个列表渐隐。

**Comment by FooIbar** [comment]
你直接把你搜索的关键词和设置发出来吧
我明天再看一下

**Comment by rurires** [comment]
> 你直接把你搜索的关键词和设置发出来吧 我明天再看一下

1.搜索：artist:kuon$
2.搜索：artist:kuon$ l:chinese$

(1目前的结果是靠前的两个为非中文画廊，也试过用高级选项关闭所有过滤设置了)

**Comment by rurires** [comment]
[a592158](https://github.com/FooIbar/EhViewer/pull/61/commits/a59215861ec8a92b7caa0865aa2b32f40fc038d3) [CI #554](https://github.com/FooIbar/EhViewer/actions/runs/6537100029) 能正常显示了。
没有整个列表的渐现渐隐效果也挺舒服的，不过因此没有了表示“正在加载”的指示。
昨晚没留意到这个更新，刚才安装了所以报告一下情况。

**Comment by FooIbar** [comment]
> [a592158](https://github.com/FooIbar/EhViewer/pull/61/commits/a59215861ec8a92b7caa0865aa2b32f40fc038d3) [CI #554](https://github.com/FooIbar/EhViewer/actions/runs/6537100029) 能正常显示了。 没有整个列表的渐现渐隐效果也挺舒服的，不过因此没有了表示“正在加载”的指示。 昨晚没留意到这个更新，刚才安装了所以报告一下情况。

竟然有用，我其实没报太大希望
加载只是可以先用 RefreshLayout 的顶着
