### ISSUE TITLE
无法跳转链接

### ISSUE THREAD

**Issue by ZerOri** [FooIbar/EhViewer#470]
### 复现步骤 / Step to reproduce

点击任意一个e站画廊链接

### 预期行为 / Expected behaviour

跳转至链接画廊所在页面

### 实际行为 / Actual Behaviour

停留或跳转至app主页，或者停留在前一个跳转成功的画廊

### 应用日志 / App logs

[log-2023-12-08-01-39-30-748.zip](https://github.com/FooIbar/EhViewer/files/13603259/log-2023-12-08-01-39-30-748.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.9.0

### EhViewer CI 版本 / EhViewer CI Version

19d14e1

### Android 系统版本 / Android version

MIUI14，安卓13

### 设备型号 / Device model

红米k40

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
#436
