### ISSUE TITLE
希望带回应用内代理功能

### ISSUE THREAD

**Issue by swift-lee** [FooIbar/EhViewer#489]
### 复现步骤 / Step to reproduce

-

### 预期行为 / Expected behaviour

使用应用内代理功能

### 实际行为 / Actual Behaviour

应用内代理功能被移除

### 应用日志 / App logs

-

### 备注 / Addition details

刚看到原项目fork到这里继续进行了，同时发现应用内代理功能被移除 
[https://github.com/FooIbar/EhViewer/issues/201#issuecomment-1797820235](url)
仅就我个人而言，因为我是Adguard用户，所以同时使用其它VPN软件并不方便；而少部分需要代理流量的软件，包括浏览器和之前的EhViewer在内，长期以来可以直接使用我部署在内网的代理服务器，从而在大多数软件可以被Adguard过滤流量和接管DNS的前提下确保这些需要单独代理的软件共同使用而无需频繁调整手机设置。Adguard确实可以和手机上的代理软件实现共存，但会造成网络性能受到显著影响，所以我不是很喜欢这种用法。
若不会造成维护困难，希望可以将应用内http代理带回到这个项目中，感谢作者

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.0

### EhViewer CI 版本 / EhViewer CI Version

e7a381f

### Android 系统版本 / Android version

氢OS11 Android 11

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

骁龙855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by BakaJzon** [comment]
+1, 另外我有个问题。是否启用了应用内代理可以避免dns泄露我的访问记录？

**Comment by LzNOHentai** [comment]
作者说过不会加回，你可以试试这个
https://github.com/UjuiUjuMandan/EhViewer
