### ISSUE TITLE
作品页面能看到缩略图，点进去无法阅读（无限加载，甚至不会超时停止）

### ISSUE THREAD

**Issue by pchu999** [FooIbar/EhViewer#508]
### 复现步骤 / Step to reproduce

0.版本1.9.0-gms正常使用，然后提示升级，于是在应用内下载安装1.10.0-gms
1.安装完重新打开APP，检查 设置->EH->图片配额 无异常，设置->高级->Http引擎 为以前默认的Cronet
2.随便点开一个作品（点进云端收藏点进去第一个），缩略图显示正常
3.随便点一页进去阅读，耐心等待加载，往后滑下一页，再耐心等待加载
4.长按屏幕，点击刷新，观察
5.将设置->高级->Http引擎 改为Apache5，重开APP重复以上流程，在系统设置清除应用缓存再重开APP重复以上流程，重新改回Cronet再重复以上流程

### 预期行为 / Expected behaviour

应当正常加载，转圈圈太久之后应当显示超时，点击刷新后应当又转圈圈开始加载

### 实际行为 / Actual Behaviour

用各种办法都无法加载图片，无限转圈圈，不会出现超时提示。
点击刷新后出现提示 Cancelled 并出现重试按钮，点击重试按钮什么事都没发生，并不会重新开始转圈圈。

### 应用日志 / App logs

[logcat-2023-12-16-11-50-21-505.txt](https://github.com/FooIbar/EhViewer/files/13691611/logcat-2023-12-16-11-50-21-505.txt)
[logcat-2023-12-16-14-46-47-178.txt](https://github.com/FooIbar/EhViewer/files/13691645/logcat-2023-12-16-14-46-47-178.txt)

### 备注 / Addition details

Clash节点正常，设置->网络->访问控制应用包列表 确实已经勾选 moe.tarsin.ehviewer，使用其他开发者版本的ehviewer可以正常浏览

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.0-gms

### EhViewer CI 版本 / EhViewer CI Version

37eb2f1

### Android 系统版本 / Android version

MIUI 12.0.3.0, Android 10

### 设备型号 / Device model

Redmi K30S Ultra

### SoC 型号 / Soc model

高通骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by pchu999** [comment]
更新：
突然想起来重启-重装-重买大法，姑且试着重启了一次手机，结果很神奇，打开APP后从云端收藏随手点进去的第一个gallery能够正常加载浏览，但是我再尝试别的gallery，之前的问题就又出现了，试了非常多gallery都这样
难道是点进去的第一个gallery才能正常浏览吗？我又清除缓存重启手机再来一次，先打开跟上次不一样的另一个gallery，看是不是这样就能正常浏览它，结果不行，看样子能不能看似乎是和gallery自身有关
一番测试后发现，似乎从我云端收藏里进的极大部分几乎都不行，从首页和从热门里点进的gallery时不时有能正常浏览的
难道是日期旧的gallery不行、日期新的gallery就可以吗？似乎不对，即使从首页最新随便点，也有很多无限加载无法浏览的，但时不时有能浏览的
从经验看，似乎能够正常浏览的gallery多是画质较差、文件较小的黑白或者ai图，不知道是不是跟图像尺寸、文件大小有关
最后，是不是我的网络节点有问题？但我当场换用其他开发者版本的ehviewer看我云端收藏，就没有这样无限加载无法浏览的
[logcat-2023-12-16-15-58-25-863.txt](https://github.com/FooIbar/EhViewer/files/13691831/logcat-2023-12-16-15-58-25-863.txt)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/7230886397
试下这个

*并没有解决这个问题，但能提供更清晰的日志

**Comment by pchu999** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/7230886397 试下这个
> 
> *并没有解决这个问题，但能提供更清晰的日志

[logcat-2023-12-16-17-31-15-955.txt](https://github.com/FooIbar/EhViewer/files/13692085/logcat-2023-12-16-17-31-15-955.txt)
我先清除缓存，然后基本上是在历史记录里刷了刷，选点了两个我记得无法浏览的，点了两个我记得可以正常浏览的，又点了一个我记得无法浏览的gallery

**Comment by wzymzx** [comment]
> > https://github.com/FooIbar/EhViewer/actions/runs/7230886397 试下这个
> > 
> > *并没有解决这个问题，但能提供更清晰的日志
> 
> [logcat-2023-12-16-17-31-15-955.txt](https://github.com/FooIbar/EhViewer/files/13692085/logcat-2023-12-16-17-31-15-955.txt)
> 我先清除缓存，然后基本上是在历史记录里刷了刷，选点了两个我记得无法浏览的，点了两个我记得可以正常浏览的，又点了一个我记得无法浏览的gallery
> 
> EDIT: 草，日志里怎么有向 https://exhentai.org/mpv/ 路径的网络请求，我一普通用户哪里有 Multi-Page Viewer 的权限啊

唔，我具有Multi-Page Viewer的权限，但是遇到了和你相同的问题，无法在线浏览，加载一直在转圈

**Comment by pchu999** [comment]
CI 版本 [d9e5bb4](https://github.com/FooIbar/EhViewer/commit/d9e5bb43998eb91fd403e2dc68845d06565861fa) 确认解决了问题，thx

**Comment by UjuiUjuMandan** [comment]
为什么我没有遇到这个 bug ，我合并了个啥...

**Comment by FooIbar** [comment]
> > https://github.com/FooIbar/EhViewer/actions/runs/7230886397 试下这个
> > *并没有解决这个问题，但能提供更清晰的日志
> 
> 我先清除缓存，然后基本上是在历史记录里刷了刷，选点了两个我记得无法浏览的，点了两个我记得可以正常浏览的，又点了一个我记得无法浏览的gallery，日志： [logcat-2023-12-16-17-31-15-955.txt](https://github.com/FooIbar/EhViewer/files/13692085/logcat-2023-12-16-17-31-15-955.txt)
> 
> EDIT: 草，日志里怎么有向 https://exhentai.org/mpv/ 路径的网络请求，我一普通用户哪里有 Multi-Page Viewer 的权限啊

忘了说，会有 mpv 的请求是因为常规请求失败，所以尝试通过 mpv 获取 token
不过这里失败的原因是请求被取消，不应该继续尝试， d9e5bb4 也修了这个
