### ISSUE TITLE
阅读页快速滑动滑块导致下载延时过多累计

### ISSUE THREAD

**Issue by Pony-CW** [FooIbar/EhViewer#512]
### 复现步骤 / Step to reproduce

0.清楚缓存
1.打开画廊进行阅读
2.快速滑动滑块

### 预期行为 / Expected behaviour

正常转圈

### 实际行为 / Actual Behaviour

大量 Cancelled

https://github.com/FooIbar/EhViewer/assets/44076275/f841d307-ab51-4af9-a9a5-e0712e89dea3

### 应用日志 / App logs

[log-2023-12-17-00-50-33-905.zip](https://github.com/FooIbar/EhViewer/files/13693250/log-2023-12-17-00-50-33-905.zip)

### 备注 / Addition details

虽然此视频的 Http 引擎为 Cronet，但 Apache 5 仍能复现
甚至 Apache 5 引擎还有一瞬的 “获取 Token 失败” ？
并没有去测试是否能正常加载完毕
不知是否与 #508 有一定共同点
> 顺便，纯爱大法好

### 浏览站点 / Browsing site

https://e-hentai.org/g/2728257/0bc77ae0dd

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT Default OSS

### EhViewer CI 版本 / EhViewer CI Version

369904f

### Android 系统版本 / Android version

ColorOS 14 PGZ110_14.0.0.82(CN01) / Android 14

### 设备型号 / Device model

一加 Ace 竞速版 / OnePlus Ace Racing Edition / PGZ110

### SoC 型号 / Soc model

天玑 8100-MAX / Dimensity 8100-MAX

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
出现 Cancelled 是正常的，不过倒是有另一个问题

**Comment by VDostoyevskiy** [comment]
这块该把currentPage做成个flow然后debounce 500ms
