### ISSUE TITLE
下载至cifs documents provider挂载的文件夹时闪退

### ISSUE THREAD

**Issue by wtyrambo** [FooIbar/EhViewer#52]
### 复现步骤 / Step to reproduce

通过 https://github.com/wa2c/cifs-documents-provider 挂载的远程文件夹只能读取，无法下载文件

### 预期行为 / Expected behaviour

下载成功

### 实际行为 / Actual Behaviour

点击下载瞬间直接应用闪退

### 应用日志 / App logs

[logcat-2023-10-14-00-09-56-224.txt](https://github.com/FooIbar/EhViewer/files/12895534/logcat-2023-10-14-00-09-56-224.txt)

### 备注 / Addition details

由于平板容量较小，想将文件下载至NAS上而不是本地，用的这个软件 https://github.com/wa2c/cifs-documents-provider 通过samba方式挂载远程文件夹，在其他应用中使用正常，但是ehviewer中无法下载文件，是否是否能够修复？

### EhViewer 版本号 / EhViewer version code

1.8.9.7

### EhViewer CI 版本 / EhViewer CI Version

019b961

### Android 系统版本 / Android version

pixelexperience 13

### 设备型号 / Device model

小米平板6

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Mapaler** [comment]
![explorer_RcIMadprDm](https://github.com/FooIbar/EhViewer/assets/6565860/36543bde-7092-4c3d-a2e7-a531880ca51f)
新的手机不支持TF卡了，我目前用移动SSD来储存数据，连到手机上确实可以设定USB设备的文件夹。

但是这样手机就没法充电了，所以我想在电脑上用安卓模拟器来下载。
共享文件夹挂载到了`/mnt/windows/EhViewer`
![HD-Player_xJNJznzcMB](https://github.com/FooIbar/EhViewer/assets/6565860/3a229495-4626-4074-8e43-459aa88b8a9a)
但是选择下载路径的时候根本无法选择这个路径
![HD-Player_N3lJXLbDxw](https://github.com/FooIbar/EhViewer/assets/6565860/3827fa1c-b799-4982-98d8-b0e29c6eb0bb)

想用软连接链接过去
![HD-Player_pIuTLbNg8T](https://github.com/FooIbar/EhViewer/assets/6565860/aa94d853-7383-4ff8-9034-603b0bf0d852)
结果选择的时候无法选择
![HD-Player_OX3jAtBZ3U](https://github.com/FooIbar/EhViewer/assets/6565860/43ffdb9f-6930-40eb-b25d-bd7f3e8b0bd1)

导入数据库文件的时候倒是可以用Mix文件管理器选择，要是可以用这个就能选择那个文件夹了。
![HD-Player_Jn26HkyDMv](https://github.com/FooIbar/EhViewer/assets/6565860/ee59b318-7faa-42e6-997b-50923b56ddf0)
或者如果能手动输入路径，也可以用`file`协议直接输入文件夹地址

**Comment by FooIbar** [comment]
> 导入数据库文件的时候倒是可以用Mix文件管理器选择，要是可以用这个就能选择那个文件夹了，但是不知道为什么选择下载文件夹的时候这个选项会消失。

这是两个不同的 intent

**Comment by FooIbar** [comment]
今天看了一下这个，这是 [cifs-documents-provider](https://github.com/wa2c/cifs-documents-provider) 的实现的问题
查询一个不存在的 URI 的时候它会返回有效的结果，所以被认为是文件已存在而且不是目录
