### ISSUE TITLE
Snackbars should appear above FABs instead of in front of them

### ISSUE THREAD

**Issue by FooIbar** [FooIbar/EhViewer#524]
![Screenshot_20231219_135428](https://github.com/FooIbar/EhViewer/assets/118464521/1e395dbb-9543-47d8-be6b-d0db06703952)

**Comment by VDostoyevskiy** [comment]
IMO fabs should move up with animation when snackbar appears.
We need to address all LocalSnackbarState usage first

**Comment by FooIbar** [comment]
Well, https://m3.material.io/components/snackbar/guidelines#f762d356-69a1-402c-ab69-3621c23f91d2

**Comment by VDostoyevskiy** [comment]
> Well, https://m3.material.io/components/snackbar/guidelines#f762d356-69a1-402c-ab69-3621c23f91d2

But our FabLayout have 4 sub-fabs, it will be ridiculous

**Comment by FooIbar** [comment]
Most times it won't be expanded when a snackbar shows.
