### ISSUE TITLE
新版本不支持分类搜索

### ISSUE THREAD

**Issue by WorldlineChanger** [FooIbar/EhViewer#532]
### 复现步骤 / Step to reproduce

正常使用

### 预期行为 / Expected behaviour

1.9及之前版本支持按分类过滤

### 实际行为 / Actual Behaviour

分类搜索消失:
![Screenshot_2023-12-21-14-04-57-406_moe tarsin ehviewer-edit](https://github.com/FooIbar/EhViewer/assets/46261730/aaf51893-bb70-4d59-88f3-04dec09053df)

### 应用日志 / App logs

-

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0

### EhViewer CI 版本 / EhViewer CI Version

8aaad07

### Android 系统版本 / Android version

MIUI 14, Android 13

### 设备型号 / Device model

MIX 4

### SoC 型号 / Soc model

888 P

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
> ## [1.10.0] - 2023-12-14 [YANKED]
> 
> ### 重大变更
> 
> * 类别和高级搜索选项移至搜索栏下方

**Comment by WorldlineChanger** [comment]
我是沙贝
