### ISSUE TITLE
搜索建议中出现关键词相同的条目时崩溃

### ISSUE THREAD

**Issue by asoulist** [FooIbar/EhViewer#533]
### 复现步骤 / Step to reproduce

首页输入框内使用带冒号标签的单个单词tag搜索，如果不带$结尾必定崩溃，包括历史记录快捷条目

### 预期行为 / Expected behaviour

正常加载对应tag的搜索结果

### 实际行为 / Actual Behaviour

如：f:robot$点击搜索正常，f:robot点击后崩溃，不带f:开头的robot直接搜索也正常
经试验，a: g:等其他种类开头的类别标签，只要是单个单词的，不使用$结尾必定会崩溃闪退
但是，f:"monster girl$"和f:"monster girl"这种多个单词的tag都可以正常搜索

### 应用日志 / App logs

[log-2023-12-22-02-16-39-984.zip](https://github.com/FooIbar/EhViewer/files/13745065/log-2023-12-22-02-16-39-984.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

EhViewer-1.10.1-default-gms-arm64-v8a(7008209)

### EhViewer CI 版本 / EhViewer CI Version

非ci版本, 稳定版7008209

### Android 系统版本 / Android version

Android 12, myui S1RN32.55-16-2

### 设备型号 / Device model

motorola edgeˢ (XT2125-4)

### SoC 型号 / Soc model

Snapdragon 870, SM8250(KONA)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [x] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by asoulist** [comment]
补充：覆盖安装了1.11.0-snapshot-gms CI版本f74c778，问题依旧存在，可以稳定触发

**Comment by FooIbar** [comment]
其实是搜索历史里有跟 tag 数据库里完全一样的条目才会崩溃

**Comment by jackslate111** [comment]
I have the same issue, tag search crashes the app. Is this actually resolved? My version says it's 51b58bb.

**Comment by FooIbar** [comment]
> I have the same issue, tag search crashes the app. Is this actually resolved? My version says it's [51b58bb](https://github.com/FooIbar/EhViewer/commit/51b58bb7973cae7510a879aa7b2e744d6432bd51).

Do not just say "I have the same issue", open a new issue and upload logs.

**Comment by jackslate111** [comment]
I wanted to avoid opening new issues if it is something that I did wrong (wrong version of app, didn't delete the cache, etc.), especially since the issue was already opened and closed, doubly so since I don't see anyone else mention this issue. I guess I'll open a new one then.

**Comment by FooIbar** [comment]
> I wanted to avoid opening new issues if it is something that I did wrong (wrong version of app, didn't delete the cache, etc.), especially since the issue was already opened and closed, doubly so since I don't see anyone else mention this issue. I guess I'll open a new one then.

Well, it's generally more helpful to start by providing logs, especially for a bug causing crashes.
Stack traces in logs make diagnosis much easier.
