### ISSUE TITLE
关于Http引擎到底是怎么选择的？

### ISSUE THREAD

**Issue by yinzhefuyun** [FooIbar/EhViewer#540]
### 复现步骤 / Step to reproduce

手机是晓龙800（32位的CPU）系统是安卓11，用GMS的apk，在http引擎只能选OkHttp，这是为什么？

### 预期行为 / Expected behaviour

由于 Apache HttpClient 5 在 Android 10 以下无法使用，后备 HTTP 引擎恢复为 OkHttp https://github.com/FooIbar/EhViewer/issues/514
看你的描述我安卓11应该可以打开吧

### 实际行为 / Actual Behaviour

只能用OKHttp

### 应用日志 / App logs

没有日志

### 浏览站点 / Browsing site

站点无关

### EhViewer 版本号 / EhViewer version code

1.11.0-gms

### EhViewer CI 版本 / EhViewer CI Version

549387a

### Android 系统版本 / Android version

crdroid7.37

### 设备型号 / Device model

三星note3

### SoC 型号 / Soc model

晓龙800

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Apache 5 已经被 OkHttp 取代了，不支持 Cronet 就只能选 OkHttp

**Comment by yinzhefuyun** [comment]
> Apache 5 已经被 OkHttp 取代了，不支持 Cronet 就只能选 OkHttp

我的意思是releases中写的Apache HttpClient 5 在 Android 10 以下无法使用，后备 HTTP 引擎恢复为 OkHttp 是不是描述不正确，毕竟我的设备是安卓11也无法打开Cronet

**Comment by FooIbar** [comment]
你怎么还在纠结 Apache 5，不支持 Cronet 的设备就算是 Android 14 也开不了

**Comment by FooIbar** [comment]
1.10.0 在不支持 Cronet 的设备上会使用 Apache 5，但是后来发现 Android 10 以下用不了 Apache 5 所以换回了 OkHttp，很难理解？
