### ISSUE TITLE
Crash when typing in tag that is already in history

### ISSUE THREAD

**Issue by jackslate111** [FooIbar/EhViewer#555]
### 复现步骤 / Step to reproduce

Type in the search a tag search, eg. f:bondage, press search.
Press on the search bar again, the app crashes.
Reopen the app, start typing in "f:bon", the app crashes.

### 预期行为 / Expected behaviour

Should not crash.

### 实际行为 / Actual Behaviour

Crashes.

### 应用日志 / App logs

[log-2023-12-28-22-23-54-279.zip](https://github.com/FooIbar/EhViewer/files/13789553/log-2023-12-28-22-23-54-279.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.0

### EhViewer CI 版本 / EhViewer CI Version

3ca3ab7

### Android 系统版本 / Android version

OxygenOS 13.1

### 设备型号 / Device model

Oneplus 9 pro

### SoC 型号 / Soc model

Snapdragon 888

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Ah, I see.
Basically it's fixed in ZH but not in other languages because they don't have tag translations.
I'll push another patch, thank you for reporting.
