### ISSUE TITLE
剪贴板读取bug

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#566]
### 复现步骤 / Step to reproduce

1.打开EhViewer
2.进入某画廊后,点击分享,复制链接
3.退出EhViewer,重新启动

### 预期行为 / Expected behaviour

在几秒钟后自动消失

### 实际行为 / Actual Behaviour

1.在画廊界面,点击分享复制链接后,即刻就会出现"剪贴板里有画廊链接"的字样(原地TP);
2.在外部复制的画廊链接,不点就消除不掉那个弹窗,无论到什么界面,哪怕重新开关EhViewer;
![image](https://github.com/FooIbar/EhViewer/assets/88327304/b5f184bb-8eb8-47bb-96ff-318fa688824e)

3.有时候会出现得连续点按"查看"才能消除弹窗;

https://github.com/FooIbar/EhViewer/assets/88327304/41b8ccef-ec8b-43df-b4a2-91e0a3f1afc6

### 应用日志 / App logs

[log-2023-12-30-21-30-45-783.zip](https://github.com/FooIbar/EhViewer/files/13798162/log-2023-12-30-21-30-45-783.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

42e0b0a

### Android 系统版本 / Android version

HarmonyOS 4.0.0.125

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
![屏幕截图 2023-12-30 221132](https://github.com/FooIbar/EhViewer/assets/118464521/ce6eaa47-4cd7-4f11-9d48-20d2db511255)
这里应该是有一个关闭按钮的，不知道为什么没显示，你可以点下试试

**Comment by tmby** [comment]
> ![屏幕截图 2023-12-30 221132](https://github.com/FooIbar/EhViewer/assets/118464521/ce6eaa47-4cd7-4f11-9d48-20d2db511255)
> 这里应该是有一个关闭按钮的，不知道为什么没显示，你可以点下试试

看到了
![Screenshot_20231230_222018_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/38c39318-fda7-4f00-8dc6-e1fbb502d76a)

![Screenshot_20231230_222007_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/2ccb475d-2141-4fb3-9ab2-722a5339c4ec)

浅色和纯黑能看到，然后开纯黑再关也能看到（重新打开eh失效）

**Comment by FooIbar** [comment]
Regression of https://android-review.googlesource.com/c/platform/frameworks/support/+/2881006

**Comment by FooIbar** [comment]
顺便一说，在几秒钟后自动消失不是预期行为
M3 规范就是如果有操作的话必须要用户关闭
https://m3.material.io/components/snackbar/guidelines#4847ca62-bc91-4259-8402-c2247e39361e

**Comment by tmby** [comment]
> 顺便一说，在几秒钟后自动消失不是预期行为
> M3 规范就是如果有操作的话必须要用户关闭
> https://m3.material.io/components/snackbar/guidelines#4847ca62-bc91-4259-8402-c2247e39361e

理解了，但是还有一个问题

>1.在画廊界面,点击分享复制链接后,即刻就会出现"剪贴板里有画廊链接"的字样(原地TP);

https://github.com/FooIbar/EhViewer/assets/88327304/968beb64-8d74-4003-b8d3-e6e99e64594b

这种情况还出现这个弹窗，不是很奇怪吗？真就原地tp，最起码等下次启动eh再出现啊。
