### ISSUE TITLE
1.10.2 界面切换动画导致 UI 错误

### ISSUE THREAD

**Issue by Cirn09** [FooIbar/EhViewer#578]
### 复现步骤 / Step to reproduce

设备是电子书（boox tab10c）
1.10.2 新加的动画会导致界面切换后 UI 会整体偏左或偏右或直接白屏
简易规避：给动画加个开关

### 预期行为 / Expected behaviour

1.10.1 没有 UI 问题

### 实际行为 / Actual Behaviour

是全屏截图，状态栏做参照物能看出来 UI 整体右偏了
![image](https://github.com/FooIbar/EhViewer/assets/25722111/c3487f14-f3ff-4207-a178-bc77749c5296)

### 应用日志 / App logs

[log-2024-01-01-02-38-25-838[1].zip](https://github.com/FooIbar/EhViewer/files/13801998/log-2024-01-01-02-38-25-838.1.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

37660ef

### Android 系统版本 / Android version

11

### 设备型号 / Device model

Boox Tab10C

### SoC 型号 / Soc model

不知道

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by jerycho007** [comment]
To add to this it was pull request #549 that broke it like this. Have the same issue on Realme GT 2 Pro

**Comment by Fan-Apple** [comment]
手机端在最近更新后遇到了同样的问题，有时候甚至直接黑掉。![Screenshot_20240104_134337_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/60562348/4665ed62-ac87-42f1-8a20-a880e0bb52fd)

**Comment by Omagician** [comment]
Wow took me a min to find this but I am also having the same problem just updated mine and it was working fine before hand. But now it's off centered.

**Comment by FooIbar** [comment]
@Cirn09 @Fan-Apple 试下最新 CI 045c6ab
@jerycho007 @Omagician Try latest CI 045c6ab

**Comment by jerycho007** [comment]
> @Cirn09 @Fan-Apple 试下最新 CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb) @jerycho007 @Omagician Try latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb)

Yeah it works fine now with the predictive back setting disabled. Cheers!

**Comment by Omagician** [comment]
> > @Cirn09 @Fan-AppleTry the latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb) @jerycho007 @Omagician Try latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb)
> 
> Yeah it works fine now with the predictive back setting disabled. Cheers!

How do I go about disabling this setting.

**Comment by FooIbar** [comment]
> > > @Cirn09 @Fan-AppleTry the latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb) @jerycho007 @Omagician Try latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb)
> > 
> > 
> > Yeah it works fine now with the predictive back setting disabled. Cheers!
> 
> How do I go about disabling this setting.

It's disabled by default.
Just update to latest CI build in Settings - About.

**Comment by Omagician** [comment]
> > > > @Cirn09 @Fan-AppleTry the latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb) @jerycho007 @Omagician Try latest CI [045c6ab](https://github.com/FooIbar/EhViewer/commit/045c6abe406ceefd3672e172de2d1f90040113bb)
> > > 
> > > 
> > > Yeah it works fine now with the predictive back setting disabled. Cheers!
> > 
> > 
> > How do I go about disabling this setting.
> 
> It's disabled by default. Just update to latest CI build in Settings - About.

Wow thanks didn't even know about that. Appreciate all the work.

**Comment by Cirn09** [comment]
更新 1.10.3 后问题消失
