### ISSUE TITLE
1.10.2 有的画廊的缩略图无法显示

### ISSUE THREAD

**Issue by liuxuming3303** [FooIbar/EhViewer#585]
### 复现步骤 / Step to reproduce

https://exhentai.org/g/2784017/2059e8017d/
在所有画廊中唯独它无法加载缩略图和封面，尝试点击http引擎切换按钮、强制使用e-hentai缩略图/API服务器、清除图片缓存、重开、保数据重装应用均无效，大图加载没问题，其他更新到最新版本群友打开能正常显示。

### 预期行为 / Expected behaviour

应该正常显示缩略图

### 实际行为 / Actual Behaviour

https://files.catbox.moe/f48yri.mp4

### 应用日志 / App logs

[log-2024-01-01-23-41-54-946.zip](https://github.com/FooIbar/EhViewer/files/13805212/log-2024-01-01-23-41-54-946.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2-oss-arm64-v8a

### EhViewer CI 版本 / EhViewer CI Version

37660ef

### Android 系统版本 / Android version

crDroidOS 9.8 Android 13

### 设备型号 / Device model

Redmi Note 7 Pro

### SoC 型号 / Soc model

Snapdragon 675

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by yinzhefuyun** [comment]
同发现这个问题，好像是一些比较旧的画廊会

**Comment by yinzhefuyun** [comment]
最新的CI好像修复了

**Comment by moleoxa** [comment]
具体来说，我是收藏夹里的封面全部不显示。

**Comment by yinzhefuyun** [comment]
> 具体来说，我是收藏夹里的封面全部不显示。

最新的CI版本依旧修复了，可以在软件设置-关于-勾选使用*****CI***跟新就好了

**Comment by liuxuming3303** [comment]
CI版的确修复了，可能等正式版出了再关吧
