### ISSUE TITLE
点开本子的一瞬间侧滑返回，会卡在本子列表页面，上划下划都没有反应，怀疑是预见式动画的bug

### ISSUE THREAD

**Issue by LostMyMind** [FooIbar/EhViewer#596]
### 复现步骤 / Step to reproduce

1.打开软件
2.在主页或者搜索结果里点开本子
3.点开本子的一瞬间进行侧划返回

### 预期行为 / Expected behaviour

正常回到主页或者搜索结果列表，并且可以正常操作。

### 实际行为 / Actual Behaviour

虽然回到了主页，但是似乎应用还以为是在本子页面，盲点本子评分位置可以给本子评分，盲点评论区位置可以进入评论区，盲点略缩图位置可以进到看图页面。
恢复也很简单，盲点左上角的退出按钮就可以。

### 应用日志 / App logs

[log-2024-01-03-20-36-12-173.zip](https://github.com/FooIbar/EhViewer/files/13819004/log-2024-01-03-20-36-12-173.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

c30c1b2

### Android 系统版本 / Android version

HyperOS1,安卓14

### 设备型号 / Device model

小米14pro

### SoC 型号 / Soc model

骁龙8gen3

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by LzNOHentai** [comment]
之前改过这些动画后确实经常出现一些奇奇怪怪的bug

**Comment by yinzhefuyun** [comment]
就是【返回预览】我还想要不加个开关吧，这个功能我用的现在非常不习惯

**Comment by GhostArtyom** [comment]
同样复现这个bug 预见式动画的开关在1.10.2版本没有了 而且默认打开了预见式返回

**Comment by FooIbar** [comment]
045c6ab
