### ISSUE TITLE
百度输入法长按退格只删除一个字符而不是连续删除

### ISSUE THREAD

**Issue by by123456by** [FooIbar/EhViewer#606]
### 复现步骤 / Step to reproduce

在搜索栏输入任意数量的字符，然后长按输入法上的退格删除，删除一个字符后停止

### 预期行为 / Expected behaviour

长按退格删除时应该连续删除字符直到松开按键

### 实际行为 / Actual Behaviour

只删除一个字符

### 应用日志 / App logs

[log-2024-01-06-12-18-17-415.zip](https://github.com/FooIbar/EhViewer/files/13848365/log-2024-01-06-12-18-17-415.zip)

### 备注 / Addition details

百度输入法版本12.1.2.13
其他app中从未出现过此问题（包括其他的EhViewer发行版）

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

37660ef

### Android 系统版本 / Android version

HyperOS1.0.3.0/Android14

### 设备型号 / Device model

Redmi K60

### SoC 型号 / Soc model

高通骁龙8+ Gen1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
@FooIbar 为什么关了呢？这和其他 Android 应用行为很不同啊。


https://github.com/FooIbar/EhViewer/assets/125150101/689a3175-b79e-4b4e-8291-03c12ce574d6

**Comment by by123456by** [comment]
> @FooIbar 为什么关了呢？这和其他 Android 应用行为很不同啊。
> 
>  VID_20240108_011903.mp4

而且其他的EhViewer版本都没有这个问题 @FooIbar

**Comment by by123456by** [comment]
> @FooIbar 为什么关了呢？这和其他 Android 应用行为很不同啊。
> 
>  VID_20240108_011903.mp4

你的输入法看起来不像是百度输入法，是其他输入法也会有这个问题吗@UjuiUjuMandan

**Comment by UjuiUjuMandan** [comment]
你为什么要强调百度输入法，这和什么输入法有关吗？另外这玩意本来就是流氓软件。

**Comment by Pony-CW** [comment]
都说了的话，那我也说一句
我是 [fcitx-android 小企鹅输入法5](https://github.com/fcitx5-android/fcitx5-android) 输入法用户，我琢磨了下，是不断改变的焦点导致的中断
如果我关闭“焦点改变时切换回键盘”选项，长按删除将变得正常

**Comment by by123456by** [comment]
> 你为什么要强调百度输入法，这和什么输入法有关吗？另外这玩意本来就是流氓软件。

@UjuiUjuMandan 因为我使用手机自带输入法测试后发现自带的输入法没这个问题

**Comment by UjuiUjuMandan** [comment]
原来如此，那我就是 Gboard 长按连续删除有问题、Android Keyboard (AOSP) 没问题。

**Comment by FooIbar** [comment]
https://issuetracker.google.com/issues/324930020
