### ISSUE TITLE
[BUG] 通过 Cookie 登录失败

### ISSUE THREAD

**Issue by devioa** [FooIbar/EhViewer#626]
### 复现步骤 / Step to reproduce

全新安装，通过 Cookie 登录

### 预期行为 / Expected behaviour

登录成功

### 实际行为 / Actual Behaviour

确认输入的 Cookie 字段都是正确的，提示登录失败`Input length = 1`
![1704982446751](https://github.com/FooIbar/EhViewer/assets/38558065/49d60c00-63f0-47fb-a994-4ad628e40734)

### 应用日志 / App logs

n/a

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2-gms

### EhViewer CI 版本 / EhViewer CI Version

37660ef

### Android 系统版本 / Android version

HyperOS 1.0.9 Android 14

### 设备型号 / Device model

Redmi K70Pro

### SoC 型号 / Soc model

骁龙 8Gen3

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by devioa** [comment]
我安装`1.8.11`版本通过 Cookie 登录没有问题，然后再更新到`1.10.2`正常使用，现在用的最新的CI版本`1.11.0`

**Comment by FooIbar** [comment]
报这个错八成是你用户名是乱码

**Comment by devioa** [comment]
并不是，我 eh 的用户名也是 devioa

**Comment by FooIbar** [comment]
日志

**Comment by devioa** [comment]
明天吧，主要是我现在通过在旧版本成功登录然后再升级最新版本的方式已经正常使用上了

**Comment by devioa** [comment]
我今天卸载了然后全新安装`1.10.2-gms`，再用 Cookie 登录居然没问题了
诡异，太诡异了

**Comment by FooIbar** [comment]
> 我今天卸载了然后全新安装`1.10.2-gms`，再用 Cookie 登录居然没问题了 诡异，太诡异了

那可能是你那天登录的时候刚好有个用户名是乱码的人在线
