### ISSUE TITLE
下载页面的页面刷新机制有问题

### ISSUE THREAD

**Issue by cherinyy** [FooIbar/EhViewer#629]
### 复现步骤 / Step to reproduce

https://github.com/FooIbar/EhViewer/assets/9050713/75cd3fd5-f510-4cb2-9f1c-9691ee0fc164

导致的问题一个是像视频所示的那样，在我完成排序后，滑到下方，随意点击一个画廊，再返回下载页面，原本应当位于上方的画廊被移到下方，并且是乱序的。

还一个是在我点击“全部停止”按钮后，当前显示的“等待中”画廊不会变成“未启动”，仍然是“等待中”。

### 预期行为 / Expected behaviour

无异常排序

### 实际行为 / Actual Behaviour

异常排序

### 应用日志 / App logs

[log-2024-01-12-18-16-03-911.zip](https://github.com/FooIbar/EhViewer/files/13917783/log-2024-01-12-18-16-03-911.zip)

### 备注 / Addition details

有一个条件可能是下载的画廊需要足够多，在另一台手机上使用最新 CI 版本测试时遭遇了“等待中”画廊不会变成“未启动”，暂时没有遇到乱序问题。

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.2

### EhViewer CI 版本 / EhViewer CI Version

37660ef

### Android 系统版本 / Android version

ColorOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
看了半天才明白乱序在哪，两本“角砂糖”中间多出来一个 DOZA 。

**Comment by cherinyy** [comment]
> 看了半天才明白乱序在哪：两本“角砂糖”中间多出来一个 DOZA 。

应该说DOZA中多了几本“角砂糖”，因为“角砂糖”是从上方被挪下来的。

**Comment by qiburu** [comment]
我也会有类似的情况出现，有的时候列表会乱序，原本是12345这样排序的，在重新打开应用之后就有概率会变成14235这样，每次下了新本子之后都容易发生这种情况，我应用里总共是一千本左右的数量，不知道是不是过多的原因
