### ISSUE TITLE
响应正文含有无效 UTF-8 字符导致解码失败

### ISSUE THREAD

**Issue by cherinyy** [FooIbar/EhViewer#643]
### 复现步骤 / Step to reproduce

访问特定画廊 https://e-hentai.org/g/1241525/7eb4b2e1ea

### 预期行为 / Expected behaviour

正常显示

### 实际行为 / Actual Behaviour

报错“Input length = 1”

![Screenshot_2024-01-19-17-10-46-79_f2f1746601bf3b868d00d5efaf12e601](https://github.com/FooIbar/EhViewer/assets/9050713/0f421383-27d3-4c74-908b-8570bdf02e37)

### 应用日志 / App logs

[log-2024-01-19-17-10-52-341.zip](https://github.com/FooIbar/EhViewer/files/13986915/log-2024-01-19-17-10-52-341.zip)

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

a37cc59

### Android 系统版本 / Android version

ColorOS 12.1, Android 12

### 设备型号 / Device model

OnePlus 7 Pro

### SoC 型号 / Soc model

Snapdragon 855

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
评论里有个人名字是乱码
![屏幕截图 2024-01-19 175945](https://github.com/FooIbar/EhViewer/assets/118464521/18364487-c601-460c-a87f-deb8d3d9a002)

**Comment by cherinyy** [comment]
😢所以这问题咱们能否兼容一下，能不能看到画廊信息无所谓，主要是会导致无法阅读和下载。
