### ISSUE TITLE
关闭后立即开启“预见式返回导航动画”导致应用崩溃

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#644]
### 复现步骤 / Step to reproduce

1. 进入设置 - 高级。
2. 确保“预见式返回导航动画”打开。
3. 关闭该选项。
4. 打开该选项。

### 预期行为 / Expected behaviour

开关开关。

### 实际行为 / Actual Behaviour

应用崩溃。

### 应用日志 / App logs

[crash-2024-01-19-22-57-01-187.log](https://github.com/FooIbar/EhViewer/files/13990754/crash-2024-01-19-22-57-01-187.log)

[logcat-2024-01-19-22-57-08-134.txt](https://github.com/FooIbar/EhViewer/files/13990753/logcat-2024-01-19-22-57-08-134.txt)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

a37cc59

### Android 系统版本 / Android version

CalyxOS 5.2.0, Android 14

### 设备型号 / Device model

Pixel 5

### SoC 型号 / Soc model

Snapdragon 765G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by cherinyy** [comment]
还有一个可能与此有关的 BUG，在启用后，返回主页，打开下载页面。这时候点击下载页面的画廊，有几率点击到主页的画廊。
不过不是每次都复现，所以我不知道是不是还有什么特定操作。

**Comment by UjuiUjuMandan** [comment]
这哪里有关了？😅
