### ISSUE TITLE
新建下载任务之后若下载任务并未真正建立（即立刻停止）会导致所有漫步都无法阅读

### ISSUE THREAD

**Issue by XiaoMiao458331** [FooIbar/EhViewer#649]
### 复现步骤 / Step to reproduce

更新下载列表可能会导致长时间无法打开已下载漫画。
下载新漫画后打开下载列表的卡顿、闪退问题在新版本已经被改善，但是依然存在新建任务之后无法打开漫画的问题。解决方法是开始下载，等待软件下载几部漫画之后才能正常打开漫画。
除此之外，删除漫画也可能会进入这种状态，也可以通过新建下载任务或者在开屏状态下等待一段时间的方式解决。

https://github.com/FooIbar/EhViewer/assets/122302938/ee831dbe-3ab9-4b55-b21e-36bd5dd0b56b

### 预期行为 / Expected behaviour

正常情况下新建下载任务或者删除漫画不应该需要那么长的等待时间。

### 实际行为 / Actual Behaviour

下载新漫画后打开下载列表的卡顿、闪退问题在新版本已经被改善，但是依然存在新建任务之后无法打开漫画的问题。解决方法是开始下载，等待软件下载几部漫画之后才能正常打开漫画。
[除此之外，删除漫画也可能会进入这种状态，也可以通过新建下载任务或者在开屏状态下等待一段时间的方式解

https://github.com/FooIbar/EhViewer/assets/122302938/918de857-7477-4f37-ab55-a625eb7af369

决。

### 应用日志 / App logs

[log-2024-01-21-14-42-48-124_024625.zip](https://github.com/FooIbar/EhViewer/files/14000393/log-2024-01-21-14-42-48-124_024625.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.3

### EhViewer CI 版本 / EhViewer CI Version

163ade5

### Android 系统版本 / Android version

zui 15 15.0361

### 设备型号 / Device model

y700 一代

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
非此仓库版本
