### ISSUE TITLE
無法從搜藏下載漫畫

### ISSUE THREAD

**Issue by newbiegituserj** [FooIbar/EhViewer#650]
### 复现步骤 / Step to reproduce

1. Go to favourite
2. Tap and hold one comic book.
3. The selected comic book has the "check mark ✓"
4. Tap the "down arrow ↓" to download

### 预期行为 / Expected behaviour

1. Go to favourite
2. Tap and hold one comic book.
3. The selected comic book has the "check mark ✓"
4. Tap the "down arrow ↓" to download
5. The comic book is being downloaded and can be found in the downloads tab

### 实际行为 / Actual Behaviour

1. Go to favourite
2. Tap and hold one comic book.
3. The selected comic book has the "check mark ✓"
4. Tap the "down arrow ↓" to download
5. The comic book is not downloaded and nothing happens

### 应用日志 / App logs

None

### 浏览站点 / Browsing site

e-hentai

### EhViewer 版本号 / EhViewer version code

1.10.3-gms

### EhViewer CI 版本 / EhViewer CI Version

1d9008a

### Android 系统版本 / Android version

Android 14

### 设备型号 / Device model

Pixel 5

### SoC 型号 / Soc model

none

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现

**Comment by FooIbar** [comment]
因缺少信息关闭
