### ISSUE TITLE
从主页进入画廊时，点击上传者tag无反应

### ISSUE THREAD

**Issue by ZerOri** [FooIbar/EhViewer#653]
### 复现步骤 / Step to reproduce

1.启动app
2.进入主页/订阅/热门/下载，点击任意作品进入画廊
3.点击「上传者/屏蔽上传者」tag无反应

### 预期行为 / Expected behaviour

点击上传者tag进入筛选界面

### 实际行为 / Actual Behaviour

点击上传者tag无反应

### 应用日志 / App logs

[log-2024-01-23-21-02-19-074.zip](https://github.com/FooIbar/EhViewer/files/14024328/log-2024-01-23-21-02-19-074.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.10.3

### EhViewer CI 版本 / EhViewer CI Version

87b1160

### Android 系统版本 / Android version

MIUI14,android 13

### 设备型号 / Device model

红米k40

### SoC 型号 / Soc model

骁龙870

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
无法复现

**Comment by ZerOri** [comment]
> 无法复现

就是画廊封面旁边的「上传者」按钮，「画廊分类」按钮可以正常点击

**Comment by FooIbar** [comment]
你的网页设置里的 display mode 是什么

**Comment by ZerOri** [comment]
原来是缩略图模式下的bug

**Comment by FooIbar** [comment]
![image](https://github.com/FooIbar/EhViewer/assets/118464521/67c6d622-f336-40f7-8807-9e4e74b42f1e)
