### ISSUE TITLE
提供将下载结果保存为CBZ格式压缩包的选项以方便本地漫画服务器管理

### ISSUE THREAD

**Issue by BEIVSIQIN** [FooIbar/EhViewer#660]
### 复现步骤 / Step to reproduce

目前常用的本地漫画管理器Komga，LANraragi，tachiyomi都支持读取CBZ格式的文件，希望ehviewer提供将下载结果保存为CBZ格式压缩包的选项以方便本地漫画服务器进行管理。

### 预期行为 / Expected behaviour

同上

### 实际行为 / Actual Behaviour

同上

### 应用日志 / App logs

同上

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.3

### EhViewer CI 版本 / EhViewer CI Version

1.10.3

### Android 系统版本 / Android version

Android

### 设备型号 / Device model

Android

### SoC 型号 / Soc model

Android

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by BEIVSIQIN** [comment]
目前似乎需要在下载完成后，再手动进行归档导出cbz，是否能在设置中添加按钮，下载完后自动保存为cbz？

**Comment by FooIbar** [comment]
> 目前似乎需要在下载完成后，再手动进行归档导出cbz，是否能在设置中添加按钮，下载完后自动保存为cbz？

这是为什么这个 issue 还没关

**Comment by FooIbar** [comment]
d0fbb35 添加了对应设置项
