### ISSUE TITLE
大图无法显示

### ISSUE THREAD

**Issue by yinzhefuyun** [FooIbar/EhViewer#68]
### 复现步骤 / Step to reproduce

打开应用点击画廊，点击缩略图，然后黑黑一片

### 预期行为 / Expected behaviour

显示图片瀑布流

### 实际行为 / Actual Behaviour

黑黑一片连菜单都出不来

### 应用日志 / App logs

--------- beginning of system
10-19 21:16:08.345  7144 18001 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-19 21:16:08.345  7144 18001 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:16:14.721  7144 18001 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:16:33.458  7144 18001 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:16:35.974 18710 18858 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-19 21:16:35.976 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:16:42.895 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:16:48.346 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:32:43.093 18710 18858 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-19 21:32:43.093 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:32:44.344 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:32:46.599 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-19 21:32:48.047 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:58:30.605 18710 18858 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-20 00:58:30.605 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:58:31.779 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:58:50.399 18710 18858 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:58:55.995 32692   481 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-20 00:58:55.995 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:03.723 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:06.952 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:08.007 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:08.948 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:10.883 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:12.123 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:15.510 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:21.202 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 00:59:25.213 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
--------- beginning of main
10-20 01:00:27.077 32692 32692 D DecorView[]: onWindowFocusChanged hasWindowFocus false
10-20 01:10:22.448 32692 32745 D AppScoutStateMachine: 32692-ScoutStateMachinecreated
10-20 01:10:22.449 32692   481 I ContentCatcher_TaplusBlackListHelper:  mActivities isEmpty
10-20 01:10:22.449 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList size: 10 package is moe.tarsin.ehviewer isInTaplusWhiteList: true
10-20 01:10:22.782 32692 32692 D DecorView[]: onWindowFocusChanged hasWindowFocus true
10-20 01:10:22.783 32692 32692 I HandWritingStubImpl: refreshLastKeyboardType: 1
10-20 01:10:22.783 32692 32692 I HandWritingStubImpl: getCurrentKeyboardType: 1
10-20 01:10:22.784 32692 32692 I HandWritingStubImpl: isKeyboardTypeChanged: false
10-20 01:10:26.334 32692 32692 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
10-20 01:10:26.334 32692 32692 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
10-20 01:10:26.336 32692   481 I ContentCatcher_TaplusBlackListHelper:  blackList siz

### EhViewer 版本号 / EhViewer version code

1.8.10.0

### EhViewer CI 版本 / EhViewer CI Version

02baa79

### Android 系统版本 / Android version

MIUI14安卓13/crdroid7.35安卓11

### 设备型号 / Device model

红米K50U/三星note3

### SoC 型号 / Soc model

8+1/800

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你自己网络的问题，可以尝试开启 强制使用 e-hentai 缩略图服务器

**Comment by yinzhefuyun** [comment]
> 你自己网络的问题，可以尝试开启 强制使用 e-hentai 缩略图服务器

不是网络问题，因为电脑可以看而且1.8.9.7-gms也可以看，不是缩略图出不来，是全屏的大图出不来，上周的CI好像还可以看，这种真的CI和昨天的正式版都不能看，打开全屏大图的时候感觉是什么崩溃了一样，双击屏幕中间没有菜单，长按屏幕没有刷新和分享，连打开时候是loading装圈圈动画都没有，就是黑黑一片，有空我2分法看下哪个CI后出问题

**Comment by FooIbar** [comment]
> > 你自己网络的问题，可以尝试开启 强制使用 e-hentai 缩略图服务器
> 
> 不是网络问题，因为电脑可以看而且1.8.9.7-gms也可以看，不是缩略图出不来，是全屏的大图出不来，上周的CI好像还可以看，这种真的CI和昨天的正式版都不能看，打开全屏大图的时候感觉是什么崩溃了一样，双击屏幕中间没有菜单，长按屏幕没有刷新和分享，连打开时候是loading装圈圈动画都没有，就是黑黑一片，有空我2分法看下哪个CI后出问题

这种一般是加载元数据失败了

**Comment by FooIbar** [comment]
不用试了，我知道是什么问题了
