### ISSUE TITLE
无法通过cooike登录

### ISSUE THREAD

**Issue by X012C** [FooIbar/EhViewer#692]
### 复现步骤 / Step to reproduce

1、安装到最新开发版本，尝试重新登陆发现无法使用cooike登录，不知道是新版本移除掉了这个功能还是原本位置UI在平板尺寸下被挤占了。
2、切换到原本的发布版，尝试用cooike登录失败，使用密码登录成功，但是cooike的igneous提示出错。
3、cooike已经在网页版EX登录过了。
附：最近几个开发版在小米平板上报毒。

### 预期行为 / Expected behaviour

应该正常登录。

### 实际行为 / Actual Behaviour

已经卸载了

### 应用日志 / App logs

已经卸载了

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.3-gms

### EhViewer CI 版本 / EhViewer CI Version

1d9008a

### Android 系统版本 / Android version

xiaomihyperOS

### 设备型号 / Device model

xiaomipad6

### SoC 型号 / Soc model

8+

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Pony-CW** [comment]
#669

**Comment by FooIbar** [comment]
Cookie 登录已移除
