### ISSUE TITLE
Crash on navigate to new version

### ISSUE THREAD

**Issue by VDostoyevskiy** [FooIbar/EhViewer#704]
### 复现步骤 / Step to reproduce

Open https://exhentai.org/g/2822625/8841fc11ae
Click new versions, select first one.

### 预期行为 / Expected behaviour

N/A

### 实际行为 / Actual Behaviour

N/A

### 应用日志 / App logs

https://bin.kv2.dev/~65c6356e5de7ed6bfdbd42d1

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

3ef45ba

### Android 系统版本 / Android version

UQ1A.240105.004

### 设备型号 / Device model

Redmi K30 5G

### SoC 型号 / Soc model

sm7250

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Oops, it's exact #310.
Should've commented back then.
