### ISSUE TITLE
直接导出ComicInfo.xml

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#711]
### 复现步骤 / Step to reproduce

Mihon（原名Tachiyomi）的本地图源支持读取ComicInfo.xml给本地压缩包提供画廊信息。

在 #660 中，导出的CBZ文件内和下载的画廊内都有ComicInfo.xml这个文件，含有画廊的元信息。

能否不需要下载画廊，可以直接导出ComicInfo.xml，用以管理归档下载的zip文件。

### 预期行为 / Expected behaviour

.

### 实际行为 / Actual Behaviour

.

### 应用日志 / App logs

.

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

b26cba8

### Android 系统版本 / Android version

HarmonyOS 4.0.0.128

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
ComicInfo.xml 不是下完了才生成的，而是开始下载就会生成
作为一个临时的解决方案可以点下载之后就暂停

**Comment by tmby** [comment]
导出的ComicInfo.xml在哪个位置？
下载归档是用 #79 的下载器下载。
没有在归档文件同目录，EhViewer data目录里找到ComicInfo.xml文件。

**Comment by FooIbar** [comment]
EhViewer 下载目录画廊文件夹下

**Comment by tmby** [comment]
> EhViewer 下载目录画廊文件夹下

设置中已开启```
压缩包元数据
```
设置中下载目录为默认的`storage/emulated/0/Android/data/moe.tarsin.ehviewer/files/download`
在该目录下未发现ComicInfo.xml文件

https://github.com/FooIbar/EhViewer/assets/88327304/cdc0b43c-ee01-4ac9-a641-6fdc9d03a117

![Screenshot_20240211_225910_ru zdevs zarchiver pro](https://github.com/FooIbar/EhViewer/assets/88327304/da8b3f7b-8c85-4411-a795-f929392fbf5a)
![Screenshot_20240211_225928_ru zdevs zarchiver pro](https://github.com/FooIbar/EhViewer/assets/88327304/44e123fc-4b24-4102-8be6-2a4c7aa4b611)

**Comment by FooIbar** [comment]
![711](https://github.com/FooIbar/EhViewer/assets/118464521/33856d07-d88a-4cd6-8fc3-58e0b53061af)
日志

**Comment by tmby** [comment]
> ![711](https://private-user-images.githubusercontent.com/118464521/303928217-33856d07-d88a-4cd6-8fc3-58e0b53061af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjY3OTQsIm5iZiI6MTcwNzY2NjQ5NCwicGF0aCI6Ii8xMTg0NjQ1MjEvMzAzOTI4MjE3LTMzODU2ZDA3LWQ4OGEtNGNkNi04ZmMzLTU4ZTBiNTMwNjFhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxNTQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWMwNGEwYzgwMDNiZWE1MmMwZDBlMzlhNzkyN2E0YWNhMDUxNzM1Mjc2YmFlZTUyYmE3YTMzZjYwZGQyMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0trcRK__sSYqx1CUAr3AxYKSSeQwFE6DnzDXnOXGglw) 日志

[log-2024-02-11-23-47-00-638.zip](https://github.com/FooIbar/EhViewer/files/14232950/log-2024-02-11-23-47-00-638.zip)

**Comment by FooIbar** [comment]
你这日志里什么都没有啊

**Comment by tmby** [comment]
我重新安装了一下eh，在设置下载路径为`/storage/emulated/0/EhViewer`后，我随便归档下载了一个画廊，以下为刚导出的日志 
[log-2024-02-12-00-19-55-997.zip](https://github.com/FooIbar/EhViewer/files/14233104/log-2024-02-12-00-19-55-997.zip)

**Comment by FooIbar** [comment]
> 我重新安装了一下eh，在设置下载路径为`/storage/emulated/0/EhViewer`后，我随便归档下载了一个画廊，以下为刚导出的日志 [log-2024-02-12-00-19-55-997.zip](https://github.com/FooIbar/EhViewer/files/14233104/log-2024-02-12-00-19-55-997.zip)

还是什么都没有
参考 https://stackoverflow.com/questions/18124334/huawei-logcat-not-showing-the-log-for-my-app

**Comment by tmby** [comment]
> > 我重新安装了一下eh，在设置下载路径为`/storage/emulated/0/EhViewer`后，我随便归档下载了一个画廊，以下为刚导出的日志 [log-2024-02-12-00-19-55-997.zip](https://github.com/FooIbar/EhViewer/files/14233104/log-2024-02-12-00-19-55-997.zip)
> 
> 还是什么都没有 参考 https://stackoverflow.com/questions/18124334/huawei-logcat-not-showing-the-log-for-my-app

这回应该有了
[log-2024-02-12-00-47-32-203.zip](https://github.com/FooIbar/EhViewer/files/14233205/log-2024-02-12-00-47-32-203.zip)

**Comment by FooIbar** [comment]
> > > 我重新安装了一下eh，在设置下载路径为`/storage/emulated/0/EhViewer`后，我随便归档下载了一个画廊，以下为刚导出的日志 [log-2024-02-12-00-19-55-997.zip](https://github.com/FooIbar/EhViewer/files/14233104/log-2024-02-12-00-19-55-997.zip)
> > 
> > 
> > 还是什么都没有 参考 https://stackoverflow.com/questions/18124334/huawei-logcat-not-showing-the-log-for-my-app
> 
> 这回应该有了 [log-2024-02-12-00-47-32-203.zip](https://github.com/FooIbar/EhViewer/files/14233205/log-2024-02-12-00-47-32-203.zip)

Nope

**Comment by tmby** [comment]
明天再说这个问题吧，我白天研究研究

**Comment by tmby** [comment]
> 参考 https://stackoverflow.com/questions/18124334/huawei-logcat-not-showing-the-log-for-my-app

根据链接中的描述，我输入代码后开启了AP LOG，然后重启了手机，在执行归档下载后的日志为
`02-12 01:08:59.831 11767 11787 E BehaviorCollectManager: Fail to acquire dataAnalyzerService...
02-12 01:08:59.947 11767 11817 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@c2253a9
02-12 01:09:00.412 11767 11828 E OpenGLRenderer: Unable to match the desired swap behavior.
02-12 01:09:08.618 11767 11828 E OpenGLRenderer: Unable to match the desired swap behavior.
02-12 01:09:09.750 11767 11828 E OpenGLRenderer: Unable to match the desired swap behavior.
02-12 01:09:29.866 11767 11828 E OpenGLRenderer: Unable to match the desired swap behavior.
02-12 01:09:29.950 11767 11828 E OpenGLRenderer: Unable to match the desired swap behavior.`
要是还不行我也没辙了😭

**Comment by FooIbar** [comment]
可以在开发者选项里找找有没有相关设置

**Comment by tmby** [comment]
我手机连接电脑，用adb logcat生成的日志如下
[logcat.txt](https://github.com/FooIbar/EhViewer/files/14234914/logcat.txt)

**Comment by FooIbar** [comment]
> 我手机连接电脑，用adb logcat生成的日志如下 [logcat.txt](https://github.com/FooIbar/EhViewer/files/14234914/logcat.txt)

试下
```
adb shell setprop persist.log.tag V
````

**Comment by tmby** [comment]
> > 我手机连接电脑，用adb logcat生成的日志如下 [logcat.txt](https://github.com/FooIbar/EhViewer/files/14234914/logcat.txt)
> 
> 试下
> 
> ```
> adb shell setprop persist.log.tag V
> ```

[logcat.txt](https://github.com/FooIbar/EhViewer/files/14235712/logcat.txt)

**Comment by FooIbar** [comment]
> > > 我手机连接电脑，用adb logcat生成的日志如下 [logcat.txt](https://github.com/FooIbar/EhViewer/files/14234914/logcat.txt)
> > 
> > 
> > 试下
> > ```
> > adb shell setprop persist.log.tag V
> > ```
> 
> [logcat.txt](https://github.com/FooIbar/EhViewer/files/14235712/logcat.txt)

虽然终于有东西了但是没有需要的
可以试下这个 https://github.com/FooIbar/EhViewer/actions/runs/7871366941

**Comment by tmby** [comment]
> > > > 我手机连接电脑，用adb logcat生成的日志如下 [logcat.txt](https://github.com/FooIbar/EhViewer/files/14234914/logcat.txt)
> > > 
> > > 
> > > 试下
> > > ```
> > > adb shell setprop persist.log.tag V
> > > ```
> > 
> > [logcat.txt](https://github.com/FooIbar/EhViewer/files/14235712/logcat.txt)
> 
> 虽然终于有东西了但是没有需要的
> 可以试下这个 https://github.com/FooIbar/EhViewer/actions/runs/7871366941

https://github.com/FooIbar/EhViewer/assets/88327304/12a11c3c-a4e5-40e7-aa18-9b5f454fc865

![log-2024-02-12-20-30-28-069.zip](https://github.com/FooIbar/EhViewer/files/14238344/log-2024-02-12-20-30-28-069.zip)

**Comment by FooIbar** [comment]
Ok 我知道是什么问题了
鸿蒙4怎么还是Android 12啊
