### ISSUE TITLE
Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### ISSUE THREAD

**Issue by Buatmaenros1** [FooIbar/EhViewer#716]
### 复现步骤 / Step to reproduce

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 预期行为 / Expected behaviour

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 实际行为 / Actual Behaviour

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 应用日志 / App logs

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 备注 / Addition details

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

Latest

### EhViewer CI 版本 / EhViewer CI Version

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### Android 系统版本 / Android version

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 设备型号 / Device model

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### SoC 型号 / Soc model

Can you add old EH function to jump between page on "more preview" instead of having to scroll down so far for gallery with alot of image?

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by Pony-CW** [comment]
¿wtf?
