### ISSUE TITLE
Separate DefaultOss DefaultGms MarshmallowOss MarshmallowGms to 4 tasks to accelerate CI 

### ISSUE THREAD

**Issue by VDostoyevskiy** [FooIbar/EhViewer#750]

**Comment by FooIbar** [comment]
Does it matter?
Artifacts are immediately available once uploaded since upload-artifact v4 anyway.

**Comment by VDostoyevskiy** [comment]
> Does it matter? Artifacts are immediately available once uploaded since upload-artifact v4 anyway.

Ah, seems in-app updater cannot fetch it until action completed.

**Comment by VDostoyevskiy** [comment]
> Does it matter? Artifacts are immediately available once uploaded since upload-artifact v4 anyway.

And with MR auto-merge, we just need to wait about 8 minutes not 20

**Comment by FooIbar** [comment]
Fair.
