### ISSUE TITLE
能否增加一个复制标题的功能？

### ISSUE THREAD

**Issue by bnbbird** [FooIbar/EhViewer#753]
### 复现步骤 / Step to reproduce

。

### 预期行为 / Expected behaviour

。

### 实际行为 / Actual Behaviour

。

### 应用日志 / App logs

。

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

。

### EhViewer CI 版本 / EhViewer CI Version

。

### Android 系统版本 / Android version

。

### 设备型号 / Device model

。

### SoC 型号 / Soc model

。

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1365
