### ISSUE TITLE
最新版打开闪退

### ISSUE THREAD

**Issue by HF64522008** [FooIbar/EhViewer#759]
### 复现步骤 / Step to reproduce

重装了应用

### 预期行为 / Expected behaviour

旧版本都能打开，新版本闪退

### 实际行为 / Actual Behaviour

所有最新版都闪退

### 应用日志 / App logs

[log-2024-02-18-21-52-33-942.zip](https://github.com/FooIbar/EhViewer/files/14322720/log-2024-02-18-21-52-33-942.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.103

### EhViewer CI 版本 / EhViewer CI Version

26f05A0

### Android 系统版本 / Android version

Android13+originos3

### 设备型号 / Device model

iQOO8

### SoC 型号 / Soc model

骁龙888

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by HF64522008** [comment]
ci版本错了，没找到填的例子

**Comment by FooIbar** [comment]
因数据库变动，不支持从最新 CI 版本降级到稳定版本
