### ISSUE TITLE
缓解中国垃圾H@H

### ISSUE THREAD

**Issue by UjuiUjuMandan** [FooIbar/EhViewer#765]
### 需求 / Requirement

H@H地区设为中国之后经常遇到垃圾机器，连接建立之后图片却一直不开始下载，应用此时也会不计算超时，就一直加载。

经过测试E站目前并没有任何信誉机制缓解此问题 https://github.com/FooIbar/EhViewer/issues/758#issuecomment-1952025038 。甚至中国区所有H@H机器的Trust和Quality都是锁在最高值不会改变。

### 建议实现 / Suggested implements

应用可能引入黑名单机制检测、并暂时封锁垃圾H@H。

我在Clash配置中手动加入相关规则之后效果非常好，我在想直接在应用中内置屏蔽器的可能性。

![Screenshot_20240219-175533](https://github.com/FooIbar/EhViewer/assets/125150101/0d243a65-591e-46b5-9cd2-d28d8862bee6)

### 备注 / Addition details

本议题是对 #758 的延伸。

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT-gms

### EhViewer CI 版本 / EhViewer CI Version

f9cb3d7

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 CI 版本测试，并且该功能在最新 CI 版本中并未按照预期实现 / This feature don't implement correctly in latest CI version

**Comment by VDostoyevskiy** [comment]
Are these H@H servers only in China?
IMO we could implement a mechanism to record bad H@H domain temporarily(7 days?) and re-request a H@H server?
What do you think? @FooIbar

**Comment by FooIbar** [comment]
> Are these H@H servers only in China? IMO we could implement a mechanism to record bad H@H domain temporarily(7 days?) and re-request a H@H server? What do you think? @FooIbar

I don't think it's worth it and re-requesting image server is somewhat expensive (50 points of image limit).
See also: https://github.com/FooIbar/EhViewer/issues/758#issuecomment-1952161465

**Comment by VDostoyevskiy** [comment]
> > Are these H@H servers only in China? IMO we could implement a mechanism to record bad H@H domain temporarily(7 days?) and re-request a H@H server? What do you think? @FooIbar
> 
> I don't think it's worth it and re-requesting image server is somewhat expensive (50 points of image limit). See also: [#758 (comment)](https://github.com/FooIbar/EhViewer/issues/758#issuecomment-1952161465)

Okay, up to you.

**Comment by FooIbar** [comment]
Close as infeasible, see https://github.com/FooIbar/EhViewer/issues/758#issuecomment-1953220167.
