### ISSUE TITLE
Sad panda api regression

### ISSUE THREAD

**Issue by mirh** [FooIbar/EhViewer#77]
### 复现步骤 / Step to reproduce

So.. I still have a *hostile* network situation as described in https://github.com/Ehviewer-Overhauled/Ehviewer/issues/1228. 
And updating to this new fork from EHV-OH got me every kind of "discovery" operation to timeout (viewing and browsing galleries that were already previously queried still works). 

Long story short after playing with EhViewer-NekoInverter and noticing that CI and official release operated differently and what the only meaningful functional change was, I can confidently say this happened due to 97c39d07e8a3c2eba158542e19921b6d0cb8cf12. 

### 预期行为 / Expected behaviour

I don't really know what the official endpoints should be (EHWiki only covers the default website)
But if `https://exhentai.org/api.php` still works, then it doesn't seem fair to only forcefully and uniquely use `https://s.exhentai.org/api.php`. 

### 实际行为 / Actual Behaviour

The later subdomain sits on a different server (178.175.128.254) than the former (188.114.96.7) and the gods got it blocked. 

### 备注 / Addition details

#76 didn't really help the slightest. 

### EhViewer 版本号 / EhViewer version code

1.8.10.1-gms

### EhViewer CI 版本 / EhViewer CI Version

4067543

### Android 系统版本 / Android version

9

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by mirh** [comment]
That makes sense I guess. 
(even though I was just thinking you could have the secondary server fallback in-between the normal one and the html mode)

**Comment by FooIbar** [comment]
> That makes sense I guess. (even though I was just thinking you could have the secondary server fallback in-between the normal one and the html mode)

#76 should work, most likely you're getting errors from somewhere else.
Do you have any logs dumped?
APIs are used in various places, like [here](https://github.com/FooIbar/EhViewer/blob/406754370195358612e5eb0f823f91672c6cae74/app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt#L399) and [here](https://github.com/FooIbar/EhViewer/blob/406754370195358612e5eb0f823f91672c6cae74/app/src/main/kotlin/com/hippo/ehviewer/client/EhEngine.kt#L416), not just for downloading.

**Comment by mirh** [comment]
I would have imagined using the ex url without the `s.` could have still been better than going back to the full vanilla _E. 

For some reason the thing now started to *mostly* work again though (that is, without even your fix). 
The only features that still appear broken are voting, and "infinite scrolling":
```
10-26 22:45:27.618 16501 16522 D EhEngine: https://exhentai.org/tag/whatever?next=2709817
10-26 22:45:27.843 16501 17153 D EhEngine: https://s.exhentai.org/api.php
10-26 22:45:38.395 16501 16501 W System.err: java.net.SocketTimeoutException: failed to connect to s.exhentai.org/178.175.128.254 (port 443) from /192.168.1.197 (port 46668) after 10000ms
10-26 22:45:38.395 16501 16501 W System.err:  at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
10-26 22:45:38.395 16501 16501 W System.err:  at libcore.io.IoBridge.connect(IoBridge.java:129)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
10-26 22:45:38.395 16501 16501 W System.err:  at java.net.Socket.connect(Socket.java:621)
10-26 22:45:38.395 16501 16501 W System.err:  at Z5.e(Unknown Source:5)
10-26 22:45:38.395 16501 16501 W System.err:  at tq.i(Unknown Source:74)
10-26 22:45:38.395 16501 16501 W System.err:  at tq.e(Unknown Source:35)
10-26 22:45:38.395 16501 16501 W System.err:  at DK.a(Unknown Source:2)
10-26 22:45:38.395 16501 16501 W System.err:  at tS0.a(Unknown Source:16)
10-26 22:45:38.395 16501 16501 W System.err:  at sS0.run(Unknown Source:49)
10-26 22:45:38.395 16501 16501 W System.err:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-26 22:45:38.396 16501 16501 W System.err:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-26 22:45:38.396 16501 16501 W System.err:  at java.lang.Thread.run(Thread.java:764)
10-26 22:45:38.396 16501 16501 W System.err:  Suppressed: java.net.SocketTimeoutException: failed to connect to s.exhentai.org/178.175.132.22 (port 443) from /192.168.1.197 (port 44826) after 10000ms
10-26 22:45:38.396 16501 16501 W System.err:   ... 17 more
10-26 22:45:38.396 16501 16501 W System.err:  Suppressed: java.net.SocketTimeoutException: failed to connect to s.exhentai.org/178.175.129.254 (port 443) from /192.168.1.197 (port 43702) after 10000ms
10-26 22:45:38.396 16501 16501 W System.err:   ... 17 more
```
(log is from the later, because failure to vote doesn't seem to log anything)

**Comment by FooIbar** [comment]
> The only features that still appear broken are voting, and "infinite scrolling"

That does not look like "working".
As I said before, voting/tagging/rating are where APIs are used.
Searching generally won't get involved unless we can't get all data we need from html, e.g. you have rated the gallery so the html will return your score instead of the average.

**Comment by mirh** [comment]
Sure, I just wanted to underline this additional oddity when (last week) not even search was working.
