### ISSUE TITLE
Predictive back transition ends prematurely in Navigation Compose

### ISSUE THREAD

**Issue by FooIbar** [FooIbar/EhViewer#775]
https://issuetracker.google.com/327292110

**Comment by yinzhefuyun** [comment]
预测返回的开关能做一个吗？感觉用不习惯这个东西

**Comment by VDostoyevskiy** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/2974195

**Comment by VDostoyevskiy** [comment]
https://android-review.googlesource.com/c/platform/frameworks/support/+/2907680
