### ISSUE TITLE
归档下载调用下载管理器

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#79]
### 复现步骤 / Step to reproduce

目前ehviewer点击归档下载会调用默认的下载管理器，但文件大了很容易出现下载中断导致的失败，不能断点续传。
能否调用本地存在的其他下载管理器？
例如：
ADM
包名 com.dv.adm
活动 com.dv.adm.AEditor
IDM+
包名 idm.internet.download.manager.plus
活动 idm.internet.download.manager.MainActivity
虽然在网页里点归档下载复制到idm+等下载管理器下载也可以，但打开默认打开后，网页点击归档下载会自动跳转到ehviewer，无法在浏览器里直接打开。
![Screenshot_20231024_145747_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/2bdde4ca-5c3a-44db-9439-b262b69a6e1b)

### 预期行为 / Expected behaviour

.

### 实际行为 / Actual Behaviour

.

### EhViewer 版本号 / EhViewer version code

1.8.10.1

### EhViewer CI 版本 / EhViewer CI Version

1ab08d0

### Android 系统版本 / Android version

HarmonyOS 4.0.0.116

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by BakaJzon** [comment]
[aria2app](https://github.com/devgianlu/Aria2App)
com.gianlu.aria2app
