### ISSUE TITLE
图片配额上限显示错误

### ISSUE THREAD

**Issue by 1sixth** [FooIbar/EhViewer#829]
### 复现步骤 / Step to reproduce

1. 登录 E-Hentai
2. 设置 -> EH -> 图片配额

### 预期行为 / Expected behaviour

显示的图片配额上限应与 <https://e-hentai.org/home.php> 保持一致

![1](https://github.com/FooIbar/EhViewer/assets/67363572/295dd4c6-4911-47fc-a382-b107ee8a956f)

### 实际行为 / Actual Behaviour

显示的配额上限为实际的 10 倍

![1](https://github.com/FooIbar/EhViewer/assets/67363572/d5069746-fa7d-446a-ae08-9b18a0f36327)

### 应用日志 / App logs

[log-2024-03-02-13-31-13-153.zip](https://github.com/FooIbar/EhViewer/files/14468165/log-2024-03-02-13-31-13-153.zip)

### 备注 / Addition details

按照 [EhWiki](https://ehwiki.org/wiki/My_Home) 的说法，图片配额上限通常在 3000-5000。

### 浏览站点 / Browsing site

E-Hentai

### EhViewer 版本号 / EhViewer version code

1.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

7357724

### Android 系统版本 / Android version

HyperOS 1.0.14.0

### 设备型号 / Device model

Xiaomi 14

### SoC 型号 / Soc model

Snapdragon 8 Gen 3

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
你开了 Hath Perk 吧

**Comment by 1sixth** [comment]
我之前开了 "Too Many Pages" 这个 Perk，原来 10 倍是这么来的...

刷新网页后上限也显示 50000，乌龙了，不好意思

![image](https://github.com/FooIbar/EhViewer/assets/67363572/8de2736b-151e-4c09-8958-c3a6c4e7afe9)
