### ISSUE TITLE
搜索选项中，“类型筛选”的布局异常

### ISSUE THREAD

**Issue by 1235789gzy1** [FooIbar/EhViewer#85]
### 复现步骤 / Step to reproduce

对搜索选项中类型筛选进行操作时
https://github.com/Ehviewer-Overhauled/Ehviewer/assets/52618207/67a930f1-e442-4bb7-bdbb-4c39a30db7e7

### 预期行为 / Expected behaviour

理论上应该固定两列

### 实际行为 / Actual Behaviour

两列三列混杂

### 备注 / Addition details

系统并没有额外修改DPI，仅将字体大小改为“小”，经另一名群友测试，字体大小改为最小即可触发

### EhViewer 版本号 / EhViewer version code

1.8.10.1-gms

### EhViewer CI 版本 / EhViewer CI Version

98d66b3

### Android 系统版本 / Android version

Hydrogen OS 10.0.15.15.IN11

### 设备型号 / Device model

OnePlus 8Pro

### SoC 型号 / Soc model

Snapdragon 865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by LzNOHentai** [comment]
借这个issue一起报个bug，搜索高级选项会遮挡搜索按钮。
![Screenshot_2023-10-25-13-26-15-341_moe tarsin ehviewer-edit](https://github.com/FooIbar/EhViewer/assets/22359967/1f1d6c64-1683-4088-86c2-07539169c9f3)
CI版本：https://github.com/FooIbar/EhViewer/commit/ab8671cc3b0a5631954b0b4e21909367de57e11a

**Comment by FooIbar** [comment]
> 借这个issue一起报个bug，搜索高级选项会遮挡搜索按钮。

这是预期的，还没改完

**Comment by LzNOHentai** [comment]
> > 借这个issue一起报个bug，搜索高级选项会遮挡搜索按钮。
> 
> ~这是预期的，还没改完~ Fixed in [8f7242b](https://github.com/FooIbar/EhViewer/commit/8f7242b9398ace89b546ec1d228a117ffbc87af6)

以及还有一个问题，在阅读的时候双指调整图片大小会直接黑屏。

**Comment by FooIbar** [comment]
单独开issue

LzNOHentai ***@***.***> 于 2023年10月25日周三 17:17写道：
