### ISSUE TITLE
顶部和侧面显示错误

### ISSUE THREAD

**Issue by tmby** [FooIbar/EhViewer#87]
### 复现步骤 / Step to reproduce

更新ci[5784eb0](https://github.com/FooIbar/EhViewer/commit/5784eb008ea3504ed8662171355606c6c43242b6) 后，ehviewer顶部和侧面显示出现错误。

### 预期行为 / Expected behaviour

![Screenshot_20231025_090551_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/ebe5a312-934e-4fad-a0e1-1338e0320161)
![Screenshot_20231025_090937_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/8f5f4166-9128-4e2f-b49d-c37ebcf40054)

### 实际行为 / Actual Behaviour

![Screenshot_20231025_085815_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/57e48ddd-5476-4c78-a823-4fb7a96a231a)
![Screenshot_20231025_090909_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/71e62281-4e1d-4df4-9daf-35d14d1f0547)

### 应用日志 / App logs

[log-2023-10-25-09-14-47-398.zip](https://github.com/FooIbar/EhViewer/files/13154350/log-2023-10-25-09-14-47-398.zip)

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

5784eb0

### Android 系统版本 / Android version

HarmonyOS 4.0.0.116

### 设备型号 / Device model

HUAWEI Nova 9 Pro

### SoC 型号 / Soc model

高通骁龙778G 4G

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by tmby** [comment]
回退版本后发现上一个ci版本[82d66c4
](https://github.com/FooIbar/EhViewer/commit/82d66c4d579f277024724f7c24aeb5ee12aeb24d)未出现此错误。

**Comment by FooIbar** [comment]
Duplicate of #84

**Comment by Shaddoll126** [comment]
借楼问一下能不能恢复右侧左滑拉出快速搜索栏   单手操作按搜索栏按钮有点困难（

**Comment by tmby** [comment]
ci[cd764a4](https://github.com/FooIbar/EhViewer/commit/cd764a4a3caf636323a7b9c7d559f1f90e5afec1)解决了顶栏
侧栏比例越来越大了😂
![Screenshot_20231025_210834_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/b216370c-c513-49b2-a7af-e7cfa91d961d)

**Comment by tmby** [comment]
侧栏和原来相比，大了一个字号，是预期行为吗？
![Screenshot_20231025_090937_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/8f5f4166-9128-4e2f-b49d-c37ebcf40054)
![Screenshot_20231026_073634_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/5384578a-9a8a-4969-8356-33f821492058)

**Comment by FooIbar** [comment]
> 侧栏和原来相比，大了一个字号，是预期行为吗？

是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs

**Comment by tmby** [comment]
> > 侧栏和原来相比，大了一个字号，是预期行为吗？
> 
> 是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs

能统一一下字体大小吗？
侧栏打开设置字体突然小一号很难受

**Comment by FooIbar** [comment]
> > > 侧栏和原来相比，大了一个字号，是预期行为吗？
> > 
> > 
> > 是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs
> 
> 能统一一下字体大小吗？ 侧栏打开设置字体突然小一号很难受

导航抽屉和设置的字体大小应该是一样的，都是16sp
从你的截图来看导航抽屉和搜索栏的字体大小也差不多

**Comment by tmby** [comment]
> > > > 侧栏和原来相比，大了一个字号，是预期行为吗？
> > > 
> > > 
> > > 是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs
> > 
> > 能统一一下字体大小吗？ 侧栏打开设置字体突然小一号很难受
> 
> 导航抽屉和设置的字体大小应该是一样的，都是16sp
> 从你的截图来看导航抽屉和搜索栏的字体大小也差不多

我这边不是啊😭应该是大了一点
https://github.com/FooIbar/EhViewer/assets/88327304/89b91a4d-b273-45ac-a460-0d835fb794f8

**Comment by FooIbar** [comment]
> > > > > 侧栏和原来相比，大了一个字号，是预期行为吗？
> > > > 
> > > > 
> > > > 是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs
> > > 
> > > 
> > > 能统一一下字体大小吗？ 侧栏打开设置字体突然小一号很难受
> > 
> > 
> > 导航抽屉和设置的字体大小应该是一样的，都是16sp
> > 从你的截图来看导航抽屉和搜索栏的字体大小也差不多
> 
> 我这边不是啊😭应该是大了一点 https://github.com/FooIbar/EhViewer/assets/88327304/89b91a4d-b273-45ac-a460-0d835fb794f8

![drawer](https://github.com/FooIbar/EhViewer/assets/118464521/4a250cb5-e498-4569-874b-bddde77338c2)![settings](https://github.com/FooIbar/EhViewer/assets/118464521/96cb6bf7-70e1-4b68-addf-2c84d9e07423)
你这录屏里也是一样大啊

**Comment by tmby** [comment]
> > > > > > 侧栏和原来相比，大了一个字号，是预期行为吗？
> > > > > 
> > > > > 
> > > > > 是，MD3规范就是360dp https://m3.material.io/components/navigation-drawer/specs
> > > > 
> > > > 
> > > > 能统一一下字体大小吗？ 侧栏打开设置字体突然小一号很难受
> > > 
> > > 
> > > 导航抽屉和设置的字体大小应该是一样的，都是16sp
> > > 从你的截图来看导航抽屉和搜索栏的字体大小也差不多
> > 
> > 我这边不是啊😭应该是大了一点 https://github.com/FooIbar/EhViewer/assets/88327304/89b91a4d-b273-45ac-a460-0d835fb794f8
> 
> ![drawer](https://github.com/FooIbar/EhViewer/assets/118464521/4a250cb5-e498-4569-874b-bddde77338c2)![settings](https://github.com/FooIbar/EhViewer/assets/118464521/96cb6bf7-70e1-4b68-addf-2c84d9e07423)
> 你这录屏里也是一样大啊

🥲难受的那就不是字号了，是比例
原![Screenshot_20231025_090937_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/88327304/8f5f4166-9128-4e2f-b49d-c37ebcf40054)
现![Screenshot_20231026_073634_moe.tarsin.ehviewer.jpg](https://github.com/FooIbar/EhViewer/assets/88327304/5384578a-9a8a-4969-8356-33f821492058)

**Comment by FooIbar** [comment]
#105
