### ISSUE TITLE
画廊不显示种子

### ISSUE THREAD

**Issue by nickhe800** [FooIbar/EhViewer#880]
### 复现步骤 / Step to reproduce

1-打开一个有种子的画廊
2-打开种子按钮
3-不显示种子
![IMG_20240308_212353](https://github.com/FooIbar/EhViewer/assets/118934938/5723965d-00b0-4cdd-a161-7557bce48ae9)
![Screenshot_2024-03-08-20-45-36-362_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/118934938/b4022b98-f25c-41cc-955b-b4a4a84952ff)

### 预期行为 / Expected behaviour

显示种子

### 实际行为 / Actual Behaviour

不显示种子

### 应用日志 / App logs

[log-2024-03-08-20-57-59-957.zip](https://github.com/FooIbar/EhViewer/files/14538682/log-2024-03-08-20-57-59-957.zip)

### 备注 / Addition details

无

### 浏览站点 / Browsing site

E-hentai

### EhViewer 版本号 / EhViewer version code

1.10.3

### EhViewer CI 版本 / EhViewer CI Version

1d9008a

### Android 系统版本 / Android version

miui12

### 设备型号 / Device model

xiaomi12

### SoC 型号 / Soc model

骁龙8gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
已于最新 CI 版本修复

**Comment by nickhe800** [comment]
> 已于最新 CI 版本修复

请问现在怎么修复呢，是需要等待下版本app发布吗，感谢

**Comment by FooIbar** [comment]
> > 已于最新 CI 版本修复
> 
> 请问现在怎么修复呢，是需要等待下版本app发布吗，感谢

设置-关于 中打开使用 CI 更新

**Comment by revonateB0T** [comment]
好像还是坏的（
https://exhentai.org/g/2851339/70797c303b

**Comment by FooIbar** [comment]
> 好像还是坏的（ https://exhentai.org/g/2851339/70797c303b

这个画廊刚更新，那两个种子都是 outdated

**Comment by tmby** [comment]
> > 好像还是坏的（ https://exhentai.org/g/2851339/70797c303b
> 
> 这个画廊刚更新，那两个种子都是 outdated

能不能只显示current种子的数量，忽略outdated种子数量？

**Comment by FooIbar** [comment]
> > > 好像还是坏的（ https://exhentai.org/g/2851339/70797c303b
> > 
> > 
> > 这个画廊刚更新，那两个种子都是 outdated
> 
> 能不能只显示current种子的数量，忽略outdated种子数量？

在请求种子列表前我们不知道两者的数量，详情页只有总数

**Comment by tmby** [comment]
> > > > 好像还是坏的（ https://exhentai.org/g/2851339/70797c303b
> > > 
> > > 
> > > 这个画廊刚更新，那两个种子都是 outdated
> > 
> > 能不能只显示current种子的数量，忽略outdated种子数量？
> 
> 在请求种子列表前我们不知道两者的数量，详情页只有总数

那干脆不要显示种子的数量了，显示总数，打开却只显示current种子，估计会有很多人来问为什么数量对不上

**Comment by FooIbar** [comment]
> > > > > 好像还是坏的（ https://exhentai.org/g/2851339/70797c303b
> > > > 
> > > > 
> > > > 这个画廊刚更新，那两个种子都是 outdated
> > > 
> > > 
> > > 能不能只显示current种子的数量，忽略outdated种子数量？
> > 
> > 
> > 在请求种子列表前我们不知道两者的数量，详情页只有总数
> 
> 那干脆不要显示种子的数量了，显示总数，打开却只显示current种子，估计会有很多人来问为什么数量对不上

#886
