### ISSUE TITLE
标签屏蔽功能无效

### ISSUE THREAD

**Issue by ssbroad** [FooIbar/EhViewer#884]
### 复现步骤 / Step to reproduce

内置的标签屏蔽完全不起作用，例如下图中添加了"选集/Anthology" 来屏蔽大量的杂志，然而搜索结果依然存在杂志画廊
![newScreenshot_2024-03-09-11-08-22-148_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/11014064/df8624ff-4e47-41af-aa9c-503c39834d3e)
![newScreenshot_2024-03-09-11-09-42-560_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/11014064/d60f1c25-35f5-461d-b424-b0585497dd2c)
![newScreenshot_2024-03-09-11-09-49-103_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/11014064/fbbdc999-1c87-47c4-97eb-c4fcb342c21e)

原版EhViewe则没有这个问题，正常从结果中屏蔽

### 预期行为 / Expected behaviour

在搜索结果中屏蔽设定的标签

### 实际行为 / Actual Behaviour

屏蔽标签完全不起作用

### 应用日志 / App logs

none

### 备注 / Addition details

none

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.10.3

### EhViewer CI 版本 / EhViewer CI Version

1d9008a

### Android 系统版本 / Android version

MIUI13

### 设备型号 / Device model

xiaomi12

### SoC 型号 / Soc model

骁龙8gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
搜索结果中可能不会显示全部标签，建议使用 [My Tags](https://ehwiki.org/wiki/My_Tags#Tag_Filtering) 屏蔽

**Comment by ssbroad** [comment]
> 搜索结果中可能不会显示全部标签，建议使用 [My Tags](https://ehwiki.org/wiki/My_Tags#Tag_Filtering) 屏蔽

所以说这个功能完全就是摆设吗？我看原版EhViewer没有这个问题啊，奇怪

**Comment by FooIbar** [comment]
> > 搜索结果中可能不会显示全部标签，建议使用 [My Tags](https://ehwiki.org/wiki/My_Tags#Tag_Filtering) 屏蔽
> 
> 所以说这个功能完全就是摆设吗？我看原版EhViewer没有这个问题啊，奇怪

你的搜索结果里连上传者都没有，显然是 Thumbnail 模式，网页上也是看不到标签的
你也可以单开个 Settings Profile 给 EhViewer 把显示模式设为 Extended，但无论如何内置的屏蔽器效果都比不上 My Tags
因为用 My Tags 的话是在返回搜索结果前在服务器端就屏蔽了，而内置屏蔽器是在客户端进行的屏蔽

**Comment by ssbroad** [comment]
> > > 搜索结果中可能不会显示全部标签，建议使用 [My Tags](https://ehwiki.org/wiki/My_Tags#Tag_Filtering) 屏蔽
> > 
> > 
> > 所以说这个功能完全就是摆设吗？我看原版EhViewer没有这个问题啊，奇怪
> 
> 你的搜索结果里连上传者都没有，显然是 Thumbnail 模式，网页上也是看不到标签的 你也可以单开个 Settings Profile 给 EhViewer 把显示模式设为 Extended，但无论如何内置的屏蔽器效果都比不上 My Tags 因为用 My Tags 的话是在返回搜索结果前在服务器端就屏蔽了，而内置屏蔽器是在客户端进行的屏蔽

懂了
