### ISSUE TITLE
1.11.0点按翻页失效，什么时候加回下载界面手动排序

### ISSUE THREAD

**Issue by mgcccc** [FooIbar/EhViewer#890]
### 复现步骤 / Step to reproduce

点按所有地方都只能出现设置界面

### 预期行为 / Expected behaviour

应该能够翻页

### 实际行为 / Actual Behaviour

上面已经描述

### 应用日志 / App logs

提交不了

### 备注 / Addition details

希望尽快修改好点按翻页以及加回下载界面手动排序

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.0

### EhViewer CI 版本 / EhViewer CI Version

6cd7b85

### Android 系统版本 / Android version

magicos8.0 Android14

### 设备型号 / Device model

荣耀magic5pro

### SoC 型号 / Soc model

骁龙8gen2

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by BEIVSIQIN** [comment]
貌似是new compose reader的问题？我取消勾选后就正常了

**Comment by FooIbar** [comment]
> 貌似是new compose reader的问题？我取消勾选后就正常了

1.11.0没有new compose reader，只有CI版本才有
而且上面写了WIP还加了感叹号了

**Comment by FooIbar** [comment]
无法复现，需要更多信息
手动排序已被新的排序模式取代，不会加回

**Comment by mgcccc** [comment]
佬，新的排序不能像以前那样把下载的本子按照自己的喜好进行调整，对我个人来说完全不如手动排序，目前1279本本子，真的做不到每次下载本子为了排序重新下载个几十几百本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FooIbar/EhViewer] 1.11.0点按翻页失效，什么时候加回下载界面手动排序 (Issue #890)




 
无法复现，需要更多信息
 手动排序已被新的排序模式取代，不会加回

**Comment by mgcccc** [comment]
我昨天是在更新CI版打开打开了new compose reader后还没使用就看到releases更新了1.11.0然后直接去更新1.11.0了，现在更新了ujuiuju的改版后有这个开关关掉就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FooIbar/EhViewer] 1.11.0点按翻页失效，什么时候加回下载界面手动排序 (Issue #890)




  
貌似是new compose reader的问题？我取消勾选后就正常了
  
1.11.0没有new compose reader，只有CI版本才有
 而且上面写了WIP还加了感叹号了

**Comment by FooIbar** [comment]
手动排序是为了达成什么样的效果？
比如同一个画师的作品放在一起？

**Comment by mgcccc** [comment]
还有同一个类别的本子开个分类，很多单行本不是单一题材会根据偏好放在不同的位置，同一个作者的本子也会因为发布顺序想要调整位置，有的时候会出现一个新发布的10年前的本子的汉化



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FooIbar/EhViewer] 1.11.0点按翻页失效，什么时候加回下载界面手动排序 (Issue #890)




 
手动排序是为了达成什么样的效果？
 比如同一个画师的作品放在一起？

**Comment by FooIbar** [comment]
首先手动排序不可行不会被支持
其次你的需求似乎可以通过下载标签-其他字段的二级排序部分满足，目前使用的是下载标签-标题，和其他字段组合的支持如果有需要的话之后可以添加

**Comment by mgcccc** [comment]
这就难受了，希望哪次能够兼容手动排序吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FooIbar/EhViewer] 1.11.0点按翻页失效，什么时候加回下载界面手动排序 (Issue #890)




 
首先手动排序不可行不会被支持
 其次你的需求似乎可以通过下载标签-其他字段的二级排序部分满足，目前使用的是下载标签-标题，和其他字段组合的支持如果有需要的话之后可以添加

**Comment by 1258020** [comment]
作者能不能看种子的问题，无法下载。

**Comment by devioa** [comment]
> 手动排序是为了达成什么样的效果？ 比如同一个画师的作品放在一起？

经常看的，或者自认为需要置顶或者根据喜好再排序的，没有这个手动排序非常难受，强烈建议加回来

**Comment by FooIbar** [comment]
> 作者能不能看种子的问题，无法下载。

与本 issue 无关的问题单独开 issue

> > 手动排序是为了达成什么样的效果？ 比如同一个画师的作品放在一起？
> 
> 经常看的，或者自认为需要置顶或者根据喜好再排序的，没有这个手动排序非常难受，强烈建议加回来

置顶可以通过下载标签实现

**Comment by devioa** [comment]
下载标签我一般用于分类或者标注，标签中的一些画廊需要再置顶或者按一些规则重新排序 @FooIbar

**Comment by ZerOri** [comment]
> 手动排序是为了达成什么样的效果？
> 比如同一个画师的作品放在一起？

很多系列作品标题并不是简单地冠以 xxx 1、2、3...的顺序命名，甚至前作和续作会采用完全不同的标题，这时候自动排序派不上用场就需要手动排序，对同人漫画来说下载作品手动排序是个十分重要的管理功能，自动排序可以有，但手动排序也不能丢，这才称得上健全，无法手动排序的结果就是作品排序混乱，逼死强迫症。
