### ISSUE TITLE
收藏页面 搜索栏中文标签转英文异常

### ISSUE THREAD

**Issue by railgun100** [FooIbar/EhViewer#902]
### 复现步骤 / Step to reproduce

在本地或者云端收藏页面输入中文标签翻译，比如姐妹

### 预期行为 / Expected behaviour

f:sister$

### 实际行为 / Actual Behaviour

sister
![IMG_20240313_204619](https://github.com/FooIbar/EhViewer/assets/98539566/328a704a-51e5-464b-b97a-52b35899e5d4)

### 应用日志 / App logs

[log-2024-03-13-20-47-41-412.zip](https://github.com/FooIbar/EhViewer/files/14587851/log-2024-03-13-20-47-41-412.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

c9919a8

### Android 系统版本 / Android version

colorOS14

### 设备型号 / Device model

oneplus10Pro

### SoC 型号 / Soc model

骁龙8+gen1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
本地收藏中的行为是故意的，因为本地的标签搜索不支持命名空间
云端收藏的之后会修
