### ISSUE TITLE
Search bar does not work properly in Japanese

### ISSUE THREAD

**Issue by voucher4323** [FooIbar/EhViewer#906]
### 复现步骤 / Step to reproduce

1.Type in search bar

### 预期行为 / Expected behaviour

![Screenshot_20240314_003000_Chrome](https://github.com/FooIbar/EhViewer/assets/163324396/e29e4b10-b598-4da5-adcb-e4295571b4f6)

A dialog box for converting to kanji or katakana will appear.

sentences deleted by long pressing backspace.
The problem did not occur until v1.10.3

### 实际行为 / Actual Behaviour

A conversion dialog appears briefly, but then disappears.
When deleting a word with backspace, it does not disappear even if you press and hold it for a long time.  need to hit repeatedly

![Screenshot_20240314_002244_EhViewer](https://github.com/FooIbar/EhViewer/assets/163324396/1cde581a-bbfa-41f2-8fec-2fa3a5f91721)

### 应用日志 / App logs

[log-2024-03-14-00-31-16-312.zip](https://github.com/FooIbar/EhViewer/files/14590059/log-2024-03-14-00-31-16-312.zip)

### 浏览站点 / Browsing site

EXhentai/e-hentai

### EhViewer 版本号 / EhViewer version code

1.11.1/1.11.0

### EhViewer CI 版本 / EhViewer CI Version

f69521f

### Android 系统版本 / Android version

13

### 设备型号 / Device model

Galaxy S20 FE

### SoC 型号 / Soc model

Exynos 990

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
Looks like it's an upstream bug, I'll look into what we can do to mitigate it.

**Comment by FooIbar** [comment]
The typing issue should be fixed in 5746e3b and will be shipped in the next release.
If you can't wait you can enable "Use CI update channel" in Settings - About to update to the latest development version.

The hold backspace key to delete issue will be tracked in #606
