### ISSUE TITLE
更新后左滑无法拉出侧边栏

### ISSUE THREAD

**Issue by Shaddoll126** [FooIbar/EhViewer#91]
### 复现步骤 / Step to reproduce

更新cl包后出现，已更新至最新仍旧无法左侧右滑拉出侧边栏

### 预期行为 / Expected behaviour

应该左侧右滑拉出侧边栏

### 实际行为 / Actual Behaviour

实际上无事发生

### 备注 / Addition details

以及希望能恢复右侧左滑唤出快速搜索

### EhViewer 版本号 / EhViewer version code

1.8.11.0

### EhViewer CI 版本 / EhViewer CI Version

70450a9

### Android 系统版本 / Android version

lineage os 20 安卓13

### 设备型号 / Device model

一加8

### SoC 型号 / Soc model

骁龙865

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
预期行为

**Comment by Marsblast** [comment]
大尺寸手机难以单手点击左、右上角的选项，以及下载页面滑动删除画廊非常容易误触
希望可以重新添加该功能，或者作为可选开关放在设置页面，非常感谢

**Comment by Marsblast** [comment]
> 预期行为，但可能在未来更改

大尺寸手机难以单手点击左、右上角的选项，以及下载页面滑动删除画廊非常容易误触
希望可以重新添加该功能，或者作为可选开关放在设置页面，非常感谢
