### ISSUE TITLE
Korean text does not write properly. 

### ISSUE THREAD

**Issue by JohnDoe107745** [FooIbar/EhViewer#915]
### 复现步骤 / Step to reproduce

Write Korean text in search bar of the app. 

### 预期行为 / Expected behaviour

The Korean text should write with no problem

### 实际行为 / Actual Behaviour

The Korean text does not write properly and break. For example, when you type 가 in the search bar, the word 가 does not produced and breaks to letters ㄱ and ㅏ 

### 应用日志 / App logs

Does not know how to provide app log

### 备注 / Addition details

The Korean text does not write properly and break. For example, when you type 가 in the search bar, the word 가 does not produced and breaks to letters ㄱ and ㅏ 

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

newest version

### EhViewer CI 版本 / EhViewer CI Version

Not sure

### Android 系统版本 / Android version

Android 11 

### 设备型号 / Device model

Lenovo legion y700

### SoC 型号 / Soc model

snapdragon 870

### 自查步骤 / Verify steps

- [x] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [x] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by JohnDoe107745** [comment]
> Looks like it's a duplicate of #906 Have you tried latest development version?

If you are saying enabling the "Use CI Update channel" yes, I tried it but the error still exists. 
The version I am using is the latest version of your release and looks like the error is appearing to older versions too since I tried installing the older version expecting if it could sovle the issue.

**Comment by FooIbar** [comment]
> > Looks like it's a duplicate of #906 Have you tried latest development version?
> 
> If you are saying enabling the "Use CI Update channel" yes, I tried it but the error still exists. The version I am using is the latest version of your release and looks like the error is appearing to older versions too since I tried installing the older version expecting if it could sovle the issue.

Have you clicked "Check for updates" after enabling "Use CI update channel"?
I want the version code in the About screen for diagnosis.

**Comment by FooIbar** [comment]
Shipped in `1.11.2`.

**Comment by JohnDoe107745** [comment]
> > > Looks like it's a duplicate of #906 Have you tried latest development version?
> > 
> > 
> > If you are saying enabling the "Use CI Update channel" yes, I tried it but the error still exists. The version I am using is the latest version of your release and looks like the error is appearing to older versions too since I tried installing the older version expecting if it could sovle the issue.
> 
> Have you clicked "Check for updates" after enabling "Use CI update channel"? I want the version code in the About screen for diagnosis.

Oh I did not clicked it after enabling the "Use CI update channel". That was the reason lol. 
And Updated to version 1.11.2. 
By the way, could you please reprovide the gallery align functionality that allows to modify the order of the gallery? 
I used this function very usefully but this function was deleted in latest versions. Any reason for deleting this functionality? Thanks

**Comment by FooIbar** [comment]
> By the way, could you please reprovide the gallery align functionality that allows to modify the order of the gallery? I used this function very usefully but this function was deleted in latest versions. Any reason for deleting this functionality? Thanks

I assume you are referring to custom order for download list.
It was replaced by the new "sort by" function due to poor performance when there are a large amount of items.
The "sort by" menu can be accessed through the floating action button.

**Comment by JohnDoe107745** [comment]
> > By the way, could you please reprovide the gallery align functionality that allows to modify the order of the gallery? I used this function very usefully but this function was deleted in latest versions. Any reason for deleting this functionality? Thanks
> 
> I assume you are referring to custom order for download list. It was replaced by the new "sort by" function due to poor performance when there are a large amount of items. The "sort by" menu can be accessed through the floating action button.

I see, but the sort by only sorts the list with some dedicated options it does not provide custom sorting option. Is there any plan to add this function again later?

**Comment by FooIbar** [comment]
> > > By the way, could you please reprovide the gallery align functionality that allows to modify the order of the gallery? I used this function very usefully but this function was deleted in latest versions. Any reason for deleting this functionality? Thanks
> > 
> > 
> > I assume you are referring to custom order for download list. It was replaced by the new "sort by" function due to poor performance when there are a large amount of items. The "sort by" menu can be accessed through the floating action button.
> 
> I see, but the sort by only sorts the list with some dedicated options and it does not provide custom sorting option. Is there any plan to add this function again later?

Currently no. But it's possible to add more sorting options per requests.

**Comment by JohnDoe107745** [comment]
> > > > By the way, could you please reprovide the gallery align functionality that allows to modify the order of the gallery? I used this function very usefully but this function was deleted in latest versions. Any reason for deleting this functionality? Thanks
> > > 
> > > 
> > > I assume you are referring to custom order for download list. It was replaced by the new "sort by" function due to poor performance when there are a large amount of items. The "sort by" menu can be accessed through the floating action button.
> > 
> > 
> > I see, but the sort by only sorts the list with some dedicated options and it does not provide custom sorting option. Is there any plan to add this function again later?
> 
> Currently no. But it's possible to add more sorting options per requests.

Ok thanks. Hope that custom sorting option could provided in near future :)
