### ISSUE TITLE
打开下载管理页面没有展示出历史下载数据的问题

### ISSUE THREAD

**Issue by skydregon** [FooIbar/EhViewer#921]
### 复现步骤 / Step to reproduce

1.点击对应画廊，点击下载
2.切回主页，拉开侧边导航栏，点击下载
3.进入下载管理页面

### 预期行为 / Expected behaviour

应当展示历史下载内容和刚刚点击下载的画廊

### 实际行为 / Actual Behaviour

没有展示下载内容，并且历史下载也没有
![Screenshot_2024-03-18-01-16-00-118_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/66740727/c1900d3a-19c9-4079-8cf1-eae2cf8c9c2d)
![Screenshot_2024-03-18-01-16-04-328_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/66740727/265c79e7-220a-4802-9b64-ecbe3d696068)

### 应用日志 / App logs

[log-2024-03-18-12-08-59-011.zip](https://github.com/FooIbar/EhViewer/files/14630794/log-2024-03-18-12-08-59-011.zip)

### 备注 / Addition details

加了内置的 cronet的UjuiUjuMandan的修改版

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.2-cc

### EhViewer CI 版本 / EhViewer CI Version

5c6480a

### Android 系统版本 / Android version

Xiaomi HyperOS 1.0.2.0ULKCNXM

### 设备型号 / Device model

红米k50 pro

### SoC 型号 / Soc model

天玑9000

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
其他版本与本仓库无关
