### ISSUE TITLE
登入后画廊列表不显示翻译语言

### ISSUE THREAD

**Issue by grasssand** [FooIbar/EhViewer#923]
### 复现步骤 / Step to reproduce

游客模式正常显示，登入后不显示。问题出现在更新1.11后，换设备全新安装也能复现

![Screenshot_20240321-140212_EhViewer](https://github.com/FooIbar/EhViewer/assets/11460505/b2057c28-981c-4401-ba0b-237bc7dbc1ce)
![Screenshot_20240321-140114_EhViewer](https://github.com/FooIbar/EhViewer/assets/11460505/419a5be4-ead7-46d9-b17e-d2fab73db92d)

### 预期行为 / Expected behaviour

列表项右下显示翻译语言和页数

### 实际行为 / Actual Behaviour

更新到1.11后只显示页数

### 应用日志 / App logs

[logcat-2024-03-21-14-45-47-031.txt](https://github.com/FooIbar/EhViewer/files/14687190/logcat-2024-03-21-14-45-47-031.txt)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

6a64ff5

### Android 系统版本 / Android version

lineageos21

### 设备型号 / Device model

mi6

### SoC 型号 / Soc model

s835

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
于 5b59dab 修复
如果不想更新 CI 版本也可以单开一个 Settings Profile 把显示模式从 Thumbnail 改成 Extended
