### ISSUE TITLE
阅读器双指缩放异常

### ISSUE THREAD

**Issue by rurires** [FooIbar/EhViewer#93]
### 复现步骤 / Step to reproduce

1.进入任意画廊开始阅读；
2.双指放大操作。

### 预期行为 / Expected behaviour

正常双指放大操作

### 实际行为 / Actual Behaviour

两种情况：
1.直接白屏(黑屏)；
2.如果先使用双击并按住下划来放大一下，再使用双指放大的话就不会白屏，但在双指按下的瞬间会直接变成最大缩放，只能在最大缩放的基础上进行缩小或移动，之后每次双指按下都会如此。

### 备注 / Addition details

具体不知道从哪个版本开始，但[CI#626](https://github.com/FooIbar/EhViewer/actions/runs/6629383106)就有这个情况

### EhViewer 版本号 / EhViewer version code

1.8.11.0-SNAPSHOT

### EhViewer CI 版本 / EhViewer CI Version

b2b12f7

### Android 系统版本 / Android version

MIUI 12.5 (Android 10)

### 设备型号 / Device model

Xiaomi Mix 2S

### SoC 型号 / Soc model

骁龙 845

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by UjuiUjuMandan** [comment]
这么明显的问题我到现在才发现，原来我之前都是双击来放大的...

**Comment by FooIbar** [comment]
可以确认只在分页模式下有这个问题
条漫和从上到下（连续）不会出现
