### ISSUE TITLE
更新后点侧栏-设置-隐私后闪退

### ISSUE THREAD

**Issue by CosineA** [FooIbar/EhViewer#953]
### 复现步骤 / Step to reproduce

0 从1.8.10.2更新（已打开使用CI更新）后App闪退
1. 卸载后直接从release 下载最新universal 版本
2. 安装后所有功能正常 但在想在设置-隐私里设置图案解锁时闪退
3. 更新至最新CI版本后 在点隐私的时候依旧闪退

### 预期行为 / Expected behaviour

应该正常进入到隐私设置页面

### 实际行为 / Actual Behaviour

实际上在点隐私的时候应用闪退

### 应用日志 / App logs

[log-2024-03-26-23-17-19-366.zip](https://github.com/FooIbar/EhViewer/files/14760706/log-2024-03-26-23-17-19-366.zip)

### 备注 / Addition details

在使用1.8.10.2以及更旧的CI版本时并未出现过这个问题

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0-Snapshot

### EhViewer CI 版本 / EhViewer CI Version

78facda

### Android 系统版本 / Android version

Android 9

### 设备型号 / Device model

LG G6

### SoC 型号 / Soc model

骁龙 821

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hardware/biometrics/BiometricManager;
```
