### ISSUE TITLE
画廊带有种子但无法被正确显示

### ISSUE THREAD

**Issue by GalaxyAlpha** [FooIbar/EhViewer#955]
### 复现步骤 / Step to reproduce

复现的画廊：
https://exhentai.org/g/2286443/fcab4aed88 
https://exhentai.org/g/1656505/365406ca7f
https://exhentai.org/g/1948593/af672bcb3b

### 预期行为 / Expected behaviour

画廊所带有的种子都应被显示

### 实际行为 / Actual Behaviour

点击后显示“没有当前版本画廊的种子”

### 应用日志 / App logs

[log-2024-03-27-13-01-01-753.zip](https://github.com/FooIbar/EhViewer/files/14768178/log-2024-03-27-13-01-01-753.zip)

### 备注 / Addition details

最新CI版本1.12.0-SNAPSHOT (78facda)问题依然存在

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

6a64ff5

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Redmi K20pro

### SoC 型号 / Soc model

SM8150

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
正如提示所说，过时（上传时间在画廊更新时间之前）的种子不会被显示

**Comment by GalaxyAlpha** [comment]
> 正如提示所说，过时（上传时间在画廊更新时间之前）的种子不会被显示

在此前的版本以及浏览器中是可以正常显示的，请问回答是否表示这个现象是正常的，所以此issue应该被关闭?

**Comment by FooIbar** [comment]
这是预期行为，因为过时的种子不能代表当前版本的画廊
之前会显示是因为 E 站从 3 月 7 日起才开始区分过时种子

> 2024-03-07
> 
> - For versioned galleries, the gallery torrent list is now separated by "current" torrents (those uploaded after the current version of the gallery was posted) and "outdated" torrents (those uploaded before that time).

https://forums.e-hentai.org/index.php?showtopic=244935
