### ISSUE TITLE
希望增加cbz阅读器功能和本地已下载漫画批量打包cbz功能

### ISSUE THREAD

**Issue by 8620hachiroku** [FooIbar/EhViewer#967]
### 复现步骤 / Step to reproduce

虽然 https://github.com/FooIbar/EhViewer/commit/d0fbb3539f3b6a4aa5dfdb3510cf32aca57d4e77
增加了此功能，但是仍然不能打开cbz文件，本地的文件也不能批量打包成cbz文件

### 预期行为 / Expected behaviour

无

### 实际行为 / Actual Behaviour

无

### 应用日志 / App logs

无

### 备注 / Addition details

无

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.11.1

### EhViewer CI 版本 / EhViewer CI Version

f69521f

### Android 系统版本 / Android version

Android

### 设备型号 / Device model

Android

### SoC 型号 / Soc model

8g1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
打开 保存为CBZ 后在下载里全部开始就可以批量打包

**Comment by 8620hachiroku** [comment]
> 打开 保存为CBZ 后在下载里全部开始就可以批量打包 不能打开CBZ文件具体是指？

在本地文件管理器选择cbz文件使用Ehviewer打开会提示读取失败

**Comment by FooIbar** [comment]
> > 打开 保存为CBZ 后在下载里全部开始就可以批量打包 不能打开CBZ文件具体是指？
> 
> 在本地文件管理器选择cbz文件使用Ehviewer打开会提示读取失败

由 EhViewer 打包的CBZ应该都是可以读取的，外部的不保证能读取
如果方便的话可以上传以下无法读取的文件吗

**Comment by 8620hachiroku** [comment]
> > > 打开 保存为CBZ 后在下载里全部开始就可以批量打包 不能打开CBZ文件具体是指？
> > 
> > 
> > 在本地文件管理器选择cbz文件使用Ehviewer打开会提示读取失败
> 
> 由 EhViewer 打包的CBZ应该都是可以读取的，外部的不保证能读取 如果方便的话可以上传下无法读取的文件吗
https://pan.shinnku.com/s/NByW5XT8xziqQ95
我将它上传到了一个网盘中以供下载
经测试，librera fd 可以正常打开该文件，该文件应该没有损坏

**Comment by FooIbar** [comment]
> > > > 打开 保存为CBZ 后在下载里全部开始就可以批量打包 不能打开CBZ文件具体是指？
> > > 
> > > 
> > > 在本地文件管理器选择cbz文件使用Ehviewer打开会提示读取失败
> > 
> > 
> > 由 EhViewer 打包的CBZ应该都是可以读取的，外部的不保证能读取 如果方便的话可以上传下无法读取的文件吗
> > https://pan.shinnku.com/s/NByW5XT8xziqQ95
> > 我将它上传到了一个网盘中以供下载
> > 经测试，librera fd 可以正常打开该文件，该文件应该没有损坏

这是由于该文件内部有一个含有日文字符的文件夹
1.11.2 的 Default 变种是可以打开该文件的，Marshmallow 变种不支持
