### ISSUE TITLE
在打开保存为cbz压缩包后点击全部开始仍然不能自动打包已下载的文件

### ISSUE THREAD

**Issue by 8620hachiroku** [FooIbar/EhViewer#968]
### 复现步骤 / Step to reproduce

如题，按照在 https://github.com/FooIbar/EhViewer/issues/967 给出的方法后仍然不能正常开始打包，只是手动点击每个画廊下载才会被打包

### 预期行为 / Expected behaviour

点击全部开始后开始自动打包

### 实际行为 / Actual Behaviour

没有自动打包

### 应用日志 / App logs

无

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.12.1

### EhViewer CI 版本 / EhViewer CI Version

6a64ff5

### Android 系统版本 / Android version

Android

### 设备型号 / Device model

Android

### SoC 型号 / Soc model

8g1

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
录屏、日志

**Comment by 8620hachiroku** [comment]
猜测是ehviewer下载逻辑的问题
下载是会先检查状态是否为：已完成
如果是已完成,则自动跳过
也许加一个：全部未完成 可以解决该问题

**Comment by 8620hachiroku** [comment]
> 录屏、日志

猜测是ehviewer下载逻辑的问题
下载是会先检查状态是否为：已完成
如果是已完成,则自动跳过
也许加一个：全部未完成 可以解决该问题

**Comment by 8620hachiroku** [comment]
> 录屏、日志

https://github.com/FooIbar/EhViewer/assets/135826748- /e881cb0e-83b8-4f61-8d5e-cea54b881773![log-2024-04-01-22-09-19-595.zip](https://github.com/FooIbar/EhViewer/files/14824300/log-2024-04-01-22-09-19-595.zip)

**Comment by FooIbar** [comment]
下拉菜单里的全部开始是会跳过已完成的画廊的
全选然后全部开始不会
