### ISSUE TITLE
导出数据失败

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#974]
### 复现步骤 / Step to reproduce

安装新的和之前同样版本均无法导出数据

### 预期行为 / Expected behaviour

导出数据

### 实际行为 / Actual Behaviour

导出数据失败，并在目录下留下一个0B文
![Screenshot_20240402_172230_edit_699552127301838](https://github.com/FooIbar/EhViewer/assets/89101669/e0905803-d196-4913-8c54-0daa5e236254)
件
![Screenshot_20240402_172250_edit_699560695275012](https://github.com/FooIbar/EhViewer/assets/89101669/bfa0acea-5788-4ac1-a034-71c9cff5da22)

### 应用日志 / App logs

无日志

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

e05fbb6

### Android 系统版本 / Android version

Magic OS 7.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
日志

**Comment by z1137** [comment]
目录下的crash没有日志

**Comment by FooIbar** [comment]
应用里导出日志

**Comment by z1137** [comment]
======== PackageInfo ========
PackageName=moe.tarsin.ehviewer
VersionName=1.12.0-SNAPSHOT
VersionCode=180053
CommitSha=e05fbb6
BuildTime=2024/03/22 08:36

======== DeviceInfo ========
BOARD=LSA
BOOTLOADER=unknown
BRAND=HONOR
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HNLSA
DISPLAY=LSA-AN00 7.0.0.181(C00E175R7P4)
FINGERPRINT=HONOR/LSA-AN00/HNLSA:12/HONORLSA-AN00/7.0.0.181C00:user/release-keys
FINGERPRINTEX=HONOR/LSA-AN00/HNLSA:12/HONORLSA-AN00/7.0.0.181C00:user/release-keys
HARDWARE=qcom
HOST=cn-snxy1c-acf5e5d291707117064538-5f879f6f88-cjwcd
HWFINGERPRINT=///LSA-LGRP1-CHN 7.0.0.181/LSA-AN00-CUST 7.0.0.175(C00)/LSA-AN00-PRELOAD 7.0.0.4(C00R7)//
ID=HONORLSA-AN00
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=HONOR
MODEL=LSA-AN00
ODM_SKU=LSA-AN00
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=LSA-AN00
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM7325
SUPPORTED_32_BIT_ABIS=armeabi-v7a, armeabi
SUPPORTED_64_BIT_ABIS=arm64-v8a
SUPPORTED_ABIS=arm64-v8a, armeabi-v7a, armeabi
TAGS=release-keys
TIME=1707119410000
TYPE=user
UNKNOWN=unknown
USER=test
ACTIVE_CODENAMES=
BASE_OS=
CODENAME=REL
INCREMENTAL=7.0.0.181C00
MEDIA_PERFORMANCE_CLASS=0
PREVIEW_SDK_FINGERPRINT=REL
PREVIEW_SDK_INT=0
RELEASE=12
RELEASE_OR_CODENAME=12
SDK=31
SDK_INT=31
SECURITY_PATCH=2024-02-01
MEMORY=16.8 MiB
MEMORY_NATIVE=23.6 MiB
MEMORY_MAX=384.0 MiB
MEMORY_TOTAL=7.3 GiB

--------- beginning of crash
04-02 15:49:40.420 29008 29105 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-27
04-02 15:49:40.420 29008 29105 E AndroidRuntime: Process: moe.tarsin.ehviewer, PID: 29008
04-02 15:49:40.420 29008 29105 E AndroidRuntime: java.lang.NullPointerException
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at QC.v(Unknown Source:299)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at rd.r(Unknown Source:8)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at gB.run(Unknown Source:112)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at T1.run(Unknown Source:560)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at VV0.run(Unknown Source:2)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	at dt.run(Unknown Source:95)
04-02 15:49:40.420 29008 29105 E AndroidRuntime: 	Suppressed: Cz: [qR0{Cancelling}@440c46, Dispatchers.IO]
--------- beginning of main
04-02 17:24:18.521 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 17:31:05.339 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 17:31:13.585 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 17:31:13.604 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 17:31:13.923 21465 21585 E qR0     : android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (Sqlite code 787 SQLITE_CONSTRAINT_FOREIGNKEY), (OS error - 88:Socket operation on non-socket)
04-02 17:31:13.923 21465 21585 E qR0     : 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
04-02 17:31:13.923 21465 21585 E qR0     : 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:992)
04-02 17:31:13.923 21465 21585 E qR0     : 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:810)
04-02 17:31:13.923 21465 21585 E qR0     : 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:93)
04-02 17:31:13.923 21465 21585 E qR0     : 	at FT.b(Unknown Source:2)
04-02 17:31:13.923 21465 21585 E qR0     : 	at ZK.k(Unknown Source:26)
04-02 17:31:13.923 21465 21585 E qR0     : 	at jC.call(Unknown Source:385)
04-02 17:31:13.923 21465 21585 E qR0     : 	at ut.v(Unknown Source:7)
04-02 17:31:13.923 21465 21585 E qR0     : 	at rd.r(Unknown Source:8)
04-02 17:31:13.923 21465 21585 E qR0     : 	at gB.run(Unknown Source:112)
04-02 17:31:13.923 21465 21585 E qR0     : 	at p5.run(Unknown Source:77)
04-02 17:31:13.923 21465 21585 E qR0     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-02 17:31:13.923 21465 21585 E qR0     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-02 17:31:13.923 21465 21585 E qR0     : 	at java.lang.Thread.run(Thread.java:930)
04-02 17:31:17.552 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
04-02 17:31:17.573 21465 21526 E OpenGLRenderer: Unable to match the desired swap behavior.
