### ISSUE TITLE
下载到本地的本子封面图片不显示

### ISSUE THREAD

**Issue by eroughter** [FooIbar/EhViewer#977]
### 复现步骤 / Step to reproduce

。

### 预期行为 / Expected behaviour

本应该正常显示本子封面图片，这是我点进本子详情退出才显示当前界面几个本子的封面。往下拉其他本子封面均不显示。
![Screenshot_20240403_112322_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/165626646/168ddfcd-1106-40f6-a0b8-856c373318c2)

### 实际行为 / Actual Behaviour

这是每次重新打开app之后本地本子封面不显示的状态
![Screenshot_20240403_112253_moe tarsin ehviewer](https://github.com/FooIbar/EhViewer/assets/165626646/bb721aae-4205-4647-9d4c-7d540dcdebf2)

### 应用日志 / App logs

[log-2024-04-03-11-25-19-298.zip](https://github.com/FooIbar/EhViewer/files/14846288/log-2024-04-03-11-25-19-298.zip)

### 备注 / Addition details

这个问题是更新到foolbar版本之后就出现的

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.12.0

### EhViewer CI 版本 / EhViewer CI Version

2c5293a

### Android 系统版本 / Android version

安卓12 鸿蒙os4.0

### 设备型号 / Device model

huawei mate 30 pro

### SoC 型号 / Soc model

kirin990

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
下载目录下有没有`thumb.jpg`？

**Comment by eroughter** [comment]
> 下载目录下有没有`thumb.jpg`？

有这个文件，点进去是空白
![Screenshot_20240404_041842_com huawei filemanager](https://github.com/FooIbar/EhViewer/assets/165626646/a4dbdf19-d6d4-4cda-8bff-4dcb0620fd24)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/8550376136/artifacts/1383782331
用这个版本再传一次日志

**Comment by eroughter** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/8550376136/artifacts/1383782331 用这个版本再传一次日志

[Uploading log-2024-04-04-16-52-51-370.zip…]()

**Comment by FooIbar** [comment]
> > https://github.com/FooIbar/EhViewer/actions/runs/8550376136/artifacts/1383782331 用这个版本再传一次日志
> 
> Uploading log-2024-04-04-16-52-51-370.zip…

没传上来

**Comment by eroughter** [comment]
[Uploading log-2024-04-04-21-39-33-305.zip…]()

**Comment by eroughter** [comment]
> > > https://github.com/FooIbar/EhViewer/actions/runs/8550376136/artifacts/1383782331 用这个版本再传一次日志
> > 
> > 
> > 正在上传 log-2024-04-04-16-52-51-370.zip...
> 
> 没传上来

[log-2024-04-04-21-39-33-305.zip](https://github.com/FooIbar/EhViewer/files/14872129/log-2024-04-04-21-39-33-305.zip)

**Comment by FooIbar** [comment]
遗憾的是日志中并没有所需要的信息
https://github.com/FooIbar/EhViewer/actions/runs/8556459614/artifacts/1385138986
修改了日志的优先级并尝试修复这个问题，可以试下

**Comment by eroughter** [comment]
不起作用，不折腾了。本地thumb.jpg文件大小是oB且不显示图像，断网状态下入手动打开本子退出来也能显示封面，让人摸不着头脑😰，不搞了。

**Comment by eroughter** [comment]
> 遗憾的是日志中并没有所需要的信息 https://github.com/FooIbar/EhViewer/actions/runs/8556459614/artifacts/1385138986 修改了日志的优先级并尝试修复这个问题，可以试下

不起作用，不折腾了。本地thumb.jpg文件大小是oB且不显示图像，断网状态下入手动打开本子退出来也能显示封面，让人摸不着头脑😰，不搞了。

**Comment by FooIbar** [comment]
> > 遗憾的是日志中并没有所需要的信息 https://github.com/FooIbar/EhViewer/actions/runs/8556459614/artifacts/1385138986 修改了日志的优先级并尝试修复这个问题，可以试下
> 
> 不起作用，不折腾了。本地thumb.jpg文件大小是oB且不显示图像，断网状态下入手动打开本子退出来也能显示封面，让人摸不着头脑😰，不搞了。

那个版本的日志呢？

**Comment by eroughter** [comment]
> > > 遗憾的是日志中并没有所需要的信息 https://github.com/FooIbar/EhViewer/actions/runs/8556459614/artifacts/1385138986 修改了日志的优先级并尝试修复这个问题，可以试下
> > 
> > 
> > 不起作用，不折腾了。本地thumb.jpg文件大小是oB且不显示图像，断网状态下入手动打开本子退出来也能显示封面，让人摸不着头脑😰，不搞了。
> 
> 那个版本的日志呢？

[log-2024-04-05-03-35-50-867.zip](https://github.com/FooIbar/EhViewer/files/14876360/log-2024-04-05-03-35-50-867.zip)

**Comment by FooIbar** [comment]
https://github.com/FooIbar/EhViewer/actions/runs/8565580179/artifacts/1387375723
应该修复了这个问题

**Comment by eroughter** [comment]
> https://github.com/FooIbar/EhViewer/actions/runs/8565580179/artifacts/1387375723 应该修复了这个问题

哇谢谢，没想到还真修好了！
