### ISSUE TITLE
[非严重]不明原因闪退

### ISSUE THREAD

**Issue by z1137** [FooIbar/EhViewer#980]
### 复现步骤 / Step to reproduce

正常使用

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

闪退

### 应用日志 / App logs

[crash-2024-04-03-08.zip](https://github.com/FooIbar/EhViewer/files/14849720/crash-2024-04-03-08.zip)

### 备注 / Addition details

2个日志分别是：快速删除画廊并重新下载时闪退 以及 边下载边观看时闪退
删除画廊时不删除文件，点击慢的时候不会闪退。

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.11.2

### EhViewer CI 版本 / EhViewer CI Version

e05fbb6

### Android 系统版本 / Android version

Magic OS 7.0

### 设备型号 / Device model

荣耀60

### SoC 型号 / Soc model

778G

### 自查步骤 / Verify steps

- [X] 您已搜索过 [Issue Tracker](https://github.com/FooIbar/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/FooIbar/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 [CI 版本](https://github.com/FooIbar/EhViewer/actions)测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest [CI version](https://github.com/FooIbar/EhViewer/actions)

**Comment by FooIbar** [comment]
```
java.lang.NullPointerException
        at com.hippo.ehviewer.download.DownloadService.ensureDownloadedBuilder(DownloadService.kt:208)
        at com.hippo.ehviewer.download.DownloadService.onFinish(DownloadService.kt:307)
        at com.hippo.ehviewer.download.DownloadManager$onFinish$1.invokeSuspend(DownloadManager.kt:636)
```
```
android.app.RemoteServiceException: Bad notification(tag=null, id=1) posted from package moe.tarsin.ehviewer, crashing app(uid=10343, pid=6646): Couldn't inflate contentViews
java.util.ConcurrentModificationException
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2393)
```
